'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),esbuild=require('esbuild');
const base=path.resolve('fullbody-tcm-v10');const common={bundle:true,minify:true,nodePaths:[process.env.NODE_PATH].filter(Boolean),target:['es2020'],loader:{'.txt':'text'},legalComments:'inline'};
for(const [input,output]of [['app.js','app.bundle.js'],['evidence-page-v10.js','evidence.bundle.js']])esbuild.buildSync({...common,entryPoints:[path.join(base,input)],outfile:path.join(base,output),format:'iife'});
esbuild.buildSync({...common,entryPoints:[path.join(base,'catalog-v10.js')],outfile:path.join(base,'catalog-check.cjs'),format:'cjs',platform:'node'});
const cat=require(path.join(base,'catalog-check.cjs'));if(cat.POINT_TERMS.GV14.pinyin!=='dà zhuī')throw Error('GV14 normalization failure');
fs.writeFileSync(path.join(base,'term-catalog.json'),JSON.stringify({audit:cat.termAudit,terms:cat.ALL_TERMS},null,2));fs.unlinkSync(path.join(base,'catalog-check.cjs'));
const info=JSON.parse(fs.readFileSync(path.join(base,'build-info.json'))),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(base,f))).digest('hex');
info.htmlSHA256=hash('index.html');info.appSHA256=hash('app.bundle.js');info.evidenceSHA256=hash('evidence.html');info.evidenceBundleSHA256=hash('evidence.bundle.js');info.onlineEntryBytes=fs.statSync(path.join(base,'index.html')).size;info.bundleBytes=fs.statSync(path.join(base,'app.bundle.js')).size;
fs.writeFileSync(path.join(base,'build-info.json'),JSON.stringify(info,null,2));
// Optional single-file offline export (an independent artifact, not the online entry).
if(process.env.OFFLINE_EXPORT){let html=fs.readFileSync(path.join(base,'index.html'),'utf8');for(const file of ['styles.css','stability-v10.css'])html=html.replace(`<link rel="stylesheet" href="${file}">`,'<style>'+fs.readFileSync(path.join(base,file),'utf8')+'</style>');const source=path.resolve('fullbody-tcm-v9');const inline={};for(const name of ['muscular','nervous'])inline[name]=fs.readFileSync(path.join(source,'assets',name+'.glb')).toString('base64');const voices={};for(const f of fs.readdirSync(path.join(source,'voice')))if(f.endsWith('.mp3'))voices[f]=fs.readFileSync(path.join(source,'voice',f)).toString('base64');const model=fs.readFileSync(path.join(source,'assets/fullbody.glb')).toString('base64');const pre='<script>window.FOOT_ATLAS_EMBEDDED='+JSON.stringify(model)+';window.ATLAS_TISSUE_INLINE='+JSON.stringify(inline)+';window.ATLAS_VOICE_INLINE='+JSON.stringify(voices)+';</script>';html=html.replace('<script src="app.bundle.js" defer></script>',()=>pre+'<script>'+fs.readFileSync(path.join(base,'app.bundle.js'),'utf8').replaceAll('</script','<\\/script')+'</script>');fs.writeFileSync(process.env.OFFLINE_EXPORT,html);}
console.log('BUILD',JSON.stringify(info));
