'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {chromium,webkit}=require('playwright');
const root=process.cwd(),dir=path.join(root,'fullbody-tcm-v10'),out=path.join(dir,'checks');fs.mkdirSync(out,{recursive:true});
const mode=process.env.BROWSER||'chromium',live=!!process.env.LIVE_URL;
const report={version:'10.0.0',browser:mode,startedAt:new Date().toISOString(),checks:[],errors:[],success:false,clinicalValidation:false};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,...(detail===undefined?{}:{detail})});console.log(pass?'PASS':'FAIL',name);if(!pass)throw Error(name+': '+JSON.stringify(detail));}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.glb':'model/gltf-binary','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{try{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep))throw Error();if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);}catch{res.writeHead(404);res.end();}});
const settle=async page=>{await page.waitForFunction(()=>window.__FOOT_ATLAS__?.getState().ready&&!window.__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:60000});await page.waitForTimeout(220);};
(async()=>{let browser,page,context;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=process.env.LIVE_URL||`http://127.0.0.1:${server.address().port}/fullbody-tcm-v10/`;report.url=url;
 const response=await fetch(url),html=Buffer.from(await response.arrayBuffer());ck('HTTP 200 and exact online HTML',response.status===200&&sha(html)===sha(fs.readFileSync(path.join(dir,'index.html'))));
 ck('Online entry is under 30KB and no embedded anatomy',html.length<30000&&!html.includes(Buffer.from('window.FOOT_ATLAS_EMBEDDED=')),html.length);
 const js=await fetch(new URL('app.bundle.js',url));ck('Exact published application bundle',js.ok&&sha(Buffer.from(await js.arrayBuffer()))===sha(fs.readFileSync(path.join(dir,'app.bundle.js'))));
 browser=await(mode==='webkit'?webkit:chromium).launch({headless:true,...(mode==='chromium'?{args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}:{})});
 context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true,serviceWorkers:'block'});await context.addInitScript(()=>{localStorage.setItem('atlas-auto-speak','0');});
 page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>report.errors.push(String(e)));const reqs=[];page.on('request',r=>{if(/^https?:/.test(r.url()))reqs.push(r.url());});
 await page.goto(url,{waitUntil:'load',timeout:90000});await page.waitForFunction(()=>window.__ATLAS_STUDY__&&window.__ATLAS_PERFORMANCE__,null,{timeout:90000});await settle(page);
 ck('V10 loads all 210 original bones',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().version==='10.0.0'&&window.__FOOT_ATLAS__.getState().visible===210));
 ck('All 670 illustrative markers and original geometry retained',await page.evaluate(()=>window.__ATLAS_LEARNING__.getState().markerInstances===670&&window.__FOOT_ATLAS__.getState().bones.reduce((n,b)=>n+b.triangles,0)===534003));
 ck('Strict mode is default; no calibrated-coordinate claim',await page.evaluate(()=>window.__ATLAS_LEARNING__.getState().precisionMode==='strict'&&window.__ATLAS_LEARNING__.getState().coordinateVerified===0));
 await page.locator('#tcmBtn').click();await page.locator('#acupointSearch').fill('da zhui');
 ck('Correct pinyin finds Dazhui in 3D directory',await page.locator('#acupointResults [data-point="GV14"]').count()===1);
 await page.locator('#acupointResults [data-point="GV14"]').click();await settle(page);
 ck('Point selection becomes the current study object',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.id==='GV14'&&document.body.dataset.currentKind==='point'));
 ck('Correct pinyin on point and explanation data',await page.evaluate(()=>document.getElementById('tcmPointCard').innerText.includes('dà zhuī')&&window.__ATLAS_EVIDENCE__.getData().points.GV14.pinyin==='dà zhuī'));
 ck('Stale bone preview is not displayed during point study',await page.locator('.preview-wrap').evaluate(e=>getComputedStyle(e).display==='none'));
 await page.locator('#focusBtn').click();await settle(page);
 ck('Global focus keeps current point, not previous sternum',await page.evaluate(()=>window.__ATLAS_LEARNING__.getState().selectedPoint.code==='GV14'&&window.__ATLAS_LEARNING__.getState().navigationFocus.title.includes('大椎')));
 await page.keyboard.press('f');await settle(page);ck('F key focuses the same active point',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.id==='GV14'));
 await page.evaluate(()=>window.__ATLAS_LEARNING__.setPrecisionMode('illustrative'));await page.locator('#focusCurrent').click();await settle(page);
 ck('Precision UI is synchronized with API state',await page.locator('#v9Strict').evaluate(e=>!e.checked));
 ck('Point target is retained when switching to illustrative view',await page.evaluate(()=>window.__ATLAS_LEARNING__.getState().selectedPoint.code==='GV14'));
 await page.evaluate(()=>window.__ATLAS_LEARNING__.setLabelMode('complete'));await settle(page);
 const dl=page.waitForEvent('download');await page.locator('#captureBtn').click();const download=await dl;
 await download.saveAs(path.join(out,mode+'-actual-export.png'));
 const cap=await page.evaluate(()=>window.__ATLAS_STUDY__.getState().lastCapture);
 ck('Actual screenshot button uses active object filename',download.suggestedFilename().includes('大椎')&&cap.filename.includes('大椎'),cap);
 ck('Screenshot captures visible acupoint label and uncalibrated state',cap.labels.some(t=>t.includes('大椎'))&&cap.mode.includes('未')&&cap.bytes>10000,cap);
 if(!live)await page.screenshot({path:path.join(out,mode+'-point-study.png'),timeout:90000});
 await page.evaluate(()=>window.__ATLAS_LEARNING__.selectPoint('PC6','right',true));await settle(page);
 const before=await page.evaluate(()=>window.__FOOT_ATLAS__.getState().target);
 await page.locator('[data-study-profile="nerves"]').click();await page.waitForFunction(()=>window.__ATLAS_TISSUES__.getState().systems.nervous.loaded,null,{timeout:90000});await settle(page);
 ck('Nerve layer loads 550 source structures',await page.evaluate(()=>window.__ATLAS_TISSUES__.getState().systems.nervous.count===550));
 ck('Nerve profile preserves active acupoint and camera',await page.evaluate(before=>{const s=window.__FOOT_ATLAS__.getState();return window.__ATLAS_STUDY__.getState().current.id==='PC6'&&s.target.every((v,i)=>Math.abs(v-before[i])<.01);},before));
 ck('Nerve reading profile is explicit and separates muscle layer',await page.evaluate(()=>{const s=window.__ATLAS_TISSUES__.getState();return s.nerveXray&&s.systems.nervous.visible>0&&!s.systems.muscular.on&&s.boneOpacity>=.3;}));
 if(!live)await page.screenshot({path:path.join(out,mode+'-nerve-context.png'),timeout:90000});
 await page.locator('#overallCurrent').click();await settle(page);
 ck('Return to whole body clears both point context and camera context',await page.evaluate(()=>!window.__ATLAS_LEARNING__.getStudyContext()&&!window.__ATLAS_LEARNING__.getState().navigationFocus&&window.__FOOT_ATLAS__.getState().region==='body'));
 ck('Global layer is no longer confined to the old point window',await page.evaluate(()=>window.__ATLAS_TISSUES__.getState().systems.nervous.visible>100));
 await page.locator('#backCurrent').click();await settle(page);ck('Return to last object restores PC6',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.id==='PC6'));
 await page.evaluate(()=>window.__ATLAS_TISSUES__.setProfile('bones'));await page.evaluate(()=>window.__FOOT_ATLAS__.setRegion('lumbar'));await settle(page);
 ck('Programmatic region navigation also clears point context',await page.evaluate(()=>!window.__ATLAS_LEARNING__.getStudyContext()&&!window.__ATLAS_LEARNING__.getState().selectedPoint));
 await page.evaluate(()=>window.__FOOT_ATLAS__.setExplode(100));await settle(page);
 ck('Lumbar vertical separation preserved',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().bones.filter(b=>/^L[1-5]$/.test(b.id)).every(b=>Math.abs(b.position[0]-b.home[0])<.001&&Math.abs(b.position[2]-b.home[2])<.001)));
 await page.locator('#dockToggle').click();await page.locator('#resetBonesBtn').click();await settle(page);
 ck('Bone reset preserves region and restores coordinates',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().region==='lumbar'&&window.__FOOT_ATLAS__.getState().bones.every(b=>b.position.every((v,i)=>Math.abs(v-b.home[i])<.001))));
 if(mode==='chromium'){
  const pt=await page.evaluate(()=>window.__FOOT_ATLAS__.getPickPoint('L3'));ck('Real L3 surface is pickable',!!pt,pt);await page.mouse.click(pt.x,pt.y);
  ck('Real bone click updates current object',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.id==='L3'));
  await page.locator('[data-mode="move"]').click();await settle(page);
  const dragPoint=await page.evaluate(()=>window.__FOOT_ATLAS__.getPickPoint('L3'));ck('Post-mode real L3 surface remains accessible',!!dragPoint,dragPoint);
  await page.mouse.move(dragPoint.x,dragPoint.y);await page.mouse.down();await page.mouse.move(dragPoint.x+45,dragPoint.y-25,{steps:7});await page.mouse.up();
  ck('Dragging selects the intended L3, not its neighbor',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().selected==='L3'));
  ck('Original single-bone dragging remains usable',await page.evaluate(()=>Math.hypot(...window.__FOOT_ATLAS__.getState().bones.find(b=>b.id==='L3').offset)>1));
  await page.locator('#resetBonesBtn').click();await settle(page);
 }
 await page.locator('#homeBtn').click();await settle(page);await page.mouse.move(5,5);await page.waitForTimeout(2000);
 const n0=await page.evaluate(()=>window.__ATLAS_PERFORMANCE__.snapshot());await page.waitForTimeout(800);const n1=await page.evaluate(()=>window.__ATLAS_PERFORMANCE__.snapshot());
 ck('Idle reading stops continuous GPU redraws',n1.framesRendered-n0.framesRendered<=3,{before:n0,after:n1});
 await page.locator('#tcmBtn').click();await page.locator('#acupointSearch').fill('印堂');await page.locator('#acupointResults [data-point="EX-YINTANG"]').click();await settle(page);
 ck('Head supplement focus survives shared context integration',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.id==='EX-YINTANG'&&window.__ATLAS_LEARNING__.getState().navigationFocus.title.includes('印堂')));
 await page.setViewportSize({width:390,height:844});await settle(page);
 ck('Phone viewport remains usable and no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.getElementById('viewport').clientHeight>300));
 if(!live)await page.screenshot({path:path.join(out,mode+'-phone-head.png'),timeout:90000});
 // A new document must recreate selected object, mode and side from the URL.
 const deeplink=new URL('./#kind=point&id=PC6&side=left&mode=strict',url).href;
 await page.goto(deeplink,{waitUntil:'load',timeout:90000});await page.waitForFunction(()=>window.__ATLAS_STUDY__?.getState().current.id==='PC6',null,{timeout:90000});await settle(page);
 ck('Direct link restores point and body side',await page.evaluate(()=>window.__ATLAS_STUDY__.getState().current.side==='left'&&window.__ATLAS_LEARNING__.getState().precisionMode==='strict'));
 await page.setViewportSize({width:1440,height:1000});await settle(page);
 const toEvidence=await page.locator('#evidenceCurrent').getAttribute('href');ck('3D evidence link preserves same target',toEvidence.includes('PC6')&&toEvidence.includes('left'));
 await page.goto(toEvidence,{waitUntil:'load',timeout:90000});
 ck('Explanation page restores same target',await page.evaluate(()=>window.__EVIDENCE_PAGE__.getState().selected==='PC6'&&window.__EVIDENCE_PAGE__.getState().side==='left'));
 await page.locator('#search').fill('da zhui');ck('Explanation correct pinyin finds Dazhui',await page.locator('#results [data-id="GV14"]').count()===1);await page.locator('#results [data-id="GV14"]').click();
 ck('Explanation heading and shared data use the same reading',await page.locator('#detail').innerText().then(t=>t.includes('dà zhuī')));
 ck('Explanation-to-3D link preserves code and side',await page.locator('#open3d').getAttribute('href').then(t=>t.includes('GV14')&&t.includes('left')));
 await page.locator('#search').fill('da chui');ck('Incorrect Dazhui pinyin is not the canonical search result',await page.locator('#results button').count()===0);
 await page.locator('#search').fill('');ck('All 361 evidence names still searchable',await page.locator('#results button').count()===361);
 const catalog=JSON.parse(fs.readFileSync(path.join(dir,'term-catalog.json')));
 ck('All displayed evidence terms match canonical catalog',await page.evaluate(terms=>Object.values(window.__EVIDENCE_PAGE__.DATA.points).every(p=>p.pinyin===terms[p.code].pinyin&&p.name===terms[p.code].name),catalog.terms));
 await page.locator('#meridianTab').click();ck('Fourteen channel descriptions retained',await page.locator('#results button').count()===14);
 await page.setViewportSize({width:390,height:844});ck('Explanation mobile layout remains within screen',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 if(!live)await page.screenshot({path:path.join(out,mode+'-evidence-phone.png')});
 const pilot=await fetch(new URL('./calibration-pilot.json',url));const pd=await pilot.json();ck('Six calibration pilot records contain no fabricated approvals or errors',pd.cases.length===6&&pd.cases.every(p=>p.clinicalApproved===false&&p.measuredError===null&&p.reviewer===null));
 const origin=new URL(url).origin;ck('Runtime anatomy is same-origin only',reqs.every(u=>new URL(u).origin===origin),reqs.filter(u=>new URL(u).origin!==origin));
 ck('No uncaught JavaScript errors in study journeys',report.errors.length===0,report.errors);
 report.success=true;report.htmlSHA256=sha(html);report.appSHA256=sha(fs.readFileSync(path.join(dir,'app.bundle.js')));report.metrics=n1;
 }catch(e){report.failure=String(e);console.error(e);if(page)try{await page.screenshot({path:path.join(out,'failure-'+mode+'.png'),timeout:15000});}catch{}process.exitCode=1;
 }finally{if(browser)await browser.close();server.close();report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,(live?'live-':'local-')+mode+'.json'),JSON.stringify(report,null,2));console.log('RESULT',JSON.stringify({success:report.success,checks:report.checks.length,failure:report.failure}));}
})();
