import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import decoderSource from './draco-decoder.txt';
export function initTissues(ctx,speech){
 const {THREE,scene,camera,renderer,viewport,bones,state,toast,focusBounds,setRegion,setView}=ctx;
 const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const root=new THREE.Group();root.name='Same-source soft tissues';scene.add(root);renderer.localClippingEnabled=true;
 const entries=new Map(),systems={muscular:{on:false,opacity:.68,loaded:false,loading:false,meshes:[],promise:null},nervous:{on:false,opacity:1,loaded:false,loading:false,meshes:[],promise:null}};
 let selected=null,isolated=false,fascia=false,lastKey='',clipBox=null;
 const draco=new DRACOLoader().setDecoderConfig({type:'js'}).setWorkerLimit(2);draco._loadLibrary=()=>Promise.resolve(decoderSource);
 const loader=new GLTFLoader().setDRACOLoader(draco);
 const sidebar=document.querySelector('.sidebar'),panel=document.createElement('section');panel.id='tissuePanel';panel.className='tissue-panel';panel.hidden=true;
 panel.innerHTML='<h2>结构图层</h2><p>同源坐标叠加，可独立显示及调节透明度。</p><label class="layer-check"><input id="bonesOn" type="checkbox" checked><b>骨骼</b><small>210个独立骨块</small></label>'+['muscular','nervous'].map((s,i)=>`<section class="layer-block"><label class="layer-check"><input type="checkbox" id="${s}On"><b>${i?'神经 / 神经节 / 脊髓':'肌肉 / 筋膜'}</b><small id="${s}Status">按需加载</small></label><label class="layer-range">透明度<input id="${s}Opacity" aria-label="${i?'神经':'肌肉'}透明度" type="range" min="10" max="100" value="${i?100:68}"><output id="${s}OpacityValue">${i?100:68}%</output></label></section>`).join('')+'<label class="layer-check"><input id="fasciaOn" type="checkbox">显示筋膜、腱鞘等附属结构</label><p class="tissue-note">未加入真实皮肤、皮下脂肪和全部神经末梢；肌肉不是皮肤，不能据此把经穴当作已完成体表配准。</p><div class="v4-button-row"><button id="chestCompare">胸廓＋胸肌对照</button><button id="tissueClear">关闭软组织</button></div><label class="tissue-search"><input id="tissueSearch" type="search" placeholder="搜索已加载结构 / 神经 / 肌肉"></label><div id="tissueList" class="tissue-list"></div>';
 sidebar.append(panel);const tab=document.createElement('button');tab.id='layersTab';tab.textContent='肌肉神经';$('closeNav').before(tab);
 function showPanel(on){panel.hidden=!on;tab.classList.toggle('active',on);if(on){ctx.learning.setPanel(false);document.querySelector('.bone-pane').hidden=true;$('tcmControls').hidden=true;document.body.classList.add('nav-open');document.body.classList.remove('detail-open');$('boneTab').classList.remove('active');$('tcmTab').classList.remove('active');}}
 tab.onclick=()=>showPanel(true);for(const id of ['boneTab','tcmTab','tcmBtn'])$(id).addEventListener('click',()=>{panel.hidden=true;tab.classList.remove('active');});
 speech.mount(panel);
 const warning=document.createElement('div');warning.id='tissuePoseWarning';warning.className='tissue-pose-warning';warning.hidden=true;warning.textContent='骨骼已拆开：软组织与穴位暂时隐藏，归位后恢复，避免显示错误的对应关系。';document.querySelector('.stage').append(warning);
 const card=document.createElement('section');card.id='tissueDetail';card.className='tissue-detail';card.hidden=true;document.querySelector('.detail-scroll').prepend(card);
 async function enable(system,on){const s=systems[system];if(!s)return;s.on=!!on;$(system+'On').checked=s.on;if(on&&!s.loaded&&!s.loading){s.loading=true;$(system+'Status').textContent='加载中…';s.promise=(async()=>{try{let bytes;if(window.ATLAS_TISSUE_INLINE?.[system]){const a=atob(window.ATLAS_TISSUE_INLINE[system]);bytes=Uint8Array.from(a,c=>c.charCodeAt(0)).buffer;}else{const r=await fetch('./assets/'+system+'.glb');if(!r.ok)throw Error('HTTP '+r.status);bytes=await r.arrayBuffer();}const gltf=await loader.parseAsync(bytes,'');gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(n=>{if(!n.isMesh||!n.userData.atlas)return;const info=n.userData.atlas;info.system=system;const mat=new THREE.MeshStandardMaterial({color:system==='nervous'?'#d9aa38':info.category==='fascia'?'#c9bba2':'#ad5550',roughness:.78,metalness:0,transparent:s.opacity<1,opacity:s.opacity,depthWrite:s.opacity>.9,side:THREE.DoubleSide});n.material=mat;n.castShadow=false;n.receiveShadow=false;n.userData.atlas.bounds=info.bounds;n.userData.originalMaterial=mat;n.geometry.computeBoundingBox();entries.set(info.id,n);s.meshes.push(n);});root.add(gltf.scene);s.loaded=true;$(system+'Status').textContent=s.meshes.length+'个结构';renderList();}catch(e){s.on=false;$(system+'On').checked=false;$(system+'Status').textContent='加载失败，可重试';toast('软组织加载失败：'+e.message);console.error(e);}finally{s.loading=false;lastKey='';updateFrame();}})();}lastKey='';updateFrame();return s.promise;}
 for(const system of Object.keys(systems)){$(system+'On').onchange=e=>enable(system,e.target.checked);$(system+'Opacity').oninput=e=>{systems[system].opacity=Number(e.target.value)/100;$(system+'OpacityValue').textContent=e.target.value+'%';lastKey='';};}
 $('fasciaOn').onchange=e=>{fascia=e.target.checked;lastKey='';};$('bonesOn').onchange=e=>{state.bonesOn=e.target.checked;ctx.applyVisibility();};$('tissueSearch').oninput=renderList;
 $('tissueClear').onclick=()=>{for(const s of Object.keys(systems))enable(s,false);clearSelection();};
 $('chestCompare').onclick=async()=>{await enable('muscular',true);setRegion('thorax');setView('front');showPanel(false);document.querySelector('.bone-pane').hidden=false;document.body.classList.remove('nav-open');toast('原胸廓坐标未改变；肌肉叠加用于比较外形');};
 function regionBox(){if(state.region==='body')return null;let box=new THREE.Box3();for(const b of bones.values())if(ctx.regionContains(b.name))box.expandByObject(b);if(box.isEmpty())return null;const ranges={head:[1440,1710],auditory:[1470,1600],cervical:[1380,1520],thoracic:[1100,1440],thorax:[1060,1410],shoulder:[1190,1430],upper:[620,1440],elbow:[970,1110],wrist:[765,860],hand:[630,825],foot:[-80,85],ankle:[-80,170],knee:[300,515],lumbar:[880,1110],hip:[735,985],pelvis:[740,985]};if(ranges[state.region]){box.min.y=ranges[state.region][0];box.max.y=ranges[state.region][1];}box.expandByScalar(25);return box;}
 function clipPlanes(b){return b?[new THREE.Plane(new THREE.Vector3(1,0,0),-b.min.x),new THREE.Plane(new THREE.Vector3(-1,0,0),b.max.x),new THREE.Plane(new THREE.Vector3(0,1,0),-b.min.y),new THREE.Plane(new THREE.Vector3(0,-1,0),b.max.y),new THREE.Plane(new THREE.Vector3(0,0,1),-b.min.z),new THREE.Plane(new THREE.Vector3(0,0,-1),b.max.z)]:[];}
 function updateFrame(){const displaced=state.explode>0||[...bones.values()].some(b=>b.userData.offset.lengthSq()>.1||b.quaternion.angleTo(new THREE.Quaternion())>.015);const key=[state.region,state.side,state.isolated,state.selected,displaced,isolated,selected?.id,fascia,...Object.values(systems).flatMap(s=>[s.on,s.loaded,s.opacity])].join('|');if(key===lastKey)return;lastKey=key;ctx.setPerformance(Object.values(systems).some(s=>s.on));clipBox=regionBox();const planes=clipPlanes(clipBox);warning.hidden=!(displaced&&Object.values(systems).some(s=>s.on));root.visible=!displaced&&!state.isolated;for(const [system,s]of Object.entries(systems))for(const n of s.meshes){const m=n.userData.atlas,bb=new THREE.Box3(new THREE.Vector3(...m.bounds[0]),new THREE.Vector3(...m.bounds[1]));n.visible=s.on&&(!isolated||m.id===selected?.id)&&(m.category!=='fascia'||fascia)&&(state.side==='both'||m.side==='midline'||m.side===state.side)&&(!clipBox||bb.intersectsBox(clipBox));n.material.opacity=s.opacity;n.material.transparent=s.opacity<.98;n.material.depthWrite=s.opacity>=.9;n.material.clippingPlanes=isolated?[]:planes;n.material.emissive.set(m.id===selected?.id?'#225c4c':'#000000');n.material.emissiveIntensity=m.id===selected?.id?.2:0;n.material.needsUpdate=true;}if(displaced)ctx.learning.suspend(true);else ctx.learning.suspend(false);}
 function renderList(){const q=$('tissueSearch').value.trim().toLowerCase();const all=[...entries.values()].filter(n=>!q||[n.userData.atlas.name,n.userData.atlas.en].join(' ').toLowerCase().includes(q));$('tissueList').replaceChildren();for(const n of all){const m=n.userData.atlas,b=document.createElement('button');b.dataset.tissue=m.id;b.innerHTML='<b>'+esc(m.name)+'</b><small>'+esc(m.en)+'</small>';b.onclick=()=>choose(m.id,true);$('tissueList').append(b);}if(!all.length)$('tissueList').textContent=entries.size?'未找到该结构':'开启一个图层后可按名称查找和单独查看。';}
 function choose(id,focus=false){const n=entries.get(id);if(!n)return false;selected=n.userData.atlas;card.hidden=false;document.body.classList.add('tissue-detail-active');document.body.classList.remove('point-detail-active');$('tcmPointCard').hidden=true;document.body.classList.remove('point-detail-active');card.innerHTML='<h2>'+esc(selected.name)+'</h2><p>'+esc(selected.en)+'</p><span class="group-tag">'+(selected.system==='muscular'?'肌肉系统':'神经系统')+'</span><p class="tissue-note">来自同一套 Z-Anatomy / BodyParts3D 网格。这里展示结构表面，不代表完整组织微结构；颜色为学习配色。</p><div class="v4-button-row"><button id="tissueIsolate">'+(isolated?'返回图层':'单独查看')+'</button><button id="tissueFocus">聚焦</button><button id="tissueSpeak">朗读</button></div><button id="tissueDetailClose">返回骨骼信息</button>';$('tissueIsolate').onclick=()=>{isolated=!isolated;lastKey='';updateFrame();choose(id,true);};$('tissueFocus').onclick=()=>focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(12));$('tissueSpeak').onclick=()=>speech.speak(selected.name);$('tissueDetailClose').onclick=clearSelection;lastKey='';if(focus){state.isolated=false;ctx.applyVisibility();focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(15));document.body.classList.remove('nav-open');}document.body.classList.add('detail-open');return true;}
 function clearSelection(){selected=null;isolated=false;card.hidden=true;document.body.classList.remove('tissue-detail-active');lastKey='';}
 window.addEventListener('atlas:bone-selected',e=>{if(e.detail.user)clearSelection();});
 function hit(e){if(!root.visible||state.mode!=='orbit')return null;const r=viewport.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(2*(e.clientX-r.left)/r.width-1,1-2*(e.clientY-r.top)/r.height),camera);const ms=[...entries.values()].filter(n=>n.visible&&n.material.opacity>.12);if(!ms.length)return null;return ray.intersectObjects(ms,false).find(x=>!clipBox||isolated||clipBox.containsPoint(x.point))||null;}
 function click(e){const p=hit(e);if(!p)return false;return choose(p.object.userData.atlas.id,false);}
 const api={enable,showPanel,updateFrame,click,hit,choose,clearSelection,getCatalog:()=>[...entries.values()].map(n=>n.userData.atlas),project:id=>{const n=entries.get(id);if(!n)return null;const v=new THREE.Box3().setFromObject(n).getCenter(new THREE.Vector3()).project(camera),r=viewport.getBoundingClientRect();return{x:r.left+(v.x*.5+.5)*r.width,y:r.top+(-v.y*.5+.5)*r.height};},getState:()=>({selected,isolated,displaced:!root.visible,skinLoaded:false,systems:Object.fromEntries(Object.entries(systems).map(([k,s])=>[k,{on:s.on,loaded:s.loaded,loading:s.loading,count:s.meshes.length,visible:s.meshes.filter(n=>n.visible&&root.visible).length,opacity:s.opacity}]))})};window.__ATLAS_TISSUES__=api;return api;
}
