import * as THREE from 'three';
import {MeshBVH} from 'three-mesh-bvh';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export function createSurfaceProjector(meshes,boneCentres){
 const records=[];for(const mesh of meshes){mesh.updateWorldMatrix(true,false);const g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.applyMatrix4(mesh.matrixWorld);if(!g.attributes.normal)g.computeVertexNormals();g.computeBoundingBox();const a=mesh.userData.atlas||{};records.push({g,box:g.boundingBox.clone(),name:(a.en||a.name||mesh.name).toLowerCase(),side:a.side||'midline'});}
 const merge=rows=>{const gs=rows.map(r=>{const g=new THREE.BufferGeometry();g.setAttribute('position',r.g.attributes.position.clone());g.setAttribute('normal',r.g.attributes.normal.clone());return g;});const g=mergeGeometries(gs,false);gs.forEach(x=>x.dispose());return{g,bvh:new MeshBVH(g,{maxLeafTris:12})};};
 const all=merge(records),cache=new Map();let calls=0,rayHits=0,fallbacks=0,maxSourceDistance=0,graph=null,bridges=0,bridgeFallbacks=0;
 function regionOf(v,c){if(c.region)return c.region;const x=Math.abs(v.x-99.553);if(x>160&&v.y>620&&v.y<800)return'hand';if(x>148&&v.y>=800&&v.y<1050)return'forearm';if(x>148&&v.y>=1050&&v.y<1320)return'upper';if(v.y>1450)return'head';if(v.y>1370)return'neck';if(v.y<150)return'foot';if(v.y<580)return'leg';if(v.y<790)return'thigh';return'body';}
 function subset(v,c){const r=regionOf(v,c),side=c.side||'midline',key=r+'|'+side;if(cache.has(key))return cache.get(key);const patterns={forearm:/forearm|wrist|elbow|cubital/,wrist:/wrist|forearm|palm|radial foveola/,hand:/hand|palm|wrist|perionyx|nail plate/,upper:/region of arm|bicipital|elbow|cubital|deltoid/,elbow:/elbow|forearm|cubital|region of arm/,head:/frontal|parietal|occipital|temporal|nasal|oral|labial|buccal|mental|orbital|auric|mastoid|zygomatic|lip|philtrum|eyebrow|tragus|helix|concha/,neck:/neck|triangle|supraclavicular/,leg:/region of leg|knee|malleol|ankle|popliteal/,thigh:/thigh|femoral|hip|knee/,foot:/foot|sole|heel|malleol|ankle|hallucial|metatarsal/};let rows=records.filter(x=>(side==='midline'||x.side==='midline'||x.side===side)&&(!patterns[r]||patterns[r].test(x.name)));if(!rows.length)rows=records;const s=merge(rows);cache.set(key,s);return s;}
 function direction(v,c){const m=c.meridian,r=regionOf(v,c),right=(c.side||'right')!=='left';if(['forearm','wrist','upper','elbow'].includes(r)){if(['LI','TE','SI'].includes(m))return new THREE.Vector3(0,0,-1);if(['LU','HT','PC'].includes(m))return new THREE.Vector3(0,0,1);}if(m==='GV'&&v.y>1530)return new THREE.Vector3(0,Math.max(0,(v.y-1530)/135),(v.z+35)/92).normalize();if(m==='GV')return new THREE.Vector3(0,0,v.y>1460&&v.z>0?1:-1);if(m==='BL'&&v.y<1440)return new THREE.Vector3(0,0,-1);if(c.view){const d=new THREE.Vector3(...c.view);if(c.side==='left')d.x*=-1;return d.normalize();}if(m==='SI'||m==='TE')return new THREE.Vector3(0,0,v.y>1470?1:-1);if(m==='GB')return new THREE.Vector3(right?-1:1,0,.1).normalize();if(m==='KI'&&v.y<80)return new THREE.Vector3(0,-1,0);if(['KI','SP','LR'].includes(m)&&v.y<780)return new THREE.Vector3(right?1:-1,0,.15).normalize();return new THREE.Vector3(0,0,1);}
 function project(v,offset=2.2,c={}){calls++;const s=subset(v,c),d=direction(v,c),origin=v.clone().addScaledVector(d,500),h=s.bvh.raycastFirst(new THREE.Ray(origin,d.clone().negate()),THREE.DoubleSide);let q;if(h&&h.point.distanceTo(v)<80){q=h.point.clone();rayHits++;}else{const near=s.bvh.closestPointToPoint(v);if(!near)throw Error('区域体表不可用');q=near.point.clone();fallbacks++;}maxSourceDistance=Math.max(maxSourceDistance,q.distanceTo(v));return q.addScaledVector(d,offset);}
 function makeGraph(){if(graph)return graph;const pos=all.g.attributes.position,normal=all.g.attributes.normal,ids=new Uint32Array(pos.count),vertices=[],normals=[],adj=[],cells=new Map(),cell=3.5;
  const key=(x,y,z)=>x+','+y+','+z;
  for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i),n=new THREE.Vector3().fromBufferAttribute(normal,i),x=Math.floor(v.x/cell),y=Math.floor(v.y/cell),z=Math.floor(v.z/cell);let found=-1,d=cell*cell;
   for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)for(let c=-1;c<=1;c++)for(const id of cells.get(key(x+a,y+b,z+c))||[]){const q=vertices[id].distanceToSquared(v);if(q<d&&normals[id].dot(n)>.1){found=id;d=q;}}
   if(found<0){found=vertices.length;vertices.push(v);normals.push(n);adj.push(new Set());const k=key(x,y,z);if(!cells.has(k))cells.set(k,[]);cells.get(k).push(found);}ids[i]=found;
  }
  const index=all.g.index,at=i=>ids[index?index.getX(i):i],count=index?index.count:pos.count;
  for(let i=0;i<count;i+=3){const a=at(i),b=at(i+1),c=at(i+2);if(a!==b){adj[a].add(b);adj[b].add(a);}if(a!==c){adj[a].add(c);adj[c].add(a);}if(b!==c){adj[b].add(c);adj[c].add(b);}}
  graph={vertices,normals,adj,ids};return graph;
 }
 function surfacePath(start,end,context){const G=makeGraph(),idx=all.g.index,vert=(p)=>{const hit=all.bvh.closestPointToPoint(p);if(!hit)return null;const vs=[0,1,2].map(k=>G.ids[idx?idx.getX(hit.faceIndex*3+k):hit.faceIndex*3+k]);return vs.sort((a,b)=>G.vertices[a].distanceToSquared(p)-G.vertices[b].distanceToSquared(p))[0];},s=vert(start),goal=vert(end);if(s==null||goal==null)return null;
  const direct=start.distanceTo(end),limit=direct*3+80,heap=[],cost=new Map([[s,0]]),parent=new Map();
  function push(id,f){let i=heap.length;heap.push({id,f});while(i){const k=(i-1)>>1;if(heap[k].f<=f)break;heap[i]=heap[k];i=k;}heap[i]={id,f};}
  function pop(){const r=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let k=i*2+1;if(k+1<heap.length&&heap[k+1].f<heap[k].f)k++;if(heap[k].f>=last.f)break;heap[i]=heap[k];i=k;}heap[i]=last;}return r;}
  push(s,G.vertices[s].distanceTo(G.vertices[goal]));const closed=new Set();let steps=0;
  while(heap.length&&steps++<40000){const{id}=pop();if(closed.has(id))continue;if(id===goal){const path=[];let k=id;while(k!==undefined){let n=G.normals[k].clone(),d=direction(G.vertices[k],context);if(n.dot(d)<0)n.negate();path.push(G.vertices[k].clone().addScaledVector(n,2.2));k=parent.get(k);}return[start.clone(),...path.reverse(),end.clone()];}closed.add(id);const current=cost.get(id);for(const n of G.adj[id]){const v=G.vertices[n];if(v.distanceTo(start)+v.distanceTo(end)>limit)continue;const candidate=current+G.vertices[id].distanceTo(v);if(candidate<(cost.get(n)??Infinity)){cost.set(n,candidate);parent.set(n,id);push(n,candidate+v.distanceTo(G.vertices[goal]));}}}
  return null;
 }
 function curve(source,context={}){
  const c=new THREE.CatmullRomCurve3(source.map(v=>v.clone()),false,'centripetal'),count=Math.max(24,Math.min(2300,Math.ceil(c.getLength()/2.5))),refs=c.getSpacedPoints(count),raw=refs.map(v=>project(v,2.2,context)),points=[],samples=[];
  // Remove isolated ray-hit spikes, not sustained anatomy changes.
  for(let i=1;i<raw.length-1;i++){if(raw[i-1].distanceTo(raw[i+1])<9&&raw[i].distanceTo(raw[i-1])>20&&raw[i].distanceTo(raw[i+1])>20)raw[i].copy(raw[i-1]).lerp(raw[i+1],.5);}
  for(let i=0;i<raw.length;i++){if(i&&raw[i].distanceTo(raw[i-1])>18){let path=surfacePath(raw[i-1],raw[i],context);if(path){bridges++;}else{bridgeFallbacks++;path=[raw[i-1],raw[i]];}
    const length=path.slice(1).reduce((n,v,j)=>n+v.distanceTo(path[j]),0);let travelled=0;
    for(let j=1;j<path.length;j++){const a=path[j-1],b=path[j],len=a.distanceTo(b),n=Math.max(1,Math.ceil(len/3));for(let k=1;k<n;k++){const t=k/n,q=a.clone().lerp(b,t),u=length?(travelled+len*t)/length:0;points.push(q);samples.push({source:refs[i-1].clone().lerp(refs[i],u),point:q.clone()});}points.push(b.clone());samples.push({source:refs[i-1].clone().lerp(refs[i],length?(travelled+len)/length:1),point:b.clone()});travelled+=len;}
   }else{points.push(raw[i].clone());samples.push({source:refs[i].clone(),point:raw[i].clone()});}}
  const sm=points.map(v=>v.clone());for(let pass=0;pass<2;pass++){const next=sm.map(v=>v.clone());for(let i=1;i<sm.length-1;i++){const v=sm[i-1].clone().addScaledVector(sm[i],2).add(sm[i+1]).multiplyScalar(.25);if(v.distanceTo(sm[i])<3)next[i].copy(v);}sm.splice(0,sm.length,...next);}
  for(let i=0;i<samples.length;i++)samples[i].point.copy(sm[i]);const route=new THREE.CatmullRomCurve3(sm,false,'centripetal');route.arcLengthDivisions=sm.length;return {geometry:new THREE.TubeGeometry(route,Math.min(6500,sm.length),1.15,10,false),points:sm,samples};
 }
 function isVisible(v,cp){const d=v.clone().sub(cp),len=d.length(),hit=all.bvh.raycastFirst(new THREE.Ray(cp,d.normalize()),THREE.DoubleSide);return !hit||hit.distance>=len-2.5;}
 return{project,curve,isVisible,stats:()=>({version:13,method:'regional directional projection with connected-surface transitions',calls,rayHits,fallbacks,maxSourceDistance,regions:cache.size,surfacePathBridges:bridges,unconnectedDisplayBridges:bridgeFallbacks,clinicalCalibration:false}),dispose:()=>{all.g.dispose();cache.forEach(s=>s.g.dispose());records.forEach(r=>r.g.dispose());}};
}
