import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import decoderSource from './draco-decoder.txt';
export function initFemale(ctx){
 const {THREE,scene,camera,renderer,viewport,controls,state,bones,modelRoot,learning,tissues,speech,toast,focusBounds,invalidate,setMode,applyVisibility,resetBones,setRegion,renderNow}=ctx;
 const $=s=>document.getElementById(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const groupNames={surface:'体表外形',breast:'乳腺结构',respiratory:'肺与气道',vascular:'心脏与血管',digestive:'消化系统',urinary:'泌尿系统',reproductive:'女性生殖',skeletal:'骨骼与关节（部分）',nervous:'脑、脊髓与感官',muscular:'肌肉（部分）',lymphatic:'淋巴与免疫'};
 const colors={surface:'#cbaf97',breast:'#b87678',respiratory:'#a56871',vascular:'#a5444e',digestive:'#ad8164',urinary:'#a86466',reproductive:'#a55876',skeletal:'#e4d9bb',nervous:'#b78837',muscular:'#98575a',lymphatic:'#638368'};
 const root=new THREE.Group();root.name='HRA Female Reference (separate source)';root.visible=false;scene.add(root);
 const maps=new Map(),systems=new Map(),hidden=new Set();let catalog=null,loadCatalog=null,active=false,serial=0,preset='surface',selected=null,isolated=false,mode='solid',side='both',saved=null,viewName='front';
 const draco=new DRACOLoader().setDecoderConfig({type:'js'}).setWorkerLimit(2);draco._loadLibrary=()=>Promise.resolve(decoderSource);const loader=new GLTFLoader().setDRACOLoader(draco);
 const pane=document.createElement('section');pane.id='femaleLibrary';pane.hidden=true;
 pane.innerHTML='<button id="femaleCloseNav" class="female-drawer-close" aria-label="收起女性目录">收起目录 ×</button><h2>女性参考模型</h2><p class="female-scope">独立女性体表与器官；部分骨骼和肌肉。</p><div class="female-presets">'+[['surface','体表外形'],['chest','胸腔心肺'],['abdomen','腹部器官'],['pelvis','盆腔与生殖'],['breast','乳腺结构'],['nerves','脑与脊髓'],['vessels','心血管'],['bones','骨骼与关节']].map(([id,n])=>`<button data-female-preset="${id}">${n}</button>`).join('')+'</div><div class="female-mode"><span>显示方式</span><select id="femaleMode" aria-label="女性显示方式"><option value="solid">原色清晰</option><option value="context">透明参照</option><option value="focus">突出所选</option></select></div><div class="female-mode"><span>左右范围</span><select id="femaleSide"><option value="both">双侧与中线</option><option value="left">人体左侧＋中线</option><option value="right">人体右侧＋中线</option></select></div><details id="femaleLayers"><summary>自定义图层</summary>'+Object.entries(groupNames).map(([id,n])=>`<label><input type="checkbox" data-female-layer="${id}">${n}<small id="femaleStatus-${id}"></small></label>`).join('')+'</details><label class="search-box"><input id="femaleSearch" type="search" placeholder="名称 / 拼音 / English"></label><div id="femaleCount"></div><div id="femaleResults"></div>';
 document.querySelector('.sidebar').append(pane);$('femaleCloseNav').onclick=()=>document.body.classList.remove('nav-open');
 const detail=document.createElement('section');detail.id='femaleDetail';detail.className='female-detail';detail.hidden=true;document.querySelector('.detail-panel').append(detail);
 const tag=document.createElement('div');tag.id='femalePointLabel';tag.hidden=true;viewport.append(tag);
 const switcher=document.createElement('div');switcher.id='bodySelector';switcher.setAttribute('aria-label','参考人体');switcher.innerHTML='<button data-body-sex="male" aria-pressed="true" class="active">男性</button><button data-body-sex="female" aria-pressed="false">女性</button>';$('releaseBadge').after(switcher);
 switcher.querySelectorAll('button').forEach(b=>b.onclick=()=>setSex(b.dataset.bodySex).catch(e=>toast(e.message)));
 pane.querySelectorAll('[data-female-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.femalePreset).catch(e=>toast(e.message)));
 pane.querySelectorAll('[data-female-layer]').forEach(b=>b.onchange=()=>enable(b.dataset.femaleLayer,b.checked).then(()=>{preset='custom';isolated=false;update();}).catch(e=>toast(e.message)));
 $('femaleMode').onchange=e=>{mode=e.target.value;update();};$('femaleSide').onchange=e=>{side=e.target.value;update();};$('femaleSearch').oninput=renderList;
 function urlState(){if(!active||restoringFemaleHash)return;const h=new URLSearchParams({sex:'female',preset,mode,side});if(selected)h.set('id',selected);try{history.replaceState(null,'','#'+h);}catch{}}
 async function getCatalog(){if(catalog)return catalog;if(!loadCatalog)loadCatalog=fetch('../fullbody-tcm-v12/assets/female/catalog.json').then(r=>{if(!r.ok)throw Error('女性目录加载失败');return r.json();}).then(d=>catalog=d).catch(e=>{loadCatalog=null;throw e;});return loadCatalog;}
 function color(r){if(r.system==='vascular'&&/vein|vena/i.test(r.sourceName))return '#4c78a6';if(/liver/i.test(r.sourceName))return '#805054';if(/gallbladder/i.test(r.sourceName))return '#6b865d';if(r.system==='breast'&&/fat/.test(r.sourceName))return '#c4af74';return colors[r.system];}
 async function enable(id,on){let s=systems.get(id);if(!s){s={on:false,loaded:false,promise:null,meshes:[]};systems.set(id,s);}s.on=!!on;const cb=pane.querySelector(`[data-female-layer="${id}"]`);if(cb)cb.checked=s.on;
  if(on&&!s.loaded){if(!s.promise){$('femaleStatus-'+id).textContent='加载中';invalidate();s.promise=(async()=>{await getCatalog();const doc=await loader.loadAsync('../fullbody-tcm-v12/assets/female/'+id+'.glb');doc.scene.updateMatrixWorld(true);doc.scene.traverse(n=>{if(!n.isMesh)return;const row=catalog.entries.find(r=>r.id===n.name);if(!row)throw Error('女性结构无来源记录');n.userData.female=row;n.material=new THREE.MeshStandardMaterial({color:color(row),roughness:.73,metalness:0,envMapIntensity:.19,side:THREE.DoubleSide});n.geometry.computeBoundingBox();n.renderOrder=3;maps.set(row.id,n);s.meshes.push(n);});root.add(doc.scene);s.loaded=true;$('femaleStatus-'+id).textContent=s.meshes.length+'结构';update();renderList();})().catch(e=>{s.promise=null;s.on=false;if(cb)cb.checked=false;$('femaleStatus-'+id).textContent='重试';throw e;});}await s.promise;}
  update();renderList();return s;
 }
 function contextMatch(r){if(preset==='chest')return r.system==='respiratory'||r.system==='vascular'&&r.ancestry.some(n=>/heart|aorta|vena_cava|pulmonary/.test(n));if(preset==='pelvis')return r.system==='reproductive'||r.system==='skeletal'&&r.ancestry.includes('VH_F_pelvis')||r.system==='urinary'&&/bladder|urethra|ureter/.test(r.sourceName);return true;}
 function coarse(r){if(r.system==='respiratory')return true;if(r.system==='skeletal')return !/spongy|enthesis|most_point|condyle_|perichondular|trochlear|fossa/.test(r.sourceName);if(r.system==='urinary')return !/papilla|pyramid|medulla|calyx/.test(r.sourceName);if(r.system==='digestive')return !/couinaud|capsule|ligament/.test(r.sourceName);return true;}
 function update(){root.visible=active;for(const [id,s] of systems){for(const n of s.meshes){const r=n.userData.female;n.visible=s.on&&!hidden.has(r.id)&&(side==='both'||r.side==='midline'||r.side===side)&&contextMatch(r)&&coarse(r)&&(!isolated||r.id===selected);if(r.id===selected)n.visible=s.on&&!hidden.has(r.id);const focus=mode==='focus'&&selected&&r.id!==selected;let opacity=focus?.12:mode==='context'&&r.system==='surface'?.18:1;if(mode==='context'&&r.system==='skeletal')opacity=.4;if(mode==='context'&&r.system==='breast'&&/fat/.test(r.sourceName))opacity=.16;n.material.transparent=opacity<1;n.material.opacity=opacity;n.material.depthWrite=opacity>.9;n.material.emissive.set(r.id===selected?'#946324':'#000000');n.material.emissiveIntensity=r.id===selected?.2:0;}}
  if(active){state.bonesOn=false;modelRoot.visible=false;$('regionHeading').textContent='女性 · '+({surface:'体表外形',chest:'胸腔心肺',abdomen:'腹部器官',pelvis:'盆腔与生殖',breast:'乳腺结构',nerves:'脑与脊髓',vessels:'心血管',bones:'骨骼与关节',custom:'自定义观察'}[preset]||'参考模型');$('visibleCount').textContent=[...maps.values()].filter(n=>n.visible).length+' 个结构';}
  pane.querySelectorAll('[data-female-preset]').forEach(b=>b.classList.toggle('active',b.dataset.femalePreset===preset));urlState();updateLabel();invalidate();
 }
 function visible(){return [...maps.values()].filter(n=>active&&n.visible);}
 function fit(dir){const ns=selected&&isolated?[maps.get(selected)]:visible();const box=new THREE.Box3();ns.forEach(n=>n&&box.expandByObject(n));if(!box.isEmpty()){focusBounds(box.expandByScalar(preset==='pelvis'?25:15),{direction:dir||[0,.04,1],up:[0,1,0]});camera.position.sub(controls.target).multiplyScalar(preset==='surface'?1.18:1.06).add(controls.target);controls.update();camera.updateMatrixWorld(true);invalidate();}}
 function focus(){const n=maps.get(selected);if(n?.visible)focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(12),{direction:camera.position.clone().sub(controls.target).normalize().toArray(),up:[0,1,0]});else fit();}
 function view(name){const dirs={front:[0,0,1],back:[0,0,-1],overview:[.8,.25,1],medial:[1,0,0],lateral:[-1,0,0],dorsal:[0,1,.01],plantar:[0,-1,.01]};if(!dirs[name])return;viewName=name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('viewBadge').lastElementChild.textContent={front:'前面',back:'后面',overview:'立体',medial:'人体左面',lateral:'人体右面',dorsal:'上方',plantar:'下方'}[name];fit(dirs[name]);}
 async function setPreset(id,options={}){const cfg={surface:['surface'],chest:['respiratory','vascular'],abdomen:['digestive','urinary'],pelvis:['reproductive','skeletal','urinary'],breast:['breast'],nerves:['nervous'],vessels:['vascular'],bones:['skeletal','surface'],muscles:['muscular','surface'],compare:['surface','skeletal','nervous']}[id];if(!cfg)return false;const token=++serial;preset=id;hidden.clear();selected=null;isolated=false;side='both';$('femaleSide').value='both';mode=['breast','compare','bones','muscles'].includes(id)?'context':'solid';$('femaleMode').value=mode;for(const[key,s]of systems){s.on=cfg.includes(key);const cb=pane.querySelector(`[data-female-layer="${key}"]`);if(cb)cb.checked=s.on;}showIntro();update();await Promise.all(cfg.map(k=>enable(k,true)));if(!active||token!==serial)return false;update();renderList();if(!options.preserveView)view('front');if(!options.preservePanel)document.body.classList.remove('nav-open','detail-open');return true;}
 function showIntro(){detail.hidden=false;detail.innerHTML='<button id="femaleCloseDetail" class="female-drawer-close" aria-label="收起女性详情">收起详情 ×</button><span class="group-tag">女性参考 · HRA</span><h2>'+({surface:'女性体表',chest:'胸腔心肺',abdomen:'腹部器官',pelvis:'盆腔与生殖',breast:'乳腺结构',nerves:'脑与脊髓',vessels:'心血管',bones:'骨骼与关节'}[preset]||'女性结构')+'</h2><p>点击结构或左侧目录，查看名称、聚焦与单独观察。</p><div class="female-actions"><button id="femaleFitAll">适配当前范围</button><button id="femaleRestore">恢复当前场景</button></div><details><summary>女性模型来源与覆盖</summary><p>HRA / HuBMAP，Visible Human Female 参考集 v1.5。独立于男性模型；不混用男性骨骼或穴位。体表与部分器官已接入，骨骼、肌肉与周围神经的覆盖不完整。</p><a href="https://purl.humanatlas.io/ref-organ/united-female/v1.5" target="_blank" rel="noopener">查看原始来源 ↗</a></details>';bindDetail();}
 function bindDetail(){$('femaleCloseDetail')&&($('femaleCloseDetail').onclick=()=>document.body.classList.remove('detail-open'));$('femaleFitAll')&&($('femaleFitAll').onclick=()=>fit());$('femaleRestore')&&($('femaleRestore').onclick=()=>setPreset(preset==='custom'?'surface':preset));$('femaleFocus')&&($('femaleFocus').onclick=focus);$('femaleIsolate')&&($('femaleIsolate').onclick=()=>{isolated=!isolated;update();focus();showSelected();});$('femaleSpeak')&&($('femaleSpeak').onclick=()=>speech.speak?.(maps.get(selected)?.userData.female.name||''));$('femaleHide')&&($('femaleHide').onclick=()=>{const n=maps.get(selected);if(n){hidden.add(selected);n.visible=false;}selected=null;isolated=false;tag.hidden=true;renderList();showIntro();invalidate();});}
 function showSelected(){const r=maps.get(selected)?.userData.female;if(!r)return showIntro();detail.hidden=false;detail.innerHTML=`<button id="femaleCloseDetail" class="female-drawer-close" aria-label="收起女性详情">收起详情 ×</button><span class="group-tag">${esc(groupNames[r.system])}</span><h2>${esc(r.name)}</h2><p class="female-pinyin">${esc(r.pinyin||'')}</p><p class="female-english">${esc(r.english)}</p><div class="female-actions"><button id="femaleFocus">聚焦当前</button><button id="femaleIsolate">${isolated?'恢复周围':'单独查看'}</button><button id="femaleHide">隐藏此结构</button><button id="femaleSpeak">朗读名称</button><button id="femaleFitAll">适配范围</button><button id="femaleRestore">恢复当前场景</button></div><h3>当前模型位置</h3><p>${esc(r.side==='left'?'人体左侧':r.side==='right'?'人体右侧':'中线或跨侧结构')} · ${esc(groupNames[r.system])}</p><p>可旋转查看外形；单独查看会暂时隐藏其他结构。</p><details><summary>名称与来源</summary><p>${esc(r.sourceName)}</p><p>HRA 女性参考集 v1.5，保留源结构。该参考集的骨骼、肌肉覆盖不完整。</p>${r.ontology?`<a href="${esc(r.ontology)}" target="_blank" rel="noopener">解剖本体条目 ↗</a>`:''}</details>`;bindDetail();}
 async function select(id,doFocus=true){await getCatalog();const row=catalog.entries.find(r=>r.id===id);if(!row)return false;await enable(row.system,true);if(!active)return false;hidden.delete(id);const keepIsolated=isolated&&selected===id;selected=id;isolated=keepIsolated;if(!contextMatch(row))preset='custom';side='both';$('femaleSide').value='both';update();showSelected();renderList();if(doFocus)focus();document.body.classList.remove('nav-open');document.body.classList.add('detail-open');return true;}
 function renderList(){if(!catalog)return;const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s/g,'');const q=norm($('femaleSearch').value);const arr=q?catalog.entries.filter(r=>norm([r.name,r.pinyin,r.english,r.id,r.sourceName].join(' ')).includes(q)):visible().map(n=>n.userData.female);$('femaleCount').textContent=(q?'搜索结果 ':'当前可见 ')+arr.length+' 个结构';$('femaleResults').innerHTML=arr.map(r=>`<button data-female-select="${r.id}" class="${r.id===selected?'active':''}"><b>${esc(r.name)}</b><small>${esc(r.pinyin||r.english)}</small></button>`).join('');$('femaleResults').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.femaleSelect,true).catch(e=>toast(e.message)));}
 let sexSerial=0,sexBusy=false;
 const femaleSceneForMale=()=>({chest:'chest',heart:'chest',abdomen:'abdomen',vascular:'vessels',surface:'surface',bones:'bones',muscles:'surface',nerves:'nerves',compare:'surface'}[tissues.getState().profile]||'surface');
 const sceneLayers={surface:['surface'],chest:['respiratory','vascular'],abdomen:['digestive','urinary'],pelvis:['reproductive','skeletal','urinary'],breast:['breast'],nerves:['nervous'],vessels:['vascular'],bones:['skeletal','surface']};
 function transferView(v,toFemale){
  // Frame normalization preserves angle and apparent scale, not clinical registration.
  const scale=toFemale?1666.348/1700:1700/1666.348,from=toFemale?[99.553,0,-20]:[94.159,-34.761,-58],to=toFemale?[94.159,-34.761,-58]:[99.553,0,-20];
  const map=a=>a.map((x,i)=>to[i]+(x-from[i])*scale);return {...v,position:map(v.position),target:map(v.target),near:v.near*scale,far:v.far*scale};
 }
 async function setSex(sex){
  if(!['male','female'].includes(sex))return false;
  const ticket=++sexSerial;if((sex==='female')===active&&!sexBusy)return true;sexBusy=true;switcher.setAttribute('aria-busy','true');
  try{if(sex==='female'){
   const wanted=femaleSceneForMale();await getCatalog();await Promise.all(sceneLayers[wanted].map(k=>enable(k,true)));if(ticket!==sexSerial)return false;
   const priorCamera=ctx.captureCamera(),viewState={nav:document.body.classList.contains('nav-open'),detail:document.body.classList.contains('detail-open')};
   saved={view:state.view,region:state.region,side:state.side,bonesOn:state.bonesOn,profile:tissues.getState().profile,systems:tissues.getState().systems,cameraState:priorCamera,surfaceAttached:learning.getState().surfaceAttached,enabled:learning.getState().enabled};
   speech.stop?.();setMode('orbit');learning.cancelPendingFocus?.();learning.toggleTCM(false);learning.suspend(true);
   for(const k of Object.keys(tissues.getState().systems))await tissues.enable(k,false);if(ticket!==sexSerial)return false;
   tissues.clearSelection();state.bonesOn=false;applyVisibility();active=true;state.bodySex='female';document.body.classList.add('female-view','organ-view-active');modelRoot.visible=false;root.visible=true;pane.hidden=false;detail.hidden=false;
   await setPreset(wanted,{preserveView:true,preservePanel:true});if(ticket!==sexSerial)return false;
   ctx.restoreCamera(transferView(priorCamera,true));document.body.classList.toggle('nav-open',viewState.nav);document.body.classList.toggle('detail-open',viewState.detail);
  }else{
   if(!active)return true;const priorCamera=ctx.captureCamera();serial++;active=false;state.bodySex='male';root.visible=false;pane.hidden=true;detail.hidden=true;tag.hidden=true;document.body.classList.remove('female-view','organ-view-active');modelRoot.visible=true;
   state.bonesOn=saved?.bonesOn??true;await tissues.setProfile(saved?.profile&&saved.profile!=='custom'?saved.profile:'bones');if(ticket!==sexSerial)return false;
   setRegion(saved?.region||'body',false);ctx.setSide(saved?.side||'both');
   if(saved?.systems)for(const[k,v]of Object.entries(saved.systems)){await tissues.enable(k,v.on);tissues.setOpacity(k,v.opacity);}
   state.bonesOn=saved?.bonesOn??true;applyVisibility();learning.suspend(false);if(saved?.surfaceAttached)await tissues.attachSurface(true);learning.toggleTCM(!!saved?.enabled);
   ctx.restoreCamera(transferView(priorCamera,false));$('renderStatus').textContent='男性 · 解剖参考';try{history.replaceState(null,'',location.pathname+location.search);}catch{}
  }
  syncSex();invalidate();window.dispatchEvent(new CustomEvent('atlas:sex-changed',{detail:{sex:active?'female':'male'}}));return true;
  }catch(e){toast('模型切换失败，可重试：'+e.message);throw e;}finally{if(ticket===sexSerial){sexBusy=false;switcher.setAttribute('aria-busy','false');syncSex();}}
 }
 function syncSex(){switcher.querySelectorAll('button').forEach(b=>{const on=(b.dataset.bodySex==='female')===active;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
 const ray=new THREE.Raycaster();function hit(e){if(!active)return null;const r=viewport.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);return ray.intersectObjects(visible(),false)[0]||null;}
 function click(e){const h=hit(e);if(h){select(h.object.name,false);return true;}return false;}
 function updateLabel(){if(active){const n=visible().length+' 个女性结构';if($('visibleCount').textContent!==n)$('visibleCount').textContent=n;if($('renderStatus').textContent!=='女性 · HRA参考')$('renderStatus').textContent='女性 · HRA参考';}if(!active||!selected){tag.hidden=true;return;}const n=maps.get(selected);if(!n?.visible){tag.hidden=true;return;}const v=new THREE.Box3().setFromObject(n).getCenter(new THREE.Vector3()).project(camera),r=viewport.getBoundingClientRect();tag.hidden=v.z<-1||v.z>1;tag.textContent=n.userData.female.name;tag.style.left=Math.max(5,Math.min(r.width-180,(v.x*.5+.5)*r.width+10))+'px';tag.style.top=Math.max(30,Math.min(r.height-80,(-v.y*.5+.5)*r.height))+'px';}
 function getPickPoint(id){const n=maps.get(id);if(!n?.visible||!active)return null;const box=new THREE.Box3().setFromObject(n),r=viewport.getBoundingClientRect(),vs=[];for(let i=0;i<8;i++)vs.push(new THREE.Vector3(i&1?box.max.x:box.min.x,i&2?box.max.y:box.min.y,i&4?box.max.z:box.min.z).project(camera));const xs=vs.map(v=>r.left+(v.x*.5+.5)*r.width),ys=vs.map(v=>r.top+(-v.y*.5+.5)*r.height);for(const x of [.5,.3,.7,.15,.85])for(const y of [.5,.3,.7,.15,.85]){const p={x:Math.min(...xs)+(Math.max(...xs)-Math.min(...xs))*x,y:Math.min(...ys)+(Math.max(...ys)-Math.min(...ys))*y};if(hit({clientX:p.x,clientY:p.y})?.object.name===id)return p;}return null;}
 async function capture(){await document.fonts?.ready;renderNow();const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;const g=c.getContext('2d');g.drawImage(renderer.domElement,0,0);const name=maps.get(selected)?.userData.female.name||'女性参考';g.fillStyle='rgba(247,250,242,.96)';g.fillRect(0,c.height-74,c.width,74);g.fillStyle='#315440';g.font='18px sans-serif';g.fillText('女性 · '+name,18,c.height-44);g.font='13px sans-serif';g.fillText('HRA / HuBMAP · CC BY 4.0 · 女性独立参考 · 部分系统覆盖 · V13',18,c.height-18);const blob=await new Promise(r=>c.toBlob(r));const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='人体研习-女性-'+name+'-V13.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);return {name,bytes:blob.size,female:true};}
 document.addEventListener('click',e=>{if(!active)return;const t=e.target.closest('button');if(!t)return;const v=t.dataset.view;if(v){e.preventDefault();e.stopImmediatePropagation();view(v);return;}if(['homeBtn','focusBtn','captureBtn','focusCurrent','overallCurrent'].includes(t.id)){e.preventDefault();e.stopImmediatePropagation();if(t.id==='captureBtn')capture();else if(t.id==='focusBtn'||t.id==='focusCurrent')focus();else{selected=null;isolated=false;update();fit();showIntro();}}},true);
 document.addEventListener('keydown',e=>{if(!active||e.target.closest?.('input,textarea,select')||e.ctrlKey||e.metaKey||document.querySelector('dialog[open]'))return;const keyViews={'1':'overview','2':'dorsal','3':'plantar','4':'medial','5':'lateral','6':'front','7':'back'};if(keyViews[e.key]){e.preventDefault();e.stopImmediatePropagation();view(keyViews[e.key]);return;}if(['f','h','g','t','l'].includes(e.key.toLowerCase())){e.preventDefault();e.stopImmediatePropagation();if(e.key.toLowerCase()==='f')focus();if(e.key.toLowerCase()==='h'){isolated=false;selected=null;update();fit();showIntro();}}},true);
 const api={setDisplayMode:v=>{if(['solid','context','focus'].includes(v)){mode=v;$('femaleMode').value=v;update();}},setSide:v=>{if(['both','left','right'].includes(v)){side=v;$('femaleSide').value=v;update();}},get active(){return active;},setSex,setPreset,select,enable,focus,fit,view,click,capture,updateFrame:updateLabel,getPickPoint,getCatalog:()=>catalog?.entries||[],getState:()=>({sexBusy,active,preset,mode,side,view:viewName,selected,isolated,source:'HRA united-female v1.5',maleMixedIn:false,visible:visible().length,hidden:[...hidden],loaded:maps.size,systems:Object.fromEntries([...systems].map(([k,s])=>[k,{on:s.on,loaded:s.loaded,count:s.meshes.length}]))})};window.__ATLAS_FEMALE__=api;
 let restoringFemaleHash=false,pendingFemaleHash=null;
 async function restoreFemaleLink(raw){
  pendingFemaleHash=raw;if(restoringFemaleHash)return;restoringFemaleHash=true;
  try{while(pendingFemaleHash!==null){
   const text=pendingFemaleHash;pendingFemaleHash=null;
   const h=new URLSearchParams(text.replace(/^#/,''));
   if(h.get('sex')!=='female')continue;
   await setSex('female');
   await setPreset(h.get('preset')||'surface');
   if(h.get('id'))await select(h.get('id'),true);
   mode=['solid','context','focus'].includes(h.get('mode'))?h.get('mode'):'solid';
   side=['left','right','both'].includes(h.get('side'))?h.get('side'):'both';
   $('femaleMode').value=mode;$('femaleSide').value=side;update();
  }}catch(e){toast('女性链接恢复失败：'+e.message);}
  finally{restoringFemaleHash=false;urlState();invalidate();}
 }
 window.addEventListener('hashchange',()=>{const raw=location.hash;if(new URLSearchParams(raw.slice(1)).get('sex')==='female')restoreFemaleLink(raw);});
 const initial=ctx.initialHash||location.hash;
 if(new URLSearchParams(initial.slice(1)).get('sex')==='female')queueMicrotask(()=>restoreFemaleLink(initial));

 return api;
}
