import {evidenceData as DATA} from './catalog-v10.js';
export const evidenceData=DATA;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=k=>{const s=DATA.sources[k];return s?`<a target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">${esc(s.title)} ↗</a>`:'';};
export function evidenceBody(p){
 const r=DATA.points[p.code],h=DATA.headExamples[p.name];
 if(!r)return `<section class="v9-evidence"><h4>部位与名称</h4><p>${esc(h?.[0]||p.locationNote||'补充部位导航')}</p><details><summary>来源与补充说明</summary><p>光环表示观察范围，不是精确穴位。本条目的单穴现代证据尚未录入。</p>${link(h?.[2]||'tara')}</details></section>`;
 return `<section class="v9-evidence"><p class="v10-point-summary"><b>${esc(r.name)} · ${esc(r.region)}</b><br>${esc(r.location)}</p><h4>名称与传统分类</h4><p>${esc(r.traditional)}</p><h4>现代研究</h4><span class="v9-level">${esc(r.evidenceLevel)}</span><p>${esc(r.evidence)}</p><p class="v9-source">${r.evidenceSources.map(link).join('<br>')}</p><details class="v12-point-source"><summary>定位依据与来源</summary><p>${esc(r.locationStatus)}</p><p>需要的标志：${esc(r.requiredLandmarks)}</p><p>${esc(r.anatomyCaution)}</p>${link('who')}<br>${link('gb')}<p>本模型位置尚未校准；体表投影只改变画面，不用于准确取穴。传统分类不等于现代疗效证据。</p></details></section>`;
}
export function pointCardV9(p,m,byID){return `<div class="tcm-card-head"><span>${esc(m.name)} · ${esc(p.code)}</span><button id="closePointCard">收起</button></div><h3>${esc(p.name)}<small>${esc(p.pinyin)} · ${p.side==='left'?'人体左侧':p.side==='right'?'人体右侧':'中线／组合'}</small></h3><div class="tcm-card-actions"><button id="focusPointBtn">看相关部位</button><button id="speakPointBtn">朗读穴名</button></div><div class="point-step"><button id="pointPrev">上一穴</button><button id="pointNext">下一穴</button></div>${evidenceBody(p)}<details class="bone-reference"><summary>附近骨性参照（不是已核实的医学关联）</summary>${(p.landmarks||[]).filter(id=>byID[id]).map(id=>`<button data-near="${esc(id)}">${esc(byID[id].name)}</button>`).join('')||'尚无已核验的结构关联'}</details>`;}
export function channelBody(ids){return ids.map(id=>{const m=DATA.meridians[id];if(!m)return '<p>经外补充不属于十四经目录；点击名称查看其单独资料状态。</p>';return `<article class="v9-channel"><h3>${esc(m.name)}<small>${esc(m.pinyin)} · ${m.id} · ${m.count}个名称</small></h3><h4>名称与分类</h4><p>${esc(m.meaning)}</p>${m.paired?`<p>传统表里配对：${esc(DATA.meridians[m.paired].name)}。这是传统分类关系，不是现代神经吻合关系。</p>`:''}<h4>当前图中的范围</h4><p>${esc(m.regions)}</p><p>${esc(m.coverage)}</p><h4>现代解读</h4><p>${esc(m.modern)}</p><p class="v9-source">${m.sourceKeys.map(link).join('<br>')}</p></article>`;}).join('');}
export function mountEvidenceUI(api){
 const panel=document.getElementById('tcmControls'),intro=document.createElement('section');intro.className='v9-mode-box';intro.innerHTML='<div class="v12-acu-actions"><button id="v9ChannelInfo">所选经脉介绍</button><button id="v12SourceInfo">来源与说明</button></div><details class="v12-acu-options"><summary>显示选项</summary><label><input id="v9Strict" type="checkbox">只读资料，暂不显示点线</label><button id="v9Diagram">只读资料</button></details>';panel.querySelector('.tcm-head').after(intro);
 const badge=document.createElement('div');badge.id='v9PrecisionBadge';badge.className='v9-precision-badge';document.querySelector('.stage').append(badge);
 const sync=v=>{document.getElementById('v9Strict').checked=v;document.getElementById('v9Diagram').textContent=v?'显示三维示意':'只读资料';badge.textContent=v?'资料模式':'经络示意 · 未校准';badge.hidden=!api.getState().enabled;};
 const set=v=>{api.setPrecisionMode(v?'strict':'illustrative');sync(v);};window.addEventListener('atlas:precision-changed',()=>sync(api.getState().precisionMode==='strict'));document.getElementById('v9Strict').onchange=e=>set(e.target.checked);document.getElementById('v9Diagram').onclick=()=>set(api.getState().precisionMode!=='strict');set(false);document.getElementById('v12SourceInfo').onclick=()=>document.getElementById('sourceDialog').showModal();window.addEventListener('atlas:tcm-visibility',()=>sync(api.getState().precisionMode==='strict'));
 const card=document.createElement('section');card.id='v9MeridianCard';card.className='tcm-point-card v9-channel-card';card.hidden=true;document.querySelector('.detail-scroll').prepend(card);
 function show(ids){api.clearPointSelection?.();card.innerHTML='<div class="tcm-card-head"><b>所选经脉 · 说明与证据</b><button id="v9CloseChannel">收起</button></div>'+channelBody(ids);card.hidden=false;document.getElementById('tcmPointCard').hidden=true;document.getElementById('tissueDetail')&&(document.getElementById('tissueDetail').hidden=true);document.body.classList.remove('tissue-detail-active');document.body.classList.add('point-detail-active','detail-open');document.body.classList.remove('nav-open');document.getElementById('v9CloseChannel').onclick=()=>{card.hidden=true;document.body.classList.remove('detail-open');};}
 document.getElementById('v9ChannelInfo').onclick=()=>show(api.getState().selectedMeridians);
 window.addEventListener('atlas:v9-channel-click',e=>show(e.detail.ids));window.addEventListener('atlas:v9-point-click',()=>card.hidden=true);window.addEventListener('atlas:bone-selected',()=>card.hidden=true);
 window.__ATLAS_EVIDENCE__={getData:()=>DATA,showChannel:show,getAudit:()=>({coordinateVerified:0,total:361,expandedTextSummaries:15,clinicalCalibration:false})};
}
