export function initRefinement({learning,tissues,female,invalidate,toast}){
 const $=s=>document.getElementById(s),panel=$('tissuePanel');
 const title=panel.querySelector('h2');title.textContent='结构图层';const subtitle=title.nextElementSibling;if(subtitle?.tagName==='P')subtitle.textContent='选一个场景，再按需要调整。';panel.prepend(title,subtitle);
 const task=document.createElement('section');task.className='v12-tasks';task.innerHTML='<h3>快捷观察</h3>';const presets=[...panel.querySelectorAll('.layer-presets')];for(const p of presets){const grid=p.querySelector('.profile-grid');if(grid)task.append(grid);}subtitle.after(task);
 const custom=document.createElement('details');custom.id='customLayers';custom.className='v12-disclosure';custom.innerHTML='<summary>自定义组合与透明度</summary><div class="v12-custom-body"></div>';const body=custom.lastElementChild;body.append($('bonesOn').closest('label'));body.append($('boneOpacity').closest('label'));panel.querySelectorAll('.layer-block').forEach(e=>body.append(e));task.after(custom);
 const advanced=document.createElement('details');advanced.id='advancedLayers';advanced.className='v12-disclosure';advanced.innerHTML='<summary>细分结构与显示选项</summary><div></div>';const extras=advanced.lastElementChild;
 for(const id of ['localStudyToggle','internalDetails','vesselFilter','earFilter','surfaceAttach','nerveXray','fasciaOn','tissueClip']){const input=$(id);if(input)extras.append(input.closest('label'));}
 extras.append($('restoreHiddenStructures'));custom.after(advanced);
 for(const p of presets)p.remove();$('tissueStudyContext').hidden=true;$('layerModeNote').hidden=true;panel.querySelectorAll('.tissue-note').forEach(e=>e.hidden=true);
 const voices=panel.querySelector('.voice-settings');if(voices){const d=document.createElement('details');d.id='voiceSettings';d.className='v12-disclosure';d.innerHTML='<summary>朗读设置</summary>';d.append(voices);advanced.after(d);}
 const tools=panel.querySelector('.v4-button-row');if(tools&&tools.querySelector('#tissueClear')){tools.querySelector('#chestCompare').hidden=true;tools.querySelector('#tissueClear').textContent='只留骨骼';tools.querySelector('#tissueClear').onclick=()=>tissues.setProfile('bones');}
 const status=document.createElement('p');status.id='layerCompactStatus';status.className='v12-layer-status';task.after(status);
 const update=()=>{const s=tissues.getState();document.body.classList.toggle('tcm-display-on',learning.getState().enabled);if(!female.active){$('renderStatus').textContent='男性 · 解剖参考';const num=Object.values(s.systems).filter(x=>x.on).reduce((n,x)=>n+x.visible,0);if(num){const count=window.__FOOT_ATLAS__.getState().visible+num;const text=count+' 个可见结构';if($('visibleCount').textContent!==text)$('visibleCount').textContent=text;}}panel.querySelectorAll('.layer-block').forEach(block=>{const cb=block.querySelector('input[type="checkbox"]');block.classList.toggle('layer-off',!cb.checked);});$('boneOpacity').closest('label').hidden=!$('bonesOn').checked;
  $('vesselFilter').closest('label').hidden=!s.systems.vessels.on;$('earFilter').closest('label').hidden=!s.systems.ear.on;$('nerveXray').closest('label').hidden=!s.systems.nervous.on;
  const list=[window.__FOOT_ATLAS__.getState().bonesOn?'骨骼':null,...Object.entries(s.systems).filter(([,v])=>v.on).map(([id])=>({muscular:'肌肉',nervous:'神经',heart:'心脏',visceral:'器官',vessels:'血管',ear:'耳部',surface:'体表'}[id]))].filter(Boolean);status.textContent=(list.length?list.join(' ＋ '):'未打开结构层')+(s.nerveXray?' · 透视辅助':'');
  panel.querySelectorAll('[data-profile]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.profile===s.profile)));panel.querySelectorAll('[data-system-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.systemView===s.profile)));};
 panel.addEventListener('change',()=>{update();requestAnimationFrame(update);});panel.addEventListener('click',()=>{update();setTimeout(update,100);});window.addEventListener('atlas:tcm-visibility',()=>requestAnimationFrame(update));window.addEventListener('atlas:profile-changed',update);window.addEventListener('atlas:sex-changed',update);new MutationObserver(update).observe(panel,{subtree:true,characterData:true});update();
 document.querySelector('.private-badge')?.remove();document.querySelector('.baseline-link')?.remove();document.querySelector('.breadcrumb')?.remove();$('footerSource').textContent='来源与说明';$('footerSource').title='模型来源、覆盖范围与经穴示意说明';$('tissueSearch').placeholder='搜索已加载的结构';
 document.querySelectorAll('.tcm-disclaimer,.selection-help,.guide-coverage').forEach(e=>e.hidden=true);
 $('sourceDialog').querySelector('.source-intro').textContent='男性：Z-Anatomy / BodyParts3D。女性：HRA / HuBMAP 独立参考集（CC BY 4.0）。两套数据分别展示；女性没有的骨骼、肌肉和周围神经，不借用男性填充。';
 const source=$('sourceDialog');source.querySelectorAll('.model-facts,.source-intro').forEach(e=>{if(e!==source.querySelector('.source-intro'))e.remove();});
 const info=document.createElement('div');info.className='v12-source-summary';info.innerHTML='<h3>怎么看</h3><p>左键旋转与点选，滚轮缩放，右键平移。选择结构后可聚焦、单独查看与恢复周围；骨骼仍支持拆解与归位。</p><h3>示意和真实结构分开</h3><p>骨骼、器官、肌肉、神经来自解剖模型。经络与穴位位置是未校准的教学示意，贴面只是图形投影，不构成准确取穴。开启经络时画面保留简短状态。</p><h3>模型覆盖</h3><p>女性具有全身体表、女性生殖与部分器官；骨骼和肌肉并未覆盖全身。两套人体的详细程度不同，女性暂不显示男性经穴坐标。血管红蓝表示分类，不表示血氧。所有模型用于学习，不用于诊断、取穴或复位。</p><p><a href="./assets/female/source-metadata.json" target="_blank" rel="noopener">女性来源与许可</a> · <a href="./calibration.html">定位工作记录</a> · <a href="./versions.html">历史版本</a></p>';
 source.querySelector('.source-intro').after(info);document.querySelector('.stage-caption').hidden=true;document.querySelector('.detail-note').hidden=true;
 panel.querySelectorAll('[data-system-view]').forEach(b=>{b.onclick=async()=>{await tissues.setAnatomyView(b.dataset.systemView);if(innerWidth>1100)tissues.showPanel(true);update();};});
 const savedRow=document.createElement('div');savedRow.className='v4-button-row';savedRow.innerHTML='<button id="saveLayerCombo">保存我的组合</button><button id="restoreLayerCombo">恢复我的组合</button>';custom.after(savedRow);
 let sessionCombo=null;
 $('saveLayerCombo').onclick=()=>{const v=tissues.getState();sessionCombo={systems:v.systems,bonesOn:$('bonesOn').checked,boneOpacity:v.boneOpacity,nerveXray:v.nerveXray};try{localStorage.setItem('atlas12:layers',JSON.stringify(sessionCombo));toast('已保存当前图层组合');}catch{toast('已保存到本次会话');}};
 $('restoreLayerCombo').onclick=async()=>{let v=sessionCombo;try{v=JSON.parse(localStorage.getItem('atlas12:layers')||'null')||v;}catch{}if(!v){toast('请先保存一个图层组合');return;}const b=$('restoreLayerCombo');b.disabled=true;try{for(const[k,x]of Object.entries(v.systems)){if(!Object.hasOwn(tissues.getState().systems,k))continue;await tissues.enable(k,!!x.on);tissues.setOpacity(k,Math.max(.1,Math.min(1,Number(x.opacity)||1)));}$('bonesOn').checked=!!v.bonesOn;$('bonesOn').dispatchEvent(new Event('change',{bubbles:true}));tissues.setBoneOpacity(v.boneOpacity||1);$('nerveXray').checked=!!v.nerveXray;$('nerveXray').dispatchEvent(new Event('change',{bubbles:true}));update();invalidate();toast('已恢复图层组合，观察位置不变');}catch(e){toast('组合恢复失败：'+e.message);}finally{b.disabled=false;}};
 const focus=document.createElement('button');focus.id='focusWorkspace';focus.className='text-button';focus.textContent='专注看图';focus.setAttribute('aria-pressed','false');$('fullscreenBtn').before(focus);
 function setFocus(on){document.body.classList.toggle('study-focus',on);focus.textContent=on?'恢复侧栏':'专注看图';focus.setAttribute('aria-pressed',String(on));window.dispatchEvent(new Event('resize'));invalidate();}
 focus.onclick=()=>setFocus(!document.body.classList.contains('study-focus'));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('study-focus')){setFocus(false);e.stopImmediatePropagation();}},true);
 document.querySelector('.brand').setAttribute('aria-label','人体研习室');document.querySelector('.brand strong').textContent='人体研习室';document.querySelector('.brand small').textContent='ANATOMY STUDY';
 document.querySelector('.brand').addEventListener('click',e=>{if(female.active){e.preventDefault();e.stopImmediatePropagation();female.fit();}},true);
 window.__ATLAS_REFINEMENT__={version:'12.0.0',setFocus,getState:()=>({focus:document.body.classList.contains('study-focus'),customOpen:custom.open,advancedOpen:advanced.open,noticeCompact:true})};
}
