import {createSurfaceProjector} from './surface-v11.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import decoderSource from './draco-decoder.txt';
export function initTissues(ctx,speech){
 const {THREE,scene,camera,renderer,viewport,bones,state,toast,focusBounds,setRegion,setView,setSide}=ctx;
 const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const root=new THREE.Group();root.name='Same-source soft tissues';scene.add(root);renderer.localClippingEnabled=true;
 const entries=new Map(),systems={muscular:{on:false,opacity:1,loaded:false,loading:false,meshes:[],promise:null},nervous:{on:false,opacity:1,loaded:false,loading:false,meshes:[],promise:null}};
 const extraSystems=['heart','visceral','vessels','ear','surface'];const systemLabels={muscular:'肌肉 / 筋膜',nervous:'神经 / 神经节',heart:'心脏',visceral:'胸腹器官与气道',vessels:'动脉与静脉',ear:'外耳与内部结构',surface:'体表参照（区域表面）'};for(const id of extraSystems)systems[id]={on:false,opacity:1,loaded:false,loading:false,meshes:[],promise:null};
 let organBox=null,details=false,vesselFilter='all',earFilter='all',surfaceProjector=null,viewSerial=0;const hiddenStructures=new Set();
 let selected=null,isolated=false,fascia=false,lastKey='',clipBox=null,nerveXray=false,clipOn=false,profile='custom',localStudy=true;
 const draco=new DRACOLoader().setDecoderConfig({type:'js'}).setWorkerLimit(2);draco._loadLibrary=()=>Promise.resolve(decoderSource);
 const loader=new GLTFLoader().setDRACOLoader(draco);
 const sidebar=document.querySelector('.sidebar'),panel=document.createElement('section');panel.id='tissuePanel';panel.className='tissue-panel';panel.hidden=true;
 panel.innerHTML='<h2>结构图层</h2><p>同源坐标叠加，可独立显示及调节透明度。</p><label class="layer-check"><input id="bonesOn" type="checkbox" checked><b>骨骼</b><small>210个独立骨块</small></label>'+Object.keys(systems).map((s,i)=>`<section class="layer-block"><label class="layer-check"><input type="checkbox" id="${s}On"><b>${systemLabels[s]}</b><small id="${s}Status">按需加载</small></label><label class="layer-range">透明度<input id="${s}Opacity" aria-label="${systemLabels[s]}透明度" type="range" min="10" max="100" value="${100}"><output id="${s}OpacityValue">${100}%</output></label></section>`).join('')+'<label class="layer-check"><input id="tissueClip" type="checkbox">局部裁切（切口仅为显示截面）</label><label class="layer-check"><input id="fasciaOn" type="checkbox">显示筋膜、腱鞘等附属结构</label><p class="tissue-note">体表为同源分区表面，不是皮肤分层或皮下脂肪。贴面仅改变显示投影，不构成经穴定位校准。血管配色表示结构分类，不表示血氧。</p><div class="v4-button-row"><button id="chestCompare">胸廓＋胸肌对照</button><button id="tissueClear">关闭软组织</button></div><label class="tissue-search"><input id="tissueSearch" type="search" placeholder="搜索已加载结构 / 神经 / 肌肉"></label><div id="tissueList" class="tissue-list"></div>';
 sidebar.append(panel);const tab=document.createElement('button');tab.id='layersTab';tab.textContent='结构图层';$('closeNav').before(tab);
 function showPanel(on){panel.hidden=!on;tab.classList.toggle('active',on);if(on){ctx.learning.setPanel(false);document.querySelector('.bone-pane').hidden=true;$('tcmControls').hidden=true;document.body.classList.add('nav-open');document.body.classList.remove('detail-open');$('boneTab').classList.remove('active');$('tcmTab').classList.remove('active');}}
 tab.onclick=()=>showPanel(true);for(const id of ['boneTab','tcmTab','tcmBtn'])$(id).addEventListener('click',()=>{panel.hidden=true;tab.classList.remove('active');});
 const presets=document.createElement('section');presets.className='layer-presets';presets.innerHTML='<h3>观察重点</h3><div class="profile-grid"><button data-profile="bones">骨骼结构</button><button data-profile="muscles">肌肉外形</button><button data-profile="nerves">神经走行</button><button data-profile="compare">分层对照</button></div><label class="layer-range">骨骼显色<input id="boneOpacity" type="range" min="8" max="100" value="100"><output id="boneOpacityValue">100%</output></label><label class="layer-check"><input type="checkbox" id="nerveXray">神经透视（明确忽略深度遮挡）</label><small>肌肉外形模式不透视；神经模式淡化参照结构，不代表神经在人体表面。</small>';panel.prepend(presets);
 const additions=document.createElement('section');additions.className='layer-presets';additions.innerHTML='<h3>器官与体表</h3><div class="profile-grid"><button data-system-view="chest">胸腔器官</button><button data-system-view="heart">心脏特写</button><button data-system-view="abdomen">腹部器官</button><button data-system-view="vascular">心血管</button><button data-system-view="ear-right">右耳</button><button data-system-view="ear-left">左耳</button><button data-system-view="surface" class="wide-system-view">体表经络（示意）</button></div><label class="layer-check"><input id="internalDetails" type="checkbox">内部细分（部分结构会重叠）</label><label class="layer-check">血管<select id="vesselFilter"><option value="all">动脉＋静脉</option><option value="artery">只看动脉</option><option value="vein">只看静脉</option></select></label><label class="layer-check">耳部<select id="earFilter"><option value="all">外耳＋内部</option><option value="external-ear">只看外耳</option><option value="inner-ear">只看内部</option></select></label><label class="layer-check"><input id="surfaceAttach" type="checkbox">经络贴面显示（未校准）</label><p class="tissue-note" id="surfaceAttachNote">首次贴面会读取体表。原参照坐标保留，可随时取消恢复；不代表标准取穴。</p><button id="restoreHiddenStructures">恢复已隐藏结构</button>';presets.after(additions);
 const quick=document.createElement('div');quick.id='organQuickBar';quick.innerHTML='<button data-quick="chest">胸腔器官</button><button data-quick="vascular">血管</button><button data-quick="ear-right">耳部</button><button data-quick="surface">体表经络</button>';document.querySelector('.bone-pane').prepend(quick);quick.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>setAnatomyView(b.dataset.quick).catch(e=>toast(e.message)));
 additions.querySelectorAll('[data-system-view]').forEach(b=>b.onclick=()=>setAnatomyView(b.dataset.systemView).catch(e=>toast(e.message)));
 $('internalDetails').onchange=e=>{details=e.target.checked;lastKey='';updateFrame();};$('vesselFilter').onchange=e=>{vesselFilter=e.target.value;lastKey='';updateFrame();};$('earFilter').onchange=e=>{earFilter=e.target.value;lastKey='';updateFrame();};$('surfaceAttach').onchange=e=>attachSurface(e.target.checked).catch(e=>toast(e.message));$('restoreHiddenStructures').onclick=()=>{hiddenStructures.clear();lastKey='';updateFrame();};
 const context=document.createElement('section');context.id='tissueStudyContext';context.className='tissue-study-context';context.innerHTML='<b id="tissueStudyTitle">未选穴位：全区域观察</b><p>四个预设共用同一套模型，仅调整图层与透明度。</p><label><input id="localStudyToggle" type="checkbox" checked>只看当前范围的结构与点线</label><small>局部范围可关闭；看全线恢复完整经脉。几何相交不表示穴位—神经支配关系。</small>';presets.after(context);
 $('localStudyToggle').onchange=e=>{localStudy=e.target.checked;lastKey='';updateFrame();};
 const legend=document.createElement('div');legend.id='layerLegend';legend.className='layer-legend';legend.innerHTML='<span class="bone-key">骨骼</span><span class="muscle-key">肌肉</span><span class="nerve-key">神经</span><span class="guide-key">经络导览：非定位</span>';document.querySelector('.stage').append(legend);
 $('boneOpacity').oninput=e=>setBoneOpacity(Number(e.target.value)/100);$('nerveXray').onchange=e=>{nerveXray=e.target.checked;lastKey='';updateFrame();};
 presets.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>setProfile(b.dataset.profile));
 function setBoneOpacity(v){state.boneOpacity=Math.max(.08,Math.min(1,v));$('boneOpacity').value=Math.round(state.boneOpacity*100);$('boneOpacityValue').textContent=Math.round(state.boneOpacity*100)+'%';ctx.applyVisibility();}
 function setOpacity(k,v){systems[k].opacity=v;$(k+'Opacity').value=Math.round(v*100);$(k+'OpacityValue').textContent=Math.round(v*100)+'%';lastKey='';}
 async function setProfile(p){ctx.invalidate();
  if(['chest','heart','abdomen','vascular','ear-right','ear-left','surface'].includes(p))return setAnatomyView(p);if(!['bones','muscles','nerves','compare'].includes(p))return;viewSerial++;document.body.classList.remove('organ-view-active');
  for(const id of extraSystems)await enable(id,false);organBox=null;profile=p;clearSelection();state.bonesOn=true;$('bonesOn').checked=true;
  const config={bones:{m:false,n:false,mo:1,bo:1,x:false},muscles:{m:true,n:false,mo:1,bo:1,x:false},nerves:{m:false,n:true,mo:.12,bo:.32,x:true},compare:{m:true,n:true,mo:.27,bo:.65,x:false}}[p];
  setOpacity('muscular',config.mo);setOpacity('nervous',1);setBoneOpacity(config.bo);nerveXray=config.x;$('nerveXray').checked=nerveXray;
  presets.querySelectorAll('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===p));
  const loads=[enable('muscular',config.m),enable('nervous',config.n)];lastKey='';updateFrame();await Promise.all(loads);
  if(profile===p){$('layerModeNote').textContent=p==='nerves'?'神经透视辅助：神经不被前方结构遮挡，骨骼作为淡化参照。':'真实遮挡观察：前后关系按模型显示，范围筛选不等于已核验的医学关系。';lastKey='';updateFrame();window.dispatchEvent(new CustomEvent('atlas:profile-changed',{detail:{profile}}));}
 }
 const layerNote=document.createElement('p');layerNote.className='v10-layer-note';layerNote.id='layerModeNote';layerNote.textContent='真实遮挡与透视辅助是显示方式，不改变解剖位置；范围内结构不等于已验证的神经支配关系。';panel.prepend(layerNote);speech.mount(panel);
 const warning=document.createElement('div');warning.id='tissuePoseWarning';warning.className='tissue-pose-warning';warning.hidden=true;warning.textContent='骨骼已拆开：软组织与穴位暂时隐藏，归位后恢复，避免显示错误的对应关系。';document.querySelector('.stage').append(warning);
 const card=document.createElement('section');card.id='tissueDetail';card.className='tissue-detail';card.hidden=true;document.querySelector('.detail-scroll').prepend(card);
 async function enable(system,on){ctx.invalidate();const s=systems[system];if(!s)return;s.on=!!on;$(system+'On').checked=s.on;if(system==='surface'&&!on){ctx.learning.setSurfaceAttachment?.(false);$('surfaceAttach').checked=false;}if(on&&!s.loaded&&!s.loading){s.loading=true;$(system+'Status').textContent='加载中…';s.promise=(async()=>{try{let bytes;if(window.ATLAS_TISSUE_INLINE?.[system]){const a=atob(window.ATLAS_TISSUE_INLINE[system]);bytes=Uint8Array.from(a,c=>c.charCodeAt(0)).buffer;}else{const r=await fetch((extraSystems.includes(system)?'../fullbody-tcm-v11/':window.ATLAS_RESOURCE_BASE||'./')+'assets/'+system+'.glb');if(!r.ok)throw Error('HTTP '+r.status);bytes=await r.arrayBuffer();}const gltf=await loader.parseAsync(bytes,'');gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(n=>{if(!n.isMesh||!n.userData.atlas)return;const info=n.userData.atlas;info.system=system;const mat=new THREE.MeshStandardMaterial({color:materialColor(system,info),roughness:.64,envMapIntensity:.18,metalness:0,transparent:s.opacity<1,opacity:s.opacity,depthWrite:s.opacity>.9,side:THREE.FrontSide});n.material=mat;n.castShadow=false;n.receiveShadow=false;n.renderOrder=system==='nervous'?16:2;n.userData.atlas.bounds=info.bounds;n.userData.originalMaterial=mat;n.geometry.computeBoundingBox();entries.set(info.id,n);s.meshes.push(n);});root.add(gltf.scene);s.loaded=true;$(system+'Status').textContent=s.meshes.length+'个结构';renderList();}catch(e){s.on=false;$(system+'On').checked=false;$(system+'Status').textContent='加载失败，请重新勾选重试';toast('软组织加载失败：'+e.message);console.error(e);}finally{s.loading=false;lastKey='';updateFrame();ctx.invalidate();}})();}lastKey='';updateFrame();return s.promise;}
 for(const system of Object.keys(systems)){$(system+'On').onchange=e=>enable(system,e.target.checked);$(system+'Opacity').oninput=e=>{systems[system].opacity=Number(e.target.value)/100;$(system+'OpacityValue').textContent=e.target.value+'%';lastKey='';};}
 $('tissueClip').onchange=e=>{clipOn=e.target.checked;lastKey='';updateFrame();};
 $('fasciaOn').onchange=e=>{fascia=e.target.checked;lastKey='';};$('bonesOn').onchange=e=>{state.bonesOn=e.target.checked;ctx.applyVisibility();};$('tissueSearch').oninput=renderList;
 $('tissueClear').onclick=()=>{for(const s of Object.keys(systems))enable(s,false);clearSelection();};
 $('chestCompare').onclick=async()=>{await enable('muscular',true);setRegion('thorax');setView('front');showPanel(false);document.querySelector('.bone-pane').hidden=false;document.body.classList.remove('nav-open');toast('原胸廓坐标未改变；肌肉叠加用于比较外形');};
 function regionBox(){if(organBox)return organBox.clone();const c=ctx.learning.getStudyContext?.();if(c&&localStudy){const v=new THREE.Vector3(...c.center);return new THREE.Box3(v.clone().addScalar(-c.radius*1.6),v.clone().addScalar(c.radius*1.6));}if(state.region==='body')return null;let box=new THREE.Box3();for(const b of bones.values())if(ctx.regionContains(b.name))box.expandByObject(b);if(box.isEmpty())return null;const ranges={head:[1440,1710],auditory:[1470,1600],cervical:[1380,1520],thoracic:[1100,1440],thorax:[1060,1410],shoulder:[1190,1430],upper:[620,1440],elbow:[970,1110],wrist:[765,860],hand:[630,825],foot:[-80,85],ankle:[-80,170],knee:[300,515],lumbar:[880,1110],hip:[735,985],pelvis:[740,985]};if(ranges[state.region]){box.min.y=ranges[state.region][0];box.max.y=ranges[state.region][1];}box.expandByScalar(25);return box;}
 function clipPlanes(b){return b?[new THREE.Plane(new THREE.Vector3(1,0,0),-b.min.x),new THREE.Plane(new THREE.Vector3(-1,0,0),b.max.x),new THREE.Plane(new THREE.Vector3(0,1,0),-b.min.y),new THREE.Plane(new THREE.Vector3(0,-1,0),b.max.y),new THREE.Plane(new THREE.Vector3(0,0,1),-b.min.z),new THREE.Plane(new THREE.Vector3(0,0,-1),b.max.z)]:[];}
 function updateFrame(){const displaced=state.explode>0||[...bones.values()].some(b=>b.userData.offset.lengthSq()>.1||b.quaternion.angleTo(new THREE.Quaternion())>.015);const study=ctx.learning.getStudyContext?.();const key=[organBox?.min.toArray().join(','),organBox?.max.toArray().join(','),details,vesselFilter,earFilter,[...hiddenStructures].join(','),study?.code,study?.side,localStudy,state.region,state.side,state.isolated,state.selected,displaced,isolated,selected?.id,fascia,nerveXray,clipOn,state.boneOpacity,...Object.values(systems).flatMap(s=>[s.on,s.loaded,s.opacity])].join('|');if(key===lastKey)return;lastKey=key;ctx.invalidate();$('tissueStudyTitle').textContent=study?'当前：'+study.name+' · '+study.regionLabel:'未选穴位：全区域观察';ctx.setPerformance(Object.values(systems).some(s=>s.on));clipBox=regionBox();const planes=clipPlanes(clipBox);warning.hidden=!(displaced&&Object.values(systems).some(s=>s.on));root.visible=!displaced&&!state.isolated;for(const [system,s]of Object.entries(systems))for(const n of s.meshes){const m=n.userData.atlas,bb=new THREE.Box3(new THREE.Vector3(...m.bounds[0]),new THREE.Vector3(...m.bounds[1]));n.visible=s.on&&(profile!=='chest'||system!=='visceral'||['lung','airway'].includes(m.category)||/oesoph|esoph/.test(m.en.toLowerCase()))&&(profile!=='abdomen'||system!=='visceral'||m.category==='organ')&&(profile!=='heart'||system!=='vessels'||/aorta|vena cava|coronary|cardiac|pulmonary/i.test(m.en))&&(!hiddenStructures.has(m.id)||isolated)&&(details||!m.detailOnly||m.id===selected?.id)&&(system!=='vessels'||vesselFilter==='all'||m.category===vesselFilter)&&(system!=='ear'||earFilter==='all'||m.category===earFilter)&&(!isolated||m.id===selected?.id)&&(m.category!=='fascia'||fascia)&&(state.side==='both'||m.side==='midline'||m.side===state.side)&&(isolated||!clipBox||bb.intersectsBox(clipBox));n.material.opacity=s.opacity;n.material.transparent=s.opacity<.98;n.material.depthWrite=s.opacity>=.98;n.material.depthTest=!(system==='nervous'&&nerveXray);n.renderOrder=system==='nervous'&&nerveXray?18:system==='nervous'?3:2;n.material.clippingPlanes=isolated||!clipOn?[]:planes;n.material.emissive.set(m.id===selected?.id?'#12534e':system==='nervous'?'#301200':'#000000');n.material.emissiveIntensity=m.id===selected?.id?.25:system==='nervous'?.14:0;n.material.needsUpdate=true;}if(displaced)ctx.learning.suspend(true);else ctx.learning.suspend(false);renderList();}
 function renderList(){const q=$('tissueSearch').value.trim().toLowerCase();const all=[...entries.values()].filter(n=>systems[n.userData.atlas.system].on&&(q||n.visible)&&(state.side==='both'||n.userData.atlas.side==='midline'||n.userData.atlas.side===state.side)&&(!clipBox||new THREE.Box3(new THREE.Vector3(...n.userData.atlas.bounds[0]),new THREE.Vector3(...n.userData.atlas.bounds[1])).intersectsBox(clipBox))&&(!q||[n.userData.atlas.name,n.userData.atlas.en].join(' ').toLowerCase().includes(q)));$('tissueList').replaceChildren();for(const n of all){const m=n.userData.atlas,b=document.createElement('button');b.dataset.tissue=m.id;b.innerHTML='<b>'+esc(m.name)+'</b><small>'+esc(m.en)+'</small>';b.onclick=()=>choose(m.id,true);$('tissueList').append(b);}if(!all.length)$('tissueList').textContent=entries.size?'未找到该结构':'开启一个图层后可按名称查找和单独查看。';}
 function choose(id,focus=false){const n=entries.get(id);if(!n)return false;selected=n.userData.atlas;card.hidden=false;document.body.classList.add('tissue-detail-active');document.body.classList.remove('point-detail-active');$('tcmPointCard').hidden=true;document.body.classList.remove('point-detail-active');card.innerHTML='<h2>'+esc(selected.name)+'</h2><p>'+esc(selected.en)+'</p><span class="group-tag">'+systemLabels[selected.system]+'</span><p class="tissue-note">'+esc(selected.description||'来自同一套 Z-Anatomy / BodyParts3D 表面网格；不表示完整微结构，颜色为学习配色。')+'</p><p>'+(selected.sourceURL?'<a target="_blank" rel="noopener noreferrer" href="'+esc(selected.sourceURL)+'">资料来源</a>':'')+'</p><div class="v4-button-row"><button id="tissueIsolate">'+(isolated?'返回图层':'单独查看')+'</button><button id="tissueFocus">聚焦</button><button id="tissueSpeak">朗读</button><button id="hideStructure">隐藏这块</button></div><button id="tissueDetailClose">返回骨骼信息</button>';$('tissueIsolate').onclick=()=>{isolated=!isolated;state.tissueIsolated=isolated;ctx.applyVisibility();lastKey='';updateFrame();choose(id,true);};$('tissueFocus').onclick=()=>focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(12));$('tissueSpeak').onclick=()=>speech.speak(selected.name);$('hideStructure').onclick=()=>{hiddenStructures.add(id);clearSelection();updateFrame();};$('tissueDetailClose').onclick=clearSelection;lastKey='';if(focus){state.isolated=false;ctx.applyVisibility();focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(15));document.body.classList.remove('nav-open');}document.body.classList.add('detail-open');window.dispatchEvent(new CustomEvent('atlas:selection',{detail:{kind:'tissue',id:selected.id,name:selected.name,side:selected.side}}));ctx.invalidate();return true;}
 function clearSelection(){selected=null;isolated=false;state.tissueIsolated=false;ctx.applyVisibility();card.hidden=true;document.body.classList.remove('tissue-detail-active');lastKey='';}
 window.addEventListener('atlas:region-changed',()=>{organBox=null;document.body.classList.remove('organ-view-active');lastKey='';});
 window.addEventListener('atlas:bone-selected',e=>{if(e.detail.user){document.body.classList.remove('organ-view-active');clearSelection();}});
 function hit(e){if(!root.visible||state.mode!=='orbit')return null;const r=viewport.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(2*(e.clientX-r.left)/r.width-1,1-2*(e.clientY-r.top)/r.height),camera);const ms=[...entries.values()].filter(n=>n.visible&&n.material.opacity>.18&&n.userData.atlas.system!=='surface');if(!ms.length)return null;return ray.intersectObjects(ms,false).find(x=>!clipOn||!clipBox||isolated||clipBox.containsPoint(x.point))||null;}
 function click(e){const p=hit(e);if(!p)return false;return choose(p.object.userData.atlas.id,false);}
 function materialColor(system,info){
  if(system==='surface')return '#af8b72';if(system==='ear')return info.category==='external-ear'?'#ccaa94':'#bc9366';
  if(system==='vessels')return info.category==='artery'?'#9d3035':info.category==='vein'?'#365b92':'#876466';
  if(system==='heart')return '#8e3b47';if(system==='visceral'){if(info.category==='lung')return /right/.test(info.en)?'#9c6065':'#a66d72';if(info.category==='airway')return '#c7b99e';if(/liver/i.test(info.en))return '#78484b';if(/kidney/i.test(info.en))return '#a35b62';if(/bladder|ureter/i.test(info.en))return '#c19a78';if(/gallbladder|bile/i.test(info.en))return '#658765';return '#b88774';}
  return system==='nervous'?'#744707':info.category==='fascia'?'#b5a38c':'#843840';
 }
 async function attachSurface(on){
  $('surfaceAttach').disabled=true;$('surfaceAttachNote').textContent=on?'正在准备同源体表显示投影…':'已恢复原示意坐标';ctx.invalidate();
  try{
   if(on){await enable('surface',true);if(!systems.surface.loaded)throw Error('体表未加载成功');root.updateWorldMatrix(true,true);if(!surfaceProjector)surfaceProjector=createSurfaceProjector(systems.surface.meshes,[...bones.values()].map(b=>new THREE.Box3().setFromObject(b).getCenter(new THREE.Vector3())));ctx.learning.setSurfaceProjector(surfaceProjector);}
   await ctx.learning.setSurfaceAttachment(!!on);$('surfaceAttach').checked=!!on;
   $('surfaceAttachNote').textContent=on?'贴面是显示投影，原穴位坐标未修改；不构成准确取穴。取消勾选可恢复原参照。':'已恢复原示意坐标；体表仍可独立显示。';
  }catch(e){$('surfaceAttach').checked=false;toast('体表投影未完成：'+e.message);throw e;}
  finally{$('surfaceAttach').disabled=false;lastKey='';updateFrame();ctx.invalidate();}
 }
 async function setAnatomyView(name){
  const valid=['chest','heart','abdomen','vascular','ear-right','ear-left','surface'];if(!valid.includes(name))return false;
  const serial=++viewSerial;profile=name;clearSelection();hiddenStructures.clear();ctx.learning.clearStudyContext(true);ctx.learning.toggleTCM(false);organBox=null;
  state.isolated=false;state.explode=0;window.__FOOT_ATLAS__?.reset();if(setSide)setSide('both');setRegion(name==='chest'||name==='heart'?'thorax':name.startsWith('ear-')?'auditory':'body');
  profile=name;const wanted={chest:['heart','visceral'],heart:['heart','vessels'],abdomen:['visceral'],vascular:['heart','vessels'],surface:['surface'],'ear-right':['ear'],'ear-left':['ear']}[name];
  const promises=Object.keys(systems).map(id=>enable(id,wanted.includes(id)));state.bonesOn=name==='vascular'||name.startsWith('ear-');$('bonesOn').checked=state.bonesOn;setBoneOpacity(name==='surface'?.08:name.startsWith('ear-')?.1:.08);nerveXray=false;$('nerveXray').checked=false;clipOn=name==='heart';$('tissueClip').checked=clipOn;
  details=false;$('internalDetails').checked=false;vesselFilter='all';earFilter='all';$('vesselFilter').value='all';$('earFilter').value='all';
  for(const id of wanted)setOpacity(id,1);
  await Promise.all(promises);if(serial!==viewSerial)return false;
  if(wanted.some(id=>!systems[id].loaded))throw Error('结构未完整加载，可重新选择重试');
  if(name==='chest')organBox=new THREE.Box3(new THREE.Vector3(-120,1050,-175),new THREE.Vector3(315,1420,155));
  if(name==='heart')organBox=new THREE.Box3(new THREE.Vector3(8,1120,-105),new THREE.Vector3(224,1390,105));
  if(name==='abdomen')organBox=new THREE.Box3(new THREE.Vector3(-100,690,-155),new THREE.Vector3(305,1140,165));
  if(name.startsWith('ear-')){const side=name==='ear-left'?'left':'right';setSide?.(side);organBox=new THREE.Box3();for(const n of systems.ear.meshes)if(n.userData.atlas.side===side)organBox.expandByObject(n);organBox.expandByScalar(8);}
  if(name==='surface'){state.bonesOn=false;$('bonesOn').checked=false;ctx.applyVisibility();await attachSurface(true);ctx.learning.setPrecisionMode('illustrative');ctx.learning.clearStudyContext(true);ctx.learning.setMeridians(['KI']);ctx.learning.setTCMSide('both');ctx.learning.toggleTCM(true,false);}
  if(serial!==viewSerial)return false;
  lastKey='';updateFrame();
  const box=new THREE.Box3();
  for(const id of wanted)for(const n of systems[id].meshes)if(n.visible){let b=new THREE.Box3().setFromObject(n);if(organBox)b.intersect(organBox);if(!b.isEmpty())box.union(b);}
  const dir=name==='ear-left'?[1,.05,.3]:name==='ear-right'?[-1,.05,.3]:[.1,.04,1];
  if(!box.isEmpty())focusBounds(box.expandByScalar(name.startsWith('ear-')?8:25),{direction:dir,up:[0,1,0]});
  if(name==='surface')ctx.learning.fitMeridian();
  additions.querySelectorAll('[data-system-view]').forEach(b=>b.classList.toggle('active',b.dataset.systemView===name));
  presets.querySelectorAll('[data-profile]').forEach(b=>b.classList.remove('active'));
  $('layerModeNote').textContent=name==='surface'?'体表经络：同源区域表面＋显示投影，不是准确经穴图。':'器官/血管：真实深度遮挡。点击可聚焦、独立查看或隐藏，未模拟生理运动。';
  document.body.classList.add('organ-view-active');const viewNames={chest:'胸腔器官',heart:'心脏与邻近血管',abdomen:'腹部器官',vascular:'心血管系统','ear-right':'右耳 · 外耳与内部','ear-left':'左耳 · 外耳与内部',surface:'体表参照与经络示意'};const heading=$('regionHeading');heading.textContent=viewNames[name];if(name!=='surface')window.dispatchEvent(new CustomEvent('atlas:selection',{detail:{kind:'region',id:state.region,name:viewNames[name],side:state.side}}));document.body.classList.remove('nav-open');window.dispatchEvent(new CustomEvent('atlas:profile-changed',{detail:{profile:name}}));ctx.invalidate();return true;
 }
 function getPickPoint(id){const n=entries.get(id);if(!n?.visible||!root.visible)return null;root.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(n),r=viewport.getBoundingClientRect(),corners=[];
  for(let i=0;i<8;i++)corners.push(new THREE.Vector3(i&1?box.max.x:box.min.x,i&2?box.max.y:box.min.y,i&4?box.max.z:box.min.z).project(camera));
  const xs=corners.map(p=>r.left+(p.x*.5+.5)*r.width),ys=corners.map(p=>r.top+(-p.y*.5+.5)*r.height);
  for(const a of [.5,.4,.6,.3,.7,.2,.8])for(const b of [.5,.4,.6,.3,.7,.2,.8]){const x=Math.min(...xs)+(Math.max(...xs)-Math.min(...xs))*a,y=Math.min(...ys)+(Math.max(...ys)-Math.min(...ys))*b;const el=document.elementFromPoint(x,y);if(el&&(el===viewport||el===renderer.domElement)&&hit({clientX:x,clientY:y})?.object.userData.atlas.id===id)return{x,y};}return null;
 }

 const api={setAnatomyView,attachSurface,getSurfaceStats:()=>surfaceProjector?.stats(),getPickPoint,clearOrganScope:()=>{organBox=null;lastKey='';updateFrame();},setProfile,setBoneOpacity,setOpacity,enable,showPanel,updateFrame,click,hit,choose,clearSelection,getVisibleCatalog:()=>[...entries.values()].filter(n=>root.visible&&n.visible).map(n=>n.userData.atlas),getCatalog:()=>[...entries.values()].map(n=>n.userData.atlas),project:id=>{const n=entries.get(id);if(!n)return null;const v=new THREE.Box3().setFromObject(n).getCenter(new THREE.Vector3()).project(camera),r=viewport.getBoundingClientRect();return{x:r.left+(v.x*.5+.5)*r.width,y:r.top+(-v.y*.5+.5)*r.height};},getState:()=>({localStudy,studyContext:ctx.learning.getStudyContext?.(),profile,nerveXray,clipOn,boneOpacity:state.boneOpacity,selected,isolated,displaced:!root.visible,skinLoaded:false,surfaceReferenceLoaded:systems.surface.loaded,organView:organBox&&[organBox.min.toArray(),organBox.max.toArray()],systems:Object.fromEntries(Object.entries(systems).map(([k,s])=>[k,{on:s.on,loaded:s.loaded,loading:s.loading,count:s.meshes.length,visible:s.meshes.filter(n=>n.visible&&root.visible).length,opacity:s.opacity}]))})};window.__ATLAS_TISSUES__=api;return api;
}
