import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {BONES} from './bones-data.js';
import {POSES,SOURCES,poseState,calculate} from './pose-data.js';
const $=id=>document.getElementById(id),viewport=$('poseViewport');
const params=new URLSearchParams(location.hash.slice(1));
let chosen=POSES.some(p=>p.id===params.get('pose'))?params.get('pose'):'stand',phase=0,playing=false,ready=false,framePending=0,lastTime=0,recordURL=null;
for(const id of ['mass','gravity','volume','density','minutes','breakEvery','share'])if(params.has(id)){const v=Number(params.get(id));const e=$(id);if(Number.isFinite(v)&&v>=Number(e.min)&&v<=Number(e.max))e.value=v;}
if(params.has('phase'))phase=THREE.MathUtils.clamp(Number(params.get('phase'))||0,0,100)/100;
$('phase').value=Math.round(phase*100);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e8eee5');
const camera=new THREE.PerspectiveCamera(37,1,.01,80);camera.position.set(2,1.4,3);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;viewport.append(renderer.domElement);
scene.add(new THREE.HemisphereLight('#fffaf1','#667865',2));const key=new THREE.DirectionalLight('#ffffff',2.2);key.position.set(3,4,3);scene.add(key);const fill=new THREE.DirectionalLight('#d6e5e4',1);fill.position.set(-3,2,-3);scene.add(fill);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=.3;controls.maxDistance=12;controls.zoomToCursor=true;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;
const supports=new THREE.Group();scene.add(supports);
const body=new THREE.Group(),forces=new THREE.Group(),markers=new THREE.Group();scene.add(body,forces,markers);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(5,5),new THREE.MeshBasicMaterial({color:'#dce6d7',transparent:true,opacity:.65,side:THREE.DoubleSide}));ground.rotation.x=-Math.PI/2;ground.position.y=-.004;scene.add(ground);
const grid=new THREE.GridHelper(5,20,'#a5b6a2','#c6d3be');grid.position.y=-.003;scene.add(grid);
const rigs={},boneMeshes=[],boneInfo=new Map(BONES.map(b=>[b.id,b])),labels=[],contactPoints=new Map();let jointDots=true,lastPoseTime=0;
const origin={pelvis:[99.55,835,-50],lumbar:[99.55,905,-50],trunk:[99.55,1100,-50],head:[99.55,1405,-64],hipR:[38,829,-43],hipL:[161,829,-43],kneeR:[20,386,-48],kneeL:[179,386,-48],ankleR:[23,28,-52],ankleL:[176,28,-52],shoulderR:[-63,1348,-51],shoulderL:[262,1348,-51],elbowR:[-144,1044,-38],elbowL:[343,1044,-38],wristR:[-201,791,-22],wristL:[400,791,-22]};
const parents={pelvis:null,lumbar:'pelvis',trunk:'lumbar',head:'trunk',hipR:'pelvis',hipL:'pelvis',kneeR:'hipR',kneeL:'hipL',ankleR:'kneeR',ankleL:'kneeL',shoulderR:'trunk',shoulderL:'trunk',elbowR:'shoulderR',elbowL:'shoulderL',wristR:'elbowR',wristL:'elbowL'};
const v=a=>new THREE.Vector3(...a).multiplyScalar(.001);
function invalidate(){if(!framePending)framePending=requestAnimationFrame(draw);}
function draw(time){framePending=0;if(playing&&ready&&!document.hidden){const dt=Math.min(.1,(time-lastTime)/1000||0);phase=(phase+dt*.16)%1;$('phase').value=Math.round(phase*100);if(time-lastPoseTime>80){applyPose(false);renderAnalysis(false);lastPoseTime=time;}}lastTime=time;controls.update();renderer.render(scene,camera);placeLabels();if(playing&&!document.hidden)invalidate();}
controls.addEventListener('change',invalidate);
function resize(){const r=viewport.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height));camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();invalidate();}
new ResizeObserver(resize).observe(viewport);
function segmentFor(b){const side=b.side==='left'?'L':'R';if(['cranial','facial','head-other','cervical'].includes(b.group))return'head';if(b.group==='lumbar')return'lumbar';if(['thoracic','thorax','shoulder'].includes(b.group))return'trunk';if(b.group==='pelvis')return'pelvis';if(b.group==='arm')return b.id.startsWith('humerus')?'shoulder'+side:'elbow'+side;if(['carpal','metacarpal','hand-phalanges'].includes(b.group))return'wrist'+side;if(b.group==='thigh')return b.id.startsWith('patella')?'knee'+side:'hip'+side;if(b.group==='leg')return'knee'+side;return'ankle'+side;}
function disposeGroup(group){while(group.children.length){const n=group.children[0];group.remove(n);n.traverse(q=>{q.geometry?.dispose();if(Array.isArray(q.material))q.material.forEach(m=>m.dispose());else q.material?.dispose();});}}
function label(text,position){const e=document.createElement('span');e.className='poseLabel';e.textContent=text;$('poseLabelLayer').append(e);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('stroke','#78a699');line.setAttribute('stroke-width','1');$('labelLeaders').append(line);labels.push({e,position,line});}
function clearLabels(){labels.splice(0).forEach(x=>{x.e.remove();x.line.remove();});}
function placeLabels(){const r=viewport.getBoundingClientRect(),placed=[];for(const x of labels){const p=x.position.clone().project(camera),px=(p.x*.5+.5)*r.width,py=(1-p.y)*r.height*.5;x.e.hidden=p.z>1||p.z<-1||px<0||px>r.width||py<85||py>r.height-140;if(x.e.hidden){x.line.style.display='none';continue;}const width=x.e.offsetWidth,height=x.e.offsetHeight,left=THREE.MathUtils.clamp(px+10,8,r.width-width-8);let top=THREE.MathUtils.clamp(py,90,r.height-155-height);for(let n=0;n<15&&placed.some(b=>left<b.x+b.w+4&&left+width+4>b.x&&top<b.y+b.h+4&&top+height+4>b.y);n++)top=THREE.MathUtils.clamp(py-(n+1)*(height+5),90,r.height-155-height);x.e.style.left=left+'px';x.e.style.top=top+'px';placed.push({x:left,y:top,w:width,h:height});x.line.style.display='';x.line.setAttribute('x1',px);x.line.setAttribute('y1',py);x.line.setAttribute('x2',THREE.MathUtils.clamp(px,left,left+width));x.line.setAttribute('y2',top+height/2);}}
function frame(direction){if(!ready)return;const bounds=new THREE.Box3().setFromObject(body),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const d=direction?new THREE.Vector3(...direction):camera.position.clone().sub(controls.target).normalize();const h=viewport.clientHeight,w=viewport.clientWidth;const usable=Math.max(.35,(h-250)/h);const distance=Math.max(size.length()/(2*Math.sin(Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.aspect*.78))),size.y/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*usable),size.x/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.aspect*.75));controls.target.copy(center);controls.target.y+=size.y*.025;camera.position.copy(controls.target).addScaledVector(d.normalize(),distance);camera.near=.01;camera.far=80;camera.updateProjectionMatrix();controls.update();invalidate();}
function getInputs(){return Object.fromEntries(['mass','gravity','volume','density','minutes','breakEvery','share'].map(id=>[id,id==='share'?Number($(id).value)/100:Number($(id).value)]));}
function saveHash(){const h=new URLSearchParams({pose:chosen,phase:String(Math.round(phase*100)),...Object.fromEntries(['mass','gravity','volume','density','minutes','breakEvery','share'].map(id=>[id,$(id).value]))});history.replaceState(null,'',location.pathname+location.search+'#'+h);}
const fmt=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:1});
function renderAnalysis(updateHash=true){if(updateHash){$('recordPreview').hidden=true;$('exportStatus').textContent='';if(recordURL){URL.revokeObjectURL(recordURL);recordURL=null;}}const p=poseState(chosen,phase),r=calculate(getInputs(),p);$('phaseName').textContent=p.phaseName;$('poseTitle').textContent=p.name+' · '+p.phaseName;$('waterInputs').hidden=!p.water;$('shareRow').hidden=!['stand','warrior'].includes(chosen);$('shareValue').value=$('share').value+'%';$('play').disabled=p.phase.length<2;$('phase').disabled=p.phase.length<2;
 $('analysis').innerHTML=`<div class="metric"><small>设定环境下的重力 · W = m × g</small><strong>${fmt(r.weight)} N</strong><small>${fmt(r.mass)} kg × ${Number(r.gravity).toLocaleString('zh-CN',{maximumFractionDigits:3})} m/s²</small></div>`+(p.water?`<div class="metric"><small>浮力估算 · ρ × g × 排水体积</small><strong>${fmt(r.buoyancy)} N</strong><small>重力减浮力：${fmt(r.netWaterWeight)} N（正值向下）</small></div>`:p.static?`<div class="metric"><small>静态平衡假设下 · 总支撑力</small><strong>${fmt(r.staticSupport)} N</strong><small>只计算总量，不代表关节内部受力。</small></div>`:`<p class="assumption">运动中的接触力幅值未计算。${p.contact.length?'当前阶段有接触，方向箭头仅作说明。':'当前为腾空阶段，没有地面支撑。'}需要身体加速度与地面反力数据。</p>`)+`<h3>支撑与接触</h3><p>${p.contact.length?p.contact.join('、'):'无地面接触'}</p>`+(r.distribution.length?'<p class="assumption">支撑比例为手动假设：'+r.distribution.map(x=>x.name+' '+fmt(x.force)+' N').join('；')+'。</p>':'<p class="intro">区域间分配未计算；标记大小不代表压力大小。</p>')+`<p class="note">${p.note}</p><h3>持续 ${fmt(r.seconds/60)} 分钟</h3><p>${p.static?'在本次静态假设中，重力和总支撑不会因时间增加而自动增大。':'动作阶段变化与本次设定的总时长是不同变量；播放速度仅为观察速度。'}</p><p>按设定间隔，期间计划换姿 ${r.changes} 次。疲劳、组织耐受、血流与损伤程度尚未建模，不能由分钟数直接推断。</p>`;
 if(updateHash)saveHash();invalidate();}
function pointFrom(group,local=[0,0,0]){return rigs[group].localToWorld(new THREE.Vector3(...local));}
function buildContacts(p){contactPoints.clear();const foot=(side)=>{const names=side==='R'?['calcaneus','metatarsal-3']:['calcaneus-left','metatarsal-3-left'];const q=new THREE.Vector3();for(const name of names){const mesh=boneMeshes.find(b=>b.name===name);q.add(mesh.getWorldPosition(new THREE.Vector3()));}return q.multiplyScalar(.5);};contactPoints.set('右脚',foot('R'));contactPoints.set('左脚',foot('L'));contactPoints.set('右手',pointFrom('wristR',[0,-.07,0]));contactPoints.set('左手',pointFrom('wristL',[0,-.07,0]));contactPoints.set('座面',pointFrom('pelvis',[0,-.08,0]));contactPoints.set('骨盆',pointFrom('pelvis'));contactPoints.set('头背部',pointFrom('trunk',[0,.22,-.08]));contactPoints.set('双下肢',foot('R').add(foot('L')).multiplyScalar(.5));contactPoints.set('水体',pointFrom('pelvis'));
 for(const name of p.contact){const pos=contactPoints.get(name);if(!pos)continue;const sphere=new THREE.Mesh(new THREE.SphereGeometry(.022,16,10),new THREE.MeshBasicMaterial({color:'#187878'}));sphere.position.copy(pos);markers.add(sphere);label(name,pos);if(!p.water&&(!p.static||calculate(getInputs(),p).weight>0)){const arrow=new THREE.ArrowHelper(new THREE.Vector3(0,1,0),pos.clone().add(new THREE.Vector3(0,-.2,0)),.22,'#187878',.065,.04);forces.add(arrow);}}
}
function drawForces(p){disposeGroup(forces);disposeGroup(markers);clearLabels();body.updateMatrixWorld(true);buildContacts(p);const r=calculate(getInputs(),p),bounds=new THREE.Box3().setFromObject(body),center=bounds.getCenter(new THREE.Vector3());if(r.weight>0){const arrow=new THREE.ArrowHelper(new THREE.Vector3(0,-1,0),center.clone().add(new THREE.Vector3(.18,.25,0)),.36,'#c05d46',.08,.05);forces.add(arrow);label('重力 '+fmt(r.weight)+' N · 位置示意',center.clone().add(new THREE.Vector3(.18,-.11,0)));}if(p.water&&r.buoyancy>0){forces.add(new THREE.ArrowHelper(new THREE.Vector3(0,1,0),center.clone().add(new THREE.Vector3(-.18,-.22,0)),.36,'#187878',.08,.05));label('浮力 '+fmt(r.buoyancy)+' N',center.clone().add(new THREE.Vector3(-.18,.14,0)));}
 if(jointDots)for(const id of ['hipR','hipL','kneeR','kneeL','shoulderR','shoulderL','elbowR','elbowL']){const sphere=new THREE.Mesh(new THREE.SphereGeometry(.009,10,8),new THREE.MeshBasicMaterial({color:'#ca9c42'}));sphere.position.copy(pointFrom(id));markers.add(sphere);}ground.visible=grid.visible=!p.water;
}
function applyPose(refit=true){if(!ready)return;const p=poseState(chosen,phase);body.position.set(0,0,0);body.rotation.set(...(p.root||[0,0,0]).map(THREE.MathUtils.degToRad));for(const [id,g]of Object.entries(rigs)){const angle=p.joints[id]||[0,0,0];g.rotation.order=chosen==='meditate'&&id.startsWith('hip')?'YXZ':'XYZ';g.rotation.set(...angle.map(THREE.MathUtils.degToRad));if(chosen==='meditate'&&id.startsWith('hip'))g.rotateY(THREE.MathUtils.degToRad(id==='hipR'?-90:90));}body.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(body);body.position.y-=b.min.y;if(p.water)body.position.y+=.35;if(chosen==='run'&&!p.contact.length)body.position.y+=.14;body.updateMatrixWorld(true);drawForces(p);drawSupports();if(refit)frame();invalidate();}
function drawSupports(){disposeGroup(supports);if(chosen!=='sit')return;const pt=pointFrom('pelvis',[0,-.08,-.08]),height=Math.max(.02,pt.y);const material=()=>new THREE.MeshStandardMaterial({color:'#739785',roughness:.85,transparent:true,opacity:.45});const seat=new THREE.Mesh(new THREE.BoxGeometry(.43,.035,.4),material());seat.position.copy(pt);seat.position.y-=.02;supports.add(seat);for(const dx of [-.17,.17])for(const dz of [-.15,.15]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.025,height,.025),material());leg.position.set(pt.x+dx,height/2,pt.z+dz);supports.add(leg);}const back=new THREE.Mesh(new THREE.BoxGeometry(.43,.4,.025),material());back.position.set(pt.x,height+.2,pt.z-.2);supports.add(back);}
function stop(){playing=false;$('analysis').setAttribute('aria-live','polite');$('play').textContent='播放动作';saveHash();}
function choose(id){stop();chosen=id;phase=0;$('phase').value=0;$('poseQuick').value=id;document.querySelectorAll('[data-pose]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pose===id)));applyPose();renderAnalysis();}
$('poseChoices').innerHTML=POSES.map(p=>`<button data-pose="${p.id}" aria-pressed="${p.id===chosen}">${p.name}</button>`).join('');$('poseChoices').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.pose));
$('poseQuick').innerHTML=POSES.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('poseQuick').value=chosen;$('poseQuick').onchange=()=>choose($('poseQuick').value);
$('poseSources').innerHTML=SOURCES.map(([title,url])=>`<li><a href="${url}" target="_blank" rel="noopener">${title} ↗</a></li>`).join('');
$('phase').oninput=()=>{stop();phase=Number($('phase').value)/100;applyPose(false);renderAnalysis();};$('resetPhase').onclick=()=>choose(chosen);$('play').onclick=()=>{playing=!playing;$('analysis').setAttribute('aria-live',playing?'off':'polite');$('play').textContent=playing?'暂停动作':'播放动作';lastTime=performance.now();invalidate();};
for(const id of ['mass','gravity','volume','density','minutes','breakEvery','share'])$(id).oninput=()=>{const e=$(id);$('inputError').textContent=e.checkValidity()?'':'请输入此字段允许范围内的数值。';$('export').disabled=!['mass','gravity','volume','density','minutes','breakEvery'].every(x=>$(x).checkValidity());if($('export').disabled)return;renderAnalysis();if(ready)drawForces(poseState(chosen,phase));};
document.querySelectorAll('[data-gravity]').forEach(b=>b.onclick=()=>{$('gravity').value=b.dataset.gravity;renderAnalysis();if(ready)drawForces(poseState(chosen,phase));});
function mode(pan){controls.mouseButtons.LEFT=pan?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;controls.touches.ONE=pan?THREE.TOUCH.PAN:THREE.TOUCH.ROTATE;$('rotate').setAttribute('aria-pressed',String(!pan));$('pan').setAttribute('aria-pressed',String(pan));} $('rotate').onclick=()=>mode(false);$('pan').onclick=()=>mode(true);
function zoom(factor){const delta=camera.position.clone().sub(controls.target),distance=delta.length(),next=THREE.MathUtils.clamp(distance*factor,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).addScaledVector(delta,next/distance);controls.update();invalidate();}
$('zoomIn').onclick=()=>zoom(.8);$('zoomOut').onclick=()=>zoom(1.25);$('frame').onclick=()=>frame();$('front').onclick=()=>frame([0,.05,1]);$('side').onclick=()=>frame([1,.05,0]);
$('export').onclick=()=>{const p=poseState(chosen,phase),r=calculate(getInputs(),p);const record={version:'37.0.0',pose:p.name,phase:p.phaseName,inputs:getInputs(),calculation:r,contacts:p.contact,jointAnglesDegrees:p.joints,assumptions:['姿势为骨架刚体示意','关节中心未动作捕捉校准','接触位置不代表压力','不预测损伤或临床结果'],sources:SOURCES};const json=JSON.stringify(record,null,2);if(recordURL)URL.revokeObjectURL(recordURL);recordURL=URL.createObjectURL(new Blob([json],{type:'application/json'}));$('recordText').value=json;$('recordDownload').href=recordURL;$('recordDownload').download='pose-observation-'+chosen+'.json';$('recordPreview').hidden=false;$('recordPreview').open=true;$('exportStatus').textContent='记录已生成：可查看、复制或下载 JSON。';};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else invalidate();});
async function load(){const gltf=await new GLTFLoader().loadAsync('../fullbody-tcm-v9/assets/fullbody.glb',e=>{if(e.total)$('modelStatus').textContent='正在加载参考骨架 '+Math.round(e.loaded/e.total*100)+'%';});gltf.scene.updateMatrixWorld(true);for(const [id,pt]of Object.entries(origin)){const g=new THREE.Group();g.name=id;g.position.copy(v(pt));if(parents[id]){g.position.sub(v(origin[parents[id]]));rigs[parents[id]].add(g);}else body.add(g);rigs[id]=g;}
 gltf.scene.traverse(n=>{if(!n.isMesh)return;const info=boneInfo.get(n.name);if(!info)throw Error('源骨块无法识别：'+n.name);const position=new THREE.Vector3(),q=new THREE.Quaternion(),scale=new THREE.Vector3();n.matrixWorld.decompose(position,q,scale);const segment=segmentFor(info);const mesh=new THREE.Mesh(n.geometry,new THREE.MeshStandardMaterial({color:'#ccba92',roughness:.7}));mesh.name=n.name;mesh.position.copy(position.multiplyScalar(.001).sub(v(origin[segment])));mesh.scale.copy(scale.multiplyScalar(.001));mesh.quaternion.copy(q);mesh.userData.segment=segment;rigs[segment].add(mesh);boneMeshes.push(mesh);});if(boneMeshes.length!==210)throw Error('骨架未完整加载');ready=true;resize();applyPose();renderAnalysis();$('modelStatus').textContent='210 骨块 · 近似关节中心 · 骨架姿势示意';}
renderAnalysis();resize();load().catch(e=>{$('modelStatus').textContent='骨架加载失败：'+e.message;const retry=document.createElement('button');retry.textContent='重新加载';retry.onclick=()=>location.reload();document.querySelector('.stageTitle').append(retry);});
// QA produces DOM evidence only on local acceptance pages; public UI has no debug button.
if(location.hostname==='127.0.0.1'&&new URLSearchParams(location.search).has('audit')){const button=document.createElement('button');button.textContent='检查姿势状态';button.style.cssText='position:fixed;bottom:2px;right:2px;z-index:100';document.body.append(button);const output=document.createElement('pre');output.id='poseAudit';output.hidden=true;document.body.append(output);button.onclick=()=>{body.updateMatrixWorld(true);const p=poseState(chosen,phase),bounds=new THREE.Box3().setFromObject(body);output.textContent=JSON.stringify({ready,pose:chosen,phase,playing,bones:boneMeshes.length,assigned:boneMeshes.every(m=>!!m.parent),finite:boneMeshes.every(m=>m.matrixWorld.elements.every(Number.isFinite)),bounds:[bounds.min.toArray(),bounds.max.toArray()],camera:camera.position.toArray(),target:controls.target.toArray(),joints:Object.fromEntries(Object.entries(rigs).map(([id,g])=>[id,g.getWorldPosition(new THREE.Vector3()).toArray()])),contacts:p.contact,calculation:calculate(getInputs(),p)});};}
