from pathlib import Path
p=Path('fullbody-tcm-v14')
f=p/'styles.css';s=f.read_text()
for old in ['.organ-view-active .detail-scroll>section:not(#currentStudy):not(#tissueDetail)', '.tissue-detail-active .detail-scroll>section:not(#tissueDetail):not(#currentStudy)']:
 assert old in s,old
 s=s.replace(old,old+':not(#femaleDetail):not(#tcmPointCard):not(#v9MeridianCard)')
f.write_text(s)
f=p/'shared-v14.css';f.write_text(f.read_text()+'''\nbody[data-shared-ui] .sidebar{display:block!important;overflow:auto;overscroll-behavior:contain;scrollbar-width:thin}body[data-shared-ui] #tissuePanel,body[data-shared-ui] #tcmControls,body[data-shared-ui] #structureLibrary{flex:none;overflow:visible;max-height:none}body[data-shared-ui] .library-tabs{flex-shrink:0} @media(max-width:1100px){body[data-shared-ui] .sidebar{display:none!important}body[data-shared-ui].nav-open .sidebar{display:block!important}}\n''')
f=Path('atlas14-delivery/verify.cjs');s=f.read_text()
s=s.replace('let server,browser;','let server,browser,testPage;')
s=s.replace('const p=await ctx.newPage();','const p=await ctx.newPage();testPage=p;')
s=s.replace("}catch(e){report.failure=String(e);console.error(e);process.exitCode=1;}","""}catch(e){report.failure=String(e);console.error(e);process.exitCode=1;
 if(testPage)try{await testPage.screenshot({path:path.join(out,type+'-failure.png')});report.failureDOM=await testPage.evaluate(()=>({bodyClass:document.body.className,kind:document.body.dataset.currentKind,panes:[...document.querySelectorAll('#femaleDetail,#tcmPointCard,#v9MeridianCard,.detail-scroll,.detail-panel')].map(x=>({id:x.id,className:x.className,hidden:x.hidden,display:getComputedStyle(x).display,visibility:getComputedStyle(x).visibility,rect:JSON.stringify(x.getBoundingClientRect()),html:x.outerHTML.slice(0,2000)})),state:window.__ATLAS_SHARED__?.getState()}));}catch{} }
""")
s=s.replace("find(r=>r.name==='子宫')", "find(r=>r.name==='子宫体')")
s=s.replace("await p.locator('[data-structure-id=\"'+id+'\"]').click();await settle(p);", "await p.locator('[data-structure-id=\"'+id+'\"]').click();await p.waitForFunction(id=>window.__ATLAS_FEMALE__.getState().selected===id,id);await settle(p);")
f.write_text(s)
f=p/'learning-enhancements.js';s=f.read_text().replace("precisionMode=mode==='illustrative'?'illustrative':'strict'", "precisionMode='illustrative'");f.write_text(s)
f=p/'stability-v10.js';s=f.read_text()
s=s.replace("u.hash=hash.toString();return u.href;", "if(window.__ATLAS_FEMALE__?.active){const f=window.__ATLAS_FEMALE__.getState();hash.set('sex','female');hash.set('preset',f.preset);hash.set('display',f.mode);}u.hash=hash.toString();return u.href;")
s=s.replace("$('currentStudyMode').textContent=['point','meridian'].includes(current.kind)?'经穴介绍':'解剖结构';invalidate();return;", "$('currentStudyMode').textContent=['point','meridian'].includes(current.kind)?'经穴介绍':'解剖结构';$('speakCurrent').disabled=current.kind==='region';$('evidenceCurrent').href=linkFor(current,'evidence.html');$('evidenceCurrent').textContent=['point','meridian'].includes(current.kind)?'查阅同一条目 ↗':'来源与说明';$('backCurrent').disabled=true;invalidate();return;")
s=s.replace("const h=new URLSearchParams(location.hash.slice(1));const kind=", "const h=new URLSearchParams(location.hash.slice(1));if(h.get('sex')==='female')return null;const kind=")
f.write_text(s)
f=p/'evidence-page-v10.js';s=f.read_text()
s=s.replace("function targetLink(id=selected){", "const refSex=hash.get('sex'),refPreset=hash.get('preset'),refDisplay=hash.get('display');function contextParams(values){const h=new URLSearchParams(values);if(refSex==='female'){h.set('sex','female');h.set('preset',refPreset||'surface');h.set('display',refDisplay||'solid');}return h;}function targetLink(id=selected){")
s=s.replace('new URLSearchParams({kind:tab,id,side,mode,layer})','contextParams({kind:tab,id,side,mode,layer})').replace('new URLSearchParams({kind:tab,id:selected,side,mode,layer})','contextParams({kind:tab,id:selected,side,mode,layer})')
f.write_text(s)
f=p/'female-v12.js';s=f.read_text()
s=s.replace("await setPreset(h.get('preset')||'surface');\n   if(h.get('id'))await select(h.get('id'),true);", """await setPreset(h.get('preset')||'surface');
   if(['point','meridian'].includes(h.get('kind'))){window.__ATLAS_SHARED__?.showSection('meridians');if(h.get('kind')==='point')learning.selectPoint(h.get('id'),h.get('side')||'right',false);else{learning.setMeridians((h.get('id')||'HT').split(','));window.__ATLAS_EVIDENCE__.showChannel((h.get('id')||'HT').split(','));}continue;}
   if(h.get('id'))await select(h.get('id'),true);""")
s=s.replace("mode=['solid','context','focus'].includes(h.get('mode'))?h.get('mode'):'solid';", "mode=['solid','context','focus'].includes(h.get('display')||h.get('mode'))?(h.get('display')||h.get('mode')):'solid';")
s=s.replace("function urlState(){", "function urlState(){if(document.body.classList.contains('reference-detail'))return;")
s=s.replace("const name=maps.get(selected)?.userData.female.name||'女性参考';", "const ref=window.__ATLAS_SHARED__?.getState().selectedPoint;const name=ref?.name||maps.get(selected)?.userData.female.name||'女性参考';")
s=s.replace("if(e.key.toLowerCase()==='f')focus();", "if(e.key.toLowerCase()==='f'&&!document.body.classList.contains('reference-detail'))focus();")
f.write_text(s)
f=p/'shared-v14.js';s=f.read_text()
s=s.replace("function redraw(){", "$('evidenceCurrent').onclick=e=>{if(!['point','meridian'].includes(window.__ATLAS_STUDY__.getState().current.kind)){e.preventDefault();$('sourceDialog').showModal();}};function redraw(){")
s=s.replace("renderDirectory();invalidate();", "if(!['point','meridian'].includes(window.__ATLAS_STUDY__.getState().current.kind))$('evidenceCurrent').textContent='来源与说明';renderDirectory();invalidate();")
f.write_text(s)
f=Path('atlas14-delivery/build.cjs');s=f.read_text()
s=s.replace("const files={};", "esbuild.buildSync({entryPoints:[root+'/evidence-page-v10.js'],bundle:true,minify:true,format:'iife',target:'es2020',nodePaths:[process.env.NODE_PATH],outfile:root+'/evidence.bundle.js'});\nconst files={};")
s=s.replace("'shared-v14.css','female-v12.js'", "'shared-v14.css','styles.css','evidence.bundle.js','female-v12.js'")
f.write_text(s)
print('FIXED shared detail visibility, asynchronous selection and reference actions')
