// Display names keyed to the original HRA node identity. Source metadata is retained.
// Do not classify vessels from a translated display name: several old labels
// disagree with their source node (e.g. superior_rectal_vein).
const names={
 hepatic_flexure_of_colon:'结肠肝曲',ileocecal_valve:'回盲瓣',caecum:'盲肠',splenic_flexure_of_colon:'结肠脾曲',
 duodenum_superior:'十二指肠上部',duodenal_ampulla:'十二指肠壶腹',duodenum_descending:'十二指肠降部',sphincter_of_heptopancreatic_ampulla:'肝胰壶腹括约肌',duodenum_ascending:'十二指肠升部',duodenum_horizontal:'十二指肠水平部',jejenum:'空肠',ileum_terminal:'回肠末段',
 common_hepatic_duct:'肝总管',hepatic_duct:'肝管',hepatopancreatic_ampulla:'肝胰壶腹',dorsal_pancreatic_duct:'背侧胰管',common_bile_duct:'胆总管',ventral_pancreatic_duct:'腹侧胰管',cystic_duct:'胆囊管',
 gastric_impression_of_liver:'肝胃压迹',suprarenal_impression_of_liver:'肝肾上腺压迹',renal_impression_of_liver:'肝肾压迹',duodenal_impression_of_liver:'肝十二指肠压迹',esophageal_impression_of_liver:'肝食管压迹',porta_hepatis:'肝门',colic_impression_of_liver:'肝结肠压迹',capsule_of_the_liver:'肝被膜',bare_area_of_liver:'肝裸区',diaphragmatic_surface_of_liver:'肝膈面',quadrate_lobe:'肝方叶',caudate_lobe:'肝尾状叶',coronary_ligament_of_liver:'肝冠状韧带',falciform_ligament:'肝镰状韧带',triangular_ligament_of_liver:'肝三角韧带',ligamentum_venosum:'静脉韧带',round_ligament_of_liver:'肝圆韧带',hepataduodenal_ligament:'肝十二指肠韧带',
 anterolateral_segment:'肝前外侧段',superomedial_segment:'肝上内侧段',superomedial_segment1:'肝上内侧段 · 部件二',inferomedial_segment:'肝下内侧段',anterosuperior_segment:'肝前上段',posteroinferior_segment:'肝后下段',posterosuperior_segment:'肝后上段',anteroinferior_segment:'肝前下段',
 tail_of_pancreas:'胰尾',body_of_pancreas:'胰体',ucinate_process1:'胰钩突',head_of_pancreas:'胰头',neck_of_pancreas:'胰颈',palatine_tonsil:'腭扁桃体',
 fundus_of_urinary_bladder_dome:'膀胱穹顶部',fundus_of_urinary_bladder_base:'膀胱底',urinary_bladder_neck_smooth_muscle:'膀胱颈平滑肌',trigone_of_urinary_bladder:'膀胱三角',ureteral_orifice:'输尿管口',kidney_capsule:'肾被膜',hilum_of_kidney:'肾门',renal_papilla:'肾乳头',renal_pyramid:'肾锥体',renal_column:'肾柱',outer_cortex_of_kidney:'肾皮质外层',minor_calyx:'肾小盏',major_calyx:'肾大盏',renal_pelvis:'肾盂',
 interventricular_septum:'室间隔',papillary_muscle_of_heart_ant:'心脏乳头肌 · 前部',papillary_muscle_of_heart_antlat:'心脏乳头肌 · 前外侧部',papillary_muscle_of_heart_med:'心脏乳头肌 · 内侧部',papillary_muscle_of_heart_pos:'心脏乳头肌 · 后部',papillary_muscle_of_heart_posmed:'心脏乳头肌 · 后内侧部',
 superior_mesenteric_vein:'肠系膜上静脉',superior_rectal_vein:'直肠上静脉',ileocolic_vein:'回结肠静脉',middle_colic_vein:'结肠中静脉',sigmoid_vein:'乙状结肠静脉',median_sacral_vein:'骶正中静脉',inferior_pancreaticoduodenal_vein:'胰十二指肠下静脉',inferior_mesenteric_vein:'肠系膜下静脉',ileocolic_artery:'回结肠动脉',middle_colic_artery:'结肠中动脉',celiac_trunk:'腹腔干',superior_rectal_artery:'直肠上动脉',superior_mesenteric_artery:'肠系膜上动脉',inferior_mesenteric_artery:'肠系膜下动脉',marginal_artery_of_Drummond:'结肠边缘动脉',sigmoid_artery:'乙状结肠动脉',splenic_artery:'脾动脉',splenic_vein:'脾静脉',cystic_artery:'胆囊动脉',cystic_vein:'胆囊静脉',proper_hepatic_artery:'肝固有动脉',common_hepatic_artery:'肝总动脉',hepatic_portal_vein:'肝门静脉',middle_hepatic_vein:'肝中静脉',coronary_sinus:'冠状窦',great_cardiac_vein:'心大静脉',middle_cardiac_vein:'心中静脉',anterior_cardiac_vein:'心前静脉',small_cardiac_vein:'心小静脉',pulmonary_trunk:'肺动脉干',brachiocephalic_artery:'头臂干',
 ophthalmic_vein:'眼静脉',superior_ophthalmic_vein:'眼上静脉',inferior_ophthalmic_vein:'眼下静脉',central_retinal_vein:'视网膜中央静脉',long_posterior_ciliary_artery:'睫状后长动脉',opthalmic_artery:'眼动脉',central_retinal_artery:'视网膜中央动脉',renal_artery:'肾动脉',renal_vein:'肾静脉',common_iliac_vein:'髂总静脉',colic_vein:'结肠静脉',inferior_rectal_vein:'直肠下静脉',internal_iliac_vein:'髂内静脉',internal_pudendal_vein:'阴部内静脉',middle_rectal_vein:'直肠中静脉',colic_artery:'结肠动脉',middle_hepatic_artery_branch_of_left_hepatic_artery:'肝中动脉支（肝左动脉分支）',hepatic_artery:'肝动脉',posterior_segmental_right_hepatic_artery:'肝右动脉后段支',anterior_segmental_right_hepatic_artery:'肝右动脉前段支',hepatic_vein:'肝静脉',branch_of_portal_vein:'肝门静脉分支',pulmonary_vein:'肺静脉',oblique_vein_of_left_atrium:'左心房斜静脉',marginal_vein:'心缘静脉',posterior_vein_of_left_ventricle:'左心室后静脉',anterior_descending_artery:'冠状动脉前降支',circumflex_artery:'冠状动脉旋支',diagonal_branch_of_left_anterior_descending_artery:'冠状动脉前降支对角支',coronary_artery:'冠状动脉',marginal_branch:'冠状动脉缘支',posterior_descending_branch_of_circumflex_branch_of_left_coronary_artery:'冠状动脉旋支后降支',posterior_left_ventricular_branch:'左心室后支',marginal_artery:'冠状动脉缘支',pulmonary_artery:'肺动脉',common_carotid_artery:'颈总动脉',subclavian_artery:'锁骨下动脉',uterine_artery:'子宫动脉',uterine_vein:'子宫静脉'
};
export function poseStructureInfo(row){
 if(!row?.sourceName?.startsWith('VH_F_'))return row;
 const raw=row.sourceName.slice(5),suffix=raw.match(/_(L|R)(?:_([a-z]+))?$/),part=raw.match(/_([a-z])$/),prefix=raw.match(/^(left|right)_/);
 const side=suffix?.[1]==='L'||prefix?.[1]==='left'?'左':suffix?.[1]==='R'||prefix?.[1]==='right'?'右':'';
 const key=raw.replace(/_(L|R)(_[a-z]+)?$/,'').replace(/^(left|right)_/,'').replace(/_[abc]$/,'');
 let label=names[key];
 if(label){if(raw.includes('pulmonary_vein'))label+=(/_(?:L|R)_sup$/.test(raw)?' · 上支':/_(?:L|R)_inf$/.test(raw)?' · 下支':'');else if(suffix?.[2]||part)label+=' · 部件 '+(suffix?.[2]||part[1]).toUpperCase();label=(side&& !label.startsWith(side)?side:'')+label;}
 // Explicit source identity wins over a conflicting old display label.
 const category=/vein|vena|coronary_sinus/.test(raw)?'vein':/artery|aorta|pulmonary_trunk|celiac_trunk|brachiocephalic/.test(raw)?'artery':undefined;
 return {...row,originalName:row.name,...(label?{name:label}:{}),...(category?{category}:{})};
}
