import * as THREE from 'three';
import {MeshBVH} from 'three-mesh-bvh';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
// Rendering registration only; female skin correspondence is not clinical calibration.
export function createSurfaceProjector(meshes,options={}){
 const female=options?.sex==='female',source=options?.source||null,gs=[],bounds=new THREE.Box3();
 for(const mesh of meshes){mesh.updateWorldMatrix(true,false);const g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.applyMatrix4(mesh.matrixWorld);const p=g.attributes.position;
  if(mesh.matrixWorld.determinant()<0)for(let i=0;i<p.count;i+=3){const x=p.getX(i+1),y=p.getY(i+1),z=p.getZ(i+1);p.setXYZ(i+1,p.getX(i+2),p.getY(i+2),p.getZ(i+2));p.setXYZ(i+2,x,y,z);}
  g.computeVertexNormals();g.computeBoundingBox();bounds.union(g.boundingBox);const bare=new THREE.BufferGeometry();bare.setAttribute('position',g.attributes.position.clone());gs.push(bare);g.dispose();}
 if(!gs.length)throw Error('体表模型尚未加载');const geometry=mergeGeometries(gs,false);gs.forEach(g=>g.dispose());const bvh=new MeshBVH(geometry,{maxLeafTris:12}),position=geometry.attributes.position;
 const height=bounds.max.y-bounds.min.y,mid=(bounds.min.x+bounds.max.x)/2,bins=new Map(),slices=new Map(),binSize=8;
 for(let i=0;i<position.count;i++){const key=Math.floor((position.getY(i)-bounds.min.y)/binSize);let b=bins.get(key);if(!b)bins.set(key,b=[]);b.push([position.getX(i),position.getZ(i)]);}
 function slice(y,region,side){const key=Math.max(0,Math.min(Math.ceil(height/binSize),Math.floor((y-bounds.min.y)/binSize))),cacheKey=key+'|'+region+'|'+side;if(slices.has(cacheKey))return slices.get(cacheKey);
  let rows=[];for(let j=key-1;j<=key+1;j++)rows.push(...(bins.get(j)||[]));if(!rows.length)return{minX:bounds.min.x,maxX:bounds.max.x,minZ:bounds.min.z,maxZ:bounds.max.z};rows.sort((a,b)=>a[0]-b[0]);const clusters=[];let c=[];
  for(const v of rows){if(c.length&&v[0]-c.at(-1)[0]>6){clusters.push(c);c=[];}c.push(v);}if(c.length)clusters.push(c);const groups=clusters.filter(c=>c.length>=15);let chosen=rows;const limb=/^(hand|wrist|forearm|upper|elbow)$/.test(region);
  if(limb&&groups.length>1)chosen=side==='left'?groups.at(-1):groups[0];else if(limb)chosen=rows.filter(v=>side==='left'?v[0]>mid+65:v[0]<mid-65);else if(/^(foot|leg|thigh)$/.test(region))chosen=rows.filter(v=>side==='left'?v[0]>=mid:v[0]<=mid);else if(groups.length>2)chosen=groups.reduce((a,b)=>a.length>b.length?a:b);if(!chosen.length)chosen=rows;
  const box={minX:Infinity,maxX:-Infinity,minZ:Infinity,maxZ:-Infinity};for(const[x,z]of chosen){box.minX=Math.min(box.minX,x);box.maxX=Math.max(box.maxX,x);box.minZ=Math.min(box.minZ,z);box.maxZ=Math.max(box.maxZ,z);}slices.set(cacheKey,box);return box;}
 function regionOf(v,c={}){if(c.region)return c.region;const x=Math.abs(v.x-99.553);if(x>160&&v.y>620&&v.y<800)return'hand';if(x>148&&v.y>=800&&v.y<1050)return'forearm';if(x>148&&v.y>=1050&&v.y<1320)return'upper';if(v.y>1450)return'head';if(v.y>1370)return'neck';if(v.y<150)return'foot';if(v.y<580)return'leg';if(v.y<790)return'thigh';return'body';}
 function mapSeed(v,c={}){if(!female||!source)return v.clone();const r=regionOf(v,c),side=c.side||'midline',sb=source.bounds,y=bounds.min.y+(v.y-sb.min.y)/(sb.max.y-sb.min.y)*height,a=source.slice(v.y,r,side),b=slice(y,r,side),ratio=(val,lo,hi)=>THREE.MathUtils.clamp((val-lo)/Math.max(1,hi-lo),-.1,1.1);return new THREE.Vector3(b.minX+ratio(v.x,a.minX,a.maxX)*(b.maxX-b.minX),y,b.minZ+ratio(v.z,a.minZ,a.maxZ)*(b.maxZ-b.minZ));}
 function direction(v,c={}){const m=c.meridian,r=regionOf(v,c),right=c.side!=='left';if(r==='hand'&&m==='LI')return new THREE.Vector3(right?-.687:.687,.0215,-.726).normalize();if(['forearm','wrist','upper','elbow'].includes(r))return new THREE.Vector3(0,0,['LI','TE','SI'].includes(m)?-1:1);if(m==='GV'&&v.y>1530)return new THREE.Vector3(0,Math.max(0,(v.y-1530)/135),(v.z+35)/92).normalize();if(m==='GV')return new THREE.Vector3(0,0,v.y>1460&&v.z>0?1:-1);if(m==='BL'&&v.y<1440)return new THREE.Vector3(0,0,-1);if(c.view){const d=new THREE.Vector3(...c.view);if(c.side==='left')d.x*=-1;return d.normalize();}if(m==='SI'||m==='TE')return new THREE.Vector3(0,0,v.y>1470?1:-1);if(m==='GB')return new THREE.Vector3(right?-1:1,0,.1).normalize();if(m==='KI'&&v.y<80)return new THREE.Vector3(0,-1,0);if(['KI','SP','LR'].includes(m)&&v.y<780)return new THREE.Vector3(right?1:-1,0,.15).normalize();return new THREE.Vector3(0,0,1);}
 const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();let calls=0,fallbacks=0,maxMove=0;
 function normalAt(face,d){const idx=geometry.index,j=face*3;a.fromBufferAttribute(position,idx?idx.getX(j):j);b.fromBufferAttribute(position,idx?idx.getX(j+1):j+1);c.fromBufferAttribute(position,idx?idx.getX(j+2):j+2);const n=b.clone().sub(a).cross(c.clone().sub(a)).normalize();if(n.dot(d)<0)n.negate();return n;}
 function projectWorld(seed,d,clearance=2.8){calls++;const ray=new THREE.Ray(seed.clone().addScaledVector(d,1800),d.clone().negate()),hits=bvh.raycast(ray,THREE.DoubleSide).filter(h=>h.point.distanceTo(seed)<160);let h=hits.length?hits.reduce((a,b)=>a.distance<b.distance?a:b):null;
  if(!h){fallbacks++;const near=bvh.closestPointToPoint(seed);if(!near)throw Error('无法取得体表');const n=normalAt(near.faceIndex,d),outer=bvh.raycastFirst(new THREE.Ray(near.point.clone().addScaledVector(n,80),n.clone().negate()),THREE.DoubleSide);h=outer&&outer.point.distanceTo(near.point)<50?outer:{point:near.point,faceIndex:near.faceIndex};d=n;}
  const n=normalAt(h.faceIndex,d);maxMove=Math.max(maxMove,h.point.distanceTo(seed));return h.point.clone().addScaledVector(n,clearance);}
 function project(v,offset=2.8,ctx={}){return projectWorld(mapSeed(v,ctx),direction(v,ctx),Math.max(2.8,offset));}
 function tube(points,radius=.95){const verts=[],norms=[],indices=[],radial=10;let previousNormal=new THREE.Vector3(0,1,0);
  for(let i=0;i<points.length;i++){const tangent=points[Math.min(i+1,points.length-1)].clone().sub(points[Math.max(0,i-1)]).normalize();let n=previousNormal.clone().addScaledVector(tangent,-previousNormal.dot(tangent));if(n.lengthSq()<1e-8)n=new THREE.Vector3(Math.abs(tangent.x)<.8?1:0,Math.abs(tangent.x)<.8?0:1,0).cross(tangent);n.normalize();previousNormal=n;const bn=tangent.clone().cross(n).normalize();
   for(let j=0;j<=radial;j++){const theta=2*Math.PI*j/radial,normal=n.clone().multiplyScalar(Math.cos(theta)).addScaledVector(bn,Math.sin(theta)),v=points[i].clone().addScaledVector(normal,radius);verts.push(...v.toArray());norms.push(...normal.toArray());if(i&&j){const d=i*(radial+1)+j,a=d-radial-1;indices.push(a-1,a,d-1,a,d,d-1);}}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(norms,3));g.setIndex(indices);g.computeBoundingSphere();return g;}
 function curve(sourcePoints,context={}){const path=new THREE.CatmullRomCurve3(sourcePoints.map(v=>v.clone()),false,'centripetal');path.arcLengthDivisions=Math.max(200,sourcePoints.length*2);const count=Math.min(5000,Math.max(30,Math.ceil(path.getLength()/2))),seeds=path.getSpacedPoints(count),events=seeds.map((v,i)=>({source:v,order:i}));
  for(const anchor of context.anchors||[]){let best=Infinity,order=0;for(let i=1;i<seeds.length;i++){const l=new THREE.Line3(seeds[i-1],seeds[i]),t=l.closestPointToPointParameter(anchor.source,true),q=l.at(t,new THREE.Vector3()),d=q.distanceToSquared(anchor.source);if(d<best){best=d;order=i-1+t;}}if(best<144)events.push({source:anchor.source.clone(),order,anchor});}
  events.sort((a,b)=>a.order-b.order);const clean=[];for(const e of events){if(clean.length&&clean.at(-1).source.distanceToSquared(e.source)<1e-8){if(e.anchor)clean[clean.length-1]=e;}else clean.push(e);}const points=clean.map(e=>e.anchor?e.anchor.point.clone():project(e.source,2.8,context));
  for(let pass=0;pass<2;pass++){const next=points.map(v=>v.clone());for(let i=1;i<points.length-1;i++){if(clean[i].anchor)continue;const v=points[i-1].clone().addScaledVector(points[i],2).add(points[i+1]).multiplyScalar(.25);if(v.distanceTo(points[i])<8)next[i]=projectWorld(v,direction(clean[i].source,context));}points.splice(0,points.length,...next);}
  const unique=[],samples=[];for(let i=0;i<points.length;i++)if(!unique.length||unique.at(-1).distanceToSquared(points[i])>1e-8){unique.push(points[i]);samples.push({source:clean[i].source.clone(),point:points[i].clone()});}return{points:unique,geometry:tube(unique),samples,anchorCount:clean.filter(e=>e.anchor).length};}
 function isVisible(v,cp){const d=v.clone().sub(cp),len=d.length(),h=bvh.raycastFirst(new THREE.Ray(cp,d.normalize()),THREE.DoubleSide);return !h||h.distance>=len-1;}
 function distanceToSkin(v){const h=bvh.closestPointToPoint(v);return h?h.distance:null;}
 return{bounds,slice,mapSeed,project,curve,isVisible,distanceToSkin,body:female?'female':'male',stats:()=>({version:17,body:female?'female':'male',method:female?'regional surface-proportion transfer + female mesh projection (illustrative)':'exterior hit + surface normal clearance + constrained tube',calls,fallbacks,maxMove,clinicalCalibration:false}),dispose:()=>geometry.dispose()};
}
