import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {MeshBVH} from 'three-mesh-bvh';
import decoderSource from './draco-decoder.txt';
import {normalizeFemaleMesh,bodyFrameInfo} from './body-frame-v18.js';
import {poseStructureInfo} from './pose-names.js';
import {addRegionHints,mergeSurfaceGeometry} from './pose-regions.js';
import {createPoseBinding,posedTriangle} from './pose-binding.js';
import {createSkinProjector} from './skin-v17.js';
import {createGuidePaths} from './route-guides-v6.js';
import {REFERENCES} from './reference-data.js';
import {applyPointRules} from './point-rules-v18.js';
import {headStudyReferences} from './head-study-v8.js';
import {NAVIGATION_POINTS} from './navigation-points-v6.js';
import {MERIDIANS,ACUPOINTS} from './acupoints-data.js';
import {canonicalPoint} from './catalog-v10.js';
import {correctRegionalReferences,createRegionalGuides} from './route-corridors-v13.js';
import {vesselKind,validVesselFilter} from './vessel-kind-v34.js';

const fromMM=v=>v.clone().multiplyScalar(.001).add(new T.Vector3(-.09955,-.835,.05));
const referencesByCode=new Map([...headStudyReferences(REFERENCES,NAVIGATION_POINTS),...NAVIGATION_POINTS].map(p=>[p.code,p]));
const referencePoints=applyPointRules(correctRegionalReferences(ACUPOINTS.map(p=>canonicalPoint({...p,...referencesByCode.get(p.code)}))));
const color={surface:'#c9a58c',organs:'#b56f67',nerves:'#c9a22d',vessels:'#ad626a'};
function bake(node,female=false,surface=false){const nativePosition=female?node.geometry.attributes.position.clone():null;if(female)normalizeFemaleMesh(node,T);node.updateWorldMatrix(true,false);const g=node.geometry.clone().applyMatrix4(node.matrixWorld);if(node.matrixWorld.determinant()<0&&g.index){const a=g.index.array;for(let i=0;i<a.length;i+=3)[a[i+1],a[i+2]]=[a[i+2],a[i+1]];}g.computeVertexNormals();addRegionHints(g,surface?{...node.userData.atlas,system:'surface'}:node.userData.atlas,nativePosition);return g;}
function meters(geometry){geometry.scale(.001,.001,.001);geometry.translate(-.09955,-.835,.05);return geometry;}
function mergedPosition(geometries){if(geometries.length===1){const g=geometries[0].clone();for(const name of Object.keys(g.attributes))if(!['position','normal','bindingArm'].includes(name))g.deleteAttribute(name);g.computeVertexNormals();g.computeBoundingBox();return g;}const hasHints=geometries.some(g=>g.hasAttribute('bindingArm'));const pieces=geometries.map(g=>{const x=g.index?g.toNonIndexed():g.clone();if(hasHints&&!x.hasAttribute('bindingArm')){const values=new Float32Array(x.attributes.position.count);for(let i=0;i<values.length;i++)values[i]=T.MathUtils.smoothstep(Math.abs(x.attributes.position.getX(i)-99.553),180,230);x.setAttribute('bindingArm',new T.Float32BufferAttribute(values,1));}for(const name of Object.keys(x.attributes))if(!['position','bindingArm'].includes(name))x.deleteAttribute(name);return x;}),g=mergeGeometries(pieces,false);pieces.forEach(x=>x.dispose());g.computeVertexNormals();g.computeBoundingBox();return g;}

export function createPoseTissues({scene,meshes,handRig,onStatus,onChange}){
 const root=new T.Group();scene.add(root);const binding=createPoseBinding(handRig),bones=binding.ids.map(()=>{const b=new T.Bone();b.matrixAutoUpdate=false;root.add(b);return b;}),skeleton=new T.Skeleton(bones,bones.map(()=>new T.Matrix4()));
 const draco=new DRACOLoader().setDecoderConfig({type:'js'}).setWorkerLimit(2);draco._loadLibrary=()=>Promise.resolve(decoderSource);const loader=new GLTFLoader().setDRACOLoader(draco);
 const documents=new Map(),models=new Map(),pending=new Map();let sex='male',view='bones',channel='PC',side='right',vesselFilter='all',detailsOn=false,pointsOn=true,linesOn=true,namesOn=true,highlightOn=false,selectedCode='PC6',selectedSide='right',currentResult=null,busy=false,epoch=0,activeInk=null,activeRoutes=[],activePoints=[],currentStructure=null;
 const doc=async url=>{if(!documents.has(url))documents.set(url,loader.loadAsync(url).catch(e=>{documents.delete(url);throw e;}));return documents.get(url);};
 function mesh(geometry,material,bodyOnly=false,surface=false,prepared=false){if(!prepared)binding.attributes(geometry,{bodyOnly,surface});const n=new T.SkinnedMesh(geometry,material);n.bind(skeleton,new T.Matrix4());n.frustumCulled=false;root.add(n);return n;}
 async function loadSurfaceBinding(g,which){
  const response=await fetch('./pose-binding-data.json');if(!response.ok)throw Error('体表绑定数据读取失败');const meta=await response.json(),row=meta.models[which],bytes=await (await fetch('./pose-skin-'+which+'.bin')).arrayBuffer(),hash=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');
  if(!row||row.vertices!==g.attributes.position.count||JSON.stringify(meta.palette)!==JSON.stringify(binding.ids)||await hash(g.attributes.position.array)!==row.positionHash||await hash(bytes)!==row.bindingHash)throw Error('体表与绑定数据不匹配');
  const header=new Uint32Array(bytes,0,2);if(header[0]!==0x534b3437||header[1]!==row.vertices||bytes.byteLength!==8+24*row.vertices)throw Error('体表绑定格式不正确');g.setAttribute('skinIndex',new T.Uint16BufferAttribute(new Uint16Array(bytes,8,row.vertices*4).slice(),4));g.setAttribute('skinWeight',new T.Float32BufferAttribute(new Float32Array(bytes,8+row.vertices*8,row.vertices*4).slice(),4));
 }
 async function ensureSkin(which){
  if(models.get(which)?.skin)return models.get(which);const maleDoc=await doc('../fullbody-tcm-v11/assets/surface.glb');maleDoc.scene.updateMatrixWorld(true);const maleNodes=[];maleDoc.scene.traverse(n=>{if(n.isMesh)maleNodes.push(n);});
  const file=which==='female'?'../fullbody-tcm-v12/assets/female/surface.glb':'../fullbody-tcm-v11/assets/surface.glb',bodyDoc=await doc(file);bodyDoc.scene.updateMatrixWorld(true);const nodes=[],geometries=[];bodyDoc.scene.traverse(n=>{if(n.isMesh){const g=bake(n,which==='female',true),temp=new T.Mesh(g);nodes.push(temp);geometries.push(g);}});
  const g=meters(mergeSurfaceGeometry(geometries));g.userData.nativeFemale=which==='female';const bvh=new MeshBVH(g,{maxLeafTris:12}),projector=createSkinProjector(nodes,{sex:which,standardized:which==='female',templateMeshes:maleNodes});
  await loadSurfaceBinding(g,which);binding.prepareSurface(g);const skin=mesh(g,new T.MeshStandardMaterial({color:color.surface,roughness:.86,side:T.DoubleSide}),false,true,true);binding.skinMaterial(skin.material);skin.applyBoneTransform=(i,v)=>binding.vertex(g,i,v);skin.visible=false;
  const model=models.get(which)||{layers:new Map(),ink:new Map()};Object.assign(model,{skin,bvh,projector,nodes,geometries,provenance:which==='female'?'HRA女性原生体表；共用教学比例配准，未个体校准':'Z-Anatomy男性分区体表；原有缺口保留'});models.set(which,model);return model;
 }
 function anchor(model,point,aim=null){const hit=model.bvh.closestPointToPoint(point);if(!hit)throw Error('无法绑定体表三角面');const g=model.skin.geometry,i=hit.faceIndex*3,indices=[g.index.getX(i),g.index.getX(i+1),g.index.getX(i+2)],v=indices.map(j=>new T.Vector3().fromBufferAttribute(g.attributes.position,j)),bary=new T.Vector3();T.Triangle.getBarycoord(hit.point,...v,bary);const normal=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0])).normalize();return {vertices:indices,bary:bary.toArray(),flip:!!aim&&normal.dot(aim)<0,rest:hit.point.toArray(),distance:hit.distance};}
 async function ensureInk(which,id,physicalSide){
  const model=await ensureSkin(which),key=id+'|'+physicalSide;if(model.ink.has(key))return model.ink.get(key);
  const m=MERIDIANS.find(m=>m.id===id),sides=['GV','CV'].includes(id)?['midline']:physicalSide==='both'?['right','left']:[physicalSide],records=[],points=[],guides=[];
  for(const s of sides){const data=referencePoints.filter(p=>p.meridian===id&&p.position).map(p=>{const source=new T.Vector3(...p.position);if(s==='left')source.x=2*99.55318155698478-source.x;return {...p,side:s,position:source,source};});
   const anchors=data.map(p=>{const context={...p,meridian:id},contact=model.projector.getContact(p.source,context),out=model.projector.project(p.source,.35,context),normal=out.clone().sub(contact).normalize(),attached=anchor(model,fromMM(contact),normal);return {...p,source:p.source,point:out,skin:contact,normal,attached};});
   for(const path of createRegionalGuides(T,new Map(),id,s,data,createGuidePaths))guides.push({value:model.projector.curve(path.points,{meridian:id,side:s,anchors:anchors.filter(a=>path.codes.includes(a.code)),codes:path.codes})});
   points.push(...anchors);records.push({side:s,count:anchors.length});
  }
  const ink=model.projector.createInk(guides,points,m.color),inkMesh=ink.mesh;meters(inkMesh.geometry);const positions=inkMesh.geometry.attributes.position,inkAnchors=[];
  for(let i=0;i<positions.count;i++)inkAnchors.push(anchor(model,new T.Vector3().fromBufferAttribute(positions,i)));
  // The distance-field primitive endpoints share the same triangle attachments
  // as their painted faces. Nothing is reprojected after the pose changes.
  const tex=inkMesh.material.uniforms.inkData.value,raw=tex.image.data,primitiveAnchors=[];
  for(let i=0;i<raw.length;i+=4)primitiveAnchors.push(anchor(model,fromMM(new T.Vector3(raw[i],raw[i+1],raw[i+2]))));
  root.add(inkMesh);inkMesh.visible=false;inkMesh.frustumCulled=false;
  const marker=new T.Points(new T.BufferGeometry(),new T.PointsMaterial({color:'#834d31',size:.007,sizeAttenuation:true,depthTest:true,depthWrite:false}));marker.visible=false;root.add(marker);
  const result={key,mesh:inkMesh,inkAnchors,primitiveAnchors,points,records,marker,stats:ink.stats};model.ink.set(key,result);return result;
 }
 async function ensureLayer(which,layer){
  const model=models.get(which)||{layers:new Map(),ink:new Map()};models.set(which,model);if(model.layers.has(layer))return model.layers.get(layer);
  const female=which==='female',systems=layer==='organs'?(female?['respiratory','digestive','urinary','reproductive','breast','vascular']:['visceral','heart']):layer==='vessels'?(female?['vascular']:['vessels']):['nervous'];const nodes=[];
  const native=female&&layer!=='nerves';let catalog=null;if(female&&native){const response=await fetch('../fullbody-tcm-v12/assets/female/catalog.json');if(!response.ok)throw Error('女性结构目录读取失败');catalog=(await response.json()).entries;}
  for(const system of systems){const url=native?'../fullbody-tcm-v12/assets/female/'+system+'.glb':layer==='nerves'?'../fullbody-tcm-v9/assets/nervous.glb':'../fullbody-tcm-v11/assets/'+system+'.glb';const d=await doc(url);d.scene.updateMatrixWorld(true);d.scene.traverse(n=>{if(!n.isMesh)return;const original=catalog?.find(x=>x.id===n.name)||n.userData.atlas,info=poseStructureInfo(original);if(!info||native&&layer==='organs'&&system==='vascular'&&!info.ancestry?.includes('VH_F_heart'))return;const g=meters(bake(n,native)),mat=new T.MeshStandardMaterial({color:layer==='vessels'&&(/vein|vena|静脉/i.test([info.name,info.en,info.english].join(' ')))?'#668ba2':color[layer],roughness:.7});const posed=mesh(g,mat,layer==='organs');posed.userData={info,layer,origin:native?'female-native':'shared-teaching'};posed.visible=false;nodes.push(posed);});}
  if(!nodes.length)throw Error('没有找到对应结构');model.layers.set(layer,nodes);return nodes;
 }
 async function ensurePelvis(which){
  if(which!=='female'||models.get('female')?.pelvis)return;const d=await doc('../fullbody-tcm-v12/assets/female/skeletal.glb');d.scene.updateMatrixWorld(true);const response=await fetch('../fullbody-tcm-v12/assets/female/catalog.json');if(!response.ok)throw Error('女性骨盆目录读取失败');const rows=(await response.json()).entries,map=new Map();d.scene.traverse(n=>{if(n.isMesh)map.set(n.name,n);});const groups={sacrum:['VH_F_sacrum'],coccyx:['VH_F_coccyx']};for(const side of ['right','left'])groups['hip-'+side]=['pubis','ilium','ischium'].map(p=>'VH_F_'+p+'_compact_bone_'+(side==='right'?'R':'L'));const pelvis=[];
  for(const [id,names] of Object.entries(groups)){const geometries=names.map(name=>{const row=rows.find(r=>r.sourceName===name),n=row&&map.get(row.id);if(!n)throw Error('缺少女性骨盆 '+name);return meters(bake(n,true));}),g=mergedPosition(geometries),n=new T.Mesh(g,new T.MeshStandardMaterial({color:'#ccba94',roughness:.75}));n.matrixAutoUpdate=false;n.userData.segment='pelvis';n.name='female-native-'+id;root.add(n);n.visible=false;pelvis.push(n);geometries.forEach(g=>g.dispose());}
  const model=models.get(which)||{layers:new Map(),ink:new Map()};model.pelvis=pelvis;models.set(which,model);
 }
 function hide(){for(const model of models.values()){if(model.skin)model.skin.visible=false;for(const nodes of model.layers.values())nodes.forEach(n=>n.visible=false);model.pelvis?.forEach(n=>n.visible=false);for(const ink of model.ink.values()){ink.mesh.visible=false;ink.marker.visible=false;}}}
 function applyView(){hide();const model=models.get(sex),internal=['organs','nerves','vessels'].includes(view);for(const n of meshes){n.visible=(view==='bones'||internal)&&!(sex==='female'&&model?.pelvis&&['sacrum','coccyx','hip-left','hip-right'].includes(n.name));n.material.transparent=internal;n.material.opacity=internal?.22:1;n.material.depthWrite=!internal;n.material.needsUpdate=true;}if(sex==='female'&&(view==='bones'||internal))model?.pelvis?.forEach(n=>{n.visible=true;n.material.transparent=internal;n.material.opacity=internal?.22:1;n.material.depthWrite=!internal;n.material.needsUpdate=true;});if(view==='surface'&&model?.skin){model.skin.visible=true;if(activeInk){activeInk.mesh.visible=linesOn||pointsOn;activeInk.marker.visible=pointsOn;activeInk.mesh.material.uniforms.linesOn.value=+linesOn;activeInk.mesh.material.uniforms.pointsOn.value=+pointsOn;}}
  if(['organs','nerves','vessels'].includes(view))model?.layers.get(view)?.forEach(n=>n.visible=(detailsOn||!n.userData.info.detail&&!n.userData.info.detailOnly)&&(view!=='vessels'||vesselFilter==='all'||vesselKind(n.userData.info)===vesselFilter));
  highlightStructure(currentStructure,highlightOn);update(currentResult);onStatus(view==='bones'?'210 骨块 · '+(sex==='female'?'原生女性骨盆＋共用参考':'男性参考'):view==='surface'?activePoints.length+' 个随体表参考点':(model?.layers.get(view)||[]).filter(n=>n.visible).length+' 个可见结构部件');onChange();
 }
 async function set(options){const previous={sex,view,channel,side};Object.assign(previous,options);const ticket=++epoch;busy=true;onStatus('正在准备'+({bones:'骨架',surface:'体表经络',organs:'器官',nerves:'神经',vessels:'血管'}[previous.view]));
  try{const key=previous.sex+'|'+previous.view+'|'+previous.channel+'|'+previous.side;let task=pending.get(key);if(!task){task=(async()=>{if(previous.sex==='female')await ensurePelvis('female');if(previous.view==='surface')return ensureInk(previous.sex,previous.channel,previous.side);if(previous.view!=='bones')await ensureLayer(previous.sex,previous.view);return null;})();pending.set(key,task);task.finally(()=>pending.delete(key)).catch(()=>{});}const ink=await task;if(ticket!==epoch)return;({sex,view,channel,side}=previous);if(options.pointsOn!==undefined)pointsOn=options.pointsOn;if(options.linesOn!==undefined)linesOn=options.linesOn;if(options.namesOn!==undefined)namesOn=options.namesOn;activeInk=ink;activePoints=ink?.points||[];activeRoutes=ink?.records||[];currentStructure=null;busy=false;applyView();}
  catch(e){if(ticket!==epoch)return;busy=false;onStatus('读取失败，可重试');throw e;}
 }
 function update(result){if(!result)return;currentResult=result;binding.update(result);for(let i=0;i<bones.length;i++)bones[i].matrix.copy(binding.matrices[i]);root.updateMatrixWorld(true);skeleton.update();for(const model of models.values()){if(model.skin)model.skin.boundingSphere=new T.Sphere(result.joints.pelvis.clone(),3);for(const nodes of model.layers.values())for(const n of nodes)n.boundingSphere=new T.Sphere(result.joints.pelvis.clone(),3);}const model=models.get(sex);model?.pelvis?.forEach(n=>{n.matrix.copy(binding.matrices[binding.ids.indexOf('pelvis')]);n.matrixWorld.copy(n.matrix);});
  if(view!=='surface'||!activeInk)return;if(!activePoints.some(p=>p.code===selectedCode&&p.side===selectedSide)){const p=activePoints.find(p=>p.code===selectedCode)||activePoints[0];if(p){selectedCode=p.code;selectedSide=p.side;}}const g=model.skin.geometry,positions=activeInk.mesh.geometry.attributes.position,v=new T.Vector3();
  for(let i=0;i<positions.count;i++){v.copy(posedTriangle(binding,g,activeInk.inkAnchors[i],.00015).point);positions.setXYZ(i,v.x,v.y,v.z);}positions.needsUpdate=true;
  const tex=activeInk.mesh.material.uniforms.inkData.value,raw=tex.image.data;for(let i=0;i<activeInk.primitiveAnchors.length;i++){v.copy(posedTriangle(binding,g,activeInk.primitiveAnchors[i],.00015).point);raw[i*4]=v.x;raw[i*4+1]=v.y;raw[i*4+2]=v.z;}tex.needsUpdate=true;
  const cloud=[];for(const p of activePoints){const h=posedTriangle(binding,g,p.attached,.0002);p.posed=h.point;p.posedNormal=h.normal;cloud.push(...p.posed.toArray());}
  activeInk.marker.geometry.dispose();activeInk.marker.geometry=new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(cloud,3));activeInk.marker.geometry.computeBoundingSphere();const selected=activePoints.find(p=>p.code===selectedCode&&p.side===selectedSide);activeInk.mesh.material.uniforms.selectedOn.value=selected?1:0;if(selected)activeInk.mesh.material.uniforms.selectedContact.value.copy(selected.posed);
 }
 const raycaster=new T.Raycaster();
 function visible(point,camera){const model=models.get(sex);if(view!=='surface'||!model?.skin)return false;const delta=point.posed.clone().sub(camera.position),distance=delta.length();raycaster.set(camera.position,delta.normalize());raycaster.far=distance-.0015;return raycaster.intersectObject(model.skin).length===0;}
 function pick(ndc,camera){raycaster.setFromCamera(ndc,camera);raycaster.far=Infinity;if(view==='surface'){if(!pointsOn)return null;const hits=raycaster.intersectObject(models.get(sex).skin);if(!hits.length)return null;const near=activePoints.filter(p=>p.posed.distanceTo(hits[0].point)<.025&&visible(p,camera)).sort((a,b)=>a.posed.distanceToSquared(hits[0].point)-b.posed.distanceToSquared(hits[0].point))[0];if(near){selectedCode=near.code;selectedSide=near.side;update(currentResult);onChange();return {kind:'point',point:near};}return null;}
  const hits=raycaster.intersectObjects((models.get(sex)?.layers.get(view)||[]).filter(n=>n.visible));if(hits.length){currentStructure=hits[0].object;onChange();return {kind:'structure',mesh:currentStructure};}return null;
 }
 function select(code,physicalSide){selectedCode=code;if(physicalSide)selectedSide=physicalSide;update(currentResult);onChange();return activePoints.find(p=>p.code===code&&p.side===selectedSide);}
 function highlightStructure(node,on=highlightOn){currentStructure=node;highlightOn=!!on;for(const nodes of models.get(sex)?.layers.values()||[])for(const n of nodes){const selected=n===node,fade=highlightOn&&node&&!selected;n.material.transparent=!!fade;n.material.opacity=fade?.18:1;n.material.depthWrite=!fade;n.material.emissive.set(highlightOn&&selected?'#71382d':'#000000');n.material.emissiveIntensity=highlightOn&&selected?.4:0;n.material.needsUpdate=true;}onChange();}
 function structureBounds(node){const b=new T.Box3(),p=new T.Vector3(),g=node.geometry;for(let i=0;i<g.attributes.position.count;i+=Math.max(1,Math.floor(g.attributes.position.count/5000)))b.expandByPoint(binding.vertex(g,i,p));return b;}
 function audit(){const model=models.get(sex);const sample=model?.skin?[0,Math.floor(model.skin.geometry.attributes.position.count/2),model.skin.geometry.attributes.position.count-1].map(i=>binding.vertex(model.skin.geometry,i).toArray()):[];return {sex,view,channel,side,vesselFilter,detailsOn,busy,pointsOn,linesOn,namesOn,highlightOn,structureId:currentStructure?.userData.info.id||null,provenance:model?.provenance||null,femaleFrame:sex==='female'?bodyFrameInfo():null,nativePelvis:model?.pelvis?.length||0,loadedLayers:Object.fromEntries([...(model?.layers||[])].map(([key,nodes])=>[key,{parts:nodes.length,visible:nodes.filter(n=>n.visible).length,origins:[...new Set(nodes.map(n=>n.userData.origin))]}])),skinSample:sample,skinVertices:model?.skin?.geometry.attributes.position.count||0,skinTriangles:model?.skin?model.skin.geometry.index.count/3:0,selectedCode,selectedSide,points:activePoints.map(p=>({code:p.code,side:p.side,rest:p.attached.rest,posed:p.posed?.toArray(),triangle:p.attached.vertices,bary:p.attached.bary,restBindingError:p.attached.distance})),ink:activeInk?.stats||null,clinicalCalibration:false,internalTissueForces:null};}
 return {set,update,pick,visible,select,highlightStructure,structureBounds,audit,setDetails:on=>{detailsOn=!!on;applyView();},setVesselFilter:filter=>{vesselFilter=validVesselFilter(filter);applyView();},structures:()=>models.get(sex)?.layers.get(view)?.filter(n=>n.visible)||[],points:()=>activePoints,selected:()=>activePoints.find(p=>p.code===selectedCode&&p.side===selectedSide),state:()=>({sex,view,channel,side,vesselFilter,detailsOn,highlightOn,structureId:currentStructure?.userData.info.id||'',pointsOn,linesOn,namesOn,selectedCode,selectedSide}),routes:()=>activeRoutes,provenance:()=>models.get(sex)?.provenance||null};
}
