import * as T from 'three';
import {REST,matrixFor} from './pose-engine.js';
// de Leva (1996), Table 4, male column. Fractions describe whole soft-tissue
// segments, never bone volumes. Cranial/proximal endpoints and alternatives
// are deliberately matched below; all mesh landmarks remain approximations.
export const INERTIA_SOURCE={title:'人体分段参数 · de Leva 1996 表4',url:'https://doi.org/10.1016/0021-9290(95)00178-6',pdf:'https://ebm.ufabc.edu.br/wp-content/uploads/2013/12/Leva-1996.pdf',population:'100名男性参考样本，平均24岁；非个体实测',table:'Table 4, male; head VERT–CERV, upper trunk CERV–XYPH, middle XYPH–OMPH, lower OMPH–MIDH, shank KJC–AJC'};
export const PARAMETERS={head:[.0694,.5002],upperTrunk:[.1596,.5066],middleTrunk:[.1633,.4502],lowerTrunk:[.1117,.6115],upperArm:[.0271,.5772],forearm:[.0162,.4574],hand:[.0061,.7900],thigh:[.1416,.4095],shank:[.0433,.4395],foot:[.0137,.4415]};
const V=a=>new T.Vector3(...a),mid=(a,b)=>a.clone().add(b).multiplyScalar(.5);
export function hull2(points){const sorted=points.map(p=>[p[0],p[1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]).filter((p,i,a)=>!i||p[0]!==a[i-1][0]||p[1]!==a[i-1][1]);if(sorted.length<3)return sorted;const cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]),half=a=>{const out=[];for(const p of a){while(out.length>1&&cross(out.at(-2),out.at(-1),p)<=0)out.pop();out.push(p);}return out;};const lo=half(sorted),hi=half([...sorted].reverse());return lo.slice(0,-1).concat(hi.slice(0,-1));}
export function pointInHull(point,hull){if(hull.length<3)return null;for(let i=0;i<hull.length;i++){const a=hull[i],b=hull[(i+1)%hull.length];if((b[0]-a[0])*(point[1]-a[1])-(b[1]-a[1])*(point[0]-a[0])< -1e-9)return false;}return true;}
export function createInertiaRig(meshes,handRig){
 const bounds=test=>{const b=new T.Box3();for(const m of meshes)if(test(m))b.union(m.geometry.boundingBox);return b;},head=bounds(m=>m.userData.segment==='head'),cerv=V(REST.C7),hip=mid(V(REST.hipR),V(REST.hipL));
 const span=cerv.y-hip.y,xyph=[cerv.x,cerv.y-span*242.1/603.3,cerv.z],omph=[cerv.x,cerv.y-span*(242.1+215.5)/603.3,cerv.z];
 const rig={vertex:new T.Vector3(head.getCenter(new T.Vector3()).x,head.max.y,head.getCenter(new T.Vector3()).z),xyph:V(xyph),omph:V(omph),feet:{},hands:{},mapping:{unit:'m',sourceScale:.001,head:'头骨最高点近似VERT，C7关节中心近似CERV',trunk:'XYPH和OMPH未测量；用论文男性纵向长度比例沿参考C7–双髋中点轴定位，XYPH随胸段、OMPH随L4，双髋中点随骨盆',limbs:'肩肘腕髋膝踝采用现有近似关节中心',hand:'第3掌骨远端采用中指根部近似，随指骨链',foot:'跟骨后端至足趾前端的足骨纵向轴；支撑图是足骨投影包络，未建足底软组织接触',xyph:xyph,omph:omph}};
 for(const side of ['R','L']){const foot=bounds(m=>m.userData.segment==='ankle'+side),heel=bounds(m=>m.name==='calcaneus-'+(side==='R'?'right':'left'));const c=foot.getCenter(new T.Vector3()),outline=[];for(const m of meshes.filter(m=>m.userData.segment==='ankle'+side)){const a=m.geometry.attributes.position;for(let i=0;i<a.count;i++){const p=new T.Vector3().fromBufferAttribute(a,i);outline.push([p.x,p.z]);}}rig.feet[side]={heel:new T.Vector3(c.x,heel.getCenter(new T.Vector3()).y,foot.min.z),toe:new T.Vector3(c.x,c.y,foot.max.z),outline:hull2(outline).map(([x,z])=>new T.Vector3(x,foot.min.y,z)),bounds:foot};rig.hands[side]=handRig[side].fingers.find(f=>f.index===3).nodes[0].clone();}
 return rig;
}
export function observeGravity(p,spec,r,rig,input,loadPoint,loadSupported){
 const mass=Math.max(20,Math.min(200,Number(input.mass)||70)),gravity=Math.max(0,Math.min(20,Number(input.gravity)||0)),segments=[];
 const map=(id,v)=>v.clone().applyMatrix4(matrixFor(r.parts[id])),add=(id,label,key,a,b,upper=false)=>{const [fraction,ratio]=PARAMETERS[key],center=a.clone().lerp(b,ratio);segments.push({id,label,fraction,mass:mass*fraction,ratio,endpoints:[a.toArray(),b.toArray()],center:center.toArray(),upper});};
 const cerv=r.joints.C7,xyph=map('trunk',rig.xyph),omph=map('L4',rig.omph),hips=mid(r.joints.hipR,r.joints.hipL);
 add('head','头颈','head',map('head',rig.vertex),cerv,true);add('upperTrunk','胸段','upperTrunk',cerv,xyph,true);add('middleTrunk','腹段','middleTrunk',xyph,omph,true);add('lowerTrunk','下躯干与骨盆','lowerTrunk',omph,hips);
 for(const side of ['R','L']){const label=side==='R'?'右':'左',j=r.joints;add('upperArm'+side,label+'上臂','upperArm',j['shoulder'+side],j['elbow'+side],true);add('forearm'+side,label+'前臂','forearm',j['elbow'+side],j['wrist'+side],true);const base=r.grip?.fingerChains.find(f=>f.side===side&&f.finger===3)?.nodes[0];add('hand'+side,label+'手','hand',j['wrist'+side],base?V(base):map('wrist'+side,rig.hands[side]),true);add('thigh'+side,label+'大腿','thigh',j['hip'+side],j['knee'+side]);add('shank'+side,label+'小腿','shank',j['knee'+side],j['ankle'+side]);add('foot'+side,label+'足','foot',map('ankle'+side,rig.feet[side].heel),map('ankle'+side,rig.feet[side].toe));}
 const sum=segments.reduce((v,s)=>v.addScaledVector(V(s.center),s.mass),new T.Vector3()),massSum=segments.reduce((n,s)=>n+s.mass,0),center=sum.divideScalar(massSum),reference=r.joints.lumbar;
 const upper=segments.filter(s=>s.upper),momentVector=upper.reduce((v,s)=>v.add(new T.Vector3(s.center[2]-reference.z,0,-(s.center[0]-reference.x)).multiplyScalar(s.mass*gravity)),new T.Vector3()),upperMass=upper.reduce((n,s)=>n+s.mass,0);
 const load=loadSupported?Math.max(0,Math.min(40,Number(input.load)||0)):0,loadValid=loadPoint?.length===3&&loadPoint.every(Number.isFinite),systemCenter=load>0&&loadValid?center.clone().multiplyScalar(mass).addScaledVector(V(loadPoint),load).divideScalar(mass+load):center.clone();
 let reason=null;if(gravity===0)reason='零重力：质心仍有定义，但没有重力作用线；不进行脚承重或支撑关系判断。';else if(p.dynamic||p.actionState||spec.water)reason='动作阶段或水中状态：加速度、浮力与推进未求解，不套用静态足底支撑判断。';else if(spec.bed||spec.chair||spec.floorSit||spec.kneeling||spec.quadruped||spec.handSupport||spec.heelSit||spec.bridge||spec.backSupport||spec.forearmSupport||spec.bike||spec.tool||spec.shelf||spec.rail||spec.window||spec.desk)reason='身体还接触床、座面、手膝、靠背、台面或工具；未测量多处支撑反力，不用足部范围代表全部支撑。';else if(!spec.feet?.length)reason='没有静态足底接触条件。';else if(spec.feet.some(side=>(spec['leg'+side]?.step||0)!==0))reason='双脚在不同高度承托；未作同一地面支撑判断。';
 let polygon=[];if(!reason){const points=[];for(const side of spec.feet){const f=rig.feet[side],matrix=matrixFor(r.parts['ankle'+side]),b=f.bounds.clone().applyMatrix4(matrix);if(Math.abs(b.min.y)>.01){reason='模型足骨最低点没有贴近同一地面，不能确认支撑范围。';break;}points.push(...f.outline.map(v=>{const w=v.clone().applyMatrix4(matrix);return [w.x,w.z];}));}if(!reason)polygon=hull2(points);}
 const support={applicable:!reason&&polygon.length>=3,reason,polygon:reason?[]:polygon,planeY:0,projection:[systemCenter.x,0,systemCenter.z],inside:reason?null:pointInHull([systemCenter.x,systemCenter.z],polygon),basis:load>0?'人体与设定外物':'人体',approximation:'足骨投影的凸包，近似支撑范围；不是实测足底接触、压力中心或平衡能力'};
 const upperReason=spec.bed||spec.backSupport||spec.forearmSupport||spec.chair||spec.floorSit||spec.handSupport||spec.quadruped||spec.water?'这是选定身体分段的重力项，支撑可能分担；不能作为腰部需要抵抗的净力矩。':p.dynamic?'当前是运动瞬时姿态；仅计算重力项，惯性、地面反力与肌肉控制未求解。':'这是模型选定分段对腰部参照点的重力项，未求支撑反力、肌肉力与内部关节力。';
 return {source:INERTIA_SOURCE,parameters:PARAMETERS,mapping:rig.mapping,segments,massSum,center:center.toArray(),systemCenter:systemCenter.toArray(),externalMass:load,gravity,upper:{mass:upperMass,fraction:upperMass/mass,center:upper.reduce((v,s)=>v.addScaledVector(V(s.center),s.mass),new T.Vector3()).divideScalar(upperMass).toArray(),reference:reference.toArray(),momentVector:momentVector.toArray(),moment:momentVector.length(),sagittal:momentVector.x,lateral:momentVector.z,segments:upper.map(s=>s.id),note:upperReason,omitted:'下躯干/骨盆与下肢未计入这一分段重力矩；并非所有位于腰点上方组织的精确分割'},support,individualCalibration:false,internalJointForce:null};
}
