const fs=require('fs'),path=require('path'),http=require('http'),{PNG}=require('pngjs'),pw=require('playwright');
const engine=process.env.BROWSER||'chromium',live=!!process.env.TEST_URL,root=process.cwd(),out=path.join(root,'fullbody-tcm-v23/checks'),prefix=(live?'compatibility-live-':'compatibility-local-')+engine;fs.mkdirSync(out,{recursive:true});
const server=live?null:http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');let f=path.join(root,decodeURIComponent(url.pathname));if(f.endsWith('/'))f+='index.html';if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}}).listen(8191,'127.0.0.1');
const report={version:'23.0.0',engine,live,checks:[],errors:[],pixelChecks:[],startedAt:new Date().toISOString(),clinicalCalibration:false};
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,pass?'':JSON.stringify(detail));if(!pass)throw Error(name);}
function diff(a,b){const x=PNG.sync.read(a),y=PNG.sync.read(b);let n=0;for(let i=0;i<x.data.length;i+=4)if(Math.abs(x.data[i]-y.data[i])+Math.abs(x.data[i+1]-y.data[i+1])+Math.abs(x.data[i+2]-y.data[i+2])>70)n++;return n;}
(async()=>{let browser,p;try{
 browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});const c=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});p=await c.newPage();p.setDefaultTimeout(120000);p.on('pageerror',e=>report.errors.push(e.message));
 const response=await p.goto(process.env.TEST_URL||'http://127.0.0.1:8191/fullbody-tcm-v23/');ck('Page responds',response.status()===200);await p.waitForFunction(()=>window.__ATLAS_STARTUP_ERROR__||(window.__ATLAS_LAYERS_V21__&&__FOOT_ATLAS__.getState().ready));const startup=await p.evaluate(()=>window.__ATLAS_STARTUP_ERROR__||null);ck('Application initializes without a caught startup error',!startup,startup);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));
 const settle=async()=>{await p.waitForFunction(()=>!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:180000});await p.waitForTimeout(160);};
 const snap=async name=>{await settle();await p.screenshot({path:path.join(out,prefix+'-'+name+'.png')});};
 const sex=async v=>{await p.locator('#bodySelector button[data-body-sex="'+v+'"]').click();await settle();};
 const choose=async v=>{await p.locator('#layersTab').click();await p.locator('[data-v21-view="'+v+'"]').click();await settle();};
 const read=()=>p.evaluate(()=>{const actual=[];__ATLAS_RENDER_AUDIT__.scene.traverseVisible(n=>{if(!n.isMesh)return;const r=n.userData.female||n.userData.atlas;if(r)actual.push({id:r.id,sex:n.userData.female?'female':'male',system:r.system,origin:r.origin,sourceId:r.sourceId,group:r.group,vertices:n.geometry.attributes.position.count,opacity:n.material.opacity,depth:n.material.depthWrite});else if(n.userData.home)actual.push({id:n.name,sex:'male',system:'bones',opacity:n.material.opacity});});actual.sort((a,b)=>a.id.localeCompare(b.id));return {s:__ATLAS_SHARED__.getState(),f:__ATLAS_FEMALE__.getState(),t:__ATLAS_TISSUES__.getState(),l:__ATLAS_LEARNING__.getState(),actual,ink:__ATLAS_LEARNING__.getInkAudit(),audit:__ATLAS_FEMALE__.getCompletionAudit()};});
 await p.locator('#layersTab').click();ck('Six direct views are visible without expanding anything',await p.locator('.v21-quick-grid button:visible').count()===6);
 ck('Custom mixer is not a collapsed details element',await p.locator('#customLayers').evaluate(e=>e.tagName==='SECTION'&&e.getBoundingClientRect().height>120));
 ck('No visible nested disclosures or duplicate display selector in layer panel',await p.locator('#tissuePanel summary:visible').count()===0&&!(await p.locator('#sharedDisplay').isVisible()));
 ck('Unsupported female-only options do not clutter male mixer',!(await p.locator('[data-shared-layer=breast]').isVisible())&&!(await p.locator('[data-v21-view=breast]').isVisible()));
 await snap('male-layer-workspace');await choose('skin');let r=await read();ck('Pure skin shortcut turns meridians off and keeps opaque skin',r.s.scene==='skin'&&!r.l.enabled&&r.actual.filter(n=>n.system==='surface').every(n=>n.opacity===1&&n.depth));
 await sex('female');r=await read();ck('Pure skin mode survives female switch',r.s.scene==='skin'&&!r.l.enabled&&r.f.systems.surface.opacity===1);
 await choose('bones');r=await read();report.coverage=r.audit;
 const femBones=r.actual.filter(n=>n.system==='skeletal');ck('Female complete skeleton contains 210 real bone meshes',femBones.length===210&&femBones.every(n=>n.vertices>=3),{count:femBones.length});
 ck('Every male bone identifier has a corresponding selectable female teaching part',await p.evaluate(()=>{const f=new Set(__ATLAS_FEMALE__.getVisibleCatalog().filter(r=>r.system==='skeletal').map(r=>r.sourceId));return __FOOT_ATLAS__.getCatalog().every(r=>f.has(r.id));}));
 ck('Teaching bone geometry exactly matches each source mesh, including small sesamoids',await p.evaluate(()=>{const source=new Map(),female=[];__ATLAS_RENDER_AUDIT__.scene.traverse(n=>{if(n.isMesh&&n.userData.home)source.set(n.name,n.geometry.attributes.position.count);if(n.isMesh&&n.userData.female?.system==='skeletal'&&n.userData.female.origin==='shared-teaching')female.push(n);});return female.length===206&&female.every(n=>n.geometry.attributes.position.count===source.get(n.userData.female.sourceId)&&Number.isFinite(n.geometry.boundingSphere.radius));}));
 const pelvis=femBones.filter(n=>n.origin==='female-native');ck('Four pelvic bones retain native female geometry',pelvis.length===4&&pelvis.every(n=>['hip-right','hip-left','sacrum','coccyx'].includes(n.sourceId)),pelvis.map(n=>n.sourceId));
 ck('Female full skeleton includes head, spine, both arms and both feet',new Set(femBones.map(n=>n.group)).size>=15,[...new Set(femBones.map(n=>n.group))]);ck('No original male scene meshes remain in female skeleton',r.actual.every(n=>n.sex==='female'));
 await snap('female-complete-skeleton');await p.locator('#labelsBtn').click();await settle();ck('Complete female bones have usable structure labels',await p.locator('#femaleStructureLabels button:visible').count()>0);await p.locator('#labelsBtn').click();
 await p.locator('#boneTab').click();await p.locator('#structureSystem').selectOption('skeletal');await p.locator('#structureScope').selectOption('all');ck('Bone directory counts whole selectable bones, not added fine meshes',await p.locator('#structureSummary').textContent().then(s=>s.includes('210')));
 await p.locator('#structureScope').selectOption('native-details');ck('Original 91 female bone/joint detail meshes remain accessible',await p.locator('#structureSummary').textContent().then(s=>s.includes('91')));await p.locator('[data-structure-id="hraf-963"]').click();await settle();r=await read();ck('Native detail opens independently without a duplicate full skeleton',r.f.selected==='hraf-963'&&r.f.isolated&&r.actual.length===1,r.actual.map(n=>n.id));
 await p.locator('#structureScope').selectOption('all');await p.locator('#structureSystem').selectOption('all');
 for(const [view,system,total,primary]of [['muscles','muscular',683,573],['nerves','nervous',550,550]]){await choose(view);r=await read();ck(view+': actual complete female system is loaded',r.f.systems[system].count===total&&r.f.systems[system].visible===primary,{system:r.f.systems[system]});ck(view+': male source scene is not accidentally enabled',r.actual.every(n=>n.sex==='female'));await snap('female-complete-'+view);await sex('male');const male=await read();ck(view+': corresponding male catalog and source mesh totals match',male.t.systems[system].count===total,male.t.systems[system]);await sex('female');r=await read();ck(view+': complete female system remains after roundtrip',r.f.systems[system].count===total&&r.f.systems[system].visible===primary);}
 await choose('muscles');await p.locator('#v21FineDetails').check();await settle();r=await read();ck('Female ancillary structures are explicit rather than silently missing',r.f.systems.muscular.visible===683);await p.locator('#v21FineDetails').uncheck();await settle();
 await sex('female');await choose('vascular');r=await read();ck('Female whole-body vessels load 649 actual parts with male-only vessels excluded',r.f.systems.vessels.count===649&&r.f.systems.vessels.visible===649,r.f.systems.vessels);ck('Native female heart and uterine vessels remain beside the non-duplicated reference circulation',r.actual.filter(n=>n.system==='vascular'&&n.origin==='female-native').length===18);ck('Male-only vessel exclusions are explicit in the coverage record',r.audit.excludedMaleOnlyVessels.length===10,r.audit.excludedMaleOnlyVessels);await snap('female-full-vascular');await sex('male');r=await read();ck('Male vascular source retains all 659 original vessel parts',r.t.systems.vessels.count===659);await sex('female');r=await read();ck('Whole-body female vessels remain complete after gender roundtrip',r.f.systems.vessels.visible===649);await choose('bones');await p.locator('#sharedLayer-ear').check();await settle();r=await read();ck('Female ear teaching layer includes all 48 actual ear parts',r.f.systems.ear.count===48&&r.f.systems.ear.visible===48,r.f.systems.ear);ck('Supplemented systems never turn the original male scene on',r.actual.every(n=>n.sex==='female'));
 for(const view of ['chest','heart','abdomen','pelvis','organs']){await sex('male');await choose(view);const before=await read();await sex('female');r=await read();ck(view+': native female organs and current scene are retained',r.s.scene===view&&r.actual.some(n=>n.origin==='female-native'&&n.system!=='skeletal')&&r.actual.every(n=>n.sex==='female'));if(view==='heart')ck('Heart shortcut does not silently enable lungs',!r.f.systems.respiratory?.on);if(['pelvis','organs'].includes(view))await snap('female-'+view);await sex('male');const after=await read();ck(view+': male organ scope restores after full female substitution',JSON.stringify(before.t.organView)===JSON.stringify(after.t.organView));}
 for(const who of ['male','female']){await sex(who);await choose('surface');await p.evaluate(()=>{__ATLAS_LEARNING__.clearStudyContext(true);__ATLAS_LEARNING__.setTCMSide('both');__ATLAS_LEARNING__.setMeridians(['HT','PC']);__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();const feature=async(lines,points)=>{await p.evaluate(({lines,points})=>{const s=__ATLAS_LEARNING__.getState();if(s.linesOn!==lines)document.querySelector('#meridianLineToggle').click();if(s.pointsOn!==points)document.querySelector('#acupointToggle').click();if(s.namesOn)document.querySelector('#pointNamesToggle').click();},{lines,points});await settle();return p.locator('#viewport canvas').first().screenshot();};const blank=await feature(false,false),line=await feature(true,false),point=await feature(false,true);await feature(true,true);r=await read();const skin=r.actual.filter(n=>n.system==='surface'),linePixels=diff(blank,line),pointPixels=diff(blank,point);report.pixelChecks.push({sex:who,linePixels,pointPixels});ck(who+': skin pigment is actually visible with opaque skin and no xray',skin.length>0&&skin.every(n=>n.opacity===1&&n.depth)&&!r.l.xray&&linePixels>350&&pointPixels>150,{linePixels,pointPixels});await snap(who+'-opaque-skin');}
 for(const who of ['male','female']){await sex(who);await choose('skin');await p.locator('#v21Meridians').check();await settle();ck(who+': custom meridian toggle honors requested value after asynchronous binding',await p.evaluate(()=>__ATLAS_LEARNING__.getState().enabled&&document.querySelector('#v21Meridians').checked));await p.locator('#v21Meridians').uncheck();await settle();ck(who+': custom meridian toggle turns pigment off again',await p.evaluate(()=>!__ATLAS_LEARNING__.getState().enabled));await choose('muscles');await p.locator('#v21FineDetails').check();await settle();ck(who+': detail toggle and actual internal-detail state agree',await p.evaluate(who=>document.querySelector('#v21FineDetails').checked&&(who==='female'?__ATLAS_FEMALE__.getState().fineDetails:(__ATLAS_TISSUES__.getState().details&&__ATLAS_TISSUES__.getState().fascia)),who));await p.locator('#v21FineDetails').uncheck();await settle();}
 await choose('skin');await p.locator('#sharedLayer-skeletal').check();await settle();await p.locator('#sharedOpacity-skeletal').evaluate(e=>{e.value='42';e.dispatchEvent(new Event('input',{bubbles:true}));});await settle();await p.locator('#saveLayerCombo').click();r=await read();const combo=r.actual;await choose('chest');await p.locator('#restoreLayerCombo').click();await settle();r=await read();ck('Saved custom mixer restores actual meshes and individual opacity',JSON.stringify(r.actual)===JSON.stringify(combo));await sex('male');await sex('female');r=await read();ck('Mixed skin and skeleton survives gender roundtrip without losing opacity',r.f.systems.skeletal.on&&Math.abs(r.f.systems.skeletal.opacity-.42)<.001&&r.f.systems.surface.opacity===1);
 await p.evaluate(async()=>{await Promise.all([__ATLAS_SHARED__.switchSex('male'),__ATLAS_SHARED__.choose('bones',false),__ATLAS_SHARED__.switchSex('female'),__ATLAS_SHARED__.choose('surface',false)]);});await settle();r=await read();ck('Rapid requests settle on final body and view',r.s.sex==='female'&&r.s.scene==='surface'&&r.ink.body==='female');ck('No transition errors',r.s.transitionErrors.length===0,r.s.transitionErrors);
 await p.locator('#layersTab').click();await p.locator('#v21Coverage').click();ck('Teaching-source distinction and non-standard-bone-count note are visible',await p.locator('#v21CoverageContent').textContent().then(s=>s.includes('不是人体标准骨数')&&s.includes('不是新增女性扫描数据')));await p.locator('#v21CoverageDialog form button').click();
 for(const [w,h]of [[1024,768],[390,844]]){await p.setViewportSize({width:w,height:h});if(!await p.evaluate(()=>document.body.classList.contains('nav-open')&&__ATLAS_SHARED__.getState().section==='layers'))await p.locator('#v21LayersOpen').click();await settle();await p.locator('#tissuePanel').evaluate(e=>e.closest('.sidebar').scrollTop=0);ck(w+': direct surface shortcuts remain accessible without disclosure',await p.locator('[data-v21-view=surface]').isVisible()&&await p.locator('[data-v21-view=skin]').isVisible());ck(w+': layer panel has no horizontal overflow',await p.locator('#tissuePanel').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await snap('layers-'+w);}
 ck('No uncaught browser errors',report.errors.length===0,report.errors);report.success=true;
 }catch(e){report.failure=e.stack;report.success=false;console.error(e);if(p)await p.screenshot({path:path.join(out,prefix+'-failure.png')}).catch(()=>{});process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();if(server)server.close();}})();
