import DATA from './evidence-data-v9.json';
export const evidenceData=DATA;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=k=>{const s=DATA.sources[k];return s?`<a target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">${esc(s.title)} ↗</a>`:'';};
export function evidenceBody(p){
 const r=DATA.points[p.code];
 if(!r){const h=DATA.headExamples[p.name];return `<section class="v9-evidence"><span class="v9-quality">补充目录 · 三维未校准</span><h4>定位与范围</h4><p>${esc(h?.[0]||p.locationNote||'本条目尚待核对原标准；仅保留部位导航。')}</p><p>本图中的光环仅表示观察范围，既不是标准误差圈，也不是精确穴位。</p><h4>现代解读</h4><p>本修订尚未录入该补充条目的单穴临床证据。名称中的“安眠”等文字不是疗效承诺。</p><p class="v9-source">${link(h?.[2]||'tara')}<br>${link('nccih')}</p></section>`;}
 return `<section class="v9-evidence"><span class="v9-quality">三维坐标：未配准 / 未通过定位审核</span><h4>1 · 定位依据</h4><p>${esc(r.location)}</p><small>${esc(r.locationStatus)}</small><p class="v9-landmarks">需要确认：${esc(r.requiredLandmarks)}</p><p>${esc(r.anatomyCaution)}</p><p class="v9-source">${link('who')}${r.sourcePage?`<br>第三方转录所引印刷页：${r.sourcePage}（尚未在本轮逐页复核原书）`:''}<br>${link('gb')}</p><h4>2 · 传统名称与意义</h4><p>${esc(r.traditional)}</p><small>传统归经或传统用途不等于现代临床证据。</small><h4>3 · 现代研究怎么理解</h4><span class="v9-level">${esc(r.evidenceLevel)}</span><p>${esc(r.evidence)}</p><p class="v9-source">${r.evidenceSources.map(link).join('<br>')}</p><h4>4 · 这个点在本模型上有多准确？</h4><dl class="v9-audit"><dt>皮肤/体表配准</dt><dd>未完成</dd><dt>逐穴独立复核</dt><dd>未完成</dd><dt>实测定位误差</dt><dd>未知，不能记成0</dd><dt>当前位置来源</dt><dd>旧版人工导航示意；不是WHO三维坐标</dd></dl><p>本模式不把“画出来、点得到”算作定位正确。用于取穴前必须有适配模型的体表标志与专业复核。本网页不提供针刺、诊断或复位指导。</p></section>`;
}
export function pointCardV9(p,m,byID){return `<div class="tcm-card-head"><span>${esc(m.name)} · ${esc(p.code)}</span><button id="closePointCard">收起</button></div><h3>${esc(p.name)}<small>${esc(p.pinyin)} · ${p.side==='left'?'人体左侧':p.side==='right'?'人体右侧':'中线／组合'}</small></h3><div class="tcm-card-actions"><button id="focusPointBtn">看相关部位</button><button id="speakPointBtn">朗读穴名</button></div><div class="point-step"><button id="pointPrev">上一穴</button><button id="pointNext">下一穴</button></div>${evidenceBody(p)}<details class="bone-reference"><summary>本模型原有骨性导航参照（不是取穴坐标）</summary>${(p.landmarks||[]).filter(id=>byID[id]).map(id=>`<button data-near="${esc(id)}">${esc(byID[id].name)}</button>`).join('')||'尚无已核验的结构关联'}</details>`;}
export function channelBody(ids){return ids.map(id=>{const m=DATA.meridians[id];if(!m)return '<p>经外补充不属于十四经目录；点击名称查看其单独资料状态。</p>';return `<article class="v9-channel"><h3>${esc(m.name)}<small>${esc(m.pinyin)} · ${m.id} · ${m.count}个名称</small></h3><h4>名称与分类</h4><p>${esc(m.meaning)}</p>${m.paired?`<p>传统表里配对：${esc(DATA.meridians[m.paired].name)}。这是传统分类关系，不是现代神经吻合关系。</p>`:''}<h4>当前图中的范围</h4><p>${esc(m.regions)}</p><p>${esc(m.coverage)}</p><h4>现代解读</h4><p>${esc(m.modern)}</p><p class="v9-source">${m.sourceKeys.map(link).join('<br>')}</p></article>`;}).join('');}
export function mountEvidenceUI(api){
 const panel=document.getElementById('tcmControls'),intro=document.createElement('section');intro.className='v9-mode-box';intro.innerHTML='<b>定位审核 · 与图形显示分开</b><p>361个名称有目录，0个坐标完成本模型临床配准。不要把“已显示”看成“已校准”。</p><label><input id="v9Strict" type="checkbox" checked> 严谨查阅：隐藏未校准的点线</label><button id="v9Diagram">切换到三维示意（未校准）</button><button id="v9ChannelInfo">查看所选经脉说明</button><a href="coordinate-audit.csv" download>查看逐穴校准清单</a>';panel.querySelector('.tcm-head').after(intro);
 const badge=document.createElement('div');badge.id='v9PrecisionBadge';badge.className='v9-precision-badge';document.querySelector('.stage').append(badge);
 const set=v=>{api.setPrecisionMode(v?'strict':'illustrative');document.getElementById('v9Strict').checked=v;document.getElementById('v9Diagram').textContent=v?'切换到三维示意（未校准）':'返回严谨查阅';badge.textContent=v?'严谨查阅 · 未校准点线已隐藏；目录仍可查阅':'三维示意 · 非真实神经，非已校准经穴位置';};
 document.getElementById('v9Strict').onchange=e=>set(e.target.checked);document.getElementById('v9Diagram').onclick=()=>set(api.getState().precisionMode!=='strict');set(true);
 const card=document.createElement('section');card.id='v9MeridianCard';card.className='tcm-point-card v9-channel-card';card.hidden=true;document.querySelector('.detail-scroll').prepend(card);
 function show(ids){api.clearPointSelection?.();card.innerHTML='<div class="tcm-card-head"><b>所选经脉 · 说明与证据</b><button id="v9CloseChannel">收起</button></div>'+channelBody(ids);card.hidden=false;document.getElementById('tcmPointCard').hidden=true;document.getElementById('tissueDetail')&&(document.getElementById('tissueDetail').hidden=true);document.body.classList.remove('tissue-detail-active');document.body.classList.add('point-detail-active','detail-open');document.body.classList.remove('nav-open');document.getElementById('v9CloseChannel').onclick=()=>{card.hidden=true;document.body.classList.remove('detail-open');};}
 document.getElementById('v9ChannelInfo').onclick=()=>show(api.getState().selectedMeridians);
 window.addEventListener('atlas:v9-channel-click',e=>show(e.detail.ids));window.addEventListener('atlas:v9-point-click',()=>card.hidden=true);window.addEventListener('atlas:bone-selected',()=>card.hidden=true);
 window.__ATLAS_EVIDENCE__={getData:()=>DATA,showChannel:show,getAudit:()=>({coordinateVerified:0,total:361,expandedTextSummaries:15,clinicalCalibration:false})};
}
