const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright');
const root=process.cwd(),engine=process.env.BROWSER||'chromium',live=!!process.env.TEST_URL,out=path.join(root,'atlas30-caption-evidence'),prefix=(live?'live':'local')+'-'+engine;fs.mkdirSync(out,{recursive:true});
const report={version:'30.0.1',engine,live,checks:[],errors:[],startedAt:new Date().toISOString()};let browser,p;
const server=live?null:http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}).listen(8331,'127.0.0.1');
const ck=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail||''));};
async function settle(){await p.waitForFunction(()=>window.__ATLAS_SHARED__&&!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:150000});await p.waitForTimeout(600);}
async function sex(value){await p.locator('button[data-body-sex="'+value+'"]').click();await settle();}
async function read(){return p.evaluate(()=>({body:document.body.dataset.bodySex,title:document.getElementById('regionHeading').textContent,count:document.getElementById('visibleCount').textContent,scene:__ATLAS_SHARED__.getState().scene,enabled:__ATLAS_LEARNING__.getState().enabled}));}
async function surfaceCaption(name,body,enabled){const a=await read();ck(name,a.body===body&&a.title===(body==='female'?'女性':'男性')+' · '+(enabled?'体表经络':'纯体表')&&a.count==='体表 · 不透明度 100%'&&a.enabled===enabled,a);}
(async()=>{try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}:{})});p=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true});p.setDefaultTimeout(150000);p.on('pageerror',e=>report.errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8331/fullbody-tcm-v30/');await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));
await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridian('TE');__ATLAS_LEARNING__.selectPoint('TE3','right',true);document.body.classList.remove('nav-open','detail-open');});await settle();await surfaceCaption('Male selected surface point is not described as a skeleton','male',true);
await sex('female');await surfaceCaption('Female selected surface uses the same scene terminology','female',true);
await sex('male');await surfaceCaption('Male return never reports zero visible bones over opaque skin','male',true);await p.screenshot({path:path.join(out,prefix+'-male-surface-caption.png')});
await p.evaluate(()=>__ATLAS_LEARNING__.toggleTCM(false));await settle();await surfaceCaption('Hidden meridians show pure-skin status without a skeleton count','male',false);await sex('female');await surfaceCaption('Hidden master remains hidden with matching female caption','female',false);await p.screenshot({path:path.join(out,prefix+'-female-pure-skin-caption.png')});
await p.evaluate(()=>__ATLAS_SHARED__.choose('bones',false));await settle();let a=await read();ck('Female bones retain the anatomical caption instead of skin status',a.scene==='bones'&&/骨/.test(a.title)&&!/体表/.test(a.title),a);await sex('male');a=await read();ck('Male bones retain the anatomical caption instead of skin status',a.scene==='bones'&&/骨/.test(a.title)&&!/体表/.test(a.title),a);
ck('No runtime errors',report.errors.length===0,report.errors);
}catch(e){report.failure=String(e.stack||e);console.error(report.failure);if(p)await p.screenshot({path:path.join(out,prefix+'-failure.png')}).catch(()=>{});}finally{report.success=!report.failure&&!report.errors.length&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));await browser?.close();server?.close();if(!report.success)process.exitCode=1;}})();