const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright'),{PNG}=require('pngjs');
const root=process.cwd(),engine=process.env.BROWSER||'webkit',live=!!process.env.TEST_URL,out=path.join(root,'fullbody-tcm-v25/checks'),prefix=(live?'quality-live-':'quality-local-')+engine;fs.mkdirSync(out,{recursive:true});
const report={version:'25.0.0',engine,live,checks:[],errors:[],comparison:{},startedAt:new Date().toISOString(),clinicalCalibration:false};
const server=live?null:http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}).listen(8225,'127.0.0.1');
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,pass?'':JSON.stringify(detail));}
const distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
function bends(routes){let severe=0,total=0,length=0;for(const r of routes)for(const b of r.branches){const p=b.points,c=b.connections;for(let i=1;i<p.length;i++){const a=distance(p[i],p[i-1]);if(c[i])length+=a;if(i===p.length-1||!c[i]||!c[i+1])continue;const d=distance(p[i+1],p[i]);if(a<=.3||d<=.3||a>=8||d>=8)continue;const v=p[i].map((x,k)=>x-p[i-1][k]),w=p[i+1].map((x,k)=>x-p[i][k]),t=Math.acos(Math.max(-1,Math.min(1,v.reduce((s,x,k)=>s+x*w[k],0)/(a*d))))*180/Math.PI;total+=t;if(t>60)severe++;}}return {severe,totalTurningDegrees:total,drawnLength:length};}
function changed(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);if(a.width!==b.width||a.height!==b.height)throw Error('Different screenshot sizes');let n=0;for(let i=0;i<a.data.length;i+=4)if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>36)n++;return n;}
const url=v=>live?(v==='25'?process.env.TEST_URL:'https://hengtong320.github.io/notionweb/fullbody-tcm-v24/?baseline=25'):'http://127.0.0.1:8225/fullbody-tcm-v'+v+'/';
let browser,p,context;
async function settle(){await p.waitForFunction(()=>!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:240000});await p.waitForTimeout(180);}
async function start(v,dpr=1){if(context)await context.close();context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:dpr,serviceWorkers:'block'});p=await context.newPage();p.setDefaultTimeout(120000);p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/WebGLProgram|VALIDATE_STATUS|GL_INVALID|shader error/i.test(m.text()))report.errors.push(m.text().slice(0,1000));});await p.goto(url(v));await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));}
async function frame(codes,ms,dir=[0,0,1],pad=20){await p.evaluate(({codes,ms,dir,pad})=>{const l=__ATLAS_LEARNING__,{THREE,camera,controls,invalidate}=__ATLAS_RENDER_AUDIT__;l.clearPointSelection();l.setMeridians(ms);if(l.getState().namesOn)document.querySelector('#pointNamesToggle').click();document.body.classList.remove('nav-open','detail-open');const qs=l.getNavigationCatalog().filter(q=>codes.includes(q.code)&&(q.side==='right'||q.side==='midline')),box=new THREE.Box3();qs.forEach(q=>box.expandByPoint(new THREE.Vector3(...q.position)));box.expandByScalar(pad);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),d=Math.max(size.y,size.x/camera.aspect)*.5/Math.tan(camera.fov*Math.PI/360)*1.2;controls.target.copy(center);camera.position.copy(center).addScaledVector(new THREE.Vector3(...dir).normalize(),d);camera.up.set(0,1,0);controls.minDistance=1;controls.maxDistance=10000;controls.update();camera.updateMatrixWorld(true);invalidate();},{codes,ms,dir,pad});await settle();}
async function shot(name){await p.screenshot({path:path.join(out,prefix+'-'+name+'.png')});}
async function features(lines,points){await p.evaluate(({lines,points})=>{const l=__ATLAS_LEARNING__,s=l.getState();if(s.linesOn!==lines)document.querySelector('#meridianLineToggle').click();if(s.pointsOn!==points)document.querySelector('#acupointToggle').click();},{lines,points});await settle();return p.locator('#viewport canvas').first().screenshot();}
(async()=>{try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});const data={};
 for(const version of ['24','25']){await start(version);data[version]={};for(const sex of ['male','female']){
  await p.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();
  const d=await p.evaluate(()=>({points:__ATLAS_LEARNING__.getNavigationCatalog(),routes:__ATLAS_LEARNING__.getRouteSamples(),ink:__ATLAS_LEARNING__.getInkAudit(),state:__ATLAS_LEARNING__.getState(),surface:__ATLAS_LEARNING__.getSurfaceState()}));data[version][sex]=d;fs.writeFileSync(path.join(out,prefix+'-v'+version+'-'+sex+'-geometry.json'),JSON.stringify(d));
  await frame(['PC7','PC8','PC9'],['PC']);await shot('v'+version+'-'+sex+'-palm');
  await frame(['PC7','PC8','PC9'],['PC'],[.45,.06,1]);await shot('v'+version+'-'+sex+'-palm-oblique');
  await frame(['LR1','LR2','SP1','SP2','SP3'],['LR','SP'],[0,.65,1],22);await shot('v'+version+'-'+sex+'-foot');
  if(version==='25'){
   const old=data['24'][sex],oldB=bends(old.routes),newB=bends(d.routes),pointShift=Math.max(...d.points.map(q=>{const previous=old.points.find(x=>x.code===q.code&&x.side===q.side);return previous?distance(q.position,previous.position):Infinity;})),traces=d.state.surfaceTrace,repairs=traces.flatMap(t=>(t.digitRepair?.spans||[]).map(x=>({...x,meridian:t.meridian,side:t.side}))),breaks=traces.reduce((n,t)=>n+t.disconnectedTransitions,0),oldBreaks=old.state.surfaceTrace.reduce((n,t)=>n+t.disconnectedTransitions,0);
   report.comparison[sex]={before:oldB,after:newB,pointShift,breaks,oldBreaks,repairs};
   ck(sex+' all 670 numbered display anchors match V24 exactly',d.points.length===670&&pointShift<1e-7,{count:d.points.length,pointShift});
   ck(sex+' total turning decreases without increasing severe sample turns',newB.totalTurningDegrees<oldB.totalTurningDegrees&&newB.severe<oldB.severe,{before:oldB,after:newB});
   ck(sex+' fixed-endpoint local skin repairs actually ran',repairs.length>0&&traces.every(t=>t.digitRepair?.anchorsMoved===0),repairs);
   ck(sex+' both palm-to-middle-finger loops improved',repairs.filter(r=>r.from==='PC8'&&r.to==='PC9').length===2&&repairs.filter(r=>r.from==='PC8'&&r.to==='PC9').every(r=>r.after<r.before*.95),repairs);
   ck(sex+' no new route disconnections',breaks<=oldBreaks,{breaks,oldBreaks});
   ck(sex+' accepted segments remain near real skin',traces.every(t=>t.maxDrawnSurfaceGap<=3.3),{maxGap:Math.max(...traces.map(t=>t.maxDrawnSurfaceGap))});
   ck(sex+' skin ink keeps normal depth and all face candidates',d.ink.active&&d.ink.depthTest&&d.ink.routes.every(r=>r.uniqueFacePainting&&r.candidateOverflow===0)&&!d.state.xray);
   await frame(['PC7','PC8','PC9'],['PC']);const blank=await features(false,false),solid=await features(true,false),point=await features(false,true);await features(true,true);
   ck(sex+' palm lines and point centers are visible in the actual canvas',changed(blank,solid)>150&&changed(blank,point)>70,{linePixels:changed(blank,solid),pointPixels:changed(blank,point)});
   await p.evaluate(()=>{const e=document.querySelector('#curveStyle');e.value='dashed';e.dispatchEvent(new Event('change',{bubbles:true}));});await settle();await shot(sex+'-round-dashes');
   const dashed=await features(true,false);ck(sex+' dashed mode changes actual line pixels without moving points',changed(dashed,solid)>100&&await p.evaluate(old=>JSON.stringify(__ATLAS_LEARNING__.getNavigationCatalog())===old,JSON.stringify(d.points)));
   await features(true,true);await p.evaluate(()=>{const e=document.querySelector('#curveStyle');e.value='smooth';e.dispatchEvent(new Event('change',{bubbles:true}));});await settle();
   await frame(['PC2','PC9','HT7','LU9'],['HT','PC','LU'],[0,0,1],40);await shot(sex+'-arm');
   await frame(['LI17','LI20','ST12','ST9','CV22'],['LI','ST','CV'],[0,0,1],40);await shot(sex+'-neck');
   await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();await shot(sex+'-all');
  }
 }}
 await start('25',2);await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await frame(['PC7','PC8','PC9'],['PC']);const blank=await features(false,false),line=await features(true,false);await features(true,true);await shot('high-dpi-palm');
 const dpi=await p.evaluate(()=>{const {scene,renderer}=__ATLAS_RENDER_AUDIT__,values=[];scene.traverseVisible(n=>{if(n.userData.skinInk)values.push(n.material.uniforms.pixelRatio.value);});return {device:devicePixelRatio,renderer:renderer.getPixelRatio(),values};});ck('High-DPI ink uses the active renderer pixel ratio',dpi.device===2&&dpi.renderer>1&&dpi.values.length>0&&dpi.values.every(v=>v===dpi.renderer),dpi);ck('High-DPI lines remain actually visible',changed(blank,line)>150,{pixels:changed(blank,line)});
 ck('No shader compilation or uncaught browser errors',report.errors.length===0,report.errors);
 }catch(e){report.failure=e.stack;console.error(e);if(p)await shot('failure').catch(()=>{});}finally{report.success=!report.failure&&!report.errors.length&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();server?.close();if(!report.success)process.exitCode=1;}})();
