import * as T from 'three';
import {REST,solveTwoBone,matrixFor} from './pose-engine.js';
const V=a=>new T.Vector3(...a),sides=['R','L'];
function basis(long,normal){long=long.clone().normalize();normal=normal.clone().addScaledVector(long,-normal.dot(long)).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(long.clone().cross(normal),long,normal));}
// Bone-end estimates are display pivots derived from the unchanged source mesh.
// They are not measured joint axes or muscle/tendon models.
export function createHandRig(meshes){const map=new Map(meshes.map(m=>[m.name,m])),rig={};
 for(const side of sides){const suffix=side==='R'?'right':'left',get=id=>map.get(id+'-'+suffix),center=m=>m.geometry.boundingBox.getCenter(new T.Vector3());
  const palm=[2,3,4,5].map(i=>center(get('hand-metacarpal-'+i))).reduce((a,b)=>a.add(b),new T.Vector3()).multiplyScalar(.25),carpal=center(get('capitate'));
  const long=center(get('hand-proximal-3')).sub(carpal).normalize(),normal=new T.Vector3(0,0,1);normal.addScaledVector(long,-normal.dot(long)).normalize();const across=long.clone().cross(normal).normalize();
  const end=(m,toward)=>{const points=m.geometry.attributes.position,dir=toward.clone().normalize(),c=center(m);let extreme=-Infinity;for(let i=0;i<points.count;i++)extreme=Math.max(extreme,new T.Vector3().fromBufferAttribute(points,i).sub(c).dot(dir));const out=new T.Vector3();let n=0;for(let i=0;i<points.count;i++){const p=new T.Vector3().fromBufferAttribute(points,i);if(p.clone().sub(c).dot(dir)>extreme-.003){out.add(p);n++;}}return n?out.multiplyScalar(1/n):c;};
  const fingers=[];for(let i=1;i<=5;i++){const names=(i===1?['metacarpal','proximal','distal']:['proximal','middle','distal']).map(k=>'hand-'+k+'-'+i),bones=names.map(get),previous=i===1?get('trapezium'):get('hand-metacarpal-'+i),all=[previous,...bones],nodes=[];
   for(let k=1;k<all.length;k++){const d=center(all[k]).sub(center(all[k-1]));nodes.push(end(all[k-1],d).add(end(all[k],d.clone().negate())).multiplyScalar(.5));}nodes.push(end(bones.at(-1),center(bones.at(-1)).sub(center(bones.at(-2)))));
   fingers.push({index:i,bones,nodes});
  }rig[side]={palm,long,normal,across,wristRest:center(get('scaphoid')).add(center(get('lunate'))).multiplyScalar(.5),frame:basis(long,normal),fingers};
 }return rig;
}
const local=(r,a)=>V(a).applyQuaternion(r.parts.trunk.rotation).add(r.joints.pelvis);
function role(point,long,normal,style){return {point,long:V(long),normal:V(normal),style};}
export function gripTask(spec,r){const id=spec.taskId,task={id,roles:{},type:null,elbowGuide:spec.boxPlacement?.elbowGuide,hingeFrame:spec.boxPlacement?.hingeFrame,hingeMix:spec.boxPlacement?.hingeMix??1,palmOffset:spec.boxPlacement?.palmOffset??.173,elbowFrame:spec.boxPlacement?.elbowFrame},wr=r.joints.wristR,wl=r.joints.wristL;
 const relative=(a)=>local(r,a),orient=v=>V(v).applyQuaternion(r.parts.trunk.rotation),set=(side,a,long,normal,style)=>{task.roles[side]=role(relative(a),long,normal,style);task.roles[side].long=orient(long);task.roles[side].normal=orient(normal);};
 if(spec.guitar){task.type='guitar';task.center=relative([-.13,.19,.28]);task.rotation=r.parts.trunk.rotation.clone();task.neck=relative([.43,.40,.28]);
  set('L',[.25,.340,.295],[-.35,.94,0],[0,0,1],'fret');set('R',[-.20,.29,.420],[0,-1,0],[0,0,-1],'strum');
 }else if(id==='rest-game'){task.type='controller';task.center=relative([0,.15,.30]);task.rotation=r.parts.trunk.rotation.clone();for(const side of sides){const sign=side==='R'?-1:1;set(side,[sign*.124,.15,.275],[0,0,1],[-sign,0,0],'controller');}
 }else if(id?.includes('phone')){task.type='phone';task.rotation=r.parts.trunk.rotation.clone();if(id.includes('ear')){task.center=r.joints.head.clone().add(orient([-.115,.050,.100]));task.rotation.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),Math.PI/2));task.roles.R=role(task.center.clone().add(orient([-.051,-.065,.045])),[0,1,0],[1,0,0],'phone');}else{const height=id==='stand-high-phone'?.55:id==='stand-phone'?.33:.23;task.center=relative([0,height,id==='sit-phone'?.32:.35]);for(const side of sides){const sign=side==='R'?-1:1;set(side,[sign*.061,height-.025+(id==='sit-phone'?0:side==='R'?.012:-.012),id==='sit-phone'?.310:.340],[0,0,-1],[-sign,0,0],'phone');}}
 }else if(spec.box){task.type='box';task.center=wr.clone().add(wl).multiplyScalar(.5).add(orient([0,-.04,.035]));task.rotation=r.parts.trunk.rotation.clone();
  if(spec.boxPlacement){task.center=spec.boxPlacement.shoulderOffset?r.joints.shoulderR.clone().add(r.joints.shoulderL).multiplyScalar(.5).add(V(spec.boxPlacement.shoulderOffset)):r.joints.kneeR.clone().add(r.joints.kneeL).multiplyScalar(.5).add(V([0,spec.boxPlacement.height,spec.boxPlacement.forward]));task.rotation.identity();}
  const boxOrient=v=>V(v).applyQuaternion(task.rotation);for(const side of sides){const sign=side==='R'?-1:1;task.roles[side]=role(task.center.clone().add(boxOrient([sign*task.palmOffset,-.062,.069])),[0,0,1],[-sign,0,0],'box');task.roles[side].long=boxOrient([0,0,1]);task.roles[side].normal=boxOrient([-sign,0,0]);}
 }else if(spec.bag){task.type='bag';const side=spec.loadSide==='L'?'L':'R';task.center=r.joints['wrist'+side].clone().add(new T.Vector3(0,-.18,.045));task.handleA=task.center.clone().add(new T.Vector3(-.07,.19,0));task.handleB=task.center.clone().add(new T.Vector3(.07,.19,0));task.roles[side]=role(task.center.clone().add(new T.Vector3(0,.25,-.032)),[0,-1,0],[0,0,1],'rod');
 }else if(spec.tool){task.type='tool';task.tip=relative([.06,-r.joints.pelvis.y+.035,.79]);task.top=relative([.02,.40,.30]);task.axis=task.top.clone().sub(task.tip).normalize();const finger=new T.Vector3(0,0,1).addScaledVector(task.axis,-task.axis.z).normalize();const sidesUsed=spec.tool==='vacuum'?['R']:sides;
  for(const side of sidesUsed){const sign=side==='R'?-1:1,c=task.top.clone().lerp(task.tip,side==='R'?.08:.31);task.roles[side]={point:c.add(new T.Vector3(sign*.038,0,0)),long:finger.clone(),normal:new T.Vector3(-sign,0,0),style:'rod'};}
 }else if(spec.bike){task.type='bike';task.center=wr.clone().add(wl).multiplyScalar(.5).add(new T.Vector3(0,-.03,.06));task.handleA=task.center.clone().add(new T.Vector3(-.21,0,0));task.handleB=task.center.clone().add(new T.Vector3(.21,0,0));for(const side of sides){const sign=side==='R'?-1:1;task.roles[side]=role(task.center.clone().add(new T.Vector3(sign*.18,.031,-.030)),[0,0,1],[0,-1,0],'rod');}
 }else if(spec.steering){task.type='wheel';task.center=relative([0,.23,.38]);task.rotation=r.parts.trunk.rotation.clone();for(const side of sides){const sign=side==='R'?-1:1;set(side,[sign*.215,.23,.367],[0,0,1],[-sign,0,0],'rod');}}
 return task.type?task:null;
}
const CURL={rod:[20,50,30],controller:[8,38,22],phone:[40,60,25],box:[5,30,18],fret:[3,18,10],strum:[-10,4,5]};
export function solveGrip(result,task,rig){if(!task)return result;
 // Move a shared held object into the common reachable region, rather than stretching arms or detaching a hand.
 if(task.type==='box'||task.type==='tool')for(let pass=0;pass<16;pass++){const shifts=[];for(const [side,role] of Object.entries(task.roles)){const h=rig[side],rotation=basis(role.long,role.normal).multiply(h.frame.clone().invert()),wrist=role.point.clone().sub(h.palm.clone().sub(h.wristRest).applyQuaternion(rotation)),shoulder=result.joints['shoulder'+side],a1=V(REST['shoulder'+side]).distanceTo(V(REST['elbow'+side])),a2=V(REST['elbow'+side]).distanceTo(h.wristRest),ik=solveTwoBone(shoulder,wrist,a1,a2,result.joints['elbow'+side]);if(ik.error>.00002)shifts.push(ik.end.clone().sub(wrist));}if(!shifts.length)break;const move=shifts.reduce((a,b)=>a.add(b),new T.Vector3()).multiplyScalar(1/shifts.length);if(task.type==='box'){task.center.add(move);for(const role of Object.values(task.roles))role.point.add(move);}else{task.top.add(move);task.axis.copy(task.top).sub(task.tip).normalize();for(const [side,role]of Object.entries(task.roles)){const sign=side==='R'?-1:1;role.point.copy(task.top).lerp(task.tip,side==='R'?.08:.31).add(new T.Vector3(sign*.038,0,0));role.long.set(0,0,1).addScaledVector(task.axis,-task.axis.z).normalize();}}}
 result.grip={type:task.type,task,contacts:[],fingerChains:[],matrices:[]};
 for(const [side,role] of Object.entries(task.roles)){const h=rig[side],rotation=basis(role.long,role.normal).multiply(h.frame.clone().invert());const wrist=role.point.clone().sub(h.palm.clone().sub(h.wristRest).applyQuaternion(rotation));const shoulder=result.joints['shoulder'+side],elbow=result.joints['elbow'+side],start=V(REST['shoulder'+side]),a1=start.distanceTo(V(REST['elbow'+side])),a2=V(REST['elbow'+side]).distanceTo(h.wristRest);const guide=task.elbowGuide|| (task.id==='carry-chest'?[.5,-.55,.02]:task.type==='phone'?(task.id.includes('ear')?[.20,-.55,.02]:task.id==='sit-phone'?[.7,.15,.02]:[.7,-.55,.02]):[.12,-.55,.02]),poleOffset=new T.Vector3((side==='R'?-1:1)*guide[0],guide[1],guide[2]),pole=shoulder.clone().add(task.elbowFrame==='thorax'?poleOffset.applyQuaternion(result.parts.T2.rotation):poleOffset),ik=solveTwoBone(shoulder,wrist,a1,a2,pole);
  // Keep the original shoulder/elbow rigid bone chain; only its target and hand orientation change.
  if(task.hingeFrame){
   const sourceUpper=V(REST['elbow'+side]).sub(start),sourceFore=h.wristRest.clone().sub(V(REST['elbow'+side])),sourceNormal=sourceUpper.clone().cross(sourceFore).normalize();
   const directionUpper=result.parts['shoulder'+side].rotation.clone().premultiply(new T.Quaternion().setFromUnitVectors(elbow.clone().sub(shoulder).normalize(),ik.mid.clone().sub(shoulder).normalize())),directionFore=result.parts['elbow'+side].rotation.clone().premultiply(new T.Quaternion().setFromUnitVectors(h.wristRest.clone().sub(V(REST['elbow'+side])).applyQuaternion(result.parts['elbow'+side].rotation).normalize(),ik.end.clone().sub(ik.mid).normalize()));
   const worldUpper=ik.mid.clone().sub(shoulder),worldFore=ik.end.clone().sub(ik.mid),worldNormal=worldUpper.clone().cross(worldFore).normalize();
   result.parts['shoulder'+side].rotation.copy(basis(worldUpper,worldNormal).multiply(basis(sourceUpper,sourceNormal).invert()));
   result.parts['elbow'+side].rotation.copy(basis(worldFore,worldNormal).multiply(basis(sourceFore,sourceNormal).invert()));
   result.parts['shoulder'+side].rotation.copy(directionUpper.slerp(result.parts['shoulder'+side].rotation,T.MathUtils.clamp(task.hingeMix,0,1)));result.parts['elbow'+side].rotation.copy(directionFore.slerp(result.parts['elbow'+side].rotation,T.MathUtils.clamp(task.hingeMix,0,1)));
   result.parts['elbow'+side].position.copy(ik.mid);result.joints['elbow'+side]=result.parts['elbow'+side].position;
  }else{
  for(const [key,from,to] of [['shoulder',elbow.clone().sub(shoulder),ik.mid.clone().sub(shoulder)],['elbow',h.wristRest.clone().sub(V(REST['elbow'+side])).applyQuaternion(result.parts['elbow'+side].rotation),ik.end.clone().sub(ik.mid)]]){const p=result.parts[key+side],delta=new T.Quaternion().setFromUnitVectors(from.normalize(),to.normalize());p.rotation.premultiply(delta);if(key==='elbow')p.position.copy(ik.mid);result.joints[key+side]=p.position;}
  }
  const hand=result.parts['wrist'+side];hand.position.copy(ik.end);hand.rest=h.wristRest.clone();hand.rotation.copy(rotation);result.joints['wrist'+side]=hand.position;const actual=h.palm.clone().applyMatrix4(matrixFor(hand));result.constraints.push({id:'grip'+side,error:actual.distanceTo(role.point),target:role.point.toArray(),actual:actual.toArray()});result.grip.contacts.push({side,style:role.style,target:role.point.toArray(),actual:actual.toArray(),error:actual.distanceTo(role.point),normal:role.normal.clone().normalize().toArray()});
  const base=matrixFor(hand);for(const f of h.fingers){let parentQ=rotation.clone(),node=f.nodes[0].clone().applyMatrix4(base);const style=CURL[role.style],worldNodes=[node.clone()];
   for(let k=0;k<f.bones.length;k++){let angle=f.index===1?(k===0?0:k===1?22:18):style[k];let turn=new T.Quaternion();if(f.index===1&&k===0&&role.style!=='strum'){const sign=side==='R'?1:-1;turn.setFromAxisAngle(h.normal,sign*24*Math.PI/180).multiply(new T.Quaternion().setFromAxisAngle(h.long,-sign*28*Math.PI/180));}else turn.setFromAxisAngle(h.across,angle*Math.PI/180);
    const q=parentQ.clone().multiply(turn);f.bones[k].matrix.copy(matrixFor({position:node,rest:f.nodes[k],rotation:q}));f.bones[k].matrixWorld.copy(f.bones[k].matrix);result.grip.matrices.push({mesh:f.bones[k],matrix:f.bones[k].matrix.clone()});node=node.clone().add(f.nodes[k+1].clone().sub(f.nodes[k]).applyQuaternion(q));parentQ=q;worldNodes.push(node.clone());}
   let tipTarget=null;
   if(role.style==='fret'&&f.index>1){const axis=task.neck.clone().sub(task.center).normalize(),axisNormal=role.normal.clone().normalize(),cross=axis.clone().cross(axisNormal).normalize(),start=worldNodes[0];const along=start.clone().sub(task.center).dot(axis);tipTarget=task.center.clone().addScaledVector(axis,along).addScaledVector(axisNormal,.078).addScaledVector(cross,-.020);}
   if(role.style==='strum'&&f.index>1){tipTarget=worldNodes[0].clone().addScaledVector(role.long.clone().normalize(),.030);const normal=role.normal.clone().normalize(),front=task.center.clone().addScaledVector(normal,-.069);tipTarget.addScaledVector(normal,front.clone().sub(tipTarget).dot(normal));}
   if(role.style==='controller'&&f.index>1)tipTarget=worldNodes[0].clone().sub(task.center).applyQuaternion(task.rotation.clone().invert()).setX((side==='R'?-1:1)*(f.index===5?.080:.070)).setZ(.055).applyQuaternion(task.rotation).add(task.center);
   if(role.style==='box'&&f.index===1)tipTarget=task.center.clone().add(V([side==='R'?-.173:.173,.025,.075]).applyQuaternion(task.rotation));
   if(task.type==='bag'&&f.index>1)tipTarget=worldNodes[0].clone().setY(task.center.y+.182).setZ(task.center.z+.028);
   if(task.type==='wheel'&&f.index>1)tipTarget=worldNodes[0].clone().setX(task.center.x+(side==='R'?-.165:.165)).setZ(task.center.z+.035);
   if(role.style==='rod'&&f.index===1)tipTarget=role.point.clone().addScaledVector(role.normal.clone().normalize(),.012).addScaledVector(role.long.clone().normalize(),.045);
   if(task.type==='wheel'&&f.index===1)tipTarget=task.center.clone().add(V([side==='R'?-.173:.173,.026,.033]).applyQuaternion(task.rotation));
   if(role.style==='fret'&&f.index===1){const axis=task.neck.clone().sub(task.center).normalize(),start=worldNodes[0],along=start.clone().sub(task.center).dot(axis);tipTarget=task.center.clone().addScaledVector(axis,along).addScaledVector(role.normal.clone().normalize(),.008);}
   if(role.style==='controller'&&f.index===1)tipTarget=task.center.clone().add(V([side==='R'?-.049:.049,.036,.009]).applyQuaternion(task.rotation));
   if(role.style==='phone'&&f.index>1&&task.id.includes('ear'))tipTarget=worldNodes[0].clone().setX(task.center.x-.020).setZ(task.center.z+.052);
   if(role.style==='phone'&&f.index===1&&task.id.includes('ear'))tipTarget=task.center.clone().add(new T.Vector3(-.020,-.025,.030));
   if(role.style==='phone'&&!task.id.includes('ear')){const sign=side==='R'?-1:1;if(f.index===1)tipTarget=task.center.clone().add(V([sign*.020,side==='R'?.004:-.032,.024]).applyQuaternion(task.rotation));else{const at=worldNodes[0].clone().sub(task.center).applyQuaternion(task.rotation.clone().invert());tipTarget=V([sign*.026,at.y,-.018]).applyQuaternion(task.rotation).add(task.center);}}
   if(tipTarget){const start=worldNodes[0],lengths=f.nodes.slice(1).map((v,i)=>v.distanceTo(f.nodes[i])),combined=role.style==='controller'&&f.index>1?Math.sqrt(lengths[1]**2+lengths[2]**2+2*lengths[1]*lengths[2]*Math.cos(Math.PI/6)):lengths[1]+lengths[2],pole=start.clone().addScaledVector(role.long.clone().normalize(),task.type==='bag'&&f.index>1?.020:role.style==='fret'&&f.index===1?0:role.style==='phone'&&f.index===1&&!task.id.includes('ear')?-.080:.080).addScaledVector(role.normal.clone().normalize(),task.type==='bag'&&f.index>1?.10:role.style==='fret'&&f.index===1?-.12:role.style==='fret'&&f.index>1?.12:role.style==='controller'&&f.index>1?.010:f.index===1?-.035:.018),ik=solveTwoBone(start,tipTarget,lengths[0],combined,pole),direction=ik.end.clone().sub(ik.mid).normalize(),nodes=[start,ik.mid,ik.mid.clone().addScaledVector(direction,lengths[1]),ik.end];if(role.style==='controller'&&f.index>1){const second=solveTwoBone(ik.mid,ik.end,lengths[1],lengths[2],ik.mid.clone().addScaledVector(role.normal.clone().normalize(),-.040));nodes[2]=second.mid;nodes[3]=second.end;}
    for(let k=0;k<3;k++){const restDelta=f.nodes[k+1].clone().sub(f.nodes[k]),worldDelta=nodes[k+1].clone().sub(nodes[k]),original=restDelta.clone().applyQuaternion(rotation).normalize(),q=new T.Quaternion().setFromUnitVectors(original,worldDelta.normalize()).multiply(rotation),matrix=matrixFor({position:nodes[k],rest:f.nodes[k],rotation:q});f.bones[k].matrix.copy(matrix);f.bones[k].matrixWorld.copy(matrix);const entry=result.grip.matrices.find(e=>e.mesh===f.bones[k]);entry.matrix.copy(matrix);}worldNodes.splice(0,worldNodes.length,...nodes);result.grip.contacts.push({side,finger:f.index,style:role.style,target:tipTarget.toArray(),actual:ik.end.toArray(),error:ik.error});
   }
   result.grip.fingerChains.push({side,finger:f.index,nodes:worldNodes.map(v=>v.toArray()),restLengths:f.nodes.slice(1).map((v,i)=>v.distanceTo(f.nodes[i]))});
  }
 }return result;
}
