const fs=require('fs'),path=require('path'),pw=require('playwright'),{PNG}=require('pngjs');
const engine=process.env.BROWSER||'chromium',out='atlas31-pointer',report={engine,public:true,checks:[],errors:[],startedAt:new Date().toISOString()};fs.mkdirSync(out,{recursive:true});let browser,p;
const ck=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail||''));};
async function settle(){await p.waitForFunction(()=>window.__ATLAS_SHARED__&&!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getState().surfaceBusy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:150000});await p.waitForTimeout(200);}
async function flags(v){await p.evaluate(v=>{const a=__ATLAS_LEARNING__;a.restoreDisplayState({...a.getState(),...v});},v);await settle();}
const image=async()=>PNG.sync.read(await p.screenshot());
function difference(a,b,q){let n=0;for(let dy=-5;dy<=5;dy++)for(let dx=-5;dx<=5;dx++){const x=Math.round(q.x)+dx,y=Math.round(q.y)+dy;if(x<0||y<0||x>=a.width||y>=a.height)continue;const i=(y*a.width+x)*4;if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>35)n++;}return n;}
(async()=>{try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(150000);p.on('pageerror',e=>report.errors.push(e.message));await p.goto('https://hengtong320.github.io/notionweb/fullbody-tcm-v31/?check=pointer');await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await settle();
for(const sex of ['male','female']){
 await p.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await settle();await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await p.evaluate(()=>{__ATLAS_LEARNING__.setTCMSide('both');__ATLAS_LEARNING__.setMeridians(['PC']);__ATLAS_LEARNING__.selectPoint('PC6','right',true);});await settle();await flags({namesOn:false,pointsOn:true,linesOn:true,guideOn:true});await p.evaluate(()=>__ATLAS_LEARNING__.clearPointSelection());await settle();
 const q=await p.evaluate(()=>__ATLAS_LEARNING__.getPointScreen('PC6','right'));await p.mouse.click(q.x,q.y);await settle();let s=await p.evaluate(()=>__ATLAS_LEARNING__.getState());ck(sex+' actual skin click selects the displayed PC6 center',s.selectedPoint?.code==='PC6'&&s.selectedPoint.side==='right',s.selectedPoint);
 await p.evaluate(()=>__ATLAS_SHARED__.showSection('directory'));await p.locator('.side-picker [data-side="left"]').click();await settle();s=await p.evaluate(()=>__ATLAS_LEARNING__.getState());ck(sex+' visible directory side button selects corresponding left skin point',s.selectedPoint?.code==='PC6'&&s.selectedPoint.side==='left'&&s.tcmSide==='left'&&s.visiblePoints>0,s.selectedPoint);
 await p.evaluate(()=>{__ATLAS_LEARNING__.clearPointSelection();__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();await flags({namesOn:false,pointsOn:true,linesOn:true,guideOn:true});const coords=await p.evaluate(()=>['left','right'].map(side=>__ATLAS_LEARNING__.getPointScreen('PC6',side)));const on=await image();await flags({pointsOn:false,linesOn:false,guideOn:false});const off=await image(),correct=difference(on,off,coords[0]),wrong=difference(on,off,coords[1]);ck(sex+' left-only view paints its visible left point',correct>=4,{correct,coords:coords[0]});ck(sex+' right-side ghost paint does not remain after left filtering',wrong===0,{wrong,coords:coords[1]});
 await flags({namesOn:true,pointsOn:true,linesOn:true,guideOn:true});await p.evaluate(()=>{__ATLAS_LEARNING__.setTCMSide('both');__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_SHARED__.showSection('layers');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();await p.screenshot({path:path.join(out,engine+'-'+sex+'-all-front.png')});await p.evaluate(()=>__ATLAS_LEARNING__.fitMeridian([0,0,-1]));await settle();await p.screenshot({path:path.join(out,engine+'-'+sex+'-all-back.png')});
}
ck('No runtime errors',!report.errors.length,report.errors);report.success=report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();}catch(e){report.failure=String(e.stack||e);report.success=false;}finally{fs.writeFileSync(path.join(out,engine+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();if(!report.success)process.exitCode=1;}})();