module.exports=async({page,settle,ck,snapshot,shot,setFlags,report})=>{
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>__ATLAS_SHARED__.switchSex('male'));await settle();await page.evaluate(()=>__ATLAS_SHARED__.choose('bones',false));await settle();
 await page.evaluate(()=>{__FOOT_ATLAS__.setExplode(.45);__ATLAS_SHARED__.showSection('layers');const e=document.querySelector('#sharedLayer-surface');e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));});await settle();
 let s=await snapshot();const bone=await page.evaluate(()=>{const b=__FOOT_ATLAS__.captureBoneState();return {explode:b.explode,moved:b.poses.filter(p=>p.offset.some(v=>Math.abs(v)>.01)||p.rotation.some((v,i)=>Math.abs(v-(i===3?1:0))>.01)).length};});
 ck('Enabling custom skin after exploded bones restores the skin pose',s.skin&&s.skinOpacity===1&&bone.explode===0&&bone.moved===0,{s,bone});await shot('male-custom-skin-after-explode');
 await page.evaluate(()=>{__ATLAS_LEARNING__.toggleTCM(true);__ATLAS_LEARNING__.setMeridians(['PC','HT']);__ATLAS_LEARNING__.selectPoint('PC6','right',true);});await settle();
 await page.evaluate(()=>__ATLAS_SHARED__.switchSex('female'));await settle();s=await snapshot();ck('Custom skin after pose repair survives female switching',s.skin&&s.reference==='female'&&s.selected?.visibleFromCamera&&s.skinOpacity===1,s);
 await page.evaluate(()=>__ATLAS_SHARED__.switchSex('male'));await settle();s=await snapshot();ck('Returning to cached male skin does not restore invisible exploded state',s.skin&&s.reference==='male'&&s.selected?.visibleFromCamera&&s.skinOpacity===1,s);
 await page.evaluate(()=>{window.__v31TransitionFrames=[];window.__v31Tracking=true;const tick=()=>{if(!window.__v31Tracking)return;const a=__ATLAS_LEARNING__.getSurfaceConsistencyAudit();if(a.transition)window.__v31TransitionFrames.push({body:a.body,ref:a.referenceBody,root:a.routeRootVisible,paint:a.ink.filter(r=>r.visible).map(r=>r.body)});requestAnimationFrame(tick);};requestAnimationFrame(tick);window.__v31Switch=__ATLAS_SHARED__.switchSex('female');});
 await page.waitForFunction(()=>__ATLAS_SHARED__.getState().transition);await page.keyboard.press('h');await page.keyboard.press('6');await page.evaluate(()=>window.__v31Switch);await settle();
 const frames=await page.evaluate(()=>{window.__v31Tracking=false;return window.__v31TransitionFrames;});s=await snapshot();ck('Transition frames never show a previous-body meridian overlay',frames.length>0&&frames.every(f=>!f.root&&f.paint.length===0),frames);ck('Global shortcuts cannot replace the selected point during switching',s.selected?.code==='PC6'&&s.skin&&s.skinOpacity===1,s);
 await page.evaluate(async()=>{await Promise.all(['male','female','male','female','male'].map(x=>__ATLAS_SHARED__.switchSex(x)));});await settle();s=await snapshot();ck('Rapid switching resolves to the final body with a matching skin binding',s.sex==='male'&&s.reference==='male'&&s.skin&&s.selected?.code==='PC6'&&s.selected.visibleFromCamera,s);
 await setFlags({namesOn:false,localStudyOnly:true});await page.evaluate(()=>document.querySelector('#saveLayerCombo').click());await settle();await page.evaluate(()=>__ATLAS_SHARED__.choose('bones',false));await settle();await page.evaluate(()=>document.querySelector('#restoreLayerCombo').click());await settle();s=await snapshot();ck('Saved local opaque-skin combination restores without reopening hidden names',s.skin&&s.skinOpacity===1&&!s.flags[3]&&s.flags[5]&&s.selected?.code==='PC6',s);
 await page.evaluate(()=>__ATLAS_SHARED__.switchSex('female'));await settle();s=await snapshot();ck('Saved local observation stays on the same named point after female switch',s.skin&&s.selected?.code==='PC6'&&s.selected.visibleFromCamera&&s.flags[5]&&!s.flags[3],s);await shot('female-restored-local-skin');
};