const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright'),{PNG}=require('pngjs');
const version=process.env.ATLAS_VERSION||'30',engine=process.env.BROWSER||'chromium',live=!!process.env.TEST_URL,strict=version!=='30',out=path.resolve(process.env.OUT_DIR||'atlas31-evidence');fs.mkdirSync(out,{recursive:true});const prefix=(live?'live-':'local-')+engine+'-v'+version;
const report={version,engine,live,checks:[],errors:[],startedAt:new Date().toISOString()};let browser,page;
const root=process.cwd(),server=live?null:http.createServer((q,r)=>{try{let f=path.resolve(root,'.'+decodeURIComponent(new URL(q.url,'http://local').pathname));if(!f.startsWith(root+path.sep))throw Error();if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');r.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');r.end(fs.readFileSync(f));}catch{r.writeHead(404).end();}}).listen(8231,'127.0.0.1');
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail??''));}
async function settle(){await page.waitForFunction(()=>window.__ATLAS_SHARED__&&!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getState().surfaceBusy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:150000});await page.waitForTimeout(180);}
async function shot(name){await page.screenshot({path:path.join(out,prefix+'-'+name+'.png')});}
async function snapshot(){return page.evaluate(()=>{const l=__ATLAS_LEARNING__.getState(),a=__ATLAS_LEARNING__.getSurfaceConsistencyAudit(),n=__ATLAS_FEMALE__.active?__ATLAS_FEMALE__.getState():__ATLAS_TISSUES__.getState();return {sex:a.body,reference:a.referenceBody,transition:a.transition,attached:a.surfaceAttached,skin:a.skinVisible,root:a.routeRootVisible,side:l.tcmSide,physical:__ATLAS_FEMALE__.active?n.side:__FOOT_ATLAS__.captureBoneState().side,points:l.visiblePoints,selected:a.selected,flags:[l.enabled,l.linesOn,l.pointsOn,l.namesOn,l.xray,l.localStudyOnly],routes:a.ink.map(r=>({meridian:r.meridian,side:r.side,body:r.body,visible:r.visible,lines:r.lines,points:r.points,selected:r.selected,cloud:r.cloud})),skinOpacity:n.systems.surface?.opacity,camera:__FOOT_ATLAS__.captureCamera()};});}
async function setFlags(v){await page.evaluate(v=>{const l=__ATLAS_LEARNING__,s=l.getState();l.restoreDisplayState({...s,...v});},v);await settle();}
(async()=>{try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(150000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/WebGLProgram|shader error|GL_INVALID/i.test(m.text()))report.errors.push(m.text());});await page.goto(process.env.TEST_URL||`http://127.0.0.1:8231/fullbody-tcm-v${version}/`);await page.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await page.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));await settle();
await page.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await page.evaluate(()=>{__ATLAS_LEARNING__.setMeridians(['HT','PC']);__ATLAS_LEARNING__.setTCMSide('right');__ATLAS_LEARNING__.selectPoint('PC6','right',true);});await settle();
// Use the real directory side button, not the meridian side method.
await page.evaluate(()=>document.querySelector('.side-picker [data-side="left"]').click());await settle();let s=await snapshot();report.sideConflict=s;ck('Physical left and meridian right cannot leave an empty surface overlay',s.physical==='left'&&s.side==='left'&&s.points>0&&s.selected?.side==='left',s);await shot('physical-side-reconciled');
await page.evaluate(()=>__ATLAS_SHARED__.switchSex('female'));await settle();s=await snapshot();ck('Female switch preserves the reconciled visible side',s.reference==='female'&&s.skin&&s.points>0&&s.routes.some(r=>r.visible)&&s.selected?.side==='left',s);await shot('female-side-switch');
await page.evaluate(()=>__ATLAS_SHARED__.switchSex('male'));await settle();s=await snapshot();ck('Return to male keeps enabled surface points visible',s.reference==='male'&&s.skin&&s.points>0&&s.routes.some(r=>r.visible),s);
// A separate fresh standard view tests actual point paint, not just JS visibility.
await page.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await page.evaluate(()=>{__ATLAS_LEARNING__.setTCMSide('both');__ATLAS_LEARNING__.setMeridian('ALL');});await settle();report.pointPaint=[];
for(const sex of ['male','female']){await page.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await settle();for(const code of ['PC6','HT7','LI4','ST36','SP6','KI3','BL40','GV14','CV12']){await page.evaluate(code=>__ATLAS_LEARNING__.selectPoint(code,'right',true),code);await settle();await setFlags({linesOn:false,guideOn:false,pointsOn:true,namesOn:false});const a=await snapshot(),q=await page.evaluate(code=>__ATLAS_LEARNING__.getPointScreen(code,'right'),code);const on=PNG.sync.read(await page.screenshot());await setFlags({pointsOn:false});const off=PNG.sync.read(await page.screenshot());let diff=0,near=0;if(q)for(let dy=-5;dy<=5;dy++)for(let dx=-5;dx<=5;dx++){const x=Math.round(q.x)+dx,y=Math.round(q.y)+dy;if(x<0||y<0||x>=on.width||y>=on.height)continue;const i=(y*on.width+x)*4;const d=Math.abs(on.data[i]-off.data[i])+Math.abs(on.data[i+1]-off.data[i+1])+Math.abs(on.data[i+2]-off.data[i+2]);if(d>30)diff++;near++;}const row={sex,code,contact:a.selected?.skinContact,visible:a.selected?.visibleFromCamera,pixelDifference:diff,near,q,skinOpacity:a.skinOpacity};report.pointPaint.push(row);ck(sex+' '+code+' opaque skin point has real visible pixels',a.skinOpacity===1&&a.selected?.visibleFromCamera&&diff>=4,row);await setFlags({pointsOn:true});if(['PC6','LI4','ST36','GV14'].includes(code))await shot(sex+'-'+code);}}
// Repeating a round trip must not accumulate coordinate drift or change flags.
await setFlags({linesOn:true,guideOn:true,pointsOn:true,namesOn:true});await page.evaluate(()=>__ATLAS_LEARNING__.selectPoint('PC6','right',true));await settle();const begin=await snapshot();const anchor=JSON.stringify(await page.evaluate(()=>__ATLAS_LEARNING__.getInkAudit().routes.map(r=>[r.meridian,r.side,r.centers])));for(const sex of ['male','female','male','female']){await page.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await settle();s=await snapshot();ck(sex+' all effective paint belongs to its current body',s.skinOpacity===1&&s.routes.filter(r=>r.visible).every(r=>r.body===sex)&&s.selected?.visibleFromCamera,s);}
ck('Round trips preserve all same-body contact coordinates exactly',anchor===JSON.stringify(await page.evaluate(()=>__ATLAS_LEARNING__.getInkAudit().routes.map(r=>[r.meridian,r.side,r.centers]))));ck('Round trips preserve line point name and depth choices',JSON.stringify(begin.flags)===JSON.stringify((await snapshot()).flags));
await setFlags({pointsOn:false,namesOn:false});await page.evaluate(()=>__ATLAS_SHARED__.switchSex('male'));await settle();await page.evaluate(()=>document.querySelector('.side-picker [data-side="left"]').click());await settle();s=await snapshot();ck('Side and sex restore do not reopen hidden point and name toggles',!s.flags[2]&&!s.flags[3]&&s.flags[1]&&s.routes.some(r=>r.visible&&r.lines),s);
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await setFlags({pointsOn:true,namesOn:true});await page.evaluate(()=>__ATLAS_LEARNING__.selectPoint('PC6','left',true));await settle();await page.evaluate(()=>__ATLAS_SHARED__.switchSex('female'));await settle();s=await snapshot();ck('Phone female surface selection remains visible',s.selected?.visibleFromCamera&&s.skinOpacity===1&&s.selected?.paintedSelection,s);await shot('phone-female-surface');
ck('No uncaught runtime or shader errors',report.errors.length===0,report.errors);report.success=report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();}catch(e){report.failure=String(e.stack||e);report.success=false;console.error(report.failure);}finally{fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();if(server)server.close();if(report.failure||strict&&!report.success)process.exitCode=1;}})();