'use strict';const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');const{chromium,webkit}=require('playwright');const p=path.resolve('fullbody-tcm-v12'),out=path.join(p,'checks');fs.mkdirSync(out,{recursive:true});const kind=process.env.BROWSER||'chromium',live=process.env.LIVE_URL,engine=kind==='webkit'?webkit:chromium;
const report={version:'12.0.0',browser:kind,startedAt:new Date().toISOString(),checks:[],errors:[],success:false,clinicalValidation:false};function ck(n,v,d){report.checks.push({name:n,pass:!!v,...(d===undefined?{}:{detail:d})});if(!v)throw Error(n+' '+JSON.stringify(d));console.log('PASS',n);}
const server=http.createServer((req,res)=>{const f=path.resolve(process.cwd(),'.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(process.cwd())){res.writeHead(403);return res.end();}let file=f;if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('content-type',({'html':'text/html; charset=utf-8','js':'text/javascript','css':'text/css','json':'application/json','glb':'model/gltf-binary','txt':'text/plain'})[file.split('.').pop()]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
let browser,page;const settle=async()=>{await page.waitForFunction(()=>!window.__FOOT_ATLAS__.getState().cameraAnimating);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));};
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=live||`http://127.0.0.1:${server.address().port}/fullbody-tcm-v12/`;report.url=url;browser=await engine.launch({headless:true,...(kind==='chromium'?{args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}:{})});const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});page=await ctx.newPage();page.setDefaultTimeout(45000);page.on('pageerror',e=>report.errors.push(String(e)));const response=await page.goto(url,{waitUntil:'load',timeout:90000});await page.waitForFunction(()=>window.__ATLAS_REFINEMENT__&&window.__ATLAS_FEMALE__&&window.__FOOT_ATLAS__.getState().ready,undefined,{timeout:90000});await settle();
ck('All 210 male bones remain',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().count===210));ck('Exact candidate HTML',crypto.createHash('sha256').update(await response.body()).digest('hex')===JSON.parse(fs.readFileSync(p+'/build-info.json')).files['index.html'].sha256);
ck('No large positioning-audit dashboard',!(await page.locator('body').innerText()).includes('361个名称有目录，0个坐标'));
await page.locator('#tcmBtn').click();await settle();ck('TCM shows illustrative routes without a blocking mode gate',await page.evaluate(()=>{const s=window.__ATLAS_LEARNING__.getState();return s.enabled&&s.precisionMode==='illustrative'&&s.routeDiagnostics.some(r=>r.visible);}));ck('Compact qualification retained',await page.locator('#v9PrecisionBadge').isVisible()&&(await page.locator('#v9PrecisionBadge').innerText()).includes('未校准'));
await page.locator('#v12SourceInfo').click();ck('Source details remain accessible',await page.locator('#sourceDialog').evaluate(e=>e.open));await page.locator('#sourceDialog [data-close]').click();await page.locator('#tcmClose').click();ck('Closing sidebar preserves meridians',await page.evaluate(()=>window.__ATLAS_LEARNING__.getState().enabled));
await page.locator('#layersTab').click();ck('Custom layers and advanced controls start collapsed',await page.locator('#customLayers').evaluate(e=>!e.open)&&await page.locator('#advancedLayers').evaluate(e=>!e.open));
await page.locator('#tissuePanel [data-profile="bones"]').click();await settle();await page.locator('#customLayers summary').click();ck('Off layer opacity is hidden',!(await page.locator('#muscularOpacity').isVisible()));await page.locator('#customLayers summary').click();
await page.locator('#tissuePanel [data-system-view="chest"]').click();await page.waitForFunction(()=>{const s=window.__ATLAS_TISSUES__.getState();return s.profile==='chest'&&s.systems.heart.loaded&&s.systems.visceral.loaded;},undefined,{timeout:90000});await settle();ck('Male chest scene still loads source organs',await page.evaluate(()=>window.__ATLAS_TISSUES__.getState().systems.visceral.visible>0));await page.screenshot({path:out+'/'+kind+'-male-chest.png'});
await page.locator('#focusWorkspace').click();ck('Focus stage hides sidebars without changing organ profile',await page.locator('.sidebar').isHidden()&&await page.evaluate(()=>window.__ATLAS_TISSUES__.getState().profile==='chest'));await page.keyboard.press('Escape');ck('Escape restores panels',await page.locator('.sidebar').isVisible());
await page.locator('[data-body-sex="female"]').click();await page.waitForFunction(()=>window.__ATLAS_FEMALE__.getState().active&&window.__ATLAS_FEMALE__.getState().systems.surface?.loaded,undefined,{timeout:120000});await settle();let female=await page.evaluate(()=>window.__ATLAS_FEMALE__.getState());ck('Independent female body surface loads',female.active&&female.systems.surface.count===1,female);ck('Male bones and tissues are not mixed into female',await page.evaluate(()=>!window.__FOOT_ATLAS__.getState().bonesOn&&Object.values(window.__ATLAS_TISSUES__.getState().systems).every(s=>!s.on)));ck('Male acupoint layer disabled in female',await page.evaluate(()=>!window.__ATLAS_LEARNING__.getState().enabled));ck('Female selection hides male TCM controls',await page.locator('.study-toolbar').isHidden());await page.screenshot({path:out+'/'+kind+'-female-body.png'});
await page.locator('[data-female-preset="pelvis"]').click();await page.waitForFunction(()=>{const s=window.__ATLAS_FEMALE__.getState();return s.preset==='pelvis'&&s.systems.reproductive?.loaded&&s.systems.skeletal?.loaded&&s.systems.urinary?.loaded;},undefined,{timeout:120000});await settle();
const parts=await page.evaluate(()=>window.__ATLAS_FEMALE__.getCatalog());const uter=parts.find(r=>r.sourceName==='VH_F_body_of_uterus');ck('Native female uterus and bilateral ovaries are present',!!uter&&parts.some(r=>r.name==='左卵巢')&&parts.some(r=>r.name==='右卵巢'));await page.locator('#femaleSearch').fill('子宫体');await page.locator(`[data-female-select="${uter.id}"]`).click();await settle();ck('Chinese search selects female uterus',await page.evaluate(id=>window.__ATLAS_FEMALE__.getState().selected===id,uter.id));await page.locator('#femaleIsolate').click();ck('Female isolation leaves one source mesh',await page.evaluate(()=>window.__ATLAS_FEMALE__.getState().visible===1));const pp=await page.evaluate(id=>window.__ATLAS_FEMALE__.getPickPoint(id),uter.id);ck('Female mesh surface is actually pickable',!!pp,pp);await page.mouse.click(pp.x,pp.y);await settle();ck('Actual mouse click identifies female uterus',await page.evaluate(id=>window.__ATLAS_FEMALE__.getState().selected===id,uter.id));await page.locator('#femaleMode').selectOption('focus');ck('Focused learning mode selectable',await page.evaluate(()=>window.__ATLAS_FEMALE__.getState().mode==='focus'));await page.locator('#femaleHide').click();await page.locator('#femaleMode').selectOption('solid');ck('Hidden female structure stays hidden after render mode change',await page.evaluate(id=>window.__ATLAS_FEMALE__.getState().hidden?.includes(id),uter.id));
await page.locator('[data-female-preset="pelvis"]').click();await settle();await page.locator('#femaleSearch').fill('');await page.screenshot({path:out+'/'+kind+'-female-pelvis.png'});
await page.locator('[data-female-preset="chest"]').click();await page.waitForFunction(()=>window.__ATLAS_FEMALE__.getState().systems.respiratory?.loaded&&window.__ATLAS_FEMALE__.getState().systems.vascular?.loaded,undefined,{timeout:120000});await settle();ck('Female cardiopulmonary assembly loads independently',await page.evaluate(()=>window.__ATLAS_FEMALE__.getState().visible>10));await page.screenshot({path:out+'/'+kind+'-female-chest.png'});
await page.locator('#femaleMode').selectOption('context');await page.locator('#femaleSide').selectOption('left');ck('Female left-side plus midline filter is active',await page.evaluate(()=>window.__ATLAS_FEMALE__.getState().side==='left'));
await page.locator('[data-female-preset="breast"]').click();await page.waitForFunction(()=>window.__ATLAS_FEMALE__.getState().systems.breast?.loaded,undefined,{timeout:120000});await settle();ck('Female breast includes 16 native structures',await page.evaluate(()=>window.__ATLAS_FEMALE__.getState().systems.breast.count===16));await page.screenshot({path:out+'/'+kind+'-female-breast.png'});
const download=page.waitForEvent('download');await page.locator('#captureBtn').click();const dl=await download;ck('Screenshot uses female context not stale male sternum',dl.suggestedFilename().includes('女性'));await dl.saveAs(out+'/'+kind+'-female-export.png');
await page.setViewportSize({width:390,height:844});await settle();ck('Phone page has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));ck('Sex selector accessible on phone',await page.locator('#bodySelector').isVisible());await page.screenshot({path:out+'/'+kind+'-female-phone.png'});
await page.setViewportSize({width:1440,height:1000});await page.locator('[data-body-sex="male"]').click();await page.waitForFunction(()=>!window.__ATLAS_FEMALE__.active);await settle();ck('Male model restores original chest context',await page.evaluate(()=>window.__ATLAS_TISSUES__.getState().profile==='chest'&&window.__ATLAS_TISSUES__.getState().systems.visceral.on));
await page.evaluate(async()=>{await window.__ATLAS_TISSUES__.setProfile('bones');window.__ATLAS_LEARNING__.toggleTCM(false);window.__FOOT_ATLAS__.setRegion('lumbar');window.__FOOT_ATLAS__.setExplode(100);});await settle();ck('Male lumbar vertical separation retained',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().bones.filter(b=>/^L[1-5]$/.test(b.id)).every(b=>Math.abs(b.position[0]-b.home[0])<.01)));await page.locator('#homeBtn').click();await settle();ck('Male global reset restores 210 bones',await page.evaluate(()=>window.__FOOT_ATLAS__.getState().visible===210));
ck('No uncaught page errors',report.errors.length===0,report.errors);report.success=true;
}catch(e){report.failure=String(e);console.error(e);if(page){try{await page.screenshot({path:out+'/failure-'+kind+'.png'});}catch{}}process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(out+'/'+(live?'live':'local')+'-'+kind+'.json',JSON.stringify(report,null,2));if(browser)await browser.close();server.close();console.log('RESULT',JSON.stringify({success:report.success,count:report.checks.length,failure:report.failure}));}})();
