const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright'),{PNG}=require('pngjs');
const root=process.cwd(),engine=process.env.BROWSER||'webkit',live=!!process.env.TEST_URL,out=path.join(root,'fullbody-tcm-v24/checks'),prefix=(live?'live-':'local-')+engine;fs.mkdirSync(out,{recursive:true});
const server=live?null:http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}).listen(8205,'127.0.0.1');
const report={version:'24.0.0',engine,live,checks:[],errors:[],bodies:{},startedAt:new Date().toISOString(),clinicalCalibration:false};
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,pass?'':JSON.stringify(detail));}
const dist=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
function curvature(routes){let severe=0,total=0,length=0;for(const r of routes)for(const branch of r.branches){const ps=branch.points||branch,con=branch.connections;for(let i=1;i<ps.length;i++){const d=dist(ps[i],ps[i-1]);if(d<8&&(!con||con[i]))length+=d;if(i<ps.length-1&&d>.3&&d<8&&dist(ps[i],ps[i+1])>.3&&dist(ps[i],ps[i+1])<8&&(!con||(con[i]&&con[i+1]))){const a=ps[i].map((x,k)=>x-ps[i-1][k]),b=ps[i+1].map((x,k)=>x-ps[i][k]),angle=Math.acos(Math.max(-1,Math.min(1,a.reduce((s,x,k)=>s+x*b[k],0)/(Math.hypot(...a)*Math.hypot(...b)))))*180/Math.PI;total+=angle;if(angle>60)severe++;}}}return {severeSampleTurns:severe,totalTurningDegrees:total,drawnLength:length};}
function pixels(a,b){a=PNG.sync.read(a);b=PNG.sync.read(b);let n=0;for(let i=0;i<a.data.length;i+=4)if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>36)n++;return n;}
(async()=>{let browser,p;try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/WebGLProgram|VALIDATE_STATUS|GL_INVALID|shader error/i.test(m.text()))report.errors.push(m.text().slice(0,1000));});p.setDefaultTimeout(120000);await p.goto(process.env.TEST_URL||'http://127.0.0.1:8205/fullbody-tcm-v24/');await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));
 const settle=async()=>{await p.waitForFunction(()=>!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:240000});await p.waitForTimeout(120);};
 const snap=async name=>{await settle();await p.screenshot({path:path.join(out,prefix+'-'+name+'.png')});};
 const feature=async(lines,points)=>{await p.evaluate(({lines,points})=>{const s=__ATLAS_LEARNING__.getState();if(s.linesOn!==lines)document.querySelector('#meridianLineToggle').click();if(s.pointsOn!==points)document.querySelector('#acupointToggle').click();if(s.namesOn)document.querySelector('#pointNamesToggle').click();},{lines,points});await settle();return p.locator('#viewport canvas').first().screenshot();};
 for(const sex of ['male','female']){
  await p.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();
  const d=await p.evaluate(()=>({display:__ATLAS_LEARNING__.getDisplayAudit(),ink:__ATLAS_LEARNING__.getInkAudit(),routes:__ATLAS_LEARNING__.getRouteSamples(),state:__ATLAS_LEARNING__.getState()}));
  const skin=await p.evaluate(()=>{const out=[];__ATLAS_RENDER_AUDIT__.scene.traverseVisible(n=>{if(n.userData.female?.system==='surface'||n.userData.atlas?.system==='surface')out.push({opacity:n.material.opacity,depth:n.material.depthWrite});});return out;});
  ck(sex+' opaque skin remains active without xray',skin.length>0&&skin.every(n=>n.opacity===1&&n.depth)&&!d.state.xray);
  ck(sex+' 670 finite registered display anchors remain available',d.display.count===670&&d.display.geometryFinite);
  ck(sex+' all anchors lie on their own route',d.display.maxLineGap<.001,{maxGap:d.display.maxLineGap});
  ck(sex+' no secondary marker relocation',d.display.maxSecondaryShift<.00001);
  ck(sex+' no duplicate point centers introduced',d.display.collisions.length===0,d.display.collisions);
  ck(sex+' all pigments use normal depth testing and unique face unions',d.ink.depthTest&&d.ink.routes.every(r=>r.uniqueFacePainting));
  ck(sex+' no stroke candidates truncated',d.ink.routes.every(r=>r.candidateOverflow===0),d.ink.routes.filter(r=>r.candidateOverflow).map(({meridian,side,candidateOverflow})=>({meridian,side,candidateOverflow})));
  ck(sex+' numbered anchors excluded from smoothing',d.state.surfaceTrace.every(r=>r.numberedAnchorsMoved===0&&r.maxIntermediateMove<=1.200001));
  const li=d.display.points.filter(p=>p.code==='LI1');ck(sex+' LI1 projects locally to the hand, not the thigh',li.length===2&&li.every(p=>sex==='female'?(p.position[1]>703&&p.position[1]<730&&(p.side==='right'?p.position[0]:199.10636311396956-p.position[0])<-230):dist(p.position,p.sourcePosition)<45),li.map(p=>({side:p.side,shift:dist(p.position,p.sourcePosition),position:p.position})));
  
  for(const id of ['CV','GV']){const ps=d.routes.filter(r=>r.meridian===id).flatMap(r=>r.branches.flatMap(b=>b.points));const deviation=Math.max(...ps.map(v=>Math.abs(v[0]-99.55318156)));ck(sex+' '+id+' route stays on the midline instead of drifting sideways',ps.length>10&&deviation<.4,{maxLateralDeviation:deviation,allowedRenderingClearance:.35,seamProbe:.02});}
  if(sex==='female'){
   const targets={LU11:{y:[770,792],x:[-240,-217]},LI1:{y:[703,730],x:[-246,-230]},LI2:{y:[738,749],x:[-227,-212]},LI3:{y:[748,760],x:[-219,-203]},PC9:{y:[660,675],x:[-222,-204]}};
   for(const [code,box] of Object.entries(targets)){const ps=d.display.points.filter(p=>p.code===code);ck('Female '+code+' remains on its intended finger on both hands',ps.length===2&&ps.every(p=>{const x=p.side==='right'?p.position[0]:199.10636311396956-p.position[0];return x>box.x[0]&&x<box.x[1]&&p.position[1]>box.y[0]&&p.position[1]<box.y[1];}),ps.map(p=>({side:p.side,position:p.position})));}
  }
  
  const local=d.display.points.filter(p=>['GB25','GB29','LR11'].includes(p.code));
  ck(sex+' flank, hip and thigh anchors stay near their intended body region',local.length===6&&local.every(p=>dist(p.position,p.sourcePosition)<90),local.map(p=>({code:p.code,side:p.side,shift:dist(p.position,p.sourcePosition)})));
  const cv=d.routes.filter(r=>r.meridian==='CV').flatMap(r=>r.branches.flatMap(b=>b.points)).filter(v=>v[1]>810&&v[1]<1250);
  ck(sex+' anterior midline stroke never switches to the back of the trunk',cv.length>50&&cv.every(v=>v[2]>0),{samples:cv.length,minZ:Math.min(...cv.map(v=>v[2]))});
  const outerAudit=await p.evaluate(()=>{const {THREE,scene}=__ATLAS_RENDER_AUDIT__,meshes=[];scene.traverseVisible(n=>{if(n.isMesh&&(n.userData.female?.system==='surface'||n.userData.atlas?.system==='surface'))meshes.push(n);});const samples=__ATLAS_LEARNING__.getRouteSamples().find(r=>r.meridian==='PC'&&r.side==='right').branches.flatMap(b=>b.points).filter(v=>v[1]>795&&v[1]<1210);let blocked=0,maxOcclusion=0;for(let i=0;i<samples.length;i+=4){const v=new THREE.Vector3(...samples[i]),ray=new THREE.Raycaster(v.clone().add(new THREE.Vector3(0,0,200)),new THREE.Vector3(0,0,-1)),hit=ray.intersectObjects(meshes,false)[0],occlusion=hit?200-hit.distance:0;if(occlusion>1){blocked++;maxOcclusion=Math.max(maxOcclusion,occlusion);}}return {tested:Math.ceil(samples.length/4),blocked,maxOcclusion};});
  ck(sex+' forearm and upper-arm stroke samples do not fall under the skin shell',outerAudit.tested>20&&outerAudit.blocked/outerAudit.tested<.02,outerAudit);
  let baseline=null;const bf=path.join('/tmp/atlas24-baseline',sex+'-routes.json');if(fs.existsSync(bf))baseline=JSON.parse(fs.readFileSync(bf));
  report.bodies[sex]={curvature:curvature(d.routes),baselineCurvature:baseline?curvature(baseline.routes):null,surfaceTriangles:d.ink.routes.reduce((n,r)=>n+r.surfaceTriangles,0),baselineTriangles:baseline?.ink.routes.reduce((n,r)=>n+r.surfaceTriangles,0),disconnections:d.state.surfaceTrace.reduce((n,r)=>n+r.disconnectedTransitions,0),pointChanges:baseline?d.display.points.map(p=>({code:p.code,side:p.side,change:dist(p.position,baseline.points.find(q=>q.code===p.code&&q.side===p.side).position)})).filter(p=>p.change>5):[],ink:d.ink.routes.map(({centers,...r})=>r)};
  if(baseline)ck(sex+' fewer skin triangles submitted than overlapping-stroke renderer',report.bodies[sex].surfaceTriangles<report.bodies[sex].baselineTriangles,report.bodies[sex]);
  await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridians(['HT','PC']);__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();const blank=await feature(false,false),line=await feature(true,false),point=await feature(false,true);await feature(true,true);const linePixels=pixels(blank,line),pointPixels=pixels(blank,point);ck(sex+' strokes and exact point centers are actually rendered',linePixels>350&&pointPixels>150,{linePixels,pointPixels});await snap(sex+'-opaque-ink');
  const before=await p.evaluate(()=>JSON.stringify(__ATLAS_LEARNING__.getNavigationCatalog()));await p.evaluate(()=>{const e=document.querySelector('#tcmXray');e.checked=true;e.dispatchEvent(new Event('change'));e.checked=false;e.dispatchEvent(new Event('change'));});await settle();ck(sex+' xray toggling does not move point locations',await p.evaluate(before=>before===JSON.stringify(__ATLAS_LEARNING__.getNavigationCatalog()),before));
  await p.evaluate(()=>{__ATLAS_LEARNING__.selectPoint('PC6','right',false);const s=__ATLAS_LEARNING__.getState();if(s.namesOn)document.querySelector('#pointNamesToggle').click();__ATLAS_RENDER_AUDIT__.invalidate();});await settle();ck(sex+' names-off is respected after selecting a point',await p.locator('.acu-name:visible').count()===0);
 }
 await p.evaluate(async()=>{await __ATLAS_SHARED__.switchSex('male');await __ATLAS_SHARED__.switchSex('female');});await settle();ck('Roundtrip restores the correct body-specific pigment',await p.evaluate(()=>__ATLAS_LEARNING__.getInkAudit().body==='female'&&__ATLAS_LEARNING__.getInkAudit().active));
 ck('No shader compilation or browser errors',report.errors.length===0,report.errors);
 }catch(e){report.failure=e.stack;console.error(e);if(p)await p.screenshot({path:path.join(out,prefix+'-failure.png')}).catch(()=>{});}finally{report.success=!report.failure&&!report.errors.length&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();server?.close();if(!report.success)process.exitCode=1;}})();
