'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium,webkit}=require('playwright');
const base=path.resolve(process.env.ATLAS_DIR||'fullbody-tcm-v3'),out=path.join(base,'qa-v3');fs.mkdirSync(out,{recursive:true});
const live=process.env.LIVE_URL,mode=process.env.BROWSER||'chromium',url=live||'file://'+path.join(base,'index.html');
const report={url,browser:mode,startedAt:new Date().toISOString(),checks:[],profiles:[],errors:[],success:false};
let browser,lastPage;
function ck(name,ok,detail){report.checks.push({name,pass:!!ok,...(detail===undefined?{}:{detail})});console.log(ok?'PASS':'FAIL',name);if(!ok)throw Error(name+': '+JSON.stringify(detail));}
async function settle(p){await p.waitForFunction(()=>!window.__FOOT_ATLAS__.getState().cameraAnimating);await p.waitForTimeout(160);}
async function state(p){return p.evaluate(()=>window.__FOOT_ATLAS__.getState());}
async function learning(p){return p.evaluate(()=>window.__ATLAS_LEARNING__.getState());}
async function start(profile){const c=await browser.newContext({viewport:{width:profile.w,height:profile.h},deviceScaleFactor:1,hasTouch:!!profile.touch,isMobile:!!profile.mobile,serviceWorkers:'block'});if(!live)await c.route(/^https?:/,r=>r.abort());await c.addInitScript(()=>{try{localStorage.setItem('atlas-auto-speak','0');localStorage.removeItem('atlas-meridian');}catch{}});const p=await c.newPage();lastPage=p;p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push(String(e)));p.on('console',m=>{if(m.type()==='error'&&/shader|VALIDATE|GL_INVALID|THREE.WebGLProgram/.test(m.text()))report.errors.push(m.text().slice(0,800));});const res=await p.goto(url,{waitUntil:'load',timeout:90000});await p.waitForFunction(()=>window.__ATLAS_LEARNING__?.getState().version==='3.0',undefined,{timeout:60000});await settle(p);if(live){ck(profile.name+' live HTTP 200',res.status()===200);const hash=crypto.createHash('sha256').update(await res.body()).digest('hex');ck(profile.name+' public build checksum',hash===JSON.parse(fs.readFileSync(path.join(base,'build-info.json'))).htmlSHA256);}return {c,p};}
async function capture(p,name){await settle(p);await p.screenshot({path:path.join(out,name+'.png')});}
function moved(s){return s.bones.filter(b=>Math.hypot(...b.offset)>.2);}
async function desktop(){const {c,p}=await start({name:'desktop',w:1440,h:1000});const s=await state(p);ck('V3 badge is visible',await p.locator('#releaseBadge').isVisible());ck('All 210 original bones and 534003 triangles',s.count===210&&s.bones.reduce((n,b)=>n+b.triangles,0)===534003);ck('All bone names retain pinyin',await p.evaluate(()=>window.__FOOT_ATLAS__.getCatalog().every(b=>b.pinyin)));
 await p.locator('#tcmBtn').click();ck('Panel and overlay enabled independently',(await learning(p)).enabled&&(await learning(p)).panelOpen);const pb=await p.locator('#tcmControls').boundingBox(),vb=await p.locator('#viewport').boundingBox();ck('Desktop settings do not cover 3D canvas',pb.x+pb.width<=vb.x+1,{panel:pb,viewport:vb});await p.locator('#tcmClose').click();ck('Collapsing settings retains meridian layer',(await learning(p)).enabled&&!(await learning(p)).panelOpen);await p.locator('#tcmLayerToggle').click();ck('Dedicated layer button hides only layer',!(await learning(p)).enabled);await p.locator('#tcmLayerToggle').click();ck('Layer can be restored without panel',(await learning(p)).enabled&&!(await learning(p)).panelOpen);
 await p.locator('#meridianQuick').selectOption('LU');await settle(p);await p.locator('#tcmBtn').click();await p.evaluate(()=>window.__ATLAS_LEARNING__.selectPoint('LU1','right'));let pt=await p.evaluate(()=>window.__ATLAS_LEARNING__.getPointScreen('LU5','right'));ck('Point is inside unobstructed canvas',await p.evaluate(p=>{const t=document.elementFromPoint(p.x,p.y);return !!t&&(t.tagName==='CANVAS'||t.id==='viewport');},pt),pt);
 const before=(await state(p)).camera;await p.mouse.move(pt.x,pt.y);await p.mouse.down();await p.mouse.move(pt.x+70,pt.y+26,{steps:12});await p.mouse.up();await settle(p);ck('Drag starting on point rotates the camera',(await state(p)).camera.some((v,i)=>Math.abs(v-before[i])>.1));ck('Drag does not select another point',(await learning(p)).selectedPoint?.code==='LU1');await p.locator('#tcmQuickFit').click();await settle(p);pt=await p.evaluate(()=>window.__ATLAS_LEARNING__.getPointScreen('LU5','right'));await p.mouse.click(pt.x,pt.y);ck('A true point click selects LU5',(await learning(p)).selectedPoint?.code==='LU5');
 await p.locator('#closePointCard').click();ck('Closing detail retains overlay and selected point',(await learning(p)).enabled&&!(await learning(p)).cardOpen&&(await learning(p)).selectedPoint?.code==='LU5');
 await p.locator('#tcmBtn').click();if(!(await learning(p)).panelOpen)await p.locator('#tcmBtn').click();await p.locator('[data-tcm-side="right"]').click();ck('Right channel side filter shows 11 LU points',(await learning(p)).visiblePoints===11);await p.locator('[data-tcm-side="left"]').click();ck('Switching side clears a wrong-side selection',!(await learning(p)).selectedPoint);await p.locator('[data-tcm-side="both"]').click();ck('Bilateral LU shows 22 points',(await learning(p)).visiblePoints===22);
 await p.locator('#acupointSearch').fill('hegu');ck('No-tone pinyin searches across channels',await p.locator('[data-point="LI4"]').count()===1);await p.locator('[data-point="LI4"]').click();ck('Search selection switches matching channel',(await learning(p)).activeMeridian==='LI'&&(await learning(p)).selectedPoint.code==='LI4');await p.locator('#acupointSearch').fill('');await p.locator('#pointNext').click();ck('Next-point navigation follows code order',(await learning(p)).selectedPoint.code==='LI5');await p.locator('#pointPrev').click();ck('Previous-point navigation returns LI4',(await learning(p)).selectedPoint.code==='LI4');await p.locator('#tcmClose').click();
 await p.locator('#meridianQuick').selectOption('BL');await capture(p,'v3-desktop-meridian');const size=(await learning(p)).pointSizePixels;await p.locator('#zoomInBtn').click();ck('Point diameter stays constant during zoom',(await learning(p)).pointSizePixels===size);await p.locator('#tcmLayerToggle').click();
 for(const region of ['lumbar','cervical','thoracic','spine','lumbosacral']){
  await p.evaluate(r=>{window.__FOOT_ATLAS__.reset();window.__FOOT_ATLAS__.setRegion(r);window.__FOOT_ATLAS__.setExplode(100);},region);await settle(p);const b=(await state(p)).bones.filter(b=>b.visible&&(/^[CTL]\d+$/.test(b.id)||['sacrum','coccyx'].includes(b.id))).sort((a,b)=>b.home[1]-a.home[1]);ck(region+' pure vertical displacement',b.every(b=>Math.abs(b.position[0]-b.home[0])<1e-6&&Math.abs(b.position[2]-b.home[2])<1e-6));const gaps=b.slice(1).map((cur,i)=>b[i].position[1]+b[i].boundsMin[1]-cur.position[1]-cur.boundsMax[1]);ck(region+' full separation leaves actual surface-box gaps',gaps.every(g=>g>15),gaps);
 }
 await p.evaluate(()=>{window.__FOOT_ATLAS__.reset();window.__FOOT_ATLAS__.setRegion('lumbar');window.__FOOT_ATLAS__.setExplode(100);});await capture(p,'v3-lumbar-separated');await p.locator('#resetBonesBtn').click();ck('Reset returns all bones exactly home',(await state(p)).bones.every(b=>Math.hypot(...b.position.map((v,i)=>v-b.home[i]))<1e-6&&Math.abs(b.rotation[3]-1)<1e-6));
 for(const id of ['L3','talus','mandible']){
  await p.evaluate(id=>{window.__FOOT_ATLAS__.selectBone(id);},id);await p.locator('#isolateBtn').click();await settle(p);await p.locator('[data-mode="move"]').click();pt=await p.evaluate(id=>window.__FOOT_ATLAS__.getPickPoint(id),id);ck(id+' real pickable surface',!!pt);await p.mouse.move(pt.x,pt.y);await p.mouse.down();await p.mouse.move(pt.x+42,pt.y-15,{steps:8});await p.mouse.up();ck(id+' independent bone drag',moved(await state(p)).length===1&&moved(await state(p))[0].id===id);await p.locator('#resetSelectedBtn').click();await settle(p);await p.locator('[data-mode="rotate"]').click();pt=await p.evaluate(id=>window.__FOOT_ATLAS__.getPickPoint(id),id);await p.mouse.move(pt.x,pt.y);await p.mouse.down();await p.mouse.move(pt.x+38,pt.y+16,{steps:7});await p.mouse.up();ck(id+' independent rotation',(await state(p)).bones.find(b=>b.id===id).rotation.slice(0,3).some(v=>Math.abs(v)>.01));await p.evaluate(()=>window.__FOOT_ATLAS__.reset());
 }
 await p.locator('#renderQuality').selectOption('balanced');ck('Flow mode switches rendering profile',(await state(p)).renderQuality==='balanced');await p.locator('#renderQuality').selectOption('high');ck('High mode can be restored',(await state(p)).renderQuality==='high');ck('Desktop has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.profiles.push({name:'desktop',width:1440,height:1000});await c.close();
}
async function compact(profile){const {c,p}=await start(profile);ck(profile.name+' canvas uses full screen width',(await p.locator('#viewport').boundingBox()).width>=profile.w*.96);ck(profile.name+' no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#openNav').click();ck(profile.name+' original region directory reachable',await p.locator('.region-picker').isVisible());await p.locator('[data-region="lumbar"]').click();await p.locator('#closeNav').click();ck(profile.name+' closing navigation preserves canvas',await p.evaluate(()=>!document.body.classList.contains('nav-open')));await p.locator('#tcmBtn').click();await p.locator('#acupointSearch').fill('LU5');await p.locator('[data-point="LU5"]').click();await settle(p);ck(profile.name+' selection closes drawer but preserves point',(await learning(p)).enabled&&!(await learning(p)).panelOpen&&(await learning(p)).selectedPoint?.code==='LU5');ck(profile.name+' no automatic detail obstruction',await p.evaluate(()=>!document.body.classList.contains('detail-open')));await p.locator('#chipDetails').click();ck(profile.name+' point detail accessible',await p.locator('#tcmPointCard').isVisible());await p.locator('#closeDetail').click();ck(profile.name+' closing detail preserves layer',(await learning(p)).enabled);await capture(p,'v3-'+profile.name);
 if(mode==='chromium'&&profile.touch&&profile.h>600){
  const session=await c.newCDPSession(p);let pt=await p.evaluate(()=>window.__ATLAS_LEARNING__.getPointScreen('LU5','right'));const before=(await state(p)).camera;await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:pt.x,y:pt.y}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:pt.x+45,y:pt.y+18}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle(p);ck(profile.name+' real touch drag rotates',(await state(p)).camera.some((v,i)=>Math.abs(v-before[i])>.1));
  const bb=await p.locator('#viewport').boundingBox(),cx=bb.x+bb.width*.45,cy=bb.y+bb.height*.5;const bs=await state(p);const dist=s=>Math.hypot(...s.camera.map((v,i)=>v-s.target[i]));await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:cx-30,y:cy},{id:2,x:cx+30,y:cy}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:cx-55,y:cy},{id:2,x:cx+55,y:cy}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle(p);ck(profile.name+' real two-finger pinch changes zoom',Math.abs(dist(await state(p))-dist(bs))>1);ck(profile.name+' pinch does not accidentally select another point',(await learning(p)).selectedPoint?.code==='LU5');
 }
 report.profiles.push(profile);await c.close();
}
(async()=>{try{browser=await (mode==='webkit'?webkit:chromium).launch({headless:true,...(mode==='chromium'?{args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}:{})});if(mode==='chromium'){await desktop();await compact({name:'tablet',w:820,h:1180,touch:true});await compact({name:'phone',w:390,h:844,touch:true,mobile:true});await compact({name:'phone-landscape',w:844,h:390,touch:true,mobile:true});}else{await compact({name:'webkit-tablet',w:820,h:1180,touch:true});await compact({name:'webkit-phone',w:390,h:844,touch:true,mobile:true});}ck('No uncaught JS or shader errors',report.errors.length===0,report.errors);report.success=true;}catch(e){report.failure=String(e);console.error(e);if(lastPage&&!lastPage.isClosed()){try{await lastPage.screenshot({path:path.join(out,(live?'live-':'')+mode+'-failure.png'),timeout:10000});}catch{}}process.exitCode=1;}finally{await browser?.close();report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,(live?'live-':'offline-')+mode+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({success:report.success,checks:report.checks.length,failure:report.failure,profiles:report.profiles}));}})();
