export function initSharedControls(ctx){
 const {learning,tissues,female,state,toast,invalidate,captureCamera,restoreCamera}=ctx,$=id=>document.getElementById(id),panel=$('tissuePanel'),femalePane=$('femaleLibrary'),tabs=document.querySelector('.library-tabs');let section='directory',pendingScene=0;
 $('boneTab').textContent='结构目录';$('layersTab').textContent='结构图层';$('tcmTab').textContent='经络穴位';
 const note=document.createElement('p');note.id='femaleAcupointStatus';note.className='shared-availability';note.textContent='女性目前可查穴名资料，暂无配准点线；当前视角保持不变。';note.hidden=true;$('tcmControls').prepend(note);
 const scope=document.createElement('p');scope.id='sharedModelScope';scope.className='shared-availability';scope.hidden=true;panel.querySelector('h2').after(scope);
 const map={bones:'skeletal',muscular:'muscular',nervous:'nervous',heart:'vascular',visceral:'digestive',vessels:'vascular',surface:'surface'};
 function redraw(){
  const f=female.active,fs=female.getState();document.body.dataset.atlasTab=section;note.hidden=!f;scope.hidden=!f;scope.textContent=f?'女性独立参考 · 骨骼与肌肉为部分覆盖':'';
  femalePane.hidden=!f||section!=='directory';document.querySelector('.bone-pane').hidden=f||section!=='directory';panel.hidden=section!=='layers';$('tcmControls').hidden=section!=='meridians';
  for(const[id,key]of[['boneTab','directory'],['tcmTab','meridians'],['layersTab','layers']]){$(id).classList.toggle('active',key===section);$(id).setAttribute('aria-selected',String(key===section));}
  if(f){for(const[k,v]of Object.entries(map)){const e=$(k==='bones'?'bonesOn':k+'On');if(e){e.checked=!!fs.systems[v]?.on;e.disabled=false;}}$('earOn').disabled=true;$('earOn').checked=false;$('layerCompactStatus').textContent=Object.entries(fs.systems).filter(([,v])=>v.on).map(([k])=>({surface:'体表',skeletal:'骨骼',muscular:'肌肉',nervous:'神经',respiratory:'心肺',vascular:'血管',digestive:'消化',urinary:'泌尿',reproductive:'生殖',breast:'乳腺'}[k]||k)).join(' ＋ ');}
  else{for(const[k,v]of Object.entries(tissues.getState().systems)){$(k+'On').disabled=false;$(k+'On').checked=v.on;}$('bonesOn').disabled=false;$('bonesOn').checked=state.bonesOn;}
  panel.querySelectorAll('.layer-block').forEach(b=>b.classList.toggle('layer-off',!b.querySelector('input[type=checkbox]').checked));panel.querySelectorAll('.layer-range').forEach(e=>e.hidden=f);
  for(const id of ['tissueSearch','tissueList'])$(id).hidden=f;
  for(const id of ['surfaceAttach','fasciaOn','tissueClip','nerveXray','internalDetails','earFilter','vesselFilter']){const e=$(id);if(e)e.closest('label').hidden=f;}
  for(const b of panel.querySelectorAll('[data-system-view]')){b.disabled=f&&b.dataset.systemView.startsWith('ear-');b.title=b.disabled?'此女性参考未提供完整耳部分层':'';}
  for(const b of document.querySelectorAll('[data-mode]')){b.disabled=f&&b.dataset.mode!=='orbit';if(b.disabled)b.title='女性参考暂无骨块拆解';}
  for(const id of ['explode','resetBonesBtn'])if($(id))$(id).disabled=f;invalidate();
 }
 function showSection(s){section=s;if(!female.active){if(s==='meridians'){learning.setPanel(true);learning.toggleTCM(true);}else if(s==='layers')tissues.showPanel(true);else learning.setPanel(false);}redraw();if(innerWidth<=1100){document.body.classList.add('nav-open');document.body.classList.remove('detail-open');}}
 for(const[id,s]of[['boneTab','directory'],['tcmTab','meridians'],['layersTab','layers']])$(id).addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showSection(s);},true);
 $('tcmBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showSection('meridians');},true);
 async function choose(key,preserve=false){const token=++pendingScene,view=preserve?captureCamera():null;
  if(female.active){const mapping={bones:'bones',muscles:'muscles',nerves:'nerves',compare:'compare',chest:'chest',heart:'chest',abdomen:'abdomen',vascular:'vessels',surface:'surface',pelvis:'pelvis',breast:'breast'};if(!mapping[key])return;await female.setPreset(mapping[key],{preserveView:preserve,preservePanel:true});}
  else if(['bones','muscles','nerves','compare'].includes(key))await tissues.setProfile(key);else if(key==='pelvis')window.__FOOT_ATLAS__.setRegion('pelvis');else if(key==='breast'){toast('男性当前模型未单列乳腺结构');return;}else await tissues.setAnatomyView(key);
  if(token!==pendingScene)return;if(view)restoreCamera(view);showSection('layers');redraw();
 }
 panel.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>choose(b.dataset.profile,true).catch(e=>toast(e.message)));
 panel.querySelectorAll('[data-system-view]').forEach(b=>b.onclick=()=>choose(b.dataset.systemView,false).catch(e=>toast(e.message)));
 const more=document.createElement('details');more.className='v12-disclosure';more.id='sharedMoreRegions';more.innerHTML='<summary>更多部位</summary><div class="profile-grid"><button data-shared-region="pelvis">盆腔结构</button><button data-shared-region="breast">乳腺结构</button></div>';panel.querySelector('.v12-tasks').append(more);more.querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.sharedRegion,false));
 const display=document.createElement('label');display.id='sharedDisplayRow';display.className='layer-check';display.innerHTML='显示方式<select id="sharedDisplay"><option value="solid">清晰原色</option><option value="context">透明参照</option><option value="focus">突出当前</option></select>';panel.querySelector('.v12-tasks').after(display);
 $('sharedDisplay').onchange=()=>{const v=$('sharedDisplay').value;if(female.active)female.setDisplayMode(v);else{const s=tissues.getState();for(const[k,x]of Object.entries(s.systems))if(x.on)tissues.setOpacity(k,v==='context'?.28:1);tissues.setBoneOpacity(v==='context'?.3:1);if(v==='focus'&&s.selected)tissues.choose(s.selected.id,false);}invalidate();};
 panel.addEventListener('change',e=>{if(!female.active)return;const key=e.target.id.replace(/On$/,'');if(map[key]){e.stopImmediatePropagation();female.enable(map[key],e.target.checked).then(redraw).catch(x=>toast(x.message));}},true);
 const pair=document.createElement('button');pair.id='pairHeartPericardium';pair.textContent='心经＋心包经';pair.title='同一视角对照；不自动调整镜头';$('pairHeart').after(pair);pair.onclick=()=>{learning.setMeridians(['HT','PC']);learning.toggleTCM(true);invalidate();};
 $('acupointResults').addEventListener('click',e=>{if(!female.active)return;const b=e.target.closest('[data-point]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const p=learning.getReferences().find(x=>x.code===b.dataset.point);if(!p)return;const d=$('femaleDetail');d.innerHTML='<button id="femalePointClose" class="female-drawer-close">收起详情 ×</button><span class="group-tag">经穴资料</span><h2></h2><p class="female-pinyin"></p><p>女性位置尚未配准，未将男性点位套到当前模型。当前画面不移动。</p><div class="female-actions"><button id="femalePointRead">朗读名称</button><a id="femalePointEvidence">查阅说明</a></div>';d.querySelector('h2').textContent=p.name+' '+p.code;d.querySelector('.female-pinyin').textContent=p.pinyin||'';$('femalePointRead').onclick=()=>window.__ATLAS_SPEECH__.speak(p.name);$('femalePointEvidence').href='evidence.html#'+new URLSearchParams({kind:'point',id:p.code,side:'right',mode:'strict'});$('femalePointClose').onclick=()=>document.body.classList.remove('detail-open');d.hidden=false;document.body.classList.add('detail-open');document.body.classList.remove('nav-open');},true);
 $('tcmControls').addEventListener('click',e=>{if(female.active&&e.target.closest('#tcmQuickFit,#tcmFitMeridian,#labelFitAll,#guideBack,#guideFront,#headPoints')){e.preventDefault();e.stopImmediatePropagation();toast('女性暂无对应点位，当前视角不改变');}},true);
 const maleSave=$('saveLayerCombo').onclick,maleRestore=$('restoreLayerCombo').onclick;let femaleSaved=null;
 $('saveLayerCombo').onclick=()=>{if(!female.active)return maleSave();femaleSaved=female.getState();try{localStorage.setItem('atlas13:femaleLayers',JSON.stringify(femaleSaved));}catch{}toast('已保存女性图层组合');};
 $('restoreLayerCombo').onclick=async()=>{if(!female.active)return maleRestore();let v=femaleSaved;try{v=JSON.parse(localStorage.getItem('atlas13:femaleLayers')||'null')||v;}catch{}if(!v)return toast('请先保存女性图层组合');const cam=captureCamera();for(const k of Object.keys(female.getState().systems))await female.enable(k,!!v.systems[k]?.on);for(const[k,x]of Object.entries(v.systems))if(x.on)await female.enable(k,true);female.setDisplayMode(v.mode);restoreCamera(cam);redraw();toast('已恢复女性组合，视角未改变');};
 $('tissueClear').onclick=()=>choose('bones',true).catch(e=>toast(e.message));femalePane.querySelector('h2').textContent='结构目录';
 window.addEventListener('atlas:sex-changed',()=>{redraw();requestAnimationFrame(redraw);});window.addEventListener('atlas:profile-changed',redraw);panel.addEventListener('change',()=>requestAnimationFrame(redraw));panel.addEventListener('click',()=>setTimeout(redraw,130));
 $('releaseBadge').textContent='V13 · 视角保持与经脉分辨';const hint=document.createElement('small');hint.id='meridianInteractionHint';hint.textContent='勾选只改显示；点穴位可聚焦；点“看全线”才移动镜头。';$('meridianChips').after(hint);$('organQuickBar')?.remove();
 window.__ATLAS_SHARED__={showSection,choose,getState:()=>({section,sex:female.active?'female':'male',sameTabs:[...tabs.querySelectorAll('button')].filter(b=>b.id!=='closeNav').map(b=>b.textContent),femalePointRegistration:false})};redraw();
}
