import * as THREE from 'three';
import {MeshBVH} from 'three-mesh-bvh';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export function createSurfaceProjector(meshes,boneCentres){
 const records=[];for(const mesh of meshes){mesh.updateWorldMatrix(true,false);const g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.applyMatrix4(mesh.matrixWorld);if(!g.attributes.normal)g.computeVertexNormals();g.computeBoundingBox();const a=mesh.userData.atlas||{};records.push({g,box:g.boundingBox.clone(),name:(a.en||a.name||mesh.name).toLowerCase(),side:a.side||'midline'});}
 const merge=rows=>{const gs=rows.map(r=>{const g=new THREE.BufferGeometry();g.setAttribute('position',r.g.attributes.position.clone());g.setAttribute('normal',r.g.attributes.normal.clone());return g;});const g=mergeGeometries(gs,false);gs.forEach(x=>x.dispose());return{g,bvh:new MeshBVH(g,{maxLeafTris:12})};};
 const all=merge(records),cache=new Map();let calls=0,rayHits=0,fallbacks=0,maxSourceDistance=0;
 function regionOf(v,c){if(c.region)return c.region;const x=Math.abs(v.x-99.553);if(x>160&&v.y>620&&v.y<800)return'hand';if(x>148&&v.y>=800&&v.y<1050)return'forearm';if(x>148&&v.y>=1050&&v.y<1320)return'upper';if(v.y>1450)return'head';if(v.y>1370)return'neck';if(v.y<150)return'foot';if(v.y<580)return'leg';if(v.y<790)return'thigh';return'body';}
 function subset(v,c){const r=regionOf(v,c),side=c.side||'midline',key=r+'|'+side;if(cache.has(key))return cache.get(key);const patterns={forearm:/forearm|wrist|elbow|cubital/,wrist:/wrist|forearm|palm|radial foveola/,hand:/hand|palm|wrist|perionyx|nail plate/,upper:/region of arm|bicipital|elbow|cubital|deltoid/,elbow:/elbow|forearm|cubital|region of arm/,head:/frontal|parietal|occipital|temporal|nasal|oral|labial|buccal|mental|orbital|auric|mastoid|zygomatic|lip|philtrum|eyebrow|tragus|helix|concha/,neck:/neck|triangle|supraclavicular/,leg:/region of leg|knee|malleol|ankle|popliteal/,thigh:/thigh|femoral|hip|knee/,foot:/foot|sole|heel|malleol|ankle|hallucial|metatarsal/};let rows=records.filter(x=>(side==='midline'||x.side==='midline'||x.side===side)&&(!patterns[r]||patterns[r].test(x.name)));if(!rows.length)rows=records;const s=merge(rows);cache.set(key,s);return s;}
 function direction(v,c){const m=c.meridian,r=regionOf(v,c),right=(c.side||'right')!=='left';if(['forearm','wrist','upper','elbow'].includes(r)){if(['LI','TE','SI'].includes(m))return new THREE.Vector3(0,0,-1);if(['LU','HT','PC'].includes(m))return new THREE.Vector3(0,0,1);}if(m==='GV'&&v.y>1530)return new THREE.Vector3(0,Math.max(0,(v.y-1530)/135),(v.z+35)/92).normalize();if(m==='GV')return new THREE.Vector3(0,0,v.y>1460&&v.z>0?1:-1);if(m==='BL'&&v.y<1440)return new THREE.Vector3(0,0,-1);if(c.view){const d=new THREE.Vector3(...c.view);if(c.side==='left')d.x*=-1;return d.normalize();}if(m==='SI'||m==='TE')return new THREE.Vector3(0,0,v.y>1470?1:-1);if(m==='GB')return new THREE.Vector3(right?-1:1,0,.1).normalize();if(m==='KI'&&v.y<80)return new THREE.Vector3(0,-1,0);if(['KI','SP','LR'].includes(m)&&v.y<780)return new THREE.Vector3(right?1:-1,0,.15).normalize();return new THREE.Vector3(0,0,1);}
 function project(v,offset=2.2,c={}){calls++;const s=subset(v,c),d=direction(v,c),origin=v.clone().addScaledVector(d,500),h=s.bvh.raycastFirst(new THREE.Ray(origin,d.clone().negate()),THREE.DoubleSide);let q;if(h&&h.point.distanceTo(v)<180){q=h.point.clone();rayHits++;}else{const near=s.bvh.closestPointToPoint(v);if(!near)throw Error('区域体表不可用');q=near.point.clone();fallbacks++;}maxSourceDistance=Math.max(maxSourceDistance,q.distanceTo(v));return q.addScaledVector(d,offset);}
 function curve(source,context={}){const c=new THREE.CatmullRomCurve3(source.map(v=>v.clone()),false,'centripetal'),count=Math.max(24,Math.min(2100,Math.ceil(c.getLength()/3))),p=c.getSpacedPoints(count).map(v=>project(v,2.2,context)),sm=new THREE.CatmullRomCurve3(p,false,'centripetal');class Routed extends THREE.Curve{getPoint(t,target=new THREE.Vector3()){return target.copy(project(sm.getPoint(t),2.2,context));}}const route=new Routed();route.arcLengthDivisions=count;const points=Array.from({length:count+1},(_,i)=>route.getPoint(i/count));return{geometry:new THREE.TubeGeometry(route,count,1.15,10,false),points};}
 function isVisible(v,cp){const d=v.clone().sub(cp),len=d.length(),hit=all.bvh.raycastFirst(new THREE.Ray(cp,d.normalize()),THREE.DoubleSide);return !hit||hit.distance>=len-2.5;}
 return{project,curve,isVisible,stats:()=>({version:13,method:'region-constrained directional surface projection',calls,rayHits,fallbacks,maxSourceDistance,regions:cache.size,clinicalCalibration:false}),dispose:()=>{all.g.dispose();cache.forEach(s=>s.g.dispose());records.forEach(r=>r.g.dispose());}};
}
