'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process'),{chromium,webkit}=require('playwright');
const base=path.resolve('fullbody-tcm-v13'),out=path.join(base,'checks');fs.mkdirSync(out,{recursive:true});const engine=process.env.BROWSER||'chromium',live=!!process.env.TEST_URL,url=process.env.TEST_URL||'http://127.0.0.1:8863/fullbody-tcm-v13/';const report={version:'13.0.0',browser:engine,url,startedAt:new Date().toISOString(),checks:[],errors:[],success:false,clinicalCalibration:false};
function ck(name,pass,detail){report.checks.push({name,pass:!!pass,...(detail===undefined?{}:{detail})});if(!pass)throw Error(name+': '+JSON.stringify(detail));console.log('PASS',name);}
const pause=ms=>new Promise(r=>setTimeout(r,ms)),dist=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
function same(a,b){return ['position','target','up'].every(k=>dist(a[k],b[k])<.0001)&&a.zoom===b.zoom;}
function dir(a){const v=a.position.map((x,i)=>x-a.target[i]),n=Math.hypot(...v);return v.map(x=>x/n);}
async function settle(p){await p.waitForFunction(()=>!window.__FOOT_ATLAS__.getState().cameraAnimating);await p.waitForTimeout(600);}
const cam=p=>p.evaluate(()=>window.__FOOT_ATLAS__.captureCamera());
const snap=(p,n)=>p.screenshot({path:path.join(out,engine+'-'+n+'.png'),timeout:30000});
function compare(routes,m1,m2,side){const a=routes.find(r=>r.meridian===m1&&r.side===side)?.branches.flat().filter(v=>v[1]>830&&v[1]<1020)||[],b=routes.find(r=>r.meridian===m2&&r.side===side)?.branches.flat().filter(v=>v[1]>825&&v[1]<1025)||[],ds=a.map(v=>Math.min(...b.map(w=>dist(v,w)))).sort((x,y)=>x-y);return{samples:ds.length,min:ds[0],median:ds[Math.floor(ds.length/2)],overlapFraction:ds.filter(x=>x<3).length/Math.max(1,ds.length)};}
(async()=>{let server,browser,page;try{
 if(!live){server=cp.spawn('python3',['-m','http.server','8863','--bind','127.0.0.1'],{stdio:'ignore'});await pause(900);}
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,serviceWorkers:'block'});page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(String(e)));
 const response=await page.goto(url,{waitUntil:'load',timeout:90000});if(live)ck('Exact published HTML',crypto.createHash('sha256').update(await response.body()).digest('hex')===crypto.createHash('sha256').update(fs.readFileSync(base+'/index.html')).digest('hex'));
 await page.waitForFunction(()=>window.__ATLAS_SHARED__&&window.__FOOT_ATLAS__.getState().ready,undefined,{timeout:90000});await settle(page);
 ck('All original 210 bones load',(await page.evaluate(()=>__FOOT_ATLAS__.getState().count))===210);
 ck('Canonical Changqiang is chang qiang',(await page.evaluate(()=>__ATLAS_LEARNING__.getReferences().find(p=>p.code==='GV1').pinyin))==='cháng qiáng');
 await page.evaluate(()=>{__FOOT_ATLAS__.setRegion('hand');__FOOT_ATLAS__.setSide('right');__FOOT_ATLAS__.setView('front');});await settle(page);
 const vp=await page.locator('#viewport').boundingBox();await page.mouse.move(vp.x+vp.width*.48,vp.y+vp.height*.5);await page.mouse.down();await page.mouse.move(vp.x+vp.width*.56,vp.y+vp.height*.54,{steps:12});await page.mouse.up();await settle(page);
 const first=await cam(page),scope=await page.evaluate(()=>({r:__FOOT_ATLAS__.getState().region,s:__FOOT_ATLAS__.getState().side}));await page.locator('#tcmTab').click();await settle(page);ck('Opening meridian panel preserves hand view',same(first,await cam(page)));
 for(const id of ['HT','PC','GV','BL','CV','KI','PC']){const before=await cam(page);await page.locator('[data-meridian="'+id+'"]').click();await settle(page);ck('Actual '+id+' checkbox preserves camera',same(before,await cam(page)));}
 const nextScope=await page.evaluate(()=>({r:__FOOT_ATLAS__.getState().region,s:__FOOT_ATLAS__.getState().side}));ck('Meridian filters do not restore whole skeleton',JSON.stringify(scope)===JSON.stringify(nextScope),nextScope);
 let before=await cam(page);await page.locator('#meridianQuick').selectOption('GV');await settle(page);ck('Quick selector does not force rear view',same(before,await cam(page)));
 before=await cam(page);await page.locator('[data-tcm-side="left"]').click();await settle(page);ck('Left-right filter does not move camera',same(before,await cam(page)));
 before=await cam(page);await page.locator('#pairHeartPericardium').click();await settle(page);ck('Pair comparison does not move camera',same(before,await cam(page)));
 before=await cam(page);await page.locator('#tcmFitMeridian').click();await settle(page);ck('Explicit fit does move camera',!same(before,await cam(page)));
 await page.evaluate(()=>{__ATLAS_LEARNING__.setTCMSide('right');__ATLAS_LEARNING__.setMeridians(['HT','PC']);});const nav=await page.evaluate(()=>__ATLAS_LEARNING__.getNavigationCatalog());ck('670 marker instances remain',nav.length===670,nav.length);ck('Original points retained in revision records',nav.filter(p=>p.navigationRevision===13).every(p=>Array.isArray(p.originalPosition)));
 let routes=await page.evaluate(()=>__ATLAS_LEARNING__.getRouteGeometry());for(const side of ['right','left']){const d=compare(routes,'HT','PC',side);ck('Unprojected HT-PC distinct '+side,d.samples>30&&d.median>8&&d.overlapFraction<.1,d);}
 await page.evaluate(()=>__ATLAS_TISSUES__.setAnatomyView('surface'));await settle(page);ck('Surface projection active',await page.evaluate(()=>__ATLAS_LEARNING__.getSurfaceState().attached));routes=await page.evaluate(()=>__ATLAS_LEARNING__.getRouteGeometry());
 for(const[m1,m2]of[['HT','PC'],['LU','PC'],['LI','TE']])for(const side of ['right','left']){const d=compare(routes,m1,m2,side);ck('Surface retains '+m1+'/'+m2+' distinction '+side,d.samples>20&&d.median>5&&d.overlapFraction<.12,d);}
 report.routeDiagnostics=routes.map(r=>{const a=r.branches.flat();let longest=0;for(const b of r.branches)for(let i=1;i<b.length;i++)longest=Math.max(longest,dist(b[i],b[i-1]));return{meridian:r.meridian,side:r.side,vertices:a.length,finite:a.every(v=>v.every(Number.isFinite)),longestSegment:longest};});ck('All 14 meridian guides finite',report.routeDiagnostics.filter(r=>r.meridian!=='EX').every(r=>r.finite&&r.vertices>10)&&new Set(report.routeDiagnostics.filter(r=>r.meridian!=='EX').map(r=>r.meridian)).size===14);report.surface=await page.evaluate(()=>__ATLAS_TISSUES__.getSurfaceStats());
 await page.evaluate(()=>{__ATLAS_LEARNING__.setMeridians(['HT','PC','LU']);__ATLAS_LEARNING__.setTCMSide('right');__ATLAS_LEARNING__.clearStudyContext(true);const v=__FOOT_ATLAS__.captureCamera();v.position=[-148,930,700];v.target=[-148,930,-25];v.up=[0,1,0];v.view=null;__FOOT_ATLAS__.restoreCamera(v);__ATLAS_SHARED__.showSection('meridians');});await settle(page);await snap(page,'forearm-courses');
 before=await cam(page);await page.locator('[data-meridian="PC"]').click();await settle(page);ck('Surface toggle keeps final zoom',same(before,await cam(page)));
 await page.evaluate(()=>__ATLAS_LEARNING__.selectPoint('PC6','right',true));await settle(page);ck('Point navigation focuses PC6',(await page.evaluate(()=>__ATLAS_LEARNING__.getState().selectedPoint?.code))==='PC6');await snap(page,'point-focus');
 await page.evaluate(()=>__ATLAS_TISSUES__.attachSurface(false));await settle(page);const restored=await page.evaluate(()=>__ATLAS_LEARNING__.getNavigationCatalog());ck('Detachment restores source revision',restored.every(p=>dist(p.position,p.sourcePosition)<1e-5));
 await page.evaluate(async()=>{__ATLAS_LEARNING__.toggleTCM(false);__ATLAS_LEARNING__.clearStudyContext(true);await __ATLAS_SHARED__.choose('chest',false);});await settle(page);
 const box=await page.locator('#viewport').boundingBox(),tabBox=await page.locator('.library-tabs').boundingBox();await page.mouse.move(box.x+box.width*.54,box.y+box.height*.47);await page.mouse.down();await page.mouse.move(box.x+box.width*.63,box.y+box.height*.5,{steps:10});await page.mouse.up();await settle(page);
 const mc=await cam(page),tabs=await page.evaluate(()=>__ATLAS_SHARED__.getState().sameTabs);await snap(page,'male-shared-controls');await page.locator('[data-body-sex="female"]').click();await page.waitForFunction(()=>__ATLAS_FEMALE__.active&&!__ATLAS_FEMALE__.getState().sexBusy,undefined,{timeout:120000});await settle(page);
 const fc=await cam(page),newBox=await page.locator('#viewport').boundingBox(),nt=await page.locator('.library-tabs').boundingBox();ck('Gender switch keeps view direction',dist(dir(mc),dir(fc))<1e-5,{male:dir(mc),female:dir(fc)});ck('Gender switch keeps relative zoom',Math.abs(dist(fc.position,fc.target)/dist(mc.position,mc.target)-1666.348/1700)<.001);
 ck('Both bodies retain same visible tabs',JSON.stringify(tabs)===JSON.stringify(await page.evaluate(()=>__ATLAS_SHARED__.getState().sameTabs)));ck('Same viewport and tab placement',Math.abs(newBox.width-box.width)<1&&Math.abs(newBox.x-box.x)<1&&Math.abs(nt.y-tabBox.y)<1,{male:box,female:newBox});ck('Same layer panel remains visible',await page.locator('#tissuePanel').isVisible());ck('Female retains chest scene',(await page.evaluate(()=>__ATLAS_FEMALE__.getState().preset))==='chest');ck('Male acupuncture not reused as female',await page.evaluate(()=>__ATLAS_LEARNING__.getState().suspended));await snap(page,'female-shared-controls');
 before=await cam(page);await page.locator('#sharedDisplay').selectOption('context');await settle(page);ck('Female display mode preserves camera',same(before,await cam(page)));before=await cam(page);await page.locator('#tcmTab').click();await settle(page);ck('Female acupoint directory preserves camera',same(before,await cam(page)));ck('Female no-registration note accessible',await page.locator('#femaleAcupointStatus').isVisible());await page.locator('#layersTab').click();
 before=await cam(page);await page.locator('[data-body-sex="male"]').click();await page.waitForFunction(()=>!__ATLAS_FEMALE__.active&&!__ATLAS_FEMALE__.getState().sexBusy);await settle(page);ck('Return to male keeps current direction',dist(dir(before),dir(await cam(page)))<1e-5);ck('Round-trip framing retained',same(mc,await cam(page)));
 await page.evaluate(async()=>{await __ATLAS_SHARED__.choose('bones',true);__FOOT_ATLAS__.setRegion('lumbar');__FOOT_ATLAS__.setView('front');});await settle(page);await page.evaluate(()=>__FOOT_ATLAS__.setExplode(65));await settle(page);const ls=await page.evaluate(()=>__FOOT_ATLAS__.getState().bones.filter(b=>/^L[1-5]$/.test(b.id)));ck('Lumbar separation remains vertical',ls.every(b=>Math.abs(b.position[0]-b.home[0])<.001&&Math.abs(b.position[2]-b.home[2])<.001));await page.evaluate(()=>__FOOT_ATLAS__.setExplode(0));await settle(page);const pick=await page.evaluate(()=>__FOOT_ATLAS__.getPickPoint('L3'));ck('L3 mesh pickable',!!pick);await page.evaluate(()=>__FOOT_ATLAS__.setMode('move'));await page.mouse.move(pick.x,pick.y);await page.mouse.down();await page.mouse.move(pick.x+47,pick.y-24,{steps:8});await page.mouse.up();ck('Actual drag separates L3',await page.evaluate(()=>__FOOT_ATLAS__.getState().bones.find(b=>b.id==='L3').offset.some(x=>Math.abs(x)>.1)));await page.locator('#resetBonesBtn').evaluate(el=>el.click());await settle(page);ck('Reset restores all bone offsets',await page.evaluate(()=>__FOOT_ATLAS__.getState().bones.every(b=>Math.hypot(...b.offset)<1e-7)));
 await page.evaluate(()=>__ATLAS_SPEECH__.speak('长强'));await page.waitForFunction(()=>__ATLAS_SPEECH__.getState().currentTime>0,undefined,{timeout:20000});const voice=await page.evaluate(()=>__ATLAS_SPEECH__.getState());ck('Changqiang plays corrected recording',voice.lastEngine==='V13 专项读音'&&voice.spokenText==='常强'&&voice.audioURL.includes('changqiang.mp3'),voice);await page.evaluate(()=>__ATLAS_SPEECH__.stop());
 const ep=await context.newPage();await ep.goto(new URL('evidence.html',url).href);await ep.waitForFunction(()=>window.__EVIDENCE_PAGE__);await ep.locator('#search').fill('chang qiang');ck('Evidence search uses correct pinyin',(await ep.locator('#results').innerText()).includes('长强'));await ep.close();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__ATLAS_SHARED__.showSection('layers'));await settle(page);ck('Phone common layer tab accessible',await page.locator('#layersTab').isVisible());ck('Phone no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await snap(page,'phone-male');await page.locator('[data-body-sex="female"]').click();await page.waitForFunction(()=>__ATLAS_FEMALE__.active&&!__ATLAS_FEMALE__.getState().sexBusy);await settle(page);ck('Phone female same layer panel',await page.locator('#tissuePanel').isVisible());await snap(page,'phone-female');ck('No uncaught script errors',report.errors.length===0,report.errors);report.success=true;
}catch(e){report.failure=String(e);console.error(e);if(page)try{report.pageText=(await page.locator('body').innerText()).slice(0,2000);await snap(page,'failure');}catch{}process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();if(browser)await browser.close();if(server)server.kill();fs.writeFileSync(path.join(out,(live?'live-':'local-')+engine+'.json'),JSON.stringify(report,null,2));console.log('RESULT',JSON.stringify({success:report.success,checks:report.checks.length,failure:report.failure}));}})();
