export function initLayersV21({learning,tissues,female,toast}){
 const $=id=>document.getElementById(id),api=window.__ATLAS_SHARED__,panel=$('tissuePanel');document.body.classList.add('layers-v21');
 const oldTask=panel.querySelector('.v12-tasks');oldTask.hidden=true;oldTask.setAttribute('aria-hidden','true');
 for(const id of ['sharedCoverage','sharedDisplayRow','layerCompactStatus','advancedLayers','voiceSettings','layerModeNote','tissueStudyContext','tissueSearch','tissueList'])if($(id))$(id).hidden=true;
 for(const p of [...panel.children])if(p.tagName==='P')p.hidden=true;
 const custom=$('customLayers');custom.open=true;
 const summary=custom.querySelector('summary');if(summary){const h=document.createElement('h3');h.textContent='自定义图层';summary.replaceWith(h);}
 const head=document.createElement('div');head.className='v21-panel-heading';head.innerHTML='<span>结构图层</span><button id="v21Coverage" type="button">模型与计数</button>';panel.querySelector('h2').replaceWith(head);
 const quick=document.createElement('section');quick.className='v21-quick';quick.id='v21Quick';
 const views=[['surface','体表经络','在线条与落点上学习'],['skin','纯体表','不显示经络'],['bones','全身骨骼','头颅 · 躯干 · 四肢'],['muscles','全身肌肉','浅层与深层'],['nerves','全身神经','中枢与周围'],['organs','胸腹内脏','心肺与消化泌尿']];
 quick.innerHTML='<h3>快速查看</h3><div class="v21-quick-grid">'+views.map(([id,name,sub])=>'<button type="button" data-v21-view="'+id+'"><b>'+name+'</b><small>'+sub+'</small></button>').join('')+'</div><div class="v21-region-row" aria-label="部位特写">'+[['chest','胸腔'],['abdomen','腹部'],['pelvis','盆腔'],['heart','心脏'],['vascular','血管'],['breast','乳腺']].map(([id,name])=>'<button type="button" data-v21-view="'+id+'">'+name+'</button>').join('')+'</div>';
 head.after(quick);quick.querySelectorAll('button').forEach(b=>b.onclick=async()=>{b.setAttribute('aria-busy','true');try{await api.choose(b.dataset.v21View,false);api.showSection('layers');if(innerWidth<=600){document.body.classList.remove('nav-open');$('v21LayersOpen').focus({preventScroll:true});}}catch(e){toast('视图切换失败：'+e.message);}finally{b.removeAttribute('aria-busy');refresh();}});
 const actions=document.createElement('div');actions.className='v21-mixer-actions';custom.querySelector('h3').after(actions);actions.append($('saveLayerCombo'),$('restoreLayerCombo'));$('saveLayerCombo').textContent='保存组合';$('restoreLayerCombo').textContent='载入组合';custom.querySelector('h3').after(actions);
 const hint=document.createElement('p');hint.className='v21-mixer-hint';hint.textContent='勾选叠加；不透明度越高，遮挡越完整';actions.after(hint);
 const master=document.createElement('label');master.className='v21-meridian-switch';master.innerHTML='<span>经络与穴位</span><input type="checkbox" id="v21Meridians" aria-label="显示经络与穴位">';$('sharedLayerRows').prepend(master);
 $('v21Meridians').onchange=e=>{const enabled=e.target.checked;api.runMutation('meridian-visibility',async()=>{if(enabled){if(female.active)await female.ensureMeridianSurface();else await tissues.ensureMeridianReference();}learning.toggleTCM(enabled);}).catch(e=>toast(e.message));};
 const detailRow=document.createElement('div');detailRow.className='v21-bottom-tools';detailRow.innerHTML='<label><input type="checkbox" id="v21FineDetails"> 内部细节</label><button type="button" id="v21RestoreHidden">恢复隐藏项</button>';
 custom.append(detailRow);$('v21FineDetails').onchange=e=>{const enabled=e.target.checked;api.runMutation('fine-details',()=>{if(female.active)female.setFineDetails(enabled);else{const old=$('internalDetails');old.checked=enabled;old.dispatchEvent(new Event('change',{bubbles:true}));const fascia=$('fasciaOn');fascia.checked=enabled;fascia.dispatchEvent(new Event('change',{bubbles:true}));}}).catch(e=>toast(e.message));};
 $('v21RestoreHidden').onclick=()=>api.runMutation('restore-hidden',()=>{if(female.active)female.restoreHidden();else{$('restoreHiddenStructures').click();const s=window.__FOOT_ATLAS__.captureBoneState();window.__FOOT_ATLAS__.restoreBoneState({...s,hidden:[],isolated:false});}}).catch(e=>toast(e.message));
 // Old nodes remain mounted for legacy state callbacks, but never compete with the mixer.
 const oldClear=$('tissueClear')?.closest('.v4-button-row');if(oldClear)oldClear.hidden=true;
 panel.querySelectorAll('.v4-button-row').forEach(row=>{if(!row.children.length)row.hidden=true;});
 $('structureScope').insertAdjacentHTML('beforeend','<option value="native-details">女性原生局部细节</option>');
 const dialog=document.createElement('dialog');dialog.id='v21CoverageDialog';dialog.innerHTML='<form method="dialog"><header><h2>模型与计数</h2><button aria-label="关闭模型说明">×</button></header></form><div id="v21CoverageContent"></div>';document.body.append(dialog);dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
 $('v21Coverage').onclick=()=>{const audit=female.getCompletionAudit(),count=window.__FOOT_ATLAS__.getCatalog().length;const b=audit?.systems,mc=api.getModelCounts();
 $('v21CoverageContent').innerHTML='<p>以下为可独立选择的模型部件，不是人体标准骨数。当前画面的数量还受左右侧、隐藏项和内部细节开关影响。</p><table><thead><tr><th>完整教学结构</th><th>男性</th><th>女性</th></tr></thead><tbody><tr><td>骨架部件</td><td>'+count+'</td><td>'+(b?.skeletal||'切换女性后读取')+'</td></tr><tr><td>肌肉及附属组织</td><td>'+(mc.muscular||'读取中')+'</td><td>'+(b?.muscular||'按需加载')+'</td></tr><tr><td>神经系统部件</td><td>'+(mc.nervous||'读取中')+'</td><td>'+(b?.nervous||'按需加载')+'</td></tr><tr><td>全身血管参考</td><td>'+(mc.vessels||'读取中')+'</td><td>'+(b?.vessels||'按需加载')+'</td></tr><tr><td>耳部参考</td><td>'+(mc.ear||'读取中')+'</td><td>'+(b?.ear||'按需加载')+'</td></tr></tbody></table><h3>两类来源，分别标明</h3><p>女性体表、盆骨、内脏、生殖与乳腺保留 HRA 女性原生模型。缺失的全身骨架、肌肉和神经，使用 Z-Anatomy / BodyParts3D 的统一比例教学参考补充；不是新增女性扫描数据。</p><p>女性全身血管补充排除了10个男性独有的睾丸、阴茎血管部件，保留女性原生心脏和子宫血管。原生局部血管可从目录单独查看，不与全身参考重复叠画。因此血管部件数不强行凑成男女相同。</p><p>骨盆的髋骨、骶骨与尾骨使用女性源几何。原有女性局部细节仍可在“结构目录 → 女性原生局部细节”查看；不与整骨重复计数。</p><p>不同来源对心脏、肾脏等拆分程度不同，所以总部件数不应强行相等。补充模型和经穴位置尚未逐项完成临床配准，只用于学习。</p>';dialog.showModal();};
 const mobileLayers=document.createElement('button');mobileLayers.type='button';mobileLayers.id='v21LayersOpen';mobileLayers.textContent='图层';mobileLayers.setAttribute('aria-controls','tissuePanel');$('openNav').after(mobileLayers);function toggleDrawer(section){if(api.getState().section===section&&document.body.classList.contains('nav-open'))document.body.classList.remove('nav-open');else api.showSection(section);refresh();}mobileLayers.onclick=()=>toggleDrawer('layers');$('openNav').textContent='目录';$('openNav').setAttribute('aria-controls','structureLibrary');$('openNav').onclick=()=>toggleDrawer('directory');$('closeNav').addEventListener('click',()=>{refresh();(api.getState().section==='layers'?mobileLayers:$('openNav')).focus({preventScroll:true});});
 let queued=false;function schedule(){if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;refresh();});}}
 function refresh(){const s=api.getState(),f=female.active;$('openNav').setAttribute('aria-expanded',String(s.section==='directory'&&document.body.classList.contains('nav-open')));mobileLayers.classList.toggle('active',s.section==='layers');mobileLayers.setAttribute('aria-expanded',String(s.section==='layers'&&document.body.classList.contains('nav-open')));quick.querySelectorAll('[data-v21-view]').forEach(b=>{b.hidden=b.dataset.v21View==='breast'&&!f;b.classList.toggle('active',b.dataset.v21View===s.scene);b.setAttribute('aria-pressed',String(b.dataset.v21View===s.scene));});
 $('v21Meridians').checked=learning.getState().enabled;$('v21FineDetails').checked=f?female.getState().fineDetails:!!$('internalDetails').checked;
 const opt=$('structureScope').querySelector('[value="native-details"]');opt.disabled=!f;opt.hidden=!f;
 if(!f&&$('structureScope').value==='native-details'){$('structureScope').value='all';$('structureScope').dispatchEvent(new Event('change',{bubbles:true}));}
 for(const row of panel.querySelectorAll('[data-shared-layer]')){const id=row.dataset.sharedLayer,cb=$('sharedLayer-'+id);row.hidden=cb.disabled;row.classList.toggle('is-on',cb.checked);const tag=$('sharedLayerState-'+id);if(tag){row.title=tag.textContent;tag.hidden=true;}const span=$('sharedOpacityRow-'+id)?.querySelector('span');if(span)span.textContent='不透明度';}
 }
 for(const event of ['atlas:transition-settled','atlas:sex-changed','atlas:tcm-visibility','atlas:profile-changed'])window.addEventListener(event,schedule);panel.addEventListener('change',schedule);panel.addEventListener('input',schedule);refresh();window.__ATLAS_LAYERS_V21__={refresh,version:'28.0.0',getState:()=>({alwaysOpen:custom.open,quickViews:views.map(v=>v[0]),nativeDetailsPreserved:true})};
}
