const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),pw=require('playwright'),{PNG}=require('pngjs');
const root=process.cwd(),engine=process.env.BROWSER||'chromium',v=process.env.ATLAS_VERSION||'28',live=!!process.env.TEST_URL,out=path.join(root,'fullbody-tcm-v'+v,'checks'),prefix=(live?'live-':'local-')+engine;fs.mkdirSync(out,{recursive:true});
const report={version:v,engine,live,checks:[],errors:[],screenshots:[],startedAt:new Date().toISOString(),clinicalCalibration:false};let browser,p,context;
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const ck=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail||''));};
const server=live?null:http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}).listen(8282,'127.0.0.1');
const url=()=>process.env.TEST_URL||`http://127.0.0.1:8282/fullbody-tcm-v${v}/`;
async function settle(){await p.waitForFunction(()=>window.__ATLAS_SHARED__&&!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:120000});await p.waitForTimeout(140);}
async function start(size={width:1440,height:1000},dpr=1){context=await browser.newContext({viewport:size,deviceScaleFactor:dpr,hasTouch:dpr>1});p=await context.newPage();p.setDefaultTimeout(90000);p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/WebGLProgram|shader error|GL_INVALID/i.test(m.text()))report.errors.push(m.text().slice(0,1000))});await p.goto(url());await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();}
async function shot(name){const f=prefix+'-'+name+'.png';await p.screenshot({path:path.join(out,f)});report.screenshots.push(f);}
async function snapshot(){const r=await p.evaluate(()=>{const L=__ATLAS_LEARNING__,s=L.getState(),a=L.getSurfaceConsistencyAudit(),mesh=[];__ATLAS_RENDER_AUDIT__.scene.traverse(n=>{if(!n.isMesh||(n.userData.atlas?.system!=='surface'&&n.userData.female?.system!=='surface'))return;for(let q=n;q;q=q.parent)if(!q.visible)return;mesh.push({opacity:n.material.opacity,depth:n.material.depthWrite,sex:n.userData.female?'female':'male'});});return {body:a.body,reference:a.referenceBody,root:a.routeRootVisible,skin:a.skinVisible,busy:a.surfaceBusy,pointCount:a.points.length,points:a.points.map(p=>[p.code,p.side,p.position]),routes:L.getRouteSamples(),inks:a.ink,selected:a.selected,transfer:a.transfer,mesh,flags:{enabled:s.enabled,linesOn:s.linesOn,pointsOn:s.pointsOn,namesOn:s.namesOn,xray:s.xray,tcmSide:s.tcmSide,local:s.localStudyOnly,style:s.curveStyle},ui:{point:document.getElementById('acupointToggle').classList.contains('active'),line:document.getElementById('meridianLineToggle').classList.contains('active'),name:document.getElementById('pointNamesToggle').classList.contains('active')},window:a.localWindow,camera:__FOOT_ATLAS__.captureCamera()};});r.geometry={points:hash(r.points),routes:hash(r.routes),ink:hash(r.inks.map(i=>[i.meridian,i.side,i.centers]))};delete r.routes;return r;}
async function switchTo(s){await p.locator('button[data-body-sex="'+s+'"]').click();await settle();}
async function focus(code,side='right'){await p.evaluate(({code,side})=>{__ATLAS_LEARNING__.setMeridian(code.replace(/\d/g,''));__ATLAS_LEARNING__.selectPoint(code,side,true);},{code,side});await settle();}
async function actualPoint(code,side='right'){return p.evaluate(({code,side})=>{const L=__ATLAS_LEARNING__,{THREE,scene,camera}=__ATLAS_RENDER_AUDIT__,q=L.getNavigationCatalog().find(q=>q.code===code&&q.side===side),point=new THREE.Vector3(...q.position),d=point.clone().sub(camera.position),distance=d.length(),skin=[];scene.updateMatrixWorld(true);scene.traverse(n=>{if(!n.isMesh||(n.userData.atlas?.system!=='surface'&&n.userData.female?.system!=='surface'))return;for(let a=n;a;a=a.parent)if(!a.visible)return;skin.push(n)});const hits=new THREE.Raycaster(camera.position,d.normalize()).intersectObjects(skin,false),hit=hits[0],screen=L.getPointScreen(code,side);return {position:q.position,screen,occlusion:hit?distance-hit.distance:null,skinMeshes:skin.length,selected:L.getState().selectedPoint};},{code,side});}
function healthy(s){return s.body===s.reference&&s.root&&s.skin&&!s.busy&&s.mesh.length>0&&s.mesh.every(m=>m.sex===s.body&&m.opacity===1&&m.depth)&&s.inks.every(i=>i.body===s.body&&i.visible);}
(async()=>{try{
 browser=await pw[engine].launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}:{})});await start();
 await p.evaluate(()=>{__ATLAS_LEARNING__.clearPointSelection();__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();
 const male=await snapshot();ck('Male opaque skin uses male-only point, line and pigment set',healthy(male),{meshes:male.mesh.length,points:male.pointCount});
 await p.evaluate(()=>{window.__V28_FRAMES__=[];window.__V28_WATCH__=true;function loop(){const {scene}=__ATLAS_RENDER_AUDIT__,sex=document.body.dataset.bodySex;let bad=0,visible=0;scene.traverse(n=>{if(!n.userData.skinInk)return;for(let a=n;a;a=a.parent)if(!a.visible)return;visible++;if(n.userData.referenceBody&&n.userData.referenceBody!==sex)bad++;});__V28_FRAMES__.push({sex,bad,visible,busy:document.body.dataset.bodySwitching==='true',locked:document.getElementById('tcmControls').inert});if(__V28_WATCH__)requestAnimationFrame(loop);}requestAnimationFrame(loop);});
 await switchTo('female');const female=await snapshot();ck('First female switch uses independent opaque female skin and complete data',healthy(female)&&female.pointCount===male.pointCount,{meshes:female.mesh.length,points:female.pointCount});
 await p.evaluate(()=>__ATLAS_LEARNING__.fitMeridian([0,0,-1]));await settle();await shot('female-all-back');
 await switchTo('male');const maleAgain=await snapshot();ck('Returning male points and complete route samples equal the original male cache',male.geometry.points===maleAgain.geometry.points&&male.geometry.routes===maleAgain.geometry.routes&&male.geometry.ink===maleAgain.geometry.ink,{before:male.geometry,after:maleAgain.geometry});
 await switchTo('female');const femaleAgain=await snapshot();ck('Returning female points and complete route samples equal the original female cache',female.geometry.points===femaleAgain.geometry.points&&female.geometry.routes===femaleAgain.geometry.routes&&female.geometry.ink===femaleAgain.geometry.ink,{before:female.geometry,after:femaleAgain.geometry});
 const frames=await p.evaluate(()=>{__V28_WATCH__=false;return __V28_FRAMES__});ck('No sampled transition frame displays pigment from the wrong body',frames.length>5&&frames.every(f=>!f.bad),{frames:frames.length,busyFrames:frames.filter(f=>f.busy).length});ck('Old-body controls are inert and pigment hidden during sampled transactions',frames.filter(f=>f.busy).length>0&&frames.filter(f=>f.busy).every(f=>f.locked&&f.visible===0));
 report.contacts={male:male.points,female:female.points};
 for(const sex of ['male','female']){await switchTo(sex);const a=await p.evaluate(()=>{const a=__ATLAS_LEARNING__.getDisplayAudit();return {count:a.count,finite:a.geometryFinite,secondaryShift:a.maxSecondaryShift,lineGap:a.maxLineGap,trace:a.surfaceTrace,points:a.points.map(p=>({code:p.code,side:p.side,lineGap:p.lineGap,skinDistance:p.skinDistance}))};});report[sex+'GeometryAudit']=a;ck(sex+' all point centers remain on their current drawn routes',a.count===670&&a.finite&&a.secondaryShift<1e-6&&a.lineGap<.01,{count:a.count,secondaryShift:a.secondaryShift,maxLineGap:a.lineGap});}
 // The selected point must not turn a hidden layer back on during restore.
 await focus('PC6');await p.evaluate(()=>{for(const id of ['acupointToggle','meridianLineToggle','pointNamesToggle'])if(document.getElementById(id).classList.contains('active'))document.getElementById(id).click()});await settle();
 for(const sex of ['male','female']){await switchTo(sex);const s=await snapshot();ck(sex+' all three off switches survive selected-point restoration',!s.flags.pointsOn&&!s.flags.linesOn&&!s.flags.namesOn&&!s.selected.markerVisible&&s.inks.every(i=>!i.points&&!i.lines),s.flags);ck(sex+' off buttons match the actual renderer state',!s.ui.point&&!s.ui.line&&!s.ui.name,s.ui);}
 await p.evaluate(()=>{for(const id of ['acupointToggle','meridianLineToggle','pointNamesToggle'])if(!document.getElementById(id).classList.contains('active'))document.getElementById(id).click()});await settle();
 await p.evaluate(()=>{for(const id of ['acupointToggle','meridianLineToggle','pointNamesToggle'])if(document.getElementById(id).classList.contains('active'))document.getElementById(id).click();__ATLAS_LEARNING__.setMeridian('TE');__ATLAS_LEARNING__.selectPoint('TE3','right',false);});await settle();const clicked=await snapshot();ck('Intentional point selection without auto-focus updates both UI and skin drawing, not lines or names',clicked.flags.pointsOn&&clicked.ui.point&&clicked.selected.markerVisible&&clicked.inks.every(i=>i.points)&&!clicked.flags.linesOn&&!clicked.flags.namesOn,clicked.flags);await p.evaluate(()=>{for(const id of ['meridianLineToggle','pointNamesToggle'])if(!document.getElementById(id).classList.contains('active'))document.getElementById(id).click()});await settle();
 // Independent scene raycasts cover dorsal, palmar, plantar and trunk points.
 for(const [code,side]of [['TE3','right'],['TE2','left'],['LI4','right'],['PC6','left'],['KI1','right'],['CV17','midline'],['BL23','left'],['BL66','right'],['LR2','left'],['ST44','left']]){
  await switchTo('male');await focus(code,side);const before=await actualPoint(code,side);const bc=await p.evaluate(()=>__FOOT_ATLAS__.captureCamera());await switchTo('female');const after=await actualPoint(code,side);const a=await snapshot();
  const distance=v=>Math.hypot(...v.position.map((x,i)=>x-v.target[i]));
  ck(code+' '+side+' visible against actual opaque male and female meshes',before.occlusion!==null&&after.occlusion!==null&&before.occlusion<.3&&after.occlusion<.3,{before:before.occlusion,after:after.occlusion});
  ck(code+' counterpart remains selected at the same local viewing scale',a.selected?.code===code&&a.selected?.side===side&&a.selected.visibleFromCamera&&Math.abs(distance(bc)-distance(a.camera))<.001,{transfer:a.transfer});
  if(code==='TE3')await shot('female-hand-after-switch');
 }
 await switchTo('male');await focus('TE3');await shot('male-hand-returned');
 // Compare rendered line pixels with lines off at the identical camera.
 for(const sex of ['male','female']){
  await switchTo(sex);await focus('TE3');await p.evaluate(()=>{for(const id of ['acupointToggle','pointNamesToggle'])if(document.getElementById(id).classList.contains('active'))document.getElementById(id).click()});await settle();
  const samples=await p.evaluate(()=>{const L=__ATLAS_LEARNING__,{THREE,camera}=__ATLAS_RENDER_AUDIT__,all=L.getNavigationCatalog(),a=all.find(p=>p.code==='TE3'&&p.side==='right'),b=all.find(p=>p.code==='TE4'&&p.side==='right'),r=document.getElementById('viewport').getBoundingClientRect();return L.getRouteSamples().find(r=>r.meridian==='TE'&&r.side==='right').branches.flatMap(b=>b.points).filter(v=>v[1]>a.position[1]+8&&v[1]<b.position[1]-8).map(v=>{const q=new THREE.Vector3(...v).project(camera);return {x:r.x+(q.x*.5+.5)*r.width,y:r.y+(-q.y*.5+.5)*r.height};}).filter(p=>p.x>r.left+10&&p.x<r.right-10&&p.y>300&&p.y<r.bottom-180);});
  const on=PNG.sync.read(await p.screenshot());await p.locator('#meridianLineToggle').evaluate(e=>e.click());await settle();const off=PNG.sync.read(await p.screenshot());let visible=0;
  for(const s of samples){let yes=false;for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const px=Math.round(s.x)+x,py=Math.round(s.y)+y;if(px<0||py<0||px>=on.width||py>=on.height)continue;const i=(py*on.width+px)*4;if(Math.abs(on.data[i]-off.data[i])+Math.abs(on.data[i+1]-off.data[i+1])+Math.abs(on.data[i+2]-off.data[i+2])>30)yes=true;}if(yes)visible++;}
  ck(sex+' dorsal hand line is present in rendered skin pixels after switching',samples.length>12&&visible/samples.length>.94,{samples:samples.length,matched:visible,coverage:visible/samples.length});
  await p.evaluate(()=>{for(const id of ['meridianLineToggle','acupointToggle','pointNamesToggle'])if(!document.getElementById(id).classList.contains('active'))document.getElementById(id).click()});await settle();
 }
 await focus('TE3','left');await p.evaluate(()=>{const e=document.getElementById('localStudyToggle');e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));__ATLAS_LEARNING__.setTCMSide('left');});await settle();
 for(const sex of ['male','female']){await switchTo(sex);const s=await snapshot(),center=s.window?.[0].map((x,i)=>(x+s.window[1][i])/2);ck(sex+' local crop follows the current same-side point with matching labels',s.flags.local&&s.flags.tcmSide==='left'&&center&&Math.hypot(...center.map((x,i)=>x-s.selected.position[i]))<1e-6&&s.inks.every(i=>i.side==='left'||i.side==='midline'),{center,point:s.selected?.position,side:s.flags.tcmSide});}
 await p.evaluate(()=>__ATLAS_FEMALE__.setSide('right'));await settle();const filtered=await snapshot();ck('Physical-side filtering hides the opposite-side selected marker',!filtered.selected.markerVisible);
 await p.evaluate(()=>__ATLAS_FEMALE__.setSide('both'));await p.evaluate(()=>__ATLAS_LEARNING__.fitMeridian());await settle();
 await p.evaluate(async()=>{await Promise.all(['male','female','male','female'].map(s=>__ATLAS_SHARED__.switchSex(s)))});await settle();const fast=await snapshot();ck('Rapid repeated switching ends in one complete female body',fast.body==='female'&&healthy(fast)&&!await p.locator('#tcmControls').evaluate(e=>e.inert));
 await p.evaluate(()=>document.getElementById('saveLayerCombo').click());await settle();await p.evaluate(()=>__ATLAS_SHARED__.choose('bones',true));await settle();await p.evaluate(()=>document.getElementById('restoreLayerCombo').click());await settle();ck('Saved surface combination restores one coherent opaque body',healthy(await snapshot()));
 await p.evaluate(()=>{__ATLAS_LEARNING__.clearPointSelection();__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,1]);});await settle();const screenBefore=await p.evaluate(()=>({camera:__FOOT_ATLAS__.captureCamera(),point:__ATLAS_LEARNING__.getPointScreen('CV17','midline')}));await switchTo('male');await switchTo('female');const screenAfter=await p.evaluate(()=>({camera:__FOOT_ATLAS__.captureCamera(),point:__ATLAS_LEARNING__.getPointScreen('CV17','midline')}));ck('Whole-body camera and view offset survive a male/female round trip',JSON.stringify(screenBefore.camera.view)===JSON.stringify(screenAfter.camera.view)&&Math.hypot(screenBefore.point.x-screenAfter.point.x,screenBefore.point.y-screenAfter.point.y)<.01,{before:screenBefore,after:screenAfter});
 await context.close();await start({width:390,height:844},2);await focus('TE3');await p.locator('#v26PointSummary [data-action="details"]').tap();await settle();await p.locator('#focusPointBtn').tap();await settle();await switchTo('female');await settle();const q=await actualPoint('TE3'),sheet=await p.locator('.detail-panel').boundingBox();ck('DPR2 phone switch keeps dorsal point above details and outside opaque skin',q.occlusion<.3&&sheet&&q.screen.y<sheet.y-12&&q.screen.y>180,{point:q,sheet});await shot('phone-female-hand-details');await switchTo('male');const back=await actualPoint('TE3');ck('DPR2 phone return preserves point identity and visibility',back.selected.code==='TE3'&&back.occlusion<.3,back);await shot('phone-male-hand-returned');
 ck('No page or shader exceptions',report.errors.length===0,report.errors);
}catch(e){report.failure=String(e.stack||e);console.error(report.failure);if(p)await shot('failure').catch(()=>{})}finally{report.success=!report.failure&&!report.errors.length&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'-surface-switch.json'),JSON.stringify(report,null,2));await browser?.close();server?.close();if(!report.success)process.exitCode=1;}})();
