import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {BONES} from './bones-data.js';
import {POSES,CATEGORIES,stateFor} from './pose-catalog.js';
import {solvePose,matrixFor} from './pose-engine.js';
import {createHandRig,gripTask,solveGrip} from './pose-grip.js';
import {analyze} from './pose-analysis.js';
const $=id=>document.getElementById(id),viewport=$('viewport'),byId=new Map(POSES.map(p=>[p.id,p])),boneData=new Map(BONES.map(b=>[b.id,b]));
const hash=new URLSearchParams(location.hash.slice(1));let selected=byId.has(hash.get('pose'))?hash.get('pose'):'stand-relaxed',phase=T.MathUtils.clamp(Number(hash.get('phase'))||0,0,100)/100,ready=false,playing=false,focus='lumbar',pinned=null,recordURL=null,renderPending=0,lastTime=0,lastPoseTime=0,phaseDirection=1,atlasPage=0,atlasGeneration=0,atlasBusy=false;
let gripFocused=false;let handRig=null;let solved=null,currentSpec=null,currentAnalysis=null,currentContacts=[];const meshes=[],labels=[],thumbnailCache=new Map();
for(const id of ['mass','gravity','load','minutes','interval','volume'])if(hash.has(id)){const e=$(id),n=Number(hash.get(id));if(Number.isFinite(n)&&n>=Number(e.min)&&n<=Number(e.max))e.value=n;}
if(!hash.has('load'))$('load').value=byId.get(selected).spec.load||0;
$('phase').value=Math.round(phase*100);
const scene=new T.Scene();scene.background=new T.Color('#e9efe2');
const camera=new T.PerspectiveCamera(36,1,.01,50);camera.position.set(1.7,1.3,2.8);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;viewport.append(renderer.domElement);
scene.add(new T.HemisphereLight('#fff9ef','#607862',1.7));for(const [xyz,power]of [[[2,4,3],2.3],[[-3,2,-2],.9]]){const l=new T.DirectionalLight('#ffffff',power);l.position.set(...xyz);scene.add(l);}
const body=new T.Group(),props=new T.Group(),signs=new T.Group();scene.add(body,props,signs);
const ground=new T.Mesh(new T.PlaneGeometry(5,5),new T.MeshBasicMaterial({color:'#d6e3cb',transparent:true,opacity:.6,side:T.DoubleSide}));ground.rotation.x=-Math.PI/2;ground.position.y=-.006;scene.add(ground);const grid=new T.GridHelper(5,25,'#abc09e','#ccd9bf');grid.position.y=-.005;scene.add(grid);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.zoomToCursor=true;controls.minDistance=.18;controls.maxDistance=15;controls.touches.TWO=T.TOUCH.DOLLY_PAN;
const thumbRenderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});thumbRenderer.setSize(280,250);thumbRenderer.outputColorSpace=T.SRGBColorSpace;thumbRenderer.toneMapping=T.ACESFilmicToneMapping;thumbRenderer.toneMappingExposure=1;const thumbCamera=new T.PerspectiveCamera(36,280/250,.01,50);
function invalidate(){if(!renderPending)renderPending=requestAnimationFrame(draw);}
function draw(time){renderPending=0;if(playing&&ready&&!atlasBusy&&!document.hidden){const dt=Math.min(.08,(time-lastTime)/1000||0);phase+=dt*.16*phaseDirection;if(phase>=1){phase=1;phaseDirection=-1;}else if(phase<=0){phase=0;phaseDirection=1;}$('phase').value=Math.round(phase*100);$('phaseName').value=Math.round(phase*100)+'%';if(time-lastPoseTime>90){applySelected(false);lastPoseTime=time;}}lastTime=time;controls.update();renderer.render(scene,camera);placeLabels();if(playing&&!document.hidden)invalidate();}
controls.addEventListener('change',()=>{const d=camera.position.clone().sub(controls.target).normalize();$('viewDirection').textContent=Math.abs(d.y)>.86?'俯视方向':Math.abs(d.x)<.18&&d.z>.7?'前面方向':Math.abs(d.z)<.18&&Math.abs(d.x)>.7?'侧面方向':'自由视角';invalidate();});
new ResizeObserver(()=>{const r=viewport.getBoundingClientRect();renderer.setSize(r.width,Math.max(1,r.height));camera.aspect=r.width/Math.max(1,r.height);camera.setViewOffset(r.width,r.height,0,innerWidth<=650?90:80,r.width,r.height);camera.updateProjectionMatrix();if(ready&&!playing)frameBody();else invalidate();}).observe(viewport);
function segment(b){const s=b.side==='left'?'L':'R';if(b.group==='cervical')return b.id;if(['cranial','facial','head-other'].includes(b.group))return'head';if(b.group==='lumbar')return b.id;if(['thorax','thoracic','shoulder'].includes(b.group))return'trunk';if(b.group==='pelvis')return'pelvis';if(b.group==='arm')return b.id.startsWith('humerus')?'shoulder'+s:'elbow'+s;if(['carpal','metacarpal','hand-phalanges'].includes(b.group))return'wrist'+s;if(b.group==='thigh')return b.id.startsWith('patella')?'patella'+s:'hip'+s;if(b.group==='leg')return'knee'+s;return'ankle'+s;}
function boundsFor(test){const box=new T.Box3();for(const m of meshes)if(test(m))box.union(m.geometry.boundingBox.clone().applyMatrix4(m.matrix));return box;}
function applyMatrices(result){for(const m of meshes){m.matrix.copy(matrixFor(result.parts[m.userData.segment]));m.matrixWorld.copy(m.matrix);}}
function translateSolved(result,dy){for(const part of Object.values(result.parts))part.position.y+=dy;for(const c of result.constraints){c.target[1]+=dy;c.actual[1]+=dy;}applyMatrices(result);}
function configure(spec){
 spec=structuredClone(spec);
 const place=()=>{let result=solvePose(spec);applyMatrices(result);const all=boundsFor(()=>true);
  if(spec.bed){if(spec.bridge){const headMin=boundsFor(m=>m.userData.segment==='head').min.y;spec.height=(spec.height||0)-headMin;result=solvePose(spec);applyMatrices(result);translateSolved(result,.45);}else translateSolved(result,.45-all.min.y);}
  else if(spec.water)translateSolved(result,.45-all.min.y);
  else if(spec.floorSit){const min=boundsFor(m=>m.userData.segment==='pelvis').min.y;if(Math.abs(min)>.002){spec.height=(spec.height||0)-min;result=solvePose(spec);applyMatrices(result);}const minY=boundsFor(()=>true).min.y;if(minY<0&&!spec.handSupport)translateSolved(result,-minY);}
  else if(spec.kneeling||spec.quadruped){const lift=Math.max(0,-boundsFor(m=>!m.userData.segment.startsWith('wrist')).min.y);if(lift&&spec.feet?.length){spec.height=(spec.height||0)+lift;result=solvePose(spec);applyMatrices(result);}else translateSolved(result,lift);}
  return result;
 };
 let r=place();
 if(spec.handSupport||spec.quadruped){for(let pass=0;pass<4;pass++){let changed=false;for(const side of spec.handSides||['R','L']){const bottom=boundsFor(m=>m.userData.segment==='wrist'+side).min.y;if(Math.abs(bottom)>.001&&spec['handTarget'+side]){spec['handTarget'+side][1]-=bottom;changed=true;}}if(!changed)break;r=place();}}
 const task=handRig&&gripTask(spec,r);if(task){solveGrip(r,task,handRig);applyMatrices(r);for(const entry of r.grip.matrices){entry.mesh.matrix.copy(entry.matrix);entry.mesh.matrixWorld.copy(entry.matrix);}}
 return r;
}
function dispose(group){while(group.children.length){const n=group.children[0];group.remove(n);n.traverse(x=>{x.geometry?.dispose();if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material?.dispose();});}}
function box(xyz,size,color='#739880',opacity=1,rotation){const m=new T.Mesh(new RoundedBoxGeometry(...size,2,.012),new T.MeshStandardMaterial({color,roughness:.85,transparent:opacity<1,opacity}));m.position.set(...xyz);if(rotation)m.quaternion.copy(rotation);props.add(m);return m;}
function rod(a,b,r=.016,color='#617767'){const delta=b.clone().sub(a),m=new T.Mesh(new T.CylinderGeometry(r,r,delta.length(),12),new T.MeshStandardMaterial({color,roughness:.8}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());props.add(m);return m;}
function centerOf(part){return boundsFor(m=>m.userData.segment===part).getCenter(new T.Vector3());}
function drawProps(spec,r){dispose(props);const pelvis=r.joints.pelvis,head=boundsFor(m=>m.userData.segment==='head');
 if(spec.bed){box([0,.39,0],[.95,.12,2.25],'#d5dac7');for(const x of [-.35,.35])for(const z of [-.95,.95])box([x,.16,z],[.04,.32,.04],'#779184');if(spec.headPillow){const c=head.getCenter(new T.Vector3()),h=Math.max(.035,head.min.y-.45+.012);box([c.x,.45+h/2,c.z],[.34,h,.32],'#f0e4c7');}if(spec.kneePillow){const c=r.joints.kneeR.clone().add(r.joints.kneeL).multiplyScalar(.5);const top=Math.max(.485,c.y-.024);box([c.x,(.45+top)/2,c.z],[.50,top-.45,.28],'#ede3c8');}if(spec.betweenPillow){const c=r.joints.kneeR.clone().add(r.joints.kneeL).multiplyScalar(.5);box(c.toArray(),[.20,Math.max(.035,Math.abs(r.joints.kneeR.y-r.joints.kneeL.y)-.025),.20],'#ede3c8');}if(spec.pelvisPillow)box([pelvis.x,.49,pelvis.z],[.42,.08,.30],'#ede3c8');if(spec.legBench){const c=r.joints.ankleR.clone().add(r.joints.ankleL).multiplyScalar(.5);box([c.x,c.y-.085,c.z],[.55,.07,.42],'#829e8b');}if(spec.backWedge){const c=r.joints.trunk;box([c.x,.55,c.z],[.62,.18,.65],'#e2d9bc',.8,r.parts.trunk.rotation);}}
 if(spec.chair){const seatY=boundsFor(m=>m.userData.segment==='pelvis').min.y-.008;box([pelvis.x,seatY-.025,pelvis.z-.04],[spec.sofa?.66:.44,.05,.44],spec.sofa?'#b7cbb4':'#8caa93');for(const dx of [-.17,.17])for(const dz of [-.16,.16])box([pelvis.x+dx,seatY/2,pelvis.z-.04+dz],[.025,seatY,.025],'#617969');if(!spec.stool&&spec.backSupport){const back=pelvis.clone().add(new T.Vector3(0,.23,-.15).applyQuaternion(r.parts.pelvis.rotation));box(back.toArray(),[.44,.46,.035],'#8caa93',.7,r.parts.pelvis.rotation);}}
 if(spec.desk){const c=r.joints.wristR.clone().add(r.joints.wristL).multiplyScalar(.5);box([0,c.y-.05,Math.max(.28,c.z+.06)],[.8,.045,.48],'#aebfac',.72);for(const x of [-.33,.33])box([x,(c.y-.07)/2,Math.max(.3,c.z+.06)],[.025,c.y-.07,.025],'#6e8b76');}
 if(spec.footrest||spec.stepProp){for(const s of ['R','L'])if(spec['leg'+s]?.step){const c=r.joints['ankle'+s],h=spec['leg'+s].step;box([c.x,h/2,c.z+.03],[.30,h,.34],'#9bae96');}}
 if(spec.wall){box([0,.9,-.26],[1.2,1.8,.035],'#b7c6b0',.35);}
 const highHand=r.joints.wristR.y>r.joints.wristL.y?r.joints.wristR:r.joints.wristL;
 if(spec.shelf){const sy=spec.box?loadPosition(spec,r).y-.13:highHand.y-.035,sz=highHand.z+.04;box([0,sy,sz],[.9,.045,.30],'#a5b7a0',.6);for(const x of [-.40,.40])box([x,sy/2,sz+.13],[.025,sy,.025],'#829782',.5);}
 if(spec.window){const c=highHand;box([c.x,c.y-.12,c.z+.035],[.70,.65,.012],'#afd7cd',.30);for(const x of [-.35,.35])rod(new T.Vector3(c.x+x,c.y-.45,c.z+.05),new T.Vector3(c.x+x,c.y+.21,c.z+.05),.01);}
 if(spec.rail){const sy=highHand.y-.10,sz=highHand.z+.03;rod(new T.Vector3(-.5,sy,sz),new T.Vector3(.5,sy,sz));for(const x of [-.50,.50])rod(new T.Vector3(x,0,sz),new T.Vector3(x,sy,sz));}
 const task=spec.taskId||selected,hands=r.joints.wristR.clone().add(r.joints.wristL).multiplyScalar(.5);
 if(spec.steering){const wheel=new T.Mesh(new T.TorusGeometry(.17,.016,8,32),new T.MeshStandardMaterial({color:'#586e5b'}));wheel.position.copy(r.grip?.task.center||hands);if(r.grip)wheel.quaternion.copy(r.grip.task.rotation);else wheel.rotation.x=Math.PI/5;props.add(wheel);}
 if(r.grip?.type==='controller'){const t=r.grip.task;box(t.center.toArray(),[.17,.038,.085],'#426c62',1,t.rotation);for(const sign of [-1,1]){const c=t.center.clone().add(new T.Vector3(sign*.073,-.012,-.015).applyQuaternion(t.rotation));box(c.toArray(),[.044,.065,.105],'#426c62',1,t.rotation);box(t.center.clone().add(new T.Vector3(sign*.048,.023,.009).applyQuaternion(t.rotation)).toArray(),[.021,.009,.021],'#d9b974',1,t.rotation);}}
 if(r.grip?.type==='phone'){const t=r.grip.task;box(t.center.toArray(),[.075,.14,.009],'#426c62',1,t.rotation);box(t.center.clone().add(new T.Vector3(0,0,.005).applyQuaternion(t.rotation)).toArray(),[.063,.122,.002],'#a5c0af',1,t.rotation);}
 if(task.includes('typing')||task==='sit-laptop'){box([hands.x,hands.y-.03,hands.z],[.36,.015,.15],'#d4ddca');if(task==='sit-laptop')box([hands.x,hands.y+.07,hands.z+.11],[.31,.20,.013],'#708f81');}
 if(spec.readingStand){const c=hands.clone().add(new T.Vector3(0,.14,.12));box(c.toArray(),[.28,.018,.22],'#d6bc89',1,new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-.7));rod(c.clone().add(new T.Vector3(0,-.02,.06)),c.clone().add(new T.Vector3(0,-.18,.06)),.016);box(c.clone().add(new T.Vector3(0,-.18,.06)).toArray(),[.25,.025,.14],'#7c9886');}else if(task.includes('read')&&!spec.water)box(hands.clone().add(new T.Vector3(0,.025,.05)).toArray(),[.26,.012,.18],'#d6bc89');
 if(r.grip?.type==='guitar'){const t=r.grip.task,c=t.center;const g=new T.Mesh(new T.SphereGeometry(1,24,16),new T.MeshStandardMaterial({color:'#bb925e',roughness:.65}));g.position.copy(c);g.quaternion.copy(t.rotation);g.scale.set(.18,.21,.065);props.add(g);const direction=t.neck.clone().sub(c).normalize(),neckCenter=c.clone().lerp(t.neck,.60).add(new T.Vector3(0,0,.047).applyQuaternion(t.rotation)),neckQ=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),direction);box(neckCenter.toArray(),[.055,c.distanceTo(t.neck)*.80,.035],'#98754c',1,neckQ);const hole=new T.Mesh(new T.CircleGeometry(.045,24),new T.MeshBasicMaterial({color:'#574331'}));hole.position.copy(c).add(new T.Vector3(0,0,.065).applyQuaternion(t.rotation));hole.quaternion.copy(t.rotation);props.add(hole);for(let i=0;i<6;i++){const offset=new T.Vector3(0,(i-2.5)*.006,.068).applyQuaternion(t.rotation);rod(c.clone().add(new T.Vector3(-.09,0,0).applyQuaternion(t.rotation)).add(offset),t.neck.clone().add(offset),.0009,'#eadfc7');}}
 if(spec.ball){const ball=new T.Mesh(new T.SphereGeometry(.12,20,12),new T.MeshStandardMaterial({color:'#c6944e'}));ball.position.copy(hands).add(new T.Vector3(0,.08,.12));props.add(ball);}
 const held=loadPosition(spec,r);if((Number($('load').value)>0&&!spec.backpack&&!atlasBusy)||spec.box||spec.bag){if(spec.bag){box(held.toArray(),[.23,.30,.15],'#b8a27b');const t=r.grip?.task;if(t){rod(t.handleA,t.handleB,.011,'#987e59');for(const a of [t.handleA,t.handleB])rod(a,a.clone().add(new T.Vector3(0,-.09,0)),.011,'#987e59');}}else box(held.toArray(),[.30,.23,.25],'#b6a380',1,r.grip?.task.rotation);}
 if(spec.backpack)box(held.toArray(),[.29,.42,.15],'#b8a27b');
 if(r.grip?.type==='tool'){const t=r.grip.task;rod(t.top,t.tip,.014,'#967f60');box(t.tip.toArray(),[.32,.05,.13],'#7a9985');}
 if(spec.bike){const rear=new T.Vector3(0,.31,-.60),front=new T.Vector3(0,.31,.65),crank=new T.Vector3(0,.31,.05),seat=pelvis.clone().add(new T.Vector3(0,-.12,0)),tube=new T.Vector3(0,.70,.50);for(const [a,b] of [[rear,seat],[rear,crank],[seat,crank],[seat,tube],[tube,crank],[tube,front],[tube,r.grip?.task.center||hands]])rod(a,b,.018);box(seat.toArray(),[.25,.04,.23],'#7f9580');rod(r.grip?.task.handleA||r.joints.wristR,r.grip?.task.handleB||r.joints.wristL,.016);for(const hub of [rear,front]){const wheel=new T.Mesh(new T.TorusGeometry(.31,.025,8,30),new T.MeshStandardMaterial({color:'#54735e'}));wheel.rotation.y=Math.PI/2;wheel.position.copy(hub);props.add(wheel);for(const angle of [0,Math.PI/3,2*Math.PI/3])rod(hub.clone().add(new T.Vector3(0,Math.cos(angle)*.29,Math.sin(angle)*.29)),hub.clone().sub(new T.Vector3(0,Math.cos(angle)*.29,Math.sin(angle)*.29)),.004);}for(const side of ['R','L']){const foot=r.joints['ankle'+side];rod(crank,foot,.01);box(foot.clone().add(new T.Vector3(0,-.03,.04)).toArray(),[.16,.025,.10],'#6b8473');}}
 ground.visible=grid.visible=!spec.water;if(spec.water){const water=new T.Mesh(new T.PlaneGeometry(3.2,2.3),new T.MeshBasicMaterial({color:'#98cacc',transparent:true,opacity:.24,side:T.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=spec.taskId==='swim-tread'?head.min.y+.03:.75;props.add(water);}
}
function loadPosition(spec,r){if(r.grip?.type==='box'||r.grip?.type==='bag')return r.grip.task.center.clone();if(spec.loadSide==='back')return r.joints.trunk.clone().add(new T.Vector3(0,0,-.23).applyQuaternion(r.parts.trunk.rotation));if(spec.loadSide==='R'||spec.loadSide==='L')return r.joints['wrist'+spec.loadSide].clone().add(new T.Vector3(0,-.10,0));return r.joints.wristR.clone().add(r.joints.wristL).multiplyScalar(.5).add(new T.Vector3(0,-.04,.035));}
function contactFor(spec){const out=[];const add=(name,test,normal=[0,1,0])=>{const b=boundsFor(test);if(b.isEmpty())return;const c=b.getCenter(new T.Vector3());c.y=b.min.y;out.push({name,point:c,normal:new T.Vector3(...normal)});};
 for(const s of spec.feet||[])add((s==='R'?'右':'左')+'脚'+(spec['leg'+s]?.step?' · 台面':spec.bed?' · 床面':' · 地面'),m=>m.userData.segment==='ankle'+s);
 if(spec.backSupport)out.push({name:'背部 · '+(spec.wall?'墙面':'靠背'),point:centerOf('trunk'),normal:new T.Vector3(0,0,1)});
 if(spec.bike){out.push({name:'骨盆 · 座垫',point:solved.joints.pelvis.clone(),normal:new T.Vector3(0,1,0)});for(const side of ['R','L'])out.push({name:(side==='R'?'右':'左')+'脚 · 脚踏示意',point:solved.joints['ankle'+side].clone(),normal:new T.Vector3(0,1,0)});}
 if(spec.chair||spec.floorSit||spec.heelSit)add(spec.chair?'骨盆 · 座面':spec.heelSit?'骨盆 · 脚跟区域':'骨盆 · 地面',m=>m.userData.segment==='pelvis');
 if(spec.bed){if(spec.lying==='left')add('左侧躯干 · 床面',m=>['trunk','pelvis'].includes(m.userData.segment),[0,1,0]);else if(spec.lying==='right')add('右侧躯干 · 床面',m=>['trunk','pelvis'].includes(m.userData.segment));else add(spec.lying==='prone'?'胸腹侧 · 床面':'背侧 · 床面',m=>m.userData.segment==='trunk');add('头部 · '+(spec.headPillow?'枕面':'床面'),m=>m.userData.segment==='head');if(!spec.bridge)add('下肢 · 床面',m=>['hipR','hipL','kneeR','kneeL'].includes(m.userData.segment));}
 if(spec.quadruped||spec.kneeling)for(const s of spec.kneeSides||['R','L'])add((s==='R'?'右':'左')+'膝 · 地面',m=>m.userData.info.id.startsWith('patella')&&m.userData.segment==='patella'+s);
 if(spec.handSupport||spec.quadruped)for(const s of spec.handSides||['R','L'])add((s==='R'?'右':'左')+'手 · 地面',m=>m.userData.segment==='wrist'+s);
 if(spec.forearmSupport)for(const s of ['R','L'])add((s==='R'?'右':'左')+'前臂 · 台面',m=>m.userData.segment==='elbow'+s);
 if(spec.water)out.push({name:'水体 · 浮力分布示意',point:centerOf('trunk'),normal:new T.Vector3(0,1,0)});
 return out;}
function clearLabels(){for(const x of labels)x.el.remove();labels.length=0;}
function label(text,point){const el=document.createElement('span');el.className='bodyLabel';el.textContent=text;$('labelLayer').append(el);labels.push({el,point});}
function drawSigns(spec){dispose(signs);clearLabels();currentContacts=contactFor(spec);for(const c of currentContacts){const sphere=new T.Mesh(new T.SphereGeometry(.014,12,8),new T.MeshBasicMaterial({color:'#237c78'}));sphere.position.copy(c.point);signs.add(sphere);label(c.name,c.point);}
 const weight=Number($('mass').value)*Number($('gravity').value);if(weight>0){const c=boundsFor(()=>true).getCenter(new T.Vector3());signs.add(new T.ArrowHelper(new T.Vector3(0,-1,0),c.clone().add(new T.Vector3(.16,.20,0)),.30,'#b76345',.07,.04));}
 if(spec.water&&Number($('gravity').value)>0){const c=centerOf('trunk');signs.add(new T.ArrowHelper(new T.Vector3(0,1,0),c.clone().add(new T.Vector3(-.17,-.15,0)),.28,'#237c78',.07,.04));}
}
function placeLabels(){if(gripFocused){for(const x of labels)x.el.hidden=true;return;}const rect=viewport.getBoundingClientRect(),used=[];for(const x of labels){const p=x.point.clone().project(camera),px=(p.x*.5+.5)*rect.width,py=(.5-p.y*.5)*rect.height;x.el.hidden=p.z>1||p.z<-1||px<0||px>rect.width||py<90||py>rect.height-220;if(x.el.hidden)continue;const w=x.el.offsetWidth,h=x.el.offsetHeight,left=T.MathUtils.clamp(px+10,8,rect.width-w-8);let top=py;for(let n=0;n<10&&used.some(b=>left<b.x+b.w+4&&left+w+4>b.x&&top<b.y+b.h+4&&top+h+4>b.y);n++)top=py-(n+1)*(h+6);top=T.MathUtils.clamp(top,95,rect.height-h-225);x.el.style.left=left+'px';x.el.style.top=top+'px';used.push({x:left,y:top,w,h});}}
function fit(cam,bounds,direction,usable=.72){const size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),vfov=T.MathUtils.degToRad(cam.fov/2),hfov=Math.atan(Math.tan(vfov)*cam.aspect),distance=size.length()/(2*Math.sin(Math.min(vfov*usable,hfov*.82)));cam.position.copy(center).addScaledVector(direction.clone().normalize(),Math.max(.35,distance));cam.lookAt(center);return center;}
function preferredDirection(spec){return spec.bed||spec.water?new T.Vector3(spec.lying==='right'?-1:1,.6,.35):new T.Vector3(.6,.15,1);}
function frameBody(direction){if(!ready)return;gripFocused=false;signs.visible=true;const rect=viewport.getBoundingClientRect();camera.setViewOffset(rect.width,rect.height,0,innerWidth<=650?90:80,rect.width,rect.height);camera.updateProjectionMatrix();const spec=currentSpec||stateFor(byId.get(selected),phase),box=boundsFor(()=>true),d=direction||camera.position.clone().sub(controls.target).normalize();if(spec.bed)box.expandByPoint(new T.Vector3(.48,.4,1.10)).expandByPoint(new T.Vector3(-.48,.4,-1.10));const center=fit(camera,box,d,Math.max(.35,(viewport.clientHeight-(innerWidth<=650?320:285))/viewport.clientHeight));controls.target.copy(center);controls.update();invalidate();}
function getInput(){return Object.fromEntries(['mass','gravity','load','minutes','interval','volume'].map(id=>[id,Number($(id).value)]));}
function valid(){const ids=['mass','gravity','load','minutes','interval',...(currentSpec?.water?['volume']:[])];return ids.every(id=>$(id).checkValidity());}
const fmt=(n,d=1)=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d});
function saveHash(){history.replaceState(null,'',location.pathname+location.search+'#'+new URLSearchParams({pose:selected,phase:String(Math.round(phase*100)),...Object.fromEntries(['mass','gravity','load','minutes','interval','volume'].map(id=>[id,$(id).value]))}));}
function invalidateRecord(){if(recordURL)URL.revokeObjectURL(recordURL);recordURL=null;$('recordPreview').hidden=true;$('recordStatus').textContent='';}
function updateAnalysis(){if(!ready)return;const p=byId.get(selected),load=loadPosition(currentSpec,solved);currentAnalysis=analyze(p,currentSpec,getInput(),load.toArray(),solved.joints.lumbar.toArray());const a=currentAnalysis;let text=focus==='lumbar'?a.lumbar.slice(1):focus==='neck'?[a.neck,a.shoulders]:[a.knees];$('analysisTitle').textContent=focus==='lumbar'?'腰背为什么需要维持':focus==='neck'?'颈肩在维持什么':'髋膝与支撑怎样配合';$('bodyAnalysis').innerHTML=text.map(t=>'<p class="analysisNote">'+t+'</p>').join('')+'<p class="supportText">支撑：'+(currentContacts.length?currentContacts.map(c=>c.name).join('；'):'当前没有地面接触')+'。</p>';
 $('timeAnalysis').innerHTML=`<div class="timeBox"><h3>这个状态持续 ${fmt(a.duration)} 分钟</h3><p>${a.timeText}</p><p>按你的计划，期间换姿 ${a.plannedChanges} 次。这里的间隔是计划，不是医学阈值；没有计算疲劳百分比、疼痛或损伤概率。</p></div>`;
 $('numbers').innerHTML=`<div class="metric"><small>设定质量与环境下的重量</small><strong>${fmt(a.weight)} N</strong><small>${fmt(a.mass)} kg × ${fmt(a.gravity,3)} m/s²</small></div>`+(a.load>0?`<div class="metric"><small>物体对腰部参照点的外力矩</small><strong>${fmt(a.externalMoment)} N·m</strong><small>${fmt(a.load)} kg × ${fmt(a.gravity,3)} m/s² × ${fmt(a.lever,3)} m。参照点为近似腰部位置，不是椎间盘内部压力。</small></div>`:'<p class="muted">当前物体质量为0。躯干自重产生的内部关节力没有求解。</p>')+(currentSpec.water?`<div class="metric"><small>水密度设为1000 kg/m³、排水体积手动输入</small><strong>浮力 ${fmt(a.buoyancy)} N</strong><small>重力减浮力 ${fmt(a.netWaterWeight)} N，正值向下；未包含水阻和推进力。</small></div>`:'');
 $('sourceLinks').innerHTML=a.refs.map(r=>`<a href="${r.url}" target="_blank" rel="noopener">${r.title} ↗</a>`).join('');$('waterRow').hidden=!currentSpec.water;renderComparison();}
function renderComparison(){const a=currentAnalysis;$('comparison').hidden=!pinned;if(!pinned||!a)return;$('comparisonBody').innerHTML=`<div class="compareRow"><div><strong>${pinned.name}</strong><p>${pinned.supports.join('、')||'无地面接触'}</p><small>物体 ${fmt(pinned.analysis.load)} kg · 重力 ${fmt(pinned.analysis.gravity,2)} m/s²<br>物体外力矩 ${fmt(pinned.analysis.externalMoment||0)} N·m<br>持续 ${fmt(pinned.analysis.duration)} 分钟</small></div><div><strong>${byId.get(selected).name}</strong><p>${currentContacts.map(c=>c.name).join('、')||'无地面接触'}</p><small>物体 ${fmt(a.load)} kg · 重力 ${fmt(a.gravity,2)} m/s²<br>物体外力矩 ${fmt(a.externalMoment||0)} N·m<br>持续 ${fmt(a.duration)} 分钟</small></div></div><p>对照动作与支撑条件，不将差值解释为损伤概率或关节压力差。</p>`;}
function applySelected(refit=false){if(!ready)return;if(refit){gripFocused=false;signs.visible=true;}const p=byId.get(selected);currentSpec=stateFor(p,phase);currentSpec.flags=p.flags;currentSpec.taskId=p.id;solved=configure(currentSpec);currentSpec=solved.spec;$('gripFocus').hidden=!solved.grip;drawProps(currentSpec,solved);drawSigns(currentSpec);updateAnalysis();if(refit)frameBody(preferredDirection(currentSpec));invalidate();}
function stop(){playing=false;$('play').textContent='播放';saveHash();}
function choose(id,restoreLoad=true){if(!byId.has(id))return;stop();selected=id;phase=0;$('phase').value=0;$('phaseName').value='0%';if(restoreLoad)$('load').value=byId.get(id).spec.load||0;invalidateRecord();const p=byId.get(id);$('sceneTitle').textContent=p.name;$('sceneCategory').textContent=p.category;$('sceneExplanation').textContent=p.explanation;$('phaseRow').hidden=!p.dynamic;$('play').hidden=!p.dynamic;$('play').disabled=!p.dynamic||!ready;$('comparePreset').hidden=!p.compare;$('mobilePose').value=id;document.querySelectorAll('[data-pose]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pose===id)));$('analysisPanel').scrollTop=0;applySelected(true);saveHash();}
function renderList(){const term=$('search').value.trim(),category=$('category').value,list=POSES.filter(p=>(category==='all'||p.category===category)&&(!term||(p.name+' '+p.explanation+' '+(p.flags.includes('staticStanding')?'久站':'')).includes(term)));$('catalogCount').textContent=`显示 ${list.length} / ${POSES.length} 种`;$('poseList').innerHTML=list.map(p=>`<button class="poseRow" data-pose="${p.id}" aria-pressed="${p.id===selected}"><span class="number">${String(POSES.indexOf(p)+1).padStart(3,'0')}</span><span><strong>${p.name}</strong><small>${p.category} · ${p.actionState?'动作阶段':'支撑姿态'}</small></span></button>`).join('')||'<p class="muted">没有找到。试试“卧”“坐”或清空搜索。</p>';$('poseList').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.pose));}
$('category').innerHTML='<option value="all">全部生活场景</option>'+CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('mobilePose').innerHTML=CATEGORIES.map(c=>`<optgroup label="${c}">`+POSES.filter(p=>p.category===c).map(p=>`<option value="${p.id}">${p.name}</option>`).join('')+'</optgroup>').join('');$('mobilePose').onchange=()=>choose($('mobilePose').value);$('category').onchange=renderList;$('search').oninput=renderList;renderList();
$('phase').oninput=()=>{stop();phase=Number($('phase').value)/100;invalidateRecord();applySelected(false);$('phaseName').value=fmt(phase*100)+'%';saveHash();};$('play').onclick=()=>{playing=!playing;invalidateRecord();$('play').textContent=playing?'暂停':'播放';lastTime=performance.now();invalidate();};
for(const id of ['mass','gravity','load','minutes','interval','volume'])$(id).required=true;
for(const id of ['mass','gravity','load','minutes','interval','volume'])$(id).oninput=()=>{invalidateRecord();const ok=valid();$('inputError').textContent=ok?'':'请填写允许范围内的数值。';$('record').disabled=!ok;if(!ok)return;applySelected(false);saveHash();};
for(const b of document.querySelectorAll('[data-gravity]'))b.onclick=()=>{$('gravity').value=b.dataset.gravity;$('gravity').dispatchEvent(new Event('input'));};for(const b of document.querySelectorAll('[data-minutes]'))b.onclick=()=>{$('minutes').value=b.dataset.minutes;$('minutes').dispatchEvent(new Event('input'));};
function panMode(on){controls.mouseButtons.LEFT=on?T.MOUSE.PAN:T.MOUSE.ROTATE;controls.touches.ONE=on?T.TOUCH.PAN:T.TOUCH.ROTATE;$('pan').setAttribute('aria-pressed',on);$('rotate').setAttribute('aria-pressed',!on);}$('pan').onclick=()=>panMode(true);$('rotate').onclick=()=>panMode(false);
function zoom(f){const delta=camera.position.clone().sub(controls.target),distance=delta.length();camera.position.copy(controls.target).addScaledVector(delta,T.MathUtils.clamp(distance*f,controls.minDistance,controls.maxDistance)/distance);controls.update();invalidate();}$('zoomIn').onclick=()=>zoom(.8);$('zoomOut').onclick=()=>zoom(1.25);$('frame').onclick=()=>frameBody();$('gripFocus').onclick=()=>{if(!solved.grip)return;const b=boundsFor(m=>m.userData.segment.startsWith('wrist')),center=b.getCenter(new T.Vector3()),direction=camera.position.clone().sub(controls.target).normalize(),rect=viewport.getBoundingClientRect(),top=document.querySelector('.stageHeading').getBoundingClientRect().bottom-rect.top+12,bottom=document.querySelector('.stageState').getBoundingClientRect().top-rect.top-12,usable=Math.max(80,bottom-top),tangent=Math.tan(T.MathUtils.degToRad(camera.fov/2));camera.lookAt(controls.target);const inverse=camera.quaternion.clone().invert(),projected=new T.Box3();for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z])projected.expandByPoint(new T.Vector3(x,y,z).sub(center).applyQuaternion(inverse));const size=projected.getSize(new T.Vector3()),distance=Math.max(.65,size.x/(2*tangent*camera.aspect*.82),size.y/(2*tangent*(usable/rect.height)*.82))+size.z/2;camera.setViewOffset(rect.width,rect.height,0,rect.height/2-(top+bottom)/2,rect.width,rect.height);camera.updateProjectionMatrix();gripFocused=true;signs.visible=false;controls.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);controls.update();invalidate();};$('side').onclick=()=>frameBody(new T.Vector3(1,.06,.02));$('front').onclick=()=>{const d=new T.Vector3(0,0,1).applyQuaternion(solved.parts.trunk.rotation);if(Math.abs(d.y)>.90)d.x=.12;frameBody(d);};$('top').onclick=()=>frameBody(new T.Vector3(.04,1,.04));
function focusPart(kind){focus=kind;updateAnalysis();const test=kind==='lumbar'?m=>m.userData.info.group==='lumbar':kind==='neck'?m=>['head','shoulderR','shoulderL'].includes(m.userData.segment)||m.userData.info.group==='cervical':m=>['hipR','hipL','kneeR','kneeL'].includes(m.userData.segment);for(const m of meshes)m.material.color.set(test(m)?'#c88836':'#ccba94');const b=boundsFor(test);controls.target.copy(b.getCenter(new T.Vector3()));const direction=camera.position.clone().sub(controls.target).normalize();camera.position.copy(controls.target).addScaledVector(direction,kind==='knees'?1.2:.65);controls.update();document.querySelectorAll('[data-focus]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.focus===kind));invalidate();}
for(const b of document.querySelectorAll('[data-focus]'))b.onclick=()=>focusPart(b.dataset.focus);$('focusBody').onclick=()=>{for(const m of meshes)m.material.color.set('#ccba94');frameBody();};
function pin(){if(!currentAnalysis)return;pinned={id:selected,name:byId.get(selected).name,phase,inputs:getInput(),analysis:structuredClone(currentAnalysis),supports:currentContacts.map(c=>c.name)};renderComparison();}$('pin').onclick=()=>{pin();$('comparison').scrollIntoView({block:'nearest',behavior:'smooth'});};$('clearPin').onclick=()=>{pinned=null;renderComparison();};$('comparePreset').onclick=()=>{pin();choose(byId.get(selected).compare,false);$('comparison').scrollIntoView({block:'nearest',behavior:'smooth'});};$('analysisJump').onclick=()=>$('analysisPanel').scrollIntoView({behavior:'smooth'});
$('record').onclick=()=>{if(!valid()||!ready)return;const record={version:'40.0.0',pose:selected,name:byId.get(selected).name,phase,inputs:getInput(),postureSpecification:currentSpec,grip:solved.grip&&{type:solved.grip.type,contacts:solved.grip.contacts,fingerChains:solved.grip.fingerChains,assumption:'指骨刚体铰链与近似接触，未模拟肌腱、肌肉和软组织形变'},analysis:currentAnalysis,comparison:pinned,contacts:currentContacts.map(c=>({name:c.name,position:c.point.toArray()})),jointCenters:Object.fromEntries(Object.entries(solved.joints).map(([id,v])=>[id,v.toArray()])),assumptions:['成人男性参考骨架，未个体校准','支撑标记不是压力或肌肉激活','外物力矩不是内部关节力','持续时间不预测疲劳程度、疼痛或损伤']};const json=JSON.stringify(record,null,2);invalidateRecord();recordURL=URL.createObjectURL(new Blob([json],{type:'application/json'}));$('recordText').value=json;$('recordDownload').href=recordURL;$('recordDownload').download='posture-'+selected+'.json';$('recordPreview').hidden=false;$('recordPreview').open=true;$('recordStatus').textContent='记录已生成，可查看、复制或下载。';};
async function renderAtlas(){if(!ready||atlasBusy)return;atlasBusy=true;const generation=++atlasGeneration;$('atlasPrev').disabled=$('atlasNext').disabled=true;stop();const pageSize=innerWidth<=650?6:12,page=POSES.slice(atlasPage*pageSize,atlasPage*pageSize+pageSize);$('atlasStatus').textContent='正在用实际骨架生成本页图像…';$('atlasGrid').innerHTML='';for(const p of page){if(generation!==atlasGeneration)return;let url=thumbnailCache.get(p.id);if(!url){const s=stateFor(p,0);s.taskId=p.id;const r=configure(s);drawProps(s,r);dispose(signs);for(const m of meshes)m.material.color.set('#ccba94');const b=boundsFor(()=>true);fit(thumbCamera,b,preferredDirection(s),.86);thumbRenderer.render(scene,thumbCamera);url=thumbRenderer.domElement.toDataURL('image/webp',.80);thumbnailCache.set(p.id,url);}const card=document.createElement('button');card.className='atlasCard';card.dataset.pose=p.id;card.innerHTML=`<img alt="${p.name}的骨架姿势" src="${url}"><strong>${POSES.indexOf(p)+1}. ${p.name}</strong><small>${p.category} · ${p.actionState?'动作阶段示意':'动作与支撑示意'}</small>`;card.onclick=()=>{$('atlas').close();choose(p.id);};$('atlasGrid').append(card);await new Promise(resolve=>requestAnimationFrame(resolve));}if(generation!==atlasGeneration)return;atlasBusy=false;applySelected(false);$('atlasStatus').textContent='每张图均由现有210骨块与对应关节链绘制；未个体动作校准。';$('atlasPage').textContent=`${atlasPage+1} / ${Math.ceil(POSES.length/(innerWidth<=650?6:12))}`;$('atlasPrev').disabled=atlasPage===0;$('atlasNext').disabled=atlasPage>=Math.ceil(POSES.length/(innerWidth<=650?6:12))-1;}
$('atlasButton').onclick=()=>{$('atlas').showModal();renderAtlas();};$('closeAtlas').onclick=()=>$('atlas').close();$('atlas').addEventListener('close',()=>{atlasGeneration++;atlasBusy=false;applySelected(false);});$('atlasPrev').onclick=()=>{atlasPage=Math.max(0,atlasPage-1);renderAtlas();};$('atlasNext').onclick=()=>{atlasPage=Math.min(Math.ceil(POSES.length/(innerWidth<=650?6:12))-1,atlasPage+1);renderAtlas();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else invalidate();});
const needsModel=document.querySelectorAll('.viewTools button,.focusButtons button,#pin,#record,#comparePreset,#atlasButton');needsModel.forEach(b=>b.disabled=true);
async function load(){const gltf=await new GLTFLoader().loadAsync('../fullbody-tcm-v9/assets/fullbody.glb',e=>{if(e.total)$('modelStatus').textContent='骨架加载 '+Math.round(e.loaded/e.total*100)+'%';});gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(n=>{if(!n.isMesh)return;const info=boneData.get(n.name);if(!info)throw Error('无法识别源骨块 '+n.name);const baked=n.geometry.clone(),matrix=new T.Matrix4().makeScale(.001,.001,.001).multiply(n.matrixWorld);baked.applyMatrix4(matrix);baked.translate(-.09955,-.835,.05);baked.computeBoundingBox();const mesh=new T.Mesh(baked,new T.MeshStandardMaterial({color:'#ccba94',roughness:.75}));mesh.name=n.name;mesh.userData={segment:segment(info),info};mesh.matrixAutoUpdate=false;body.add(mesh);meshes.push(mesh);});if(meshes.length!==210)throw Error('骨架没有完整载入');handRig=createHandRig(meshes);ready=true;needsModel.forEach(b=>b.disabled=false);$('modelStatus').textContent='210 骨块 · 支撑与关节链';choose(selected,false);phase=T.MathUtils.clamp(Number(hash.get('phase'))||0,0,100)/100;$('phase').value=Math.round(phase*100);applySelected(true);}
choose(selected,false);load().catch(e=>{$('modelStatus').textContent='加载失败，请刷新重试';$('inputError').textContent=e.message;});
if(location.hostname==='127.0.0.1'&&new URLSearchParams(location.search).has('audit')){const button=document.createElement('button');button.id='poseAuditButton';button.textContent='检查姿势状态';button.style.cssText='position:fixed;right:3px;bottom:3px;z-index:2000';const out=document.createElement('pre');out.id='poseAudit';out.hidden=true;document.body.append(button,out);button.onclick=()=>{const b=boundsFor(()=>true);out.textContent=JSON.stringify({ready,selected,phase,playing,bones:meshes.length,finite:meshes.every(m=>m.matrix.elements.every(Number.isFinite)),bounds:[b.min.toArray(),b.max.toArray()],partBounds:Object.fromEntries(Object.keys(solved?.parts||{}).map(id=>{const x=boundsFor(m=>m.userData.segment===id);return [id,[x.min.toArray(),x.max.toArray()]];})),projectedCorners:[0,1,2,3,4,5,6,7].map(i=>new T.Vector3(i&1?b.max.x:b.min.x,i&2?b.max.y:b.min.y,i&4?b.max.z:b.min.z).project(camera).toArray()),grip:solved?.grip&&{type:solved.grip.type,contacts:solved.grip.contacts,fingerChains:solved.grip.fingerChains},constraints:solved?.constraints,joints:Object.fromEntries(Object.entries(solved?.joints||{}).map(([id,v])=>[id,v.toArray()])),contacts:currentContacts.map(c=>({name:c.name,point:c.point.toArray()})),camera:camera.position.toArray(),target:controls.target.toArray(),analysis:currentAnalysis});};}
