const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright'),{PNG}=require('pngjs');
const root=process.cwd(),engine=process.env.BROWSER||'webkit',live=!!process.env.TEST_URL,out=path.join(root,'fullbody-tcm-v26/checks'),prefix=(live?'live-':'local-')+engine;fs.mkdirSync(out,{recursive:true});
const report={version:'26.0.0',engine,live,checks:[],errors:[],comparison:{},startedAt:new Date().toISOString(),clinicalCalibration:false};
const server=live?null:http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}).listen(8226,'127.0.0.1');
const ck=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail||''));};
let browser,p,context;
async function settle(){await p.waitForFunction(()=>window.__ATLAS_SHARED__&&!__ATLAS_SHARED__.getState().busy&&!__ATLAS_LEARNING__.getSurfaceState().busy&&!__FOOT_ATLAS__.getState().cameraAnimating,null,{timeout:180000});await p.waitForTimeout(220);}
async function start(v,dpr=1){if(context)await context.close();context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:dpr});p=await context.newPage();p.setDefaultTimeout(90000);p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/WebGLProgram|VALIDATE_STATUS|GL_INVALID|shader error/i.test(m.text()))report.errors.push(m.text().slice(0,1800));});const u=live?(v==='26'?process.env.TEST_URL:'https://hengtong320.github.io/notionweb/fullbody-tcm-v25/?baseline=26'):'http://127.0.0.1:8226/fullbody-tcm-v'+v+'/';await p.goto(u);await p.waitForFunction(()=>window.__ATLAS_SHARED__&&__FOOT_ATLAS__.getState().ready);await p.evaluate(()=>localStorage.setItem('atlas-auto-speak','0'));await settle();}
async function shot(name){await p.screenshot({path:path.join(out,prefix+'-'+name+'.png')});}
async function toggle(id,on){await p.evaluate(({id,on})=>{const e=document.getElementById(id);if(e.type==='checkbox'){if(e.checked!==on){e.checked=on;e.dispatchEvent(new Event('change',{bubbles:true}));}}else if(e.classList.contains('active')!==on)e.click();},{id,on});await settle();}
async function frame(){await p.evaluate(()=>{const l=__ATLAS_LEARNING__,{THREE,camera,controls,invalidate}=__ATLAS_RENDER_AUDIT__;controls.enableDamping=false;controls.update();camera.clearViewOffset();l.clearPointSelection();l.setMeridians(['PC']);const local=document.getElementById('localStudyToggle');local.checked=false;local.dispatchEvent(new Event('change',{bubbles:true}));document.body.classList.remove('nav-open','detail-open');const qs=l.getNavigationCatalog().filter(q=>['PC3','PC7'].includes(q.code)&&q.side==='right'),box=new THREE.Box3();qs.forEach(q=>box.expandByPoint(new THREE.Vector3(...q.position)));box.expandByScalar(24);const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),d=Math.max(size.y,size.x/camera.aspect)*.5/Math.tan(camera.fov*Math.PI/360)*1.1;controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(0,0,d));camera.up.set(0,1,0);controls.minDistance=1;controls.maxDistance=10000;controls.update();camera.updateMatrixWorld(true);invalidate();});await toggle('pointNamesToggle',false);await toggle('acupointToggle',false);await p.evaluate(()=>{const e=document.getElementById('curveStyle');e.value='smooth';e.dispatchEvent(new Event('change',{bubbles:true}));});await settle();}
async function stroke(){await toggle('meridianLineToggle',false);const blank=await p.locator('#viewport canvas').first().screenshot();await toggle('meridianLineToggle',true);const ink=await p.locator('#viewport canvas').first().screenshot();const sample=await p.evaluate(()=>{const l=__ATLAS_LEARNING__,{THREE,camera,scene}=__ATLAS_RENDER_AUDIT__,rect=document.querySelector('#viewport canvas').getBoundingClientRect(),pts=l.getNavigationCatalog(),a=pts.find(q=>q.code==='PC5'&&q.side==='right'),b=pts.find(q=>q.code==='PC6'&&q.side==='right'),count=l.getInkAudit().routes.find(r=>r.meridian==='PC'&&r.side==='right').drawnSegments;let mesh;scene.traverseVisible(n=>{if(n.userData.skinInk&&n.userData.meridian==='PC'&&n.userData.bodySide==='right')mesh=n;});const data=mesh.material.uniforms.inkData.value.image.data,g=[];for(let k=0;k<count;k++){if(!k)g.push(Array.from(data.slice(k*8,k*8+3)));g.push(Array.from(data.slice(k*8+4,k*8+7)));}const dist=(q,r)=>Math.hypot(...q.map((n,i)=>n-r[i]));const near=q=>g.reduce((best,r,i)=>dist(q,r)<dist(q,g[best])?i:best,0);let i=near(a.position),j=near(b.position);if(i>j)[i,j]=[j,i];const values=g.slice(i,j+1).map(q=>{const v=new THREE.Vector3(...q).project(camera);return [(v.x*.5+.5)*rect.width,(-v.y*.5+.5)*rect.height];});return {points:values,width:rect.width,height:rect.height};});const a=PNG.sync.read(blank),b=PNG.sync.read(ink),scale=a.width/sample.width;let n=0,good=0,run=0,longest=0,changed=0;for(let i=0;i<a.data.length;i+=4)if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>30)changed++;
 for(let k=1;k<sample.points.length;k++){const u=sample.points[k-1],v=sample.points[k],len=Math.hypot(v[0]-u[0],v[1]-u[1]);if(len>25)continue;for(let t=0;t<len;t+=1){const x=Math.round((u[0]+(v[0]-u[0])*t/len)*scale),y=Math.round((u[1]+(v[1]-u[1])*t/len)*scale);if(x<3||y<3||x>=a.width-3||y>=a.height-3)continue;let found=false;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const i=((y+dy)*a.width+x+dx)*4;if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>30)found=true;}n++;if(found){good++;run=0;}else{run++;longest=Math.max(longest,run);}}}
 return {sampleCount:n,coverage:n?good/n:0,longestMissingSamples:longest,changedPixels:changed};}
async function catalog(){return p.evaluate(()=>__ATLAS_LEARNING__.getNavigationCatalog().map(q=>({code:q.code,side:q.side,position:q.position})));}
async function labels(){return p.evaluate(()=>{__ATLAS_LEARNING__.flushLabels();return __ATLAS_LEARNING__.getLabelPlacementAudit?.()||[];});}
(async()=>{try{browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox','--enable-unsafe-swiftshader']}: {})});const baseline={};
 await start('25');for(const sex of ['male','female']){await p.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();baseline[sex]={points:await catalog()};await frame();baseline[sex].stroke=await stroke();await shot('v25-'+sex+'-forearm');}
 await start('26');ck('New reading and meridian modules are mounted',await p.evaluate(()=>!!window.__ATLAS_READING_V26__&&!!window.__ATLAS_MERIDIAN_UX__));ck('Local crop is off by default',await p.evaluate(()=>!document.getElementById('localStudyToggle').checked));
 for(const sex of ['male','female']){await p.evaluate(sex=>__ATLAS_SHARED__.switchSex(sex),sex);await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();const pts=await catalog(),old=baseline[sex].points,shift=Math.max(...pts.map(q=>{const o=old.find(x=>x.code===q.code&&x.side===q.side);return o?Math.hypot(...q.position.map((v,i)=>v-o.position[i])):Infinity;}));ck(sex+' all 670 display anchors preserved',pts.length===670&&shift<1e-7,{count:pts.length,maxShift:shift});const ia=await p.evaluate(()=>__ATLAS_LEARNING__.getInkAudit());ck(sex+' opaque skin ink uses normal depth',ia.active&&ia.depthTest&&await p.evaluate(()=>!__ATLAS_LEARNING__.getState().xray&&Number(document.getElementById('sharedOpacity-surface').value)===100));
 await frame();const current=await stroke();report.comparison[sex]={before:baseline[sex].stroke,after:current};ck(sex+' forearm solid stroke covers sampled centerline',current.sampleCount>40&&current.coverage>=.97&&current.longestMissingSamples<=3,current);ck(sex+' centerline coverage does not regress',current.coverage>=baseline[sex].stroke.coverage-.005,{before:baseline[sex].stroke,after:current});await shot('v26-'+sex+'-forearm');
 await p.evaluate(()=>{document.getElementById('guideToggle').checked=false;document.getElementById('guideToggle').dispatchEvent(new Event('change',{bubbles:true}));});await toggle('meridianLineToggle',true);ck(sex+' line switch controls actual guide',await p.evaluate(()=>{const s=__ATLAS_LEARNING__.getState();return s.linesOn&&s.guideOn;}));
 await toggle('pointNamesToggle',false);await p.evaluate(()=>__ATLAS_LEARNING__.fitMeridian([0,0,1]));await settle();ck(sex+' fitting does not force names back on',await p.evaluate(()=>!__ATLAS_LEARNING__.getState().namesOn));
 await toggle('acupointToggle',true);await toggle('pointNamesToggle',true);await p.evaluate(()=>{__ATLAS_LEARNING__.setMeridians(['HT','PC']);__ATLAS_LEARNING__.selectPoint('PC6','right',true);});await settle();const la=await labels();ck(sex+' selected point has a named leader',la.some(x=>x.code==='PC6'&&x.side==='right'),la);const bounds=await p.locator('#viewport').boundingBox();ck(sex+' labels remain within viewport',la.length>0&&la.every(x=>x.box[0]>=0&&x.box[1]>=0&&x.box[0]+x.box[2]<=bounds.width+1&&x.box[1]+x.box[3]<=bounds.height+1),la);ck(sex+' point card has one compact location and retained review notice',await p.evaluate(()=>document.querySelectorAll('#tcmPointCard .v26-point-notice').length===1&&document.querySelectorAll('#tcmPointCard .v10-point-summary').length===1&&!!document.querySelector('#tcmPointCard .v26-point-basis')));await shot(sex+'-point-reading');
 await p.evaluate(()=>{__ATLAS_LEARNING__.clearPointSelection();__ATLAS_LEARNING__.setMeridian('ALL');__ATLAS_LEARNING__.fitMeridian([0,0,-1]);});await settle();await shot(sex+'-all-back');ck(sex+' all-meridian title is compact',await p.locator('#currentStudyName').textContent().then(s=>s.length<35));
 await p.evaluate(()=>__ATLAS_SHARED__.choose('bones',false));await settle();ck(sex+' skeleton remains available after meridian study',await p.evaluate(()=>document.body.dataset.bodySex==='female'?__ATLAS_FEMALE__.getVisibleCatalog().filter(r=>r.system==='skeletal').length===210:__FOOT_ATLAS__.getState().visible===210));await p.evaluate(()=>__ATLAS_SHARED__.choose('chest',false));await settle();ck(sex+' chest selection does not leave stale meridian skin',await p.evaluate(()=>__ATLAS_SHARED__.getState().scene==='chest'));await shot(sex+'-chest');}
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();await p.evaluate(()=>{document.body.classList.remove('detail-open','nav-open');__ATLAS_LEARNING__.setMeridians(['HT','PC']);__ATLAS_LEARNING__.selectPoint('PC6','right',true);});await settle();ck('Phone point selection leaves model visible',await p.evaluate(()=>!document.body.classList.contains('detail-open')&&!document.getElementById('v26PointSummary').hidden));await shot('phone-point-model');await p.locator('#v26PointSummary [data-action="details"]').click();await settle();ck('Phone details open on request',await p.evaluate(()=>document.body.classList.contains('detail-open')));const sheet=await p.locator('.detail-panel').boundingBox();ck('Phone details use a limited-height bottom sheet',sheet&&sheet.height<=340&&sheet.y>420,sheet);await p.locator('#focusPointBtn').click();await settle();ck('Focusing from phone details keeps the details open',await p.evaluate(()=>document.body.classList.contains('detail-open')));const q=await p.evaluate(()=>__ATLAS_LEARNING__.getPointScreen('PC6','right'));ck('Focused point stays above phone details and below toolbar',q&&q.y>200&&q.y<sheet.y-10&&q.x>20&&q.x<330,{point:q,sheet});await shot('phone-point-details');if(await p.locator('#closePointCard').isVisible())await p.locator('#closePointCard').click();await settle();await p.evaluate(()=>__ATLAS_SHARED__.showSection('meridians'));await settle();await shot('phone-controls');ck('Phone controls do not overflow horizontally',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>__ATLAS_SHARED__.switchSex('male'));await p.evaluate(()=>__ATLAS_SHARED__.choose('surface',false));await settle();ck('Male return restores current-body skin reference',await p.evaluate(()=>{const s=__ATLAS_LEARNING__.getState();return s.referenceBody==='male'&&s.surfaceAttached&&!s.suspended;}));
 ck('No shader compilation or uncaught errors',report.errors.length===0,report.errors);
 }catch(e){report.failure=e.stack;console.error(e);if(p)await shot('failure').catch(()=>{});}finally{report.success=!report.failure&&!report.errors.length&&report.checks.every(c=>c.pass);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,prefix+'.json'),JSON.stringify(report,null,2));if(browser)await browser.close();server?.close();if(!report.success)process.exitCode=1;}})();
