import {createFemaleCompletion} from './female-complete-v21.js';
import {normalizeFemaleMesh,bodyFrameInfo} from './body-frame-v18.js';
import {createSkinProjector} from './skin-v17.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import decoderSource from './draco-decoder.txt';
export function initFemale(ctx){
 const {THREE,scene,camera,renderer,viewport,controls,state,bones,modelRoot,learning,tissues,speech,toast,focusBounds,invalidate,setMode,applyVisibility,resetBones,setRegion,renderNow}=ctx;
 const $=s=>document.getElementById(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const groupNames={surface:'体表外形',breast:'乳腺结构',respiratory:'肺与气道',vascular:'心脏与血管',digestive:'消化系统',urinary:'泌尿系统',reproductive:'女性生殖',skeletal:'全身骨架',nervous:'全身神经',muscular:'全身肌肉',lymphatic:'淋巴与免疫'};
 groupNames['native-skeletal']='女性原生骨关节细节';groupNames['native-muscular']='女性原生局部肌肉';groupNames['native-nervous']='女性原生脑与感官细节';
 groupNames.vessels='全身血管参考';groupNames.ear='耳部参考';
 const colors={surface:'#a9826c',breast:'#b87678',respiratory:'#a56871',vascular:'#a5444e',digestive:'#ad8164',urinary:'#a86466',reproductive:'#a55876',skeletal:'#c3b79d',nervous:'#896126',muscular:'#98575a',lymphatic:'#638368'};
 const root=new THREE.Group();root.name='Female teaching body (native HRA plus attributed shared reference)';root.visible=false;scene.add(root);
 const maps=new Map(),systems=new Map(),hidden=new Set();let catalog=null,loadCatalog=null,active=false,serial=0,preset='surface',selected=null,isolated=false,mode='solid',labelsOn=false,fineDetails=false,side='both',saved=null,viewName='front';
 const draco=new DRACOLoader().setDecoderConfig({type:'js'}).setWorkerLimit(2);draco._loadLibrary=()=>Promise.resolve(decoderSource);const loader=new GLTFLoader().setDRACOLoader(draco);
 const completion=createFemaleCompletion({THREE,bones,loader});
 const pane=document.createElement('section');pane.id='femaleLibrary';pane.hidden=true;
 pane.innerHTML='<button id="femaleCloseNav" class="female-drawer-close" aria-label="收起女性目录">收起目录 ×</button><h2>女性参考模型</h2><p class="female-scope">统一教学体型；保留女性特有结构，原始模型文件不变。</p><div class="female-presets">'+[['surface','体表外形'],['chest','胸腔心肺'],['abdomen','腹部器官'],['pelvis','盆腔与生殖'],['breast','乳腺结构'],['nerves','脑与脊髓'],['vessels','心血管'],['bones','骨骼与关节']].map(([id,n])=>`<button data-female-preset="${id}">${n}</button>`).join('')+'</div><div class="female-mode"><span>显示方式</span><select id="femaleMode" aria-label="女性显示方式"><option value="solid">原色清晰</option><option value="context">透明参照</option><option value="focus">突出所选</option></select></div><div class="female-mode"><span>左右范围</span><select id="femaleSide"><option value="both">双侧与中线</option><option value="left">人体左侧＋中线</option><option value="right">人体右侧＋中线</option></select></div><details id="femaleLayers"><summary>自定义图层</summary>'+Object.entries(groupNames).map(([id,n])=>`<label><input type="checkbox" data-female-layer="${id}">${n}<small id="femaleStatus-${id}"></small></label>`).join('')+'</details><label class="search-box"><input id="femaleSearch" type="search" placeholder="名称 / 拼音 / English"></label><div id="femaleCount"></div><div id="femaleResults"></div>';
 document.querySelector('.sidebar').append(pane);$('femaleCloseNav').onclick=()=>document.body.classList.remove('nav-open');
 const detail=document.createElement('section');detail.id='femaleDetail';detail.className='female-detail';detail.hidden=true;document.querySelector('.detail-panel').append(detail);
 const tag=document.createElement('div');tag.id='femalePointLabel';tag.hidden=true;viewport.append(tag);
 const switcher=document.createElement('div');switcher.id='bodySelector';switcher.setAttribute('aria-label','参考人体');switcher.innerHTML='<button data-body-sex="male" aria-pressed="true" class="active">男性</button><button data-body-sex="female" aria-pressed="false">女性</button>';$('releaseBadge').after(switcher);
 switcher.querySelectorAll('button').forEach(b=>b.onclick=()=>setSex(b.dataset.bodySex).catch(e=>toast(e.message)));
 pane.querySelectorAll('[data-female-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.femalePreset).catch(e=>toast(e.message)));
 pane.querySelectorAll('[data-female-layer]').forEach(b=>b.onchange=()=>enable(b.dataset.femaleLayer,b.checked).then(()=>{preset='custom';isolated=false;update();}).catch(e=>toast(e.message)));
 $('femaleMode').onchange=e=>{mode=e.target.value;update();};$('femaleSide').onchange=e=>{side=e.target.value;update();};$('femaleSearch').oninput=renderList;
 function urlState(){if(state.bodyTransition)return;if(document.body.classList.contains('reference-detail'))return;if(!active||restoringFemaleHash)return;const h=new URLSearchParams({sex:'female',preset,mode,side});if(selected)h.set('id',selected);try{history.replaceState(null,'','#'+h);}catch{}}
 async function getCatalog(){if(catalog)return catalog;if(!loadCatalog)loadCatalog=fetch('../fullbody-tcm-v12/assets/female/catalog.json').then(r=>{if(!r.ok)throw Error('女性目录加载失败');return r.json();}).then(async d=>catalog=await completion.getCatalog(d)).catch(e=>{loadCatalog=null;throw e;});return loadCatalog;}
 function color(r){if(r.system==='ear')return '#bc9d86';if(r.system==='vessels')return /vein|vena/i.test(r.sourceName)?'#3b6190':'#98434a';if(r.system==='vascular'&&/vein|vena/i.test(r.sourceName))return '#4c78a6';if(/liver/i.test(r.sourceName))return '#805054';if(/gallbladder/i.test(r.sourceName))return '#6b865d';if(r.system==='breast'&&/fat/.test(r.sourceName))return '#c4af74';return colors[r.nativeSystem||r.system]||'#c8b38e';}
 function systemStatus(id,text){const node=$('femaleStatus-'+id);if(node)node.textContent=text;}
 async function enable(id,on){
  let entry=systems.get(id);if(!entry){entry={on:false,opacity:1,loaded:false,promise:null,meshes:[]};systems.set(id,entry);}entry.on=!!on;
  const cb=pane.querySelector(`[data-female-layer="${id}"]`);if(cb)cb.checked=entry.on;
  if(on&&!entry.loaded){if(!entry.promise){systemStatus(id,'加载中…');invalidate();entry.promise=(async()=>{
   await getCatalog();let nodes=[];
   if(completion.handles(id))nodes=await completion.load(id);
   else{const doc=await loader.loadAsync('../fullbody-tcm-v12/assets/female/'+id+'.glb');doc.scene.updateMatrixWorld(true);doc.scene.traverse(n=>{if(!n.isMesh)return;const row=catalog.entries.find(r=>r.id===n.name);if(!row)throw Error('女性结构无来源记录');n.userData.female=row;normalizeFemaleMesh(n,THREE);nodes.push(n);});const holder=new THREE.Group();for(const n of nodes){n.updateWorldMatrix(true,false);const g=n.geometry.clone().applyMatrix4(n.matrixWorld);n.geometry=g;n.position.set(0,0,0);n.quaternion.identity();n.scale.set(1,1,1);} }
   const holder=new THREE.Group();holder.name='female-system-'+id;
   for(const n of nodes){const row=n.userData.female;n.material=new THREE.MeshStandardMaterial({color:color(row),roughness:.73,metalness:0,envMapIntensity:row.system==='surface'?.08:.19,side:THREE.DoubleSide});n.geometry.computeBoundingBox();n.renderOrder=3;maps.set(row.id,n);holder.add(n);}
   entry.meshes=nodes;root.add(holder);entry.loaded=true;systemStatus(id,nodes.length+'部件');update();renderList();
  })().catch(e=>{entry.promise=null;entry.on=false;if(cb)cb.checked=false;systemStatus(id,'加载失败，点选重试');throw e;});}await entry.promise;}
  update();renderList();return entry;
 }
 let femaleSkinProjector=null,skinTask=null;
 async function ensureMeridianSurface(){
  if(skinTask)return skinTask;
  skinTask=(async()=>{if(!femaleSkinProjector){const prior=systems.get('surface')?.on;await enable('surface',true);const templateMeshes=await tissues.getSurfaceReferenceMeshes();root.updateWorldMatrix(true,true);femaleSkinProjector=createSkinProjector(systems.get('surface').meshes,{sex:'female',templateMeshes,standardized:true});if(!prior){systems.get('surface').on=false;update();}}
   if(!active)return false;await learning.setReferenceBody('female',femaleSkinProjector,true);if(!state.bodyTransition)learning.suspend(false);return true;
  })();try{return await skinTask;}finally{skinTask=null;}
 }
 const nativeVascularCore=r=>/uterine_(artery|vein)$/.test(r.sourceName)||/^VH_F_(interventricular_septum|(left|right)_(cardiac_atrium|ventricle)|papillary_muscle_of_heart_.+|aortic_valve|pulmonary_valve|mitral_valve|tricuspid_valve)$/.test(r.sourceName);
 function contextMatch(r){if(systems.get('vessels')?.on&&r.system==='vascular'&&!nativeVascularCore(r))return false;if(r.nativeDetail)return r.id===selected;if(['chest','abdomen','pelvis','vessels'].includes(preset)&&['surface','skeletal'].includes(r.system))return true;if(preset==='heart')return r.system==='skeletal'||r.system==='vascular'&&r.ancestry.some(n=>/heart|aorta|vena_cava|pulmonary|cardiac/.test(n));if(preset==='chest')return r.system==='respiratory'||r.system==='vascular'&&r.ancestry.some(n=>/heart|aorta|vena_cava|pulmonary/.test(n));if(preset==='pelvis')return r.system==='reproductive'||r.system==='skeletal'&&r.ancestry.includes('VH_F_pelvis')||r.system==='urinary'&&/bladder|urethra|ureter/.test(r.sourceName);return true;}
 function coarse(r){if(r.nativeDetail)return r.id===selected;if(fineDetails)return true;if(r.origin==='shared-teaching')return r.category!=='fascia';if(r.system==='respiratory')return true;if(r.system==='skeletal')return !/spongy|enthesis|most_point|condyle_|perichondular|trochlear|fossa/.test(r.sourceName);if(r.system==='urinary')return !/papilla|pyramid|medulla|calyx/.test(r.sourceName);if(r.system==='digestive')return !/couinaud|capsule|ligament/.test(r.sourceName);return true;}
 function update(){root.visible=active;for(const [id,s] of systems){for(const n of s.meshes){const r=n.userData.female;n.visible=s.on&&!hidden.has(r.id)&&(side==='both'||r.side==='midline'||r.side==='bilateral'||r.side===side)&&contextMatch(r)&&coarse(r)&&(!isolated||r.id===selected);if(r.id===selected)n.visible=s.on&&!hidden.has(r.id)&&(side==='both'||r.side==='midline'||r.side==='bilateral'||r.side===side);const focus=mode==='focus'&&selected&&r.id!==selected;let opacity=(s.opacity??1)*(focus?.18:1);n.material.transparent=opacity<1;n.material.opacity=opacity;n.material.depthWrite=opacity>.9;n.material.emissive.set(r.id===selected?'#946324':'#000000');n.material.emissiveIntensity=r.id===selected?(r.system==='surface'?.025:.2):0;}}
  if(active){state.bonesOn=false;modelRoot.visible=false;$('regionHeading').textContent='女性 · '+({organs:'胸腹内脏',surface:'体表外形',heart:'心脏与邻近血管',chest:'胸腔心肺',abdomen:'腹部器官',pelvis:'盆腔与生殖',breast:'乳腺结构',muscles:'全身肌肉',compare:'分层对照',nerves:'全身神经',vessels:'心血管',bones:'骨骼与关节',custom:'自定义观察'}[preset]||'参考模型');$('visibleCount').textContent=[...maps.values()].filter(n=>n.visible).length+' 个已启用部件';}
  pane.querySelectorAll('[data-female-preset]').forEach(b=>b.classList.toggle('active',b.dataset.femalePreset===preset));urlState();updateLabel();invalidate();
 }
 function visible(){return [...maps.values()].filter(n=>active&&n.visible);}
 function fit(dir){let ns=selected&&isolated?[maps.get(selected)]:visible();const contextual=!isolated&&['organs','chest','heart','abdomen','pelvis'].includes(preset);if(contextual){const selected=ns.filter(n=>!['surface','skeletal'].includes(n.userData.female.system)&&(preset!=='chest'||n.userData.female.system==='respiratory'));if(selected.length)ns=selected;}const box=new THREE.Box3();ns.forEach(n=>n&&box.expandByObject(n));if(contextual)box.expandByScalar(115);if(!box.isEmpty()){focusBounds(box.expandByScalar(preset==='pelvis'?25:15),{direction:dir||[0,.04,1],up:[0,1,0]});camera.position.sub(controls.target).multiplyScalar(preset==='surface'?1.18:1.06).add(controls.target);controls.update();camera.updateMatrixWorld(true);invalidate();}}
 async function ensureBodyContext(){isolated=false;await Promise.all([enable('surface',true),enable('skeletal',true)]);systems.get('surface').opacity=.18;systems.get('skeletal').opacity=.40;update();return true;}
 function focus(){const n=maps.get(selected);if(n?.visible)focusBounds(new THREE.Box3().setFromObject(n).expandByScalar(!isolated&&['respiratory','vascular','digestive','urinary','reproductive'].includes(n.userData.female.system)?115:12),{direction:camera.position.clone().sub(controls.target).normalize().toArray(),up:[0,1,0]});else fit();}
 function view(name){const dirs={front:[0,0,1],back:[0,0,-1],overview:[.8,.25,1],medial:[1,0,0],lateral:[-1,0,0],dorsal:[0,1,.01],plantar:[0,-1,.01]};if(!dirs[name])return;viewName=name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('viewBadge').lastElementChild.textContent={front:'前面',back:'后面',overview:'立体',medial:'人体左面',lateral:'人体右面',dorsal:'上方',plantar:'下方'}[name];fit(dirs[name]);}
 async function setPreset(id,options={}){if(!options.managed&&window.__ATLAS_SHARED__)return window.__ATLAS_SHARED__.choose(id==='vessels'?'vascular':id,!!options.preserveView,{keepSection:true});const cfg={organs:['respiratory','vascular','digestive','urinary','reproductive','lymphatic','skeletal'],surface:['surface'],chest:['respiratory','vascular','skeletal'],heart:['vascular','skeletal'],abdomen:['digestive','urinary','skeletal'],pelvis:['reproductive','skeletal','urinary'],breast:['breast'],nerves:['nervous','skeletal'],vessels:['vessels','vascular','skeletal'],bones:['skeletal'],muscles:['muscular'],compare:['skeletal','nervous','muscular']}[id];if(!cfg)return false;const token=++serial;preset=id;hidden.clear();selected=null;isolated=false;side='both';$('femaleSide').value='both';mode='solid';$('femaleMode').value=mode;for(const[key,s]of systems){s.on=cfg.includes(key);const cb=pane.querySelector(`[data-female-layer="${key}"]`);if(cb)cb.checked=s.on;}showIntro();update();await Promise.all(cfg.map(k=>enable(k,true)));if(!active||token!==serial)return false;for(const k of cfg)systems.get(k).opacity=1;if(id==='compare'){systems.get('muscular').opacity=.27;systems.get('skeletal').opacity=.65;}if(['organs','chest','heart','abdomen','pelvis','vessels','nerves'].includes(id)){systems.get('skeletal').opacity=.32;}else if(id!=='compare'){if(systems.get('surface'))systems.get('surface').opacity=1;if(systems.get('skeletal'))systems.get('skeletal').opacity=1;}update();renderList();if(!options.preserveView)view('front');if(!options.preservePanel)document.body.classList.remove('nav-open','detail-open');return true;}
 function showIntro(){document.body.classList.remove('reference-detail');detail.hidden=false;detail.innerHTML='<button id="femaleCloseDetail" class="female-drawer-close" aria-label="收起女性详情">收起详情 ×</button><span class="group-tag">女性 · 完整教学参考</span><h2>'+({organs:'胸腹内脏',surface:'女性体表',heart:'心脏与邻近血管',chest:'胸腔心肺',abdomen:'腹部器官',pelvis:'盆腔与生殖',breast:'乳腺结构',muscles:'全身肌肉',compare:'分层对照',nerves:'全身神经',vessels:'心血管',bones:'骨骼与关节'}[preset]||'女性结构')+'</h2><p>点击结构或左侧目录，查看名称、聚焦与单独观察。</p><div class="female-actions"><button id="femaleFitAll">适配当前范围</button><button id="femaleRestore">恢复当前场景</button></div><details><summary>女性模型来源与覆盖</summary><p>女性体表、骨盆、内脏及特有器官来自 HRA / HuBMAP。全身骨架、肌肉与神经以 Z-Anatomy / BodyParts3D 统一比例教学参考补齐。补充结构不是女性原生扫描，不是临床器官配准。原生局部细节另在结构目录保留。</p><a href="https://purl.humanatlas.io/ref-organ/united-female/v1.5" target="_blank" rel="noopener">查看原始来源 ↗</a></details>';bindDetail();}
 function detailMutation(key,fn){const a=window.__ATLAS_SHARED__,target=selected,job=()=>{if(!active||target!==selected)return false;return fn();};return (a?a.runMutation(key,job):Promise.resolve().then(job)).catch(e=>toast('操作未完成：'+e.message));}
 function announceRegion(){window.dispatchEvent(new CustomEvent('atlas:selection',{detail:{kind:'region',id:preset,name:'女性 · 当前结构',side}}));window.dispatchEvent(new Event('atlas:structure-updated'));}
 function bindDetail(){$('femaleCloseDetail')&&($('femaleCloseDetail').onclick=()=>document.body.classList.remove('detail-open'));$('femaleFitAll')&&($('femaleFitAll').onclick=()=>fit());$('femaleRestore')&&($('femaleRestore').onclick=()=>setPreset(preset==='custom'?'surface':preset));$('femaleFocus')&&($('femaleFocus').onclick=focus);$('femaleIsolate')&&($('femaleIsolate').onclick=()=>detailMutation('isolate-structure',()=>{isolated=!isolated;update();focus();showSelected();}));$('femaleSpeak')&&($('femaleSpeak').onclick=()=>speech.speak?.(maps.get(selected)?.userData.female.name||''));$('femaleHide')&&($('femaleHide').onclick=()=>detailMutation('hide-structure',()=>{if(selected)hidden.add(selected);selected=null;isolated=false;tag.hidden=true;update();renderList();showIntro();announceRegion();}));}
 function showSelected(){const r=maps.get(selected)?.userData.female;if(!r)return showIntro();detail.hidden=false;detail.innerHTML=`<button id="femaleCloseDetail" class="female-drawer-close" aria-label="收起女性详情">收起详情 ×</button><span class="group-tag">${esc(groupNames[r.system])}</span><h2>${esc(r.name)}</h2><p class="female-pinyin">${esc(r.pinyin||'')}</p><p class="female-english">${esc(r.english)}</p><div class="female-actions"><button id="femaleFocus">聚焦当前</button><button id="femaleIsolate">${isolated?'恢复周围':'单独查看'}</button><button id="femaleHide">隐藏此结构</button><button id="femaleSpeak">朗读名称</button><button id="femaleFitAll">适配范围</button><button id="femaleRestore">恢复当前场景</button></div><h3>当前模型位置</h3><p>${esc(r.side==='left'?'人体左侧':r.side==='right'?'人体右侧':'中线或跨侧结构')} · ${esc(groupNames[r.system])}</p><p>可旋转查看外形；单独查看会暂时隐藏其他结构。</p><details><summary>名称与来源</summary><p>${esc(r.sourceName)}</p><p>${r.origin==='shared-teaching'?'Z-Anatomy / BodyParts3D 统一比例教学补充；不是女性原生扫描或临床配准。':'HRA 女性参考集 v1.5 原生几何；以统一教学比例显示。'}</p>${r.ontology?`<a href="${esc(r.ontology)}" target="_blank" rel="noopener">解剖本体条目 ↗</a>`:''}</details>`;bindDetail();}
 async function select(id,doFocus=true){if(!state.bodyTransition&&window.__ATLAS_SHARED__)return window.__ATLAS_SHARED__.runMutation('selection',()=>select(id,doFocus));document.body.classList.remove('reference-detail','point-detail-active');await getCatalog();const row=catalog.entries.find(r=>r.id===id);if(!row)return false;await enable(row.system,true);if(!active)return false;hidden.delete(id);const keepIsolated=isolated&&selected===id;selected=id;isolated=keepIsolated||!!row.nativeDetail||(row.system==='vascular'&&systems.get('vessels')?.on&&!nativeVascularCore(row));if(!contextMatch(row))preset='custom';if(side!=='both'&&!['midline','bilateral',side].includes(row.side))side='both';$('femaleSide').value=side;update();showSelected();renderList();if(doFocus)focus();document.body.classList.remove('nav-open');document.body.classList.add('detail-open');window.dispatchEvent(new CustomEvent('atlas:selection',{detail:{kind:'tissue',id:row.id,name:row.name,side:row.side}}));window.dispatchEvent(new Event('atlas:structure-updated'));return true;}
 function renderList(){if(!catalog)return;const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s/g,'');const q=norm($('femaleSearch').value);const arr=q?catalog.entries.filter(r=>norm([r.name,r.pinyin,r.english,r.id,r.sourceName].join(' ')).includes(q)):visible().map(n=>n.userData.female);$('femaleCount').textContent=(q?'搜索结果 ':'当前可见 ')+arr.length+' 个已启用部件';$('femaleResults').innerHTML=arr.map(r=>`<button data-female-select="${r.id}" class="${r.id===selected?'active':''}"><b>${esc(r.name)}</b><small>${esc(r.pinyin||r.english)}</small></button>`).join('');$('femaleResults').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.femaleSelect,true).catch(e=>toast(e.message)));}
 let sexSerial=0,sexBusy=false;
 const femaleSceneForMale=()=>({chest:'chest',heart:'heart',abdomen:'abdomen',vascular:'vessels',surface:'surface',bones:'bones',muscles:'muscles',nerves:'nerves',compare:'compare'}[tissues.getState().profile]||'surface');
 const sceneLayers={muscles:['muscular','surface'],compare:['skeletal','nervous','muscular'],surface:['surface'],chest:['respiratory','vascular','surface','skeletal'],abdomen:['digestive','urinary','surface','skeletal'],pelvis:['reproductive','skeletal','urinary','surface'],breast:['breast'],nerves:['nervous'],vessels:['vascular','surface','skeletal'],bones:['skeletal','surface']};
 function transferView(v,toFemale){return {...v,position:[...v.position],target:[...v.target]};}
 async function setSex(sex,options={}){
  if(!options.managed&&window.__ATLAS_SHARED__)return window.__ATLAS_SHARED__.switchSex(sex);
  if(options.managed){if(!['male','female'].includes(sex))return false;if((sex==='female')===active)return true;sexBusy=true;learning.suspend(true);speech.stop?.();learning.cancelPendingFocus?.();selected=null;isolated=false;tag.hidden=true;hidden.clear();try{if(sex==='female'){await getCatalog();for(const k of Object.keys(tissues.getState().systems))await tissues.enable(k,false);tissues.clearSelection();state.bonesOn=false;applyVisibility();active=true;state.bodySex='female';modelRoot.visible=false;root.visible=true;document.body.classList.add('female-view','organ-view-active');}else{active=false;state.bodySex='male';root.visible=false;modelRoot.visible=true;pane.hidden=true;detail.hidden=true;document.body.classList.remove('female-view','organ-view-active');await learning.setReferenceBody('male',null,true);}for(const [k,v]of systems)v.on=false;syncSex();update();window.dispatchEvent(new CustomEvent('atlas:sex-changed',{detail:{sex}}));return true;}finally{sexBusy=false;invalidate();}}
  if(!['male','female'].includes(sex))return false;
  const tcmEnabled=learning.getState().enabled;const ticket=++sexSerial;if((sex==='female')===active&&!sexBusy)return true;sexBusy=true;switcher.setAttribute('aria-busy','true');
  try{if(sex==='female'){
   const wanted=femaleSceneForMale();await getCatalog();await Promise.all(sceneLayers[wanted].map(k=>enable(k,true)));if(ticket!==sexSerial)return false;
   const priorCamera=ctx.captureCamera(),viewState={nav:document.body.classList.contains('nav-open'),detail:document.body.classList.contains('detail-open')};
   saved={view:state.view,region:state.region,side:state.side,bonesOn:state.bonesOn,profile:tissues.getState().profile,systems:tissues.getState().systems,cameraState:priorCamera,surfaceAttached:learning.getState().surfaceAttached,enabled:learning.getState().enabled};
   speech.stop?.();setMode('orbit');learning.cancelPendingFocus?.();learning.suspend(true);
   for(const k of Object.keys(tissues.getState().systems))await tissues.enable(k,false);if(ticket!==sexSerial)return false;
   tissues.clearSelection();state.bonesOn=false;applyVisibility();active=true;state.bodySex='female';document.body.classList.add('female-view','organ-view-active');modelRoot.visible=false;root.visible=true;pane.hidden=false;detail.hidden=false;
   await setPreset(wanted,{preserveView:true,preservePanel:true});if(ticket!==sexSerial)return false;
   await ensureMeridianSurface();learning.toggleTCM(tcmEnabled);ctx.restoreCamera(transferView(priorCamera,true));document.body.classList.toggle('nav-open',viewState.nav);document.body.classList.toggle('detail-open',viewState.detail);
  }else{
   if(!active)return true;const priorCamera=ctx.captureCamera();serial++;active=false;state.bodySex='male';root.visible=false;pane.hidden=true;detail.hidden=true;tag.hidden=true;document.body.classList.remove('female-view','organ-view-active');modelRoot.visible=true;
   await learning.setReferenceBody('male',null,false);state.bonesOn=saved?.bonesOn??true;await tissues.setProfile(saved?.profile&&saved.profile!=='custom'?saved.profile:'bones');if(ticket!==sexSerial)return false;
   setRegion(saved?.region||'body',false);ctx.setSide(saved?.side||'both');
   if(saved?.systems)for(const[k,v]of Object.entries(saved.systems)){await tissues.enable(k,v.on);tissues.setOpacity(k,v.opacity);}
   state.bonesOn=saved?.bonesOn??true;applyVisibility();learning.suspend(false);if(saved?.surfaceAttached)await tissues.attachSurface(true);learning.toggleTCM(tcmEnabled);
   ctx.restoreCamera(transferView(priorCamera,false));$('renderStatus').textContent='男性 · 解剖参考';try{history.replaceState(null,'',location.pathname+location.search);}catch{}
  }
  syncSex();invalidate();window.dispatchEvent(new CustomEvent('atlas:sex-changed',{detail:{sex:active?'female':'male'}}));return true;
  }catch(e){toast('模型切换失败，可重试：'+e.message);throw e;}finally{if(ticket===sexSerial){sexBusy=false;switcher.setAttribute('aria-busy','false');syncSex();}}
 }
 function syncSex(){switcher.querySelectorAll('button').forEach(b=>{const on=(b.dataset.bodySex==='female')===active;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
 const ray=new THREE.Raycaster();function hit(e){if(!active)return null;const r=viewport.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);return ray.intersectObjects(visible().filter(n=>n.userData.female.system!=='surface'),false)[0]||null;}
 function click(e){const h=hit(e);if(h){select(h.object.name,false);return true;}return false;}


 const viewCue=document.createElement('div');viewCue.id='femaleViewCue';viewCue.className='empty-view-cue';viewCue.hidden=true;viewCue.setAttribute('role','status');viewCue.innerHTML='<span></span><button type="button">看当前结构</button>';document.querySelector('.stage').append(viewCue);
 const viewFrustum=new THREE.Frustum(),viewMatrix=new THREE.Matrix4(),viewBox=new THREE.Box3(),sampleVertex=new THREE.Vector3(),visibilityRay=new THREE.Raycaster();let coverageSignature='',viewCoverage={active:false,loadedVisible:0,inFrustum:0,visibleSurfaceHits:0,needsRefocus:false};
 function syncViewCoverage(){
  if(!active){viewCue.hidden=true;coverageSignature='';viewCoverage={active:false,loadedVisible:0,inFrustum:0,visibleSurfaceHits:0,needsRefocus:false};return;}
  const pending=sexBusy||window.__ATLAS_SHARED__?.getState().busy||[...systems.values()].some(x=>x.promise&&!x.loaded);
  if(pending){viewCue.hidden=true;coverageSignature='';return;}
  camera.updateMatrixWorld(true);root.updateMatrixWorld(true);
  const ns=visible(),signature=camera.matrixWorld.elements.join(',')+'|'+camera.projectionMatrix.elements.join(',')+'|'+ns.map(n=>n.uuid).join(',');if(signature===coverageSignature)return;coverageSignature=signature;
  viewMatrix.multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);viewFrustum.setFromProjectionMatrix(viewMatrix);
  const candidates=[];for(const n of ns){if(!n.geometry.boundingBox)n.geometry.computeBoundingBox();viewBox.copy(n.geometry.boundingBox).applyMatrix4(n.matrixWorld);if(viewFrustum.intersectsBox(viewBox))candidates.push(n);}
  let surfaceHits=0,samples=0,rayChecks=0;
  for(const n of candidates){const a=n.geometry.attributes.position,step=Math.max(1,Math.floor(a.count/64));for(let i=0;i<a.count;i+=step){sampleVertex.fromBufferAttribute(a,i).applyMatrix4(n.matrixWorld).project(camera);samples++;if(sampleVertex.z>=-1&&sampleVertex.z<=1&&Math.abs(sampleVertex.x)<.92&&sampleVertex.y>-.82&&sampleVertex.y<.56){surfaceHits++;break;}}if(surfaceHits)break;}
  // A large surface can fill the view even when all sampled vertices are outside.
  // Confirm with real triangle hits; a loose artery bounding box is not a visible organ.
  if(!surfaceHits&&candidates.length){visibilityRay.near=camera.near;visibilityRay.far=camera.far;for(const [x,y]of [[0,0],[0,.35],[0,-.35],[-.35,0],[.35,0]]){visibilityRay.setFromCamera(new THREE.Vector2(x,y),camera);rayChecks++;if(visibilityRay.intersectObjects(candidates,false).length){surfaceHits++;break;}}}
  viewCoverage={active:true,loadedVisible:ns.length,inFrustum:candidates.length,visibleSurfaceHits:surfaceHits,sampledVertices:samples,raycastChecks:rayChecks,needsRefocus:ns.length>0&&surfaceHits===0};
  viewCue.hidden=surfaceHits>0;viewCue.querySelector('span').textContent=ns.length?'当前结构不在主要视野内，已保留你的视角。':'当前图层没有可见结构。';viewCue.querySelector('button').textContent=ns.length?'看当前结构':'看女性体表';
 }
 viewCue.querySelector('button').onclick=()=>{if(visible().length){fit(camera.position.clone().sub(controls.target).normalize().toArray());invalidate();}else window.__ATLAS_SHARED__?.choose('surface',false);};
 const structureLabels=document.createElement('div');structureLabels.id='femaleStructureLabels';structureLabels.className='female-structure-labels';viewport.append(structureLabels);let labelKey='';
 function updateStructureLabels(){structureLabels.hidden=!active||!labelsOn;if(structureLabels.hidden){structureLabels.replaceChildren();labelKey='';return;}const available=visible().filter(n=>!['surface'].includes(n.userData.female.system));const unique=new Map();for(const n of available)if(!unique.has(n.userData.female.name))unique.set(n.userData.female.name,n);let nodes=[...unique.values()];const rect=viewport.getBoundingClientRect();nodes=nodes.map(n=>({n,v:new THREE.Box3().setFromObject(n).getCenter(new THREE.Vector3()).project(camera)})).filter(q=>Math.abs(q.v.x)<.94&&Math.abs(q.v.y)<.75&&q.v.z>-1&&q.v.z<1).sort((a,b)=>a.v.y-b.v.y);const step=Math.max(1,Math.ceil(nodes.length/12));nodes=nodes.filter((n,i)=>i%step===0).slice(0,12);const key=nodes.map(q=>q.n.name).join(',');if(labelKey!==key){labelKey=key;structureLabels.innerHTML=nodes.map(q=>'<button data-female-label="'+esc(q.n.name)+'">'+esc(q.n.userData.female.name)+'</button>').join('');structureLabels.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();select(b.dataset.femaleLabel,true);});}const used=[];for(let i=0;i<nodes.length;i++){const b=structureLabels.children[i],q=nodes[i],x=Math.max(8,Math.min(rect.width-180,(q.v.x*.5+.5)*rect.width+12)),y=Math.max(160,Math.min(rect.height-120,(-q.v.y*.5+.5)*rect.height));const clash=used.some(z=>Math.abs(z.x-x)<160&&Math.abs(z.y-y)<30);b.hidden=clash;if(!clash){b.style.left=x+'px';b.style.top=y+'px';used.push({x,y});}}}
 function updateLabel(){updateStructureLabels();syncViewCoverage();if(active){const n=visible().length+' 个已启用部件';if($('visibleCount').textContent!==n)$('visibleCount').textContent=n;if($('renderStatus').textContent!=='女性 · 原生＋教学补充')$('renderStatus').textContent='女性 · 原生＋教学补充';}if(!active||!selected){tag.hidden=true;return;}const n=maps.get(selected);if(!n?.visible){tag.hidden=true;return;}const v=new THREE.Box3().setFromObject(n).getCenter(new THREE.Vector3()).project(camera),r=viewport.getBoundingClientRect();tag.hidden=v.z<-1||v.z>1;tag.textContent=n.userData.female.name;tag.style.left=Math.max(5,Math.min(r.width-180,(v.x*.5+.5)*r.width+10))+'px';tag.style.top=Math.max(30,Math.min(r.height-80,(-v.y*.5+.5)*r.height))+'px';}
 function getPickPoint(id){const n=maps.get(id);if(!n?.visible||!active)return null;const box=new THREE.Box3().setFromObject(n),r=viewport.getBoundingClientRect(),vs=[];for(let i=0;i<8;i++)vs.push(new THREE.Vector3(i&1?box.max.x:box.min.x,i&2?box.max.y:box.min.y,i&4?box.max.z:box.min.z).project(camera));const xs=vs.map(v=>r.left+(v.x*.5+.5)*r.width),ys=vs.map(v=>r.top+(-v.y*.5+.5)*r.height);for(const x of [.5,.3,.7,.15,.85])for(const y of [.5,.3,.7,.15,.85]){const p={x:Math.min(...xs)+(Math.max(...xs)-Math.min(...xs))*x,y:Math.min(...ys)+(Math.max(...ys)-Math.min(...ys))*y};if(hit({clientX:p.x,clientY:p.y})?.object.name===id)return p;}return null;}
 async function capture(){await document.fonts?.ready;renderNow();const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;const g=c.getContext('2d');g.drawImage(renderer.domElement,0,0);const ref=window.__ATLAS_SHARED__?.getState().selectedPoint;const name=ref?.name||maps.get(selected)?.userData.female.name||'女性参考';g.fillStyle='rgba(247,250,242,.96)';g.fillRect(0,c.height-74,c.width,74);g.fillStyle='#315440';g.font='18px sans-serif';g.fillText('女性 · '+name,18,c.height-44);g.font='13px sans-serif';g.fillText('HRA 女性原生＋Z-Anatomy 教学参考 · 未逐穴临床配准 · V23',18,c.height-18);const blob=await new Promise(r=>c.toBlob(r));const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='人体研习-女性-'+name+'-V23.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);return {name,bytes:blob.size,female:true};}
 document.addEventListener('click',e=>{if(!active)return;const t=e.target.closest('button');if(!t)return;if(document.body.classList.contains('reference-detail')&&['focusBtn','focusCurrent'].includes(t.id)){e.preventDefault();e.stopImmediatePropagation();learning.focusSelectedPoint();return;}const v=t.dataset.view;if(v){e.preventDefault();e.stopImmediatePropagation();view(v);return;}if(['homeBtn','focusBtn','captureBtn','focusCurrent','overallCurrent'].includes(t.id)){e.preventDefault();e.stopImmediatePropagation();if(t.id==='captureBtn')capture();else if(t.id==='focusBtn'||t.id==='focusCurrent')focus();else{selected=null;isolated=false;update();fit();showIntro();}}},true);
 document.addEventListener('keydown',e=>{if(!active||e.target.closest?.('input,textarea,select')||e.ctrlKey||e.metaKey||document.querySelector('dialog[open]'))return;const keyViews={'1':'overview','2':'dorsal','3':'plantar','4':'medial','5':'lateral','6':'front','7':'back'};if(keyViews[e.key]){e.preventDefault();e.stopImmediatePropagation();view(keyViews[e.key]);return;}if(['f','h','g','t','l'].includes(e.key.toLowerCase())){e.preventDefault();e.stopImmediatePropagation();if(e.key.toLowerCase()==='f'){if(document.body.classList.contains('reference-detail'))learning.focusSelectedPoint();else focus();}if(e.key.toLowerCase()==='l')$('labelsBtn').click();if(e.key.toLowerCase()==='h'){isolated=false;selected=null;update();fit();showIntro();}}},true);

 function captureState(){return {preset,selected,isolated,mode,side,labelsOn,fineDetails,hidden:[...hidden],systems:Object.fromEntries([...systems].map(([id,s])=>[id,{on:s.on,opacity:s.opacity}]))};}
 async function restoreState(v){
  serial++;for(const [id,s]of systems)s.on=!!v.systems?.[id]?.on;
  for(const [id,s]of Object.entries(v.systems||{})){await enable(id,s.on);systems.get(id).opacity=s.opacity??1;}
  preset=v.preset||'custom';selected=v.selected&&maps.has(v.selected)?v.selected:null;isolated=!!v.isolated&&!!selected;mode=v.mode||'solid';side=v.side||'both';labelsOn=!!v.labelsOn;fineDetails=!!v.fineDetails;
  hidden.clear();for(const id of v.hidden||[])hidden.add(id);$('femaleMode').value=mode;$('femaleSide').value=side;update();renderList();if(selected)showSelected();else showIntro();return true;
 }

 window.addEventListener('atlas:transition-settled',()=>{if(active){update();urlState();}$('renderStatus').textContent=active?'女性 · 原生＋教学补充':'男性 · 解剖参考';});
 const api={getCompletionAudit:()=>completion.audit(),setFineDetails:v=>{fineDetails=!!v;update();},setIsolated:v=>{isolated=!!v&&!!selected;update();showSelected();},restoreHidden:()=>{hidden.clear();isolated=false;update();renderList();if(selected)showSelected();else showIntro();},captureState,restoreState,setLabels:v=>{labelsOn=!!v;updateStructureLabels();invalidate();},getLabels:()=>labelsOn,ensureMeridianSurface,ensureBodyContext,setDisplayMode:(v,options={})=>{if(['solid','context','focus'].includes(v)){mode=v;$('femaleMode').value=v;if(!options.preserveOpacity)for(const s of systems.values())if(s.on)s.opacity=v==='context'?.28:1;update();}},setSide:v=>{if(['both','left','right'].includes(v)){side=v;$('femaleSide').value=v;const r=maps.get(selected)?.userData.female;if(r&&v!=='both'&&!['midline','bilateral',v].includes(r.side)){selected=null;isolated=false;showIntro();announceRegion();}update();renderList();}},setOpacity:(id,v)=>{const s=systems.get(id);if(s){s.opacity=Math.max(.08,Math.min(1,Number(v)||1));update();}},getVisibleCatalog:()=>visible().map(n=>n.userData.female),clearSelection:()=>{selected=null;isolated=false;update();showIntro();},setCustom:()=>{preset='custom';isolated=false;update();},getViewCoverage:()=>({...viewCoverage}),get active(){return active;},setSex,setPreset,select,enable,focus,fit,view,click,capture,updateFrame:updateLabel,getPickPoint,getCatalog:()=>catalog?.entries||[],getState:()=>({sexBusy,active,preset,mode,side,fineDetails,view:viewName,selected,isolated,source:'HRA female + Z-Anatomy shared teaching',bodyFrame:bodyFrameInfo(),mixedReferenceSources:true,originalMaleSceneVisible:false,visible:visible().length,hidden:[...hidden],loaded:maps.size,systems:Object.fromEntries([...systems].map(([k,s])=>[k,{on:s.on,opacity:s.opacity??1,loaded:s.loaded,loading:!!s.promise&&!s.loaded,count:s.meshes.length,visible:s.meshes.filter(n=>n.visible&&active).length}]))})};window.__ATLAS_FEMALE__=api;
 let restoringFemaleHash=false,pendingFemaleHash=null;
 async function restoreFemaleLink(raw){
  pendingFemaleHash=raw;if(restoringFemaleHash)return;restoringFemaleHash=true;
  try{while(pendingFemaleHash!==null){
   const text=pendingFemaleHash;pendingFemaleHash=null;
   const h=new URLSearchParams(text.replace(/^#/,''));
   if(h.get('sex')!=='female')continue;
   await setSex('female');
   await setPreset(h.get('preset')||'surface');
   if(['point','meridian'].includes(h.get('kind'))){window.__ATLAS_SHARED__?.showSection('meridians');if(h.get('kind')==='point')learning.selectPoint(h.get('id'),h.get('side')||'right',false);else{learning.setMeridians((h.get('id')||'HT').split(','));window.__ATLAS_EVIDENCE__.showChannel((h.get('id')||'HT').split(','));}continue;}
   if(h.get('id'))await select(h.get('id'),true);
   mode=['solid','context','focus'].includes(h.get('display')||h.get('mode'))?(h.get('display')||h.get('mode')):'solid';
   side=['left','right','both'].includes(h.get('side'))?h.get('side'):'both';
   $('femaleMode').value=mode;$('femaleSide').value=side;update();
  }}catch(e){toast('女性链接恢复失败：'+e.message);}
  finally{restoringFemaleHash=false;urlState();invalidate();}
 }
 window.addEventListener('hashchange',()=>{const raw=location.hash;if(new URLSearchParams(raw.slice(1)).get('sex')==='female')restoreFemaleLink(raw);});
 const initial=ctx.initialHash||location.hash;
 if(new URLSearchParams(initial.slice(1)).get('sex')==='female')queueMicrotask(()=>restoreFemaleLink(initial));

 return api;
}
